In [1]:
import librosa
import matplotlib.pyplot as plt
import librosa.display
import os
import numpy as np
from tensorflow.keras import layers
from IPython.display import Audio
import wave
import pandas as pd
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt

2024-10-27 21:09:27.424474: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-27 21:09:27.435331: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-27 21:09:27.438811: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-27 21:09:27.447786: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-27 21:09:28.011726: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
df = pd.read_csv("../data_processing/sep28k-mfcc.csv")

In [3]:
df = df[df['NaturalPause'] == 0]
df = df[df['Block'] == 0]
df = df[df['Prolongation'] == 0]
df = df[df['WordRep'] == 0]
df = df[df['SoundRep'] == 0]
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
6,HeStutters,0,6,37251200,37299200,0,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
9,HeStutters,0,9,41417440,41465440,0,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
10,HeStutters,0,10,41861760,41909760,0,0,0,0,0,...,-2.898894,-6.209611,-3.659979,-5.923317,-2.773856,-3.547750,2.452112,1.432807,3.639793,2.238830

In [4]:
df = df.reset_index()
df.head()

,index,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,...,29,30,31,32,33,34,35,36,37,38
0,2,HeStutters,0,2,34809760,34857760,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
1,4,HeStutters,0,4,35721920,35769920,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
2,6,HeStutters,0,6,37251200,37299200,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
3,9,HeStutters,0,9,41417440,41465440,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
4,10,HeStutters,0,10,41861760,41909760,0,0,0,0,...,-2.898894,-6.209611,-3.659979,-5.923317,-2.773856,-3.547750,2.452112,1.432807,3.639793,2.238830

In [5]:
df = df.drop(columns=['index'])
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
0,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
1,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
2,HeStutters,0,6,37251200,37299200,0,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
3,HeStutters,0,9,41417440,41465440,0,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
4,HeStutters,0,10,41861760,41909760,0,0,0,0,0,...,-2.898894,-6.209611,-3.659979,-5.923317,-2.773856,-3.547750,2.452112,1.432807,3.639793,2.238830

In [6]:
df.to_csv("interjection.csv",index=False)

In [7]:
import os

def list_files(directory):
    return [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]

# Replace 'directory_path' with the path to your directory
directory_path = '/home/alien/Git/DATA/mel_spects_interjection'
# names_list = list_files(directory_path)
names_list = pd.read_csv("interjection.csv")['Name'].values.tolist()
# full_names_list = ["/home/alien/Git/DATA/mfcc_images/" + img + ".jpg" for img in names_list]
full_names_list = []
for img in names_list:
    corresponding_sound = df.loc[df['Name'] == img, 'Interjection'].values[0]
    if corresponding_sound == 0:
        full_names_list.append("/home/alien/Git/DATA/mel_spects_interjection/" + img + "_fluent.jpg")
    if corresponding_sound >= 1:
        full_names_list.append("/home/alien/Git/DATA/mel_spects_interjection/" + img + "_stutter.jpg")

# Replace 'directory_path' with the path to your directory
directory_path = '/home/alien/Git/DATA/mel_specaugment_interjection'
# names_list = list_files(directory_path)
names_list = pd.read_csv("interjection.csv")['Name'].values.tolist()
# full_names_list = ["/home/alien/Git/DATA/mfcc_images/" + img + ".jpg" for img in names_list]
for img in names_list:
    corresponding_sound = df.loc[df['Name'] == img, 'Interjection'].values[0]
    if corresponding_sound == 0:
        full_names_list.append("/home/alien/Git/DATA/mel_specaugment_interjection/" + img + "_fluent.jpg")
    if corresponding_sound >= 1:
        full_names_list.append("/home/alien/Git/DATA/mel_specaugment_interjection/" + img + "_stutter.jpg")

print(full_names_list[30])
print(full_names_list[-30])

/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_118_fluent.jpg
/home/alien/Git/DATA/mel_specaugment_interjection/WomenWhoStutter_106_7_fluent.jpg

In [8]:
def load_all(imagefile_list):
    data = []
    labels = []

    for imagefile in imagefile_list:
        print(imagefile)
        image = cv2.imread(imagefile)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (224, 224))
        data.append(image)

        if "fluent" in imagefile:
            labels.append(0)
        else:
            labels.append(1)

    labels = np.array(labels)
    data = np.array(data)

    return data, labels

In [9]:
X, y = load_all(full_names_list)

/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_6_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_10_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_32_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_103_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_107_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_178_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_195_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_228_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_256_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_14_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_43_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_52_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_88_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_118_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_170_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_180_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_182_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_2_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_4_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_29_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_5_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_7_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_10_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_31_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_42_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_43_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_67_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_75_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_86_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_116_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_17_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_32_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_40_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_77_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_78_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_102_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_104_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_105_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_113_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_120_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_126_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_135_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_140_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_143_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_146_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_156_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_159_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_167_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_176_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_191_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_198_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_199_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_220_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_232_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_239_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_253_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_254_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_255_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_256_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_261_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_268_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_276_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_286_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_292_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_11_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_14_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_17_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_18_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_38_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_5_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_19_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_58_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_132_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_139_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_163_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_164_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_166_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_172_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_195_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_197_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_3_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_5_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_7_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_10_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_29_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_8_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_13_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_14_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_20_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_26_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_31_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_36_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_25_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_62_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_67_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_73_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_106_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_118_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_150_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_179_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_181_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_188_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_194_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_204_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_0_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_12_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_14_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_18_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_27_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_68_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_79_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_101_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_105_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_114_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_120_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_125_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_127_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_133_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_142_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_148_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_158_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_165_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_178_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_201_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_202_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_206_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_207_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_3_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_10_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_13_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_31_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_36_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_17_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_19_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_33_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_37_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_91_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_139_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_140_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_164_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_188_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_56_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_186_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_187_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_189_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_3_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_7_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_11_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_12_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_22_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_24_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_57_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_58_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_59_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_60_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_77_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_84_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_101_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_115_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_136_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_153_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_168_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_174_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_201_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_212_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_215_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_6_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_41_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_42_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_54_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_59_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_67_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_69_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_71_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_79_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_80_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_81_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_100_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_109_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_122_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_126_fluent.jpg

In [10]:
print(X[0])
print(y[0])

[[[ 68  33  60]
  [ 96  28  68]
  [ 89  27  67]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 [[114  57  88]
  [166  57 117]
  [157  55 112]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 [[140  60  94]
  [190  55 118]
  [198  65 126]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 ...

 [[126  65 103]
  [194  56 123]
  [189  69 128]
  ...
  [ 29  13  72]
  [ 18   5  59]
  [ 21   6  57]]

 [[ 90  48 102]
  [145  31 116]
  [141  39 122]
  ...
  [ 26  18  68]
  [ 24  17  63]
  [ 27  19  61]]

 [[ 86  33  88]
  [122  36 120]
  [134  36 131]
  ...
  [ 23  14  63]
  [ 27  18  70]
  [ 26  14  66]]]
0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.15, random_state=8)

In [12]:
print("x_train shape:", X_train.shape)
print("x_test shape:", X_test.shape)
print('y_train shape:', y_train.shape)
print("y_test shape:", y_test.shape)

x_train shape: (4112, 224, 224, 3)
x_test shape: (726, 224, 224, 3)
y_train shape: (4112,)
y_test shape: (726,)

In [13]:
print(len(X_train), len(X_test), len(y_train), len(y_test))

4112 726 4112 726

In [14]:
from collections import Counter
print(Counter(y_train))
print(Counter(y_test))

Counter({0: 2883, 1: 1229})
Counter({0: 513, 1: 213})

In [15]:
print(X_train)

[[[[  0   0   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [  5   4  24]
   [  6   4  19]
   [  7   4  23]]

  [[  0   0   0]
   [  0   0   1]
   [  0   0   2]
   ...
   [ 23  12  47]
   [ 23  17  41]
   [  3   1  22]]

  [[  0   0   3]
   [  0   0   4]
   [  0   0   4]
   ...
   [ 23   4  57]
   [ 30  17  57]
   [  4   2  27]]

  ...

  [[ 15   5  42]
   [ 47  22  89]
   [ 55  19 110]
   ...
   [ 98  19 128]
   [138  39 131]
   [133  46 138]]

  [[  8   4  18]
   [ 20  11  38]
   [ 24  10  48]
   ...
   [ 44  11  58]
   [ 62  20  58]
   [ 59  23  60]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   2]
   [  0   0   2]
   [  0   0   2]]]


 [[[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  ...

  [[ 23  11  52]
   [ 29  10  66]
   [ 31   8  79]
   ...
   [ 30  14  77]
   [ 36  17  89]
   [ 37  16  85]]

  [[ 30  18  60]
   [ 42  23  81]
   [ 42  19  89]
   ...
   [ 36  19  85]
   [ 40  20  94]
   [ 39  18  87]]

  [[ 32  18  66]
   [ 40  18  88]
   [ 45  17  98]
   ...
   [ 40  15  87]
   [ 40  15  87]
   [ 38  15  84]]]


 [[[  1   1   0]
   [  0   0   0]
   [  0   0   0]
   ...
   [137  35 116]
   [176  56 128]
   [178  51 127]]

  [[  1   1   1]
   [  0   0   1]
   [  0   0   1]
   ...
   [149  43 124]
   [177  55 126]
   [181  53 126]]

  [[  0   0   3]
   [  1   0   5]
   [  0   0   4]
   ...
   [156  44 122]
   [178  53 120]
   [183  53 123]]

  ...

  [[ 71  22 120]
   [ 73  13 127]
   [ 34  16  82]
   ...
   [110  23 128]
   [163  44 135]
   [179  55 126]]

  [[ 32  10  56]
   [ 31   6  58]
   [ 16   8  42]
   ...
   [ 51  15  60]
   [ 74  23  61]
   [ 80  28  53]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   2]
   [  0   0   2]
   [  0   0   2]]]


 ...


 [[[  9   7  23]
   [  7   5  27]
   [  2   1  18]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[ 12   9  25]
   [ 18  15  38]
   [  2   0  18]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[ 13  10  27]
   [ 15  12  35]
   [  4   1  20]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  ...

  [[106  49  97]
   [152  43 125]
   [128  28 122]
   ...
   [  0   0   4]
   [  1   0   8]
   [  0   0   4]]

  [[105  49  98]
   [149  42 124]
   [121  26 120]
   ...
   [  4   0   3]
   [  6   0   7]
   [  3   0   5]]

  [[ 99  44  90]
   [141  42 122]
   [118  28 125]
   ...
   [  1   0   2]
   [  1   0   3]
   [  0   0   3]]]


 [[[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  ...

  [[  0   0   5]
   [  0   0   9]
   [  5   4  20]
   ...
   [134  42 127]
   [135  45 127]
   [128  46 126]]

  [[  0   0   0]
   [  1   1   2]
   [  2   1   6]
   ...
   [ 48  13  88]
   [ 50  17  90]
   [ 55  13  91]]

  [[  0   0   1]
   [  0   0   2]
   [  0   0   2]
   ...
   [ 41  15  88]
   [ 42  15  92]
   [ 42  14  90]]]


 [[[ 20  13  54]
   [ 10   7  36]
   [  6   4  33]
   ...
   [ 44  10  91]
   [ 59  12 110]
   [ 58  16 108]]

  [[ 26  19  62]
   [ 15  11  45]
   [ 15  10  44]
   ...
   [ 44  11  93]
   [ 58  13 111]
   [ 56  16 108]]

  [[ 26  16  65]
   [ 17   7  50]
   [ 14   5  48]
   ...
   [ 45  13  96]
   [ 58  15 112]
   [ 54  18 107]]

  ...

  [[  5   0  19]
   [ 16  11  23]
   [  7   1  21]
   ...
   [ 69  14 106]
   [ 71  14 115]
   [ 78  21 127]]

  [[  2   0  13]
   [  7   4  12]
   [  4   1  19]
   ...
   [ 32   9  46]
   [ 32   8  49]
   [ 33  12  54]]

  [[  0   0   2]
   [  0   0   0]
   [  1   0  11]
   ...
   [  0   0   2]
   [  0   0   2]
   [  0   0   2]]]]

In [16]:
from PIL import Image
IMAGE_DIR = "/home/alien/Git/DATA/mel_spects_interjection/"

def get_image_dimensions(image_path):
    with Image.open(image_path) as img:
        width, height = img.size
    return width, height

image_path = '/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_0_fluent.jpg'  # Change this to the path of your image file
width, height = get_image_dimensions(image_path)
print("Image width:", width)
print("Image height:", height)

Image width: 610
Image height: 450

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from sklearn.metrics import accuracy_score
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications import VGG19
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization, MultiHeadAttention
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dropout, Flatten, Dense, Input, AveragePooling2D, Attention, Reshape, TimeDistributed, Bidirectional, LSTM, GRU
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input, decode_predictions
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.layers import ConvLSTM2D
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
# from tensorflow.keras.constraints import ClipValue
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import Layer, MultiHeadAttention
from tensorflow.keras.layers import LayerNormalization

In [18]:
# def build_model(input_shape=(224, 224, 3)):
#     base_model = VGG19(weights='imagenet', include_top=True, input_tensor=Input(shape=input_shape))
#     # Get the output of the 'fc2' layer in VGG16
#     a = base_model.get_layer('fc2').output

#     # Add a Dense layer with 13 neurons
#     dense_layer = Dense(13, activation='relu')(a)

#     # Add a final output layer with sigmoid activation
#     output_layer = Dense(1, activation='sigmoid')(dense_layer)

#     # Define the model with VGG16 base and the added layers
#     model = Model(inputs=base_model.input, outputs=output_layer)

#     # Freeze the weights of the VGG16 layers
#     for layer in base_model.layers:
#         layer.trainable = False

#     return model

def build_model(input_shape=(224, 224, 3), use_float16=False):
    inputs = Input(shape=input_shape)

    # Convert to lower precision if specified
    if use_float16:
        x = tf.keras.layers.Lambda(lambda t: tf.cast(t, tf.float16))(inputs)
    else:
        x = inputs

    x = Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)
    
    x = Conv2D(128, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(128, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)
    
    x = Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = TimeDistributed(Flatten())(x)  # Flatten along the time dimension
    x = Bidirectional(LSTM(128, return_sequences=True))(x)
    x = Attention()([x, x])  # Self-attention mechanism

    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)  # Adding dropout with a rate of 0.5
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)  # Adding dropout with a rate of 0.5
    
    outputs = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=inputs, outputs=outputs)

    return model

In [19]:
  # base_model = VGG19(weights='imagenet', include_top=True,
  #                   input_tensor=Input(shape=(224, 224, 3)))
  # base_model.summary()

In [20]:
vgg_model = build_model()
vgg_model.summary()

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1730077775.191746   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730077775.213041   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730077775.218873   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730077775.232603   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730077775.238546   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730077775.243328   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730077775.376574   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730077775.377755   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730077775.380167   35758 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-10-27 21:09:35.382071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6597 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:13:00.0, compute capability: 8.6

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 224, 224,  │      1,792 │ input_layer[0][0] │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 224, 224,  │     36,928 │ conv2d[0][0]      │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d       │ (None, 112, 112,  │          0 │ conv2d_1[0][0]    │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 112, 112,  │        256 │ max_pooling2d[0]… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 112, 112,  │     73,856 │ batch_normalizat… │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_3 (Conv2D)   │ (None, 112, 112,  │    147,584 │ conv2d_2[0][0]    │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_1     │ (None, 56, 56,    │          0 │ conv2d_3[0][0]    │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 56, 56,    │        512 │ max_pooling2d_1[… │
│ (BatchNormalizatio… │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_4 (Conv2D)   │ (None, 56, 56,    │    295,168 │ batch_normalizat… │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_5 (Conv2D)   │ (None, 56, 56,    │    590,080 │ conv2d_4[0][0]    │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_2     │ (None, 28, 28,    │          0 │ conv2d_5[0][0]    │
│ (MaxPooling2D)      │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 28, 28,    │      1,024 │ max_pooling2d_2[… │
│ (BatchNormalizatio… │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed    │ (None, 28, 7168)  │          0 │ batch_normalizat… │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional       │ (None, 28, 256)   │  7,472,128 │ time_distributed… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attention           │ (None, 28, 256)   │          0 │ bidirectional[0]… │
│ (Attention)         │                   │            │ bidirectional[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 7168)      │          0 │ attention[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 512)       │  3,670,528 │ flatten_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 512)       │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 128)       │     65,664 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 128)       │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 1)         │        129 │ dropout_1[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 12,355,649 (47.13 MB)

 Trainable params: 12,354,753 (47.13 MB)

 Non-trainable params: 896 (3.50 KB)

In [21]:
from tensorflow.keras import optimizers
vgg_model.compile(
  optimizer=Adam(0.001),
  loss='binary_crossentropy',
  metrics=['accuracy']
)

In [22]:
# batch_size = 16
# history = vgg_model.fit(
#     X_train,
#     y_train,
#     batch_size=batch_size,
#     epochs=35,
#     callbacks=[
#         ReduceLROnPlateau(
#             monitor = 'accuracy',
#             factor = 0.2,
#             patience = 5,
#             verbose = 1,
#             min_lr = 0.0001
#         ),
#         EarlyStopping(
#             monitor = 'accuracy',
#             patience = 10,
#             verbose = 1,
#             restore_best_weights = True
#         )
#     ]
# )
batch_size = 36
history = vgg_model.fit(
    X_train,
    y_train,
    batch_size=batch_size,
    epochs=70,
    callbacks=[
        ReduceLROnPlateau(
            monitor = 'accuracy',
            patience = 5,
            verbose = 1,
            min_lr = 0.0001
        ),
    ]
)

Epoch 1/70

2024-10-27 21:09:39.358058: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:531] Loaded cuDNN version 8907
W0000 00:00:1730077779.428221   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.450877   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.452879   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.454279   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.458965   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.467407   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.471467   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.473243   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.475167   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.477323   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.481026   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.483047   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.485676   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.490136   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.492823   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.497231   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.500055   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.505080   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.510753   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.513796   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.517127   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.521245   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.524884   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.528470   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.532881   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.538224   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.545096   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.549953   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.555759   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.560710   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.565479   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.571845   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.577866   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.587153   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.594571   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.600711   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.609572   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.616937   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.680795   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.687566   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.694077   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.704628   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.712008   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.722663   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.730094   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.738696   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.749094   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.760350   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.771674   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.777143   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.783367   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.795389   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.807406   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.815640   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.825659   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.833678   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.841735   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.850044   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.861708   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.873085   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.886026   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.894388   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.902767   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.914492   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.927915   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.937681   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.945545   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.954462   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.962878   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.974166   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.988228   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077779.997076   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.009076   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.021319   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.033392   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.046701   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.324477   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.327261   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.329962   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.332873   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.336560   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.339314   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.342235   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.345338   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.348717   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.352883   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.356384   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.359951   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.363493   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.367140   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.371702   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.375345   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.378199   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.381443   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.385853   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.389839   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.393862   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.397768   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.402514   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.406409   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.410220   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.413906   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.419802   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.423938   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.427695   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.431721   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.436737   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.441888   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.446404   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.452363   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.458221   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.463582   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.470804   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.477046   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.482534   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.489791   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.506876   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.512473   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.518062   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.524101   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.529653   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.535847   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.541059   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.546629   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.553409   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.559279   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.565060   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.571850   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.577770   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.583782   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.590829   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.596828   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.602849   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.609595   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.617278   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.624653   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.629418   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.637312   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.645761   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.653643   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.660291   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.665865   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.674677   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.680430   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.690513   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.697787   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.706474   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.714736   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.726332   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.736713   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.745802   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.758771   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.771513   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.782688   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.793413   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.804133   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.829990   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.833107   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.837133   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.840299   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.843474   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.846681   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.849837   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.854017   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077780.857075   35904 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced

  1/115 ━━━━━━━━━━━━━━━━━━━━ 16:27 9s/step - accuracy: 0.6944 - loss: 0.6058

W0000 00:00:1730077785.026565   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.029135   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.032225   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.034942   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.038241   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.042319   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.045368   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.048648   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.052322   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.057544   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.063597   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.067545   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.071847   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.076717   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.086147   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.092603   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.101699   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.105864   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.119787   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077785.134697   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced

114/115 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.6430 - loss: 0.7497

W0000 00:00:1730077799.204142   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.205188   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.205982   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.206545   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.207214   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.207827   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.208481   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.209091   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.209972   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.210848   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.211729   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.212480   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.213160   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.213964   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.214997   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.216025   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.217067   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.217859   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.218687   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.219504   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.220316   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.221910   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.222722   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.223743   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.224915   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.226085   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.227570   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.228829   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.230119   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.231443   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.232730   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.233965   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.235298   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.237034   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.239567   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.241322   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.243055   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.253850   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.255949   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.258585   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.260502   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.262969   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.264414   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.266147   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.267756   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.269725   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.273154   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.275075   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.277684   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.280343   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.282362   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.284362   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.287082   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.289911   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.292766   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.294780   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.297640   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.299668   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.301809   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.304708   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.307507   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.310257   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.312365   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.314928   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.316884   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.319592   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.323096   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.325288   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.328240   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.331264   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.334312   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.337273   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.341530   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.344543   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.348781   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.352903   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.357919   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.370753   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.372511   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.373480   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.374515   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.375546   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.376575   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.377555   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.378672   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.379720   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.380820   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.381874   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.383033   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.384142   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.385305   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.386421   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.387936   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.389488   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.390599   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.391519   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.392693   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.393703   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.395211   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.396402   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.397583   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.398744   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.399877   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.401016   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.402428   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.403646   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.404782   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.406673   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.407892   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.409297   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.410593   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.411979   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.413474   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.414875   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.416336   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.417933   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.419536   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.430739   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.432312   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.433782   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.435318   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.436847   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.438605   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.440656   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.442280   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.443762   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.445355   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.446946   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.448582   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.450155   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.451778   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.453390   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.455003   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.457578   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.459200   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.460524   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.462220   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.463720   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.465697   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.467475   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.469187   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.471178   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.473417   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.475344   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.477454   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.479432   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.481321   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.483287   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.485350   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.487511   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.490478   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.492793   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.495190   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.497667   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.500137   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.502817   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.506503   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.518902   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.519818   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.520733   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.522101   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.523481   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.524421   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.525370   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.526334   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077799.527246   35902 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced

115/115 ━━━━━━━━━━━━━━━━━━━━ 24s 135ms/step - accuracy: 0.6431 - loss: 0.7490 - learning_rate: 0.0010
Epoch 2/70

W0000 00:00:1730077800.416563   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.424492   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.428311   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.434509   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.441190   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.448583   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.459496   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.476768   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.477696   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.478613   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.479534   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.480547   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.481440   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.482294   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.483326   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.484200   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.485250   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.486257   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.487850   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.488923   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.490342   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.492131   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.493778   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.495104   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.496428   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.497782   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.500262   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.501965   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.504271   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.505894   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.509715   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730077800.513075   35899 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced

115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 124ms/step - accuracy: 0.6771 - loss: 0.6353 - learning_rate: 0.0010
Epoch 3/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.6970 - loss: 0.6088 - learning_rate: 0.0010
Epoch 4/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.7188 - loss: 0.5630 - learning_rate: 0.0010
Epoch 5/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.7063 - loss: 0.5677 - learning_rate: 0.0010
Epoch 6/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.7105 - loss: 0.5618 - learning_rate: 0.0010
Epoch 7/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 127ms/step - accuracy: 0.7508 - loss: 0.5070 - learning_rate: 0.0010
Epoch 8/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.7691 - loss: 0.4876 - learning_rate: 0.0010
Epoch 9/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.8038 - loss: 0.4387 - learning_rate: 0.0010
Epoch 10/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 127ms/step - accuracy: 0.8222 - loss: 0.4081 - learning_rate: 0.0010
Epoch 11/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.8458 - loss: 0.3541 - learning_rate: 0.0010
Epoch 12/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.8911 - loss: 0.2790 - learning_rate: 0.0010
Epoch 13/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.8895 - loss: 0.2589 - learning_rate: 0.0010
Epoch 14/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9177 - loss: 0.1961 - learning_rate: 0.0010
Epoch 15/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9330 - loss: 0.1619 - learning_rate: 0.0010
Epoch 16/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9469 - loss: 0.1327 - learning_rate: 0.0010
Epoch 17/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 125ms/step - accuracy: 0.9617 - loss: 0.1064 - learning_rate: 0.0010
Epoch 18/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9672 - loss: 0.1084 - learning_rate: 0.0010
Epoch 19/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9676 - loss: 0.0907 - learning_rate: 0.0010
Epoch 20/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9802 - loss: 0.0576 - learning_rate: 0.0010
Epoch 21/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9618 - loss: 0.0949 - learning_rate: 0.0010
Epoch 22/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9866 - loss: 0.0424 - learning_rate: 0.0010
Epoch 23/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9867 - loss: 0.0409 - learning_rate: 0.0010
Epoch 24/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9883 - loss: 0.0319 - learning_rate: 0.0010
Epoch 25/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9829 - loss: 0.0518 - learning_rate: 0.0010
Epoch 26/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9802 - loss: 0.0640 - learning_rate: 0.0010
Epoch 27/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9852 - loss: 0.0462 - learning_rate: 0.0010
Epoch 28/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9922 - loss: 0.0213 - learning_rate: 0.0010
Epoch 29/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9887 - loss: 0.0319 - learning_rate: 0.0010
Epoch 30/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9922 - loss: 0.0221 - learning_rate: 0.0010
Epoch 31/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9859 - loss: 0.0461 - learning_rate: 0.0010
Epoch 32/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 126ms/step - accuracy: 0.9916 - loss: 0.0261 - learning_rate: 0.0010
Epoch 33/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9926 - loss: 0.0217 - learning_rate: 0.0010
Epoch 34/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9889 - loss: 0.0350 - learning_rate: 0.0010
Epoch 35/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9881 - loss: 0.0311 - learning_rate: 0.0010
Epoch 36/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9960 - loss: 0.0132 - learning_rate: 0.0010
Epoch 37/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9905 - loss: 0.0290 - learning_rate: 0.0010
Epoch 38/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9941 - loss: 0.0155 - learning_rate: 0.0010
Epoch 39/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9899 - loss: 0.0231 - learning_rate: 0.0010
Epoch 40/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9945 - loss: 0.0188 - learning_rate: 0.0010
Epoch 41/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9815 - loss: 0.0513 - learning_rate: 0.0010
Epoch 42/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9953 - loss: 0.0155 - learning_rate: 0.0010
Epoch 43/70
114/115 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.9926 - loss: 0.0228
Epoch 43: ReduceLROnPlateau reducing learning rate to 0.00010000000474974513.
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9925 - loss: 0.0229 - learning_rate: 0.0010
Epoch 44/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9967 - loss: 0.0135 - learning_rate: 1.0000e-04
Epoch 45/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9989 - loss: 0.0061 - learning_rate: 1.0000e-04
Epoch 46/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 0.9990 - loss: 0.0046 - learning_rate: 1.0000e-04
Epoch 47/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9997 - loss: 0.0020 - learning_rate: 1.0000e-04
Epoch 48/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9993 - loss: 0.0024 - learning_rate: 1.0000e-04
Epoch 49/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9998 - loss: 0.0016 - learning_rate: 1.0000e-04
Epoch 50/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 0.0011 - learning_rate: 1.0000e-04
Epoch 51/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 7.5307e-04 - learning_rate: 1.0000e-04
Epoch 52/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9998 - loss: 0.0012 - learning_rate: 1.0000e-04
Epoch 53/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 125ms/step - accuracy: 1.0000 - loss: 9.6879e-04 - learning_rate: 1.0000e-04
Epoch 54/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 7.6248e-04 - learning_rate: 1.0000e-04
Epoch 55/70
114/115 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 1.0000 - loss: 6.1635e-04
Epoch 55: ReduceLROnPlateau reducing learning rate to 0.0001.
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 6.1423e-04 - learning_rate: 1.0000e-04
Epoch 56/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 6.4425e-04 - learning_rate: 1.0000e-04
Epoch 57/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9999 - loss: 5.7168e-04 - learning_rate: 1.0000e-04
Epoch 58/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 3.4945e-04 - learning_rate: 1.0000e-04
Epoch 59/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 1.9273e-04 - learning_rate: 1.0000e-04
Epoch 60/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 1.0000 - loss: 1.7753e-04 - learning_rate: 1.0000e-04
Epoch 61/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9998 - loss: 5.3012e-04 - learning_rate: 1.0000e-04
Epoch 62/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 1.8838e-04 - learning_rate: 1.0000e-04
Epoch 63/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 1.0000 - loss: 1.5487e-04 - learning_rate: 1.0000e-04
Epoch 64/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 127ms/step - accuracy: 1.0000 - loss: 2.1780e-04 - learning_rate: 1.0000e-04
Epoch 65/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 2.1101e-04 - learning_rate: 1.0000e-04
Epoch 66/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 3.7955e-04 - learning_rate: 1.0000e-04
Epoch 67/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 14s 125ms/step - accuracy: 1.0000 - loss: 2.0922e-04 - learning_rate: 1.0000e-04
Epoch 68/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 1.2326e-04 - learning_rate: 1.0000e-04
Epoch 69/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 1.0000 - loss: 6.7579e-04 - learning_rate: 1.0000e-04
Epoch 70/70
115/115 ━━━━━━━━━━━━━━━━━━━━ 15s 126ms/step - accuracy: 0.9998 - loss: 2.4370e-04 - learning_rate: 1.0000e-04

In [25]:
# predictions
vgg_pred = vgg_model.predict(X_test, batch_size=1)

vgg_pred = np.round(vgg_pred)

  # model evaluation
confusion = confusion_matrix(y_test, vgg_pred)
print(classification_report(y_test, vgg_pred))
print(confusion)

726/726 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step
              precision    recall  f1-score   support

           0       0.88      0.92      0.90       513
           1       0.78      0.71      0.74       213

    accuracy                           0.86       726
   macro avg       0.83      0.81      0.82       726
weighted avg       0.85      0.86      0.85       726

[[471  42]
 [ 62 151]]

In [26]:
vgg_model.save('./model_interjection_AUGMENT.keras', overwrite=True)