In [1]:
import librosa
import matplotlib.pyplot as plt
import librosa.display
import os
import numpy as np
from tensorflow.keras import layers
from IPython.display import Audio
import wave
import pandas as pd
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt

2024-10-27 19:10:16.753856: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-27 19:10:16.764786: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-27 19:10:16.768301: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-27 19:10:16.777576: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-27 19:10:17.366549: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
df = pd.read_csv("../data_processing/sep28k-mfcc.csv")

In [3]:
df = df[df['NaturalPause'] == 0]
df = df[df['Interjection'] == 0]
df = df[df['Prolongation'] == 0]
df = df[df['WordRep'] == 0]
df = df[df['SoundRep'] == 0]
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
6,HeStutters,0,6,37251200,37299200,0,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
9,HeStutters,0,9,41417440,41465440,0,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
11,HeStutters,0,11,42928800,42976800,0,0,0,0,0,...,-3.798326,-6.705790,-1.544637,-6.356187,-0.987506,-3.107216,-1.422836,-3.615824,-1.171095,-1.937332

In [4]:
df = df.reset_index()
df.head()

,index,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,...,29,30,31,32,33,34,35,36,37,38
0,2,HeStutters,0,2,34809760,34857760,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
1,4,HeStutters,0,4,35721920,35769920,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
2,6,HeStutters,0,6,37251200,37299200,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
3,9,HeStutters,0,9,41417440,41465440,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
4,11,HeStutters,0,11,42928800,42976800,0,0,0,0,...,-3.798326,-6.705790,-1.544637,-6.356187,-0.987506,-3.107216,-1.422836,-3.615824,-1.171095,-1.937332

In [5]:
df = df.drop(columns=['index'])
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
0,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
1,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
2,HeStutters,0,6,37251200,37299200,0,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
3,HeStutters,0,9,41417440,41465440,0,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
4,HeStutters,0,11,42928800,42976800,0,0,0,0,0,...,-3.798326,-6.705790,-1.544637,-6.356187,-0.987506,-3.107216,-1.422836,-3.615824,-1.171095,-1.937332

In [6]:
df.to_csv("block.csv",index=False)

In [7]:
import os

def list_files(directory):
    return [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]

# Replace 'directory_path' with the path to your directory
directory_path = '/home/alien/Git/DATA/mel_spects_block'
# names_list = list_files(directory_path)
names_list = pd.read_csv("block.csv")['Name'].values.tolist()
# full_names_list = ["/home/alien/Git/DATA/mfcc_images/" + img + ".jpg" for img in names_list]
full_names_list = []
for img in names_list:
    corresponding_sound = df.loc[df['Name'] == img, 'Block'].values[0]
    if corresponding_sound == 0:
        full_names_list.append("/home/alien/Git/DATA/mel_spects_block/" + img + "_fluent.jpg")
    if corresponding_sound >= 1:
        full_names_list.append("/home/alien/Git/DATA/mel_spects_block/" + img + "_stutter.jpg")

print(full_names_list[-2])

/home/alien/Git/DATA/mel_spects_block/WomenWhoStutter_109_33_fluent.jpg

In [8]:
def load_all(imagefile_list):
    data = []
    labels = []

    for imagefile in imagefile_list:
        print(imagefile)
        image = cv2.imread(imagefile)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (224, 224))
        data.append(image)

        if "fluent" in imagefile:
            labels.append(0)
        else:
            labels.append(1)

    labels = np.array(labels)
    data = np.array(data)

    return data, labels

In [9]:
X, y = load_all(full_names_list)

/home/alien/Git/DATA/mel_spects_block/HeStutters_0_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_6_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_14_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_32_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_0_39_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_9_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_16_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_38_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_107_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_113_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_122_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_132_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_150_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_187_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_189_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_195_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_228_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_1_256_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_0_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_14_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_22_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_43_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_79_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_88_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_89_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_111_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_118_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_134_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_138_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_157_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_170_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_182_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_2_191_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_3_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_3_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_4_5_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_4_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_4_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_4_20_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_4_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_4_31_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_4_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_0_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_3_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_27_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_42_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_43_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_67_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_86_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_5_116_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_18_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_40_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_78_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_104_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_105_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_106_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_113_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_120_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_126_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_135_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_140_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_143_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_159_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_172_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_176_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_178_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_198_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_205_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_220_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_232_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_239_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_243_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_252_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_254_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_255_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_261_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_268_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_271_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_276_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_286_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_6_292_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_7_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_8_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_17_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_18_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_19_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_33_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_38_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_7_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_5_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_19_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_37_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_85_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_132_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_139_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_152_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_163_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_164_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_166_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_172_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_188_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_195_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_8_197_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_3_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_6_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_7_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_10_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_11_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_13_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_18_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_22_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_23_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_24_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_9_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_10_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_10_8_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_10_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_10_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_10_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_10_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_10_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_21_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_50_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_53_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_62_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_67_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_73_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_150_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_170_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_181_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_185_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_194_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_203_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_11_204_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_14_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_18_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_27_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_68_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_79_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_101_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_110_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_114_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_115_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_125_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_133_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_155_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_165_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_178_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_180_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_186_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_202_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_207_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_12_215_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_13_3_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_13_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_13_13_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_13_18_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_13_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_13_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_13_31_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_13_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_14_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_14_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_14_16_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_14_19_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_14_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_14_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_14_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_15_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_15_80_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_15_88_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_15_91_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_15_134_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_15_139_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_15_164_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_15_188_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_16_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_16_142_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_16_187_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_16_189_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_7_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_15_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_21_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_30_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_17_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_38_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_101_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_115_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_136_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_152_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_153_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_168_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_18_212_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_0_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_6_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_10_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_20_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_28_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_41_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_42_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_44_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_45_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_54_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_59_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_69_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_71_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_100_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_109_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_125_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_126_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_134_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_138_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_144_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_145_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_157_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_159_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_166_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_171_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_19_173_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_6_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_32_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_66_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_82_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_94_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_127_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_147_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_193_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_218_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_232_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_20_249_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_21_13_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_21_46_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_21_89_stutter.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_21_106_fluent.jpg
/home/alien/Git/DATA/mel_spects_block/HeStutters_21_125_fluent.jpg

In [10]:
print(X[0])
print(y[0])

[[[ 68  33  60]
  [ 96  28  68]
  [ 89  27  67]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 [[114  57  88]
  [166  57 117]
  [157  55 112]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 [[140  60  94]
  [190  55 118]
  [198  65 126]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 ...

 [[126  65 103]
  [194  56 123]
  [189  69 128]
  ...
  [ 29  13  72]
  [ 18   5  59]
  [ 21   6  57]]

 [[ 90  48 102]
  [145  31 116]
  [141  39 122]
  ...
  [ 26  18  68]
  [ 24  17  63]
  [ 27  19  61]]

 [[ 86  33  88]
  [122  36 120]
  [134  36 131]
  ...
  [ 23  14  63]
  [ 27  18  70]
  [ 26  14  66]]]
0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.3, random_state=9)

In [12]:
print("x_train shape:", X_train.shape)
print("x_test shape:", X_test.shape)
print('y_train shape:', y_train.shape)
print("y_test shape:", y_test.shape)

x_train shape: (1829, 224, 224, 3)
x_test shape: (784, 224, 224, 3)
y_train shape: (1829,)
y_test shape: (784,)

In [13]:
print(len(X_train), len(X_test), len(y_train), len(y_test))

1829 784 1829 784

In [14]:
from collections import Counter
print(Counter(y_train))
print(Counter(y_test))

Counter({0: 1223, 1: 606})
Counter({0: 475, 1: 309})

In [15]:
print(X_train)

[[[[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  ...

  [[ 11   7  33]
   [ 12   3  51]
   [ 33  16  81]
   ...
   [ 36  15  90]
   [ 36  16  87]
   [ 35  14  83]]

  [[ 23  14  52]
   [ 37  23  85]
   [ 44  22  99]
   ...
   [ 38  19  92]
   [ 38  20  91]
   [ 39  18  84]]

  [[ 30  18  59]
   [ 40  18  88]
   [ 47  17 104]
   ...
   [ 38  17  89]
   [ 41  17  91]
   [ 40  15  88]]]


 [[[ 29  12  42]
   [ 35  11  78]
   [ 41  13  69]
   ...
   [  7   0  15]
   [ 30   6  65]
   [ 27   9  61]]

  [[ 49  20  65]
   [ 65  21 112]
   [ 68  17 101]
   ...
   [  6   0  21]
   [ 52  21  92]
   [ 50  17  90]]

  [[ 59  19  81]
   [ 79  19 129]
   [101  33 134]
   ...
   [ 18   1  43]
   [ 56  22 100]
   [ 56  13 105]]

  ...

  [[ 96  42  98]
   [134  36 131]
   [112  29 132]
   ...
   [168  49 127]
   [182  56 130]
   [175  55 120]]

  [[ 99  40  98]
   [140  37 135]
   [110  25 130]
   ...
   [162  43 121]
   [182  55 129]
   [177  54 118]]

  [[ 95  43  91]
   [135  37 124]
   [110  26 126]
   ...
   [147  43 115]
   [174  52 121]
   [172  51 114]]]


 [[[  3   7  10]
   [  3   6  13]
   [  1   2  15]
   ...
   [  6   4  26]
   [ 17   8  49]
   [ 16  11  51]]

  [[  9   8  22]
   [ 13  11  29]
   [  6   3  24]
   ...
   [ 13   9  40]
   [ 33  25  72]
   [ 31  18  70]]

  [[ 12   8  32]
   [ 18  12  41]
   [  8   2  32]
   ...
   [  5   4  39]
   [ 27  21  72]
   [ 31  16  74]]

  ...

  [[182 111  95]
   [236 129  94]
   [232  94  89]
   ...
   [196  50  90]
   [247  89 102]
   [233  90  94]]

  [[196 105  95]
   [246 120  96]
   [237  87  93]
   ...
   [169  42 100]
   [221  84 103]
   [222  85  96]]

  [[183 102  87]
   [242 115  93]
   [226  90  89]
   ...
   [162  43 107]
   [221  81  97]
   [221  81  94]]]


 ...


 [[[ 44  15  52]
   [ 57  13  75]
   [ 36   9  60]
   ...
   [  6   1   4]
   [ 41   6  68]
   [ 41  10  68]]

  [[ 59  26  78]
   [ 90  26 116]
   [ 59  19  93]
   ...
   [  5   0  11]
   [ 70  22 107]
   [ 64  20 101]]

  [[ 67  27  94]
   [ 93  23 129]
   [ 63  15 107]
   ...
   [  6   0  22]
   [ 66  16 115]
   [ 65  15 112]]

  ...

  [[119  54 101]
   [172  47 127]
   [135  39 125]
   ...
   [ 28   2  63]
   [ 98  33 134]
   [104  31 131]]

  [[107  53 102]
   [155  44 125]
   [119  36 120]
   ...
   [ 10   0  29]
   [ 80  19 113]
   [ 80  15 117]]

  [[104  46  95]
   [146  46 121]
   [120  31 120]
   ...
   [  8   0  13]
   [ 71  16 114]
   [ 74  17 117]]]


 [[[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  ...

  [[  0   0   4]
   [  0   0   4]
   [  1   1   6]
   ...
   [ 17   6  51]
   [ 36  20  79]
   [ 35  16  79]]

  [[  0   0   4]
   [  1   0   5]
   [  0   0   2]
   ...
   [  2   1  19]
   [ 25  18  56]
   [ 29  16  68]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  1   0  12]
   [ 25  16  60]
   [ 25  14  65]]]


 [[[ 26  14  39]
   [ 41  10  75]
   [ 58  17  73]
   ...
   [  1   1   2]
   [  2   2   2]
   [  0   1   0]]

  [[ 47  22  64]
   [ 75  19 110]
   [100  32 113]
   ...
   [  0   0   7]
   [  0   0   5]
   [  0   1   4]]

  [[ 61  20  82]
   [ 94  20 131]
   [122  33 133]
   ...
   [  9   5  26]
   [  7   4  22]
   [  4   3  18]]

  ...

  [[142  63  87]
   [199  62 111]
   [213  74 115]
   ...
   [153  38 118]
   [165  46 124]
   [161  45 117]]

  [[119  52 102]
   [167  45 119]
   [176  50 119]
   ...
   [191  64 114]
   [194  64 112]
   [189  60 117]]

  [[120  52  96]
   [153  50 122]
   [167  47 125]
   ...
   [195  61 112]
   [192  59 111]
   [188  58 112]]]]

In [16]:
from PIL import Image
IMAGE_DIR = "/home/alien/Git/DATA/mel_spects_block/"

def get_image_dimensions(image_path):
    with Image.open(image_path) as img:
        width, height = img.size
    return width, height

image_path = '/home/alien/Git/DATA/mel_spects_block/HeStutters_0_0_fluent.jpg'  # Change this to the path of your image file
width, height = get_image_dimensions(image_path)
print("Image width:", width)
print("Image height:", height)

Image width: 610
Image height: 450

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from sklearn.metrics import accuracy_score
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications import VGG19
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization, MultiHeadAttention
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dropout, Flatten, Dense, Input, AveragePooling2D, Attention, Reshape, TimeDistributed, Bidirectional, LSTM, GRU
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input, decode_predictions
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
# from tensorflow.keras.constraints import ClipValue
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import Layer, MultiHeadAttention
from tensorflow.keras.layers import LayerNormalization

In [18]:
# def build_model(input_shape=(224, 224, 3)):
#     base_model = VGG19(weights='imagenet', include_top=True, input_tensor=Input(shape=input_shape))
#     # Get the output of the 'fc2' layer in VGG16
#     a = base_model.get_layer('fc2').output

#     # Add a Dense layer with 13 neurons
#     dense_layer = Dense(13, activation='relu')(a)

#     # Add a final output layer with sigmoid activation
#     output_layer = Dense(1, activation='sigmoid')(dense_layer)

#     # Define the model with VGG16 base and the added layers
#     model = Model(inputs=base_model.input, outputs=output_layer)

#     # Freeze the weights of the VGG16 layers
#     for layer in base_model.layers:
#         layer.trainable = False

#     return model
def build_model(input_shape=(224, 224, 3), use_float16=False):
    inputs = Input(shape=input_shape)

    # Convert to lower precision if specified
    if use_float16:
        x = tf.keras.layers.Lambda(lambda t: tf.cast(t, tf.float16))(inputs)
    else:
        x = inputs

    x = Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)
    
    x = Conv2D(128, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(128, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)
    
    x = Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = TimeDistributed(Flatten())(x)  # Flatten along the time dimension
    x = Bidirectional(LSTM(128, return_sequences=True))(x)
    x = Attention()([x, x])  # Self-attention mechanism

    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)  # Adding dropout with a rate of 0.5
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)  # Adding dropout with a rate of 0.5
    
    outputs = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=inputs, outputs=outputs)

    return model

In [19]:
  # base_model = VGG19(weights='imagenet', include_top=True,
  #                   input_tensor=Input(shape=(224, 224, 3)))
  # base_model.summary()

In [20]:
vgg_model = build_model()
vgg_model.summary()

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1730070621.761099   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730070621.780043   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730070621.782016   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730070621.785065   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730070621.786919   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730070621.790342   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730070621.917851   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730070621.919085   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1730070621.920202   15656 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-10-27 19:10:21.922907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6656 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:13:00.0, compute capability: 8.6

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 224, 224,  │      1,792 │ input_layer[0][0] │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 224, 224,  │     36,928 │ conv2d[0][0]      │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d       │ (None, 112, 112,  │          0 │ conv2d_1[0][0]    │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 112, 112,  │        256 │ max_pooling2d[0]… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 112, 112,  │     73,856 │ batch_normalizat… │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_3 (Conv2D)   │ (None, 112, 112,  │    147,584 │ conv2d_2[0][0]    │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_1     │ (None, 56, 56,    │          0 │ conv2d_3[0][0]    │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 56, 56,    │        512 │ max_pooling2d_1[… │
│ (BatchNormalizatio… │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_4 (Conv2D)   │ (None, 56, 56,    │    295,168 │ batch_normalizat… │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_5 (Conv2D)   │ (None, 56, 56,    │    590,080 │ conv2d_4[0][0]    │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_2     │ (None, 28, 28,    │          0 │ conv2d_5[0][0]    │
│ (MaxPooling2D)      │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 28, 28,    │      1,024 │ max_pooling2d_2[… │
│ (BatchNormalizatio… │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed    │ (None, 28, 7168)  │          0 │ batch_normalizat… │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional       │ (None, 28, 256)   │  7,472,128 │ time_distributed… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attention           │ (None, 28, 256)   │          0 │ bidirectional[0]… │
│ (Attention)         │                   │            │ bidirectional[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 7168)      │          0 │ attention[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 512)       │  3,670,528 │ flatten_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 512)       │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 128)       │     65,664 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 128)       │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 1)         │        129 │ dropout_1[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 12,355,649 (47.13 MB)

 Trainable params: 12,354,753 (47.13 MB)

 Non-trainable params: 896 (3.50 KB)

In [21]:
vgg_model.compile(
  optimizer=Adam(0.01),
  loss='binary_crossentropy',
  metrics=['accuracy']
)

In [22]:
batch_size = 40
history = vgg_model.fit(
    X_train,
    y_train,
    batch_size=batch_size,
    epochs=60,
    callbacks=[
        ReduceLROnPlateau(
            monitor = 'accuracy',
            factor = 0.2,
            patience = 5,
            verbose = 1,
            min_lr = 0.0001
        ),
        # early_stop
    ]
)

Epoch 1/60

2024-10-27 19:10:25.760760: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:531] Loaded cuDNN version 8907
W0000 00:00:1730070625.834510   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.855388   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.856950   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.858505   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.863489   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.872006   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.876094   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.878243   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.880356   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.883174   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.887144   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.889409   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.891632   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.897100   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.900990   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.905768   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.908995   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.915097   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.921829   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.925171   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.928950   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.933387   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.937374   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.941342   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.946460   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.952484   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.960098   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.965741   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.972129   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.977627   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.984023   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.990302   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070625.997324   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.008121   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.017470   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.023714   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.033374   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.042009   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.110532   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.118671   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.126934   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.139548   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.148471   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.159713   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.168682   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.177269   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.190102   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.203103   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.215511   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.221791   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.229022   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.242936   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.257251   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.267329   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.277774   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.287547   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.296825   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.306822   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.321116   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.333415   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.346839   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.357022   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.366221   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.379562   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.393781   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.404223   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.413654   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.423541   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.432870   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.446424   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.462124   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.473046   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.485341   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.497788   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.512224   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.526946   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.814301   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.818005   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.820943   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.824108   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.827244   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.830563   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.834404   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.837770   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.841458   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.845330   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.849128   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.853670   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.857610   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.861789   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.865884   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.870572   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.873750   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.877288   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.881868   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.886859   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.890990   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.895449   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.900424   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.905162   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.909503   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.913629   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.919976   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.924589   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.928980   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.933813   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.938650   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.944373   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.950123   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.956034   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.962710   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.969469   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.976560   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.984719   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.990864   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070626.998002   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.017172   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.023699   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.030097   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.036882   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.042988   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.049826   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.055855   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.062054   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.069538   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.076208   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.083307   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.090048   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.096807   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.104031   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.110726   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.118349   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.123934   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.131392   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.140894   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.148429   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.154540   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.162216   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.172677   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.180791   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.189051   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.195218   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.204803   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.210794   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.221435   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.229533   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.238819   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.248168   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.261360   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.273600   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.284590   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.298158   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.312202   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.325822   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.337725   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.348836   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.378018   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.382940   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.386915   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.390518   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.393941   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.397720   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.401383   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.405235   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070627.408805   15796 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced

45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.5980 - loss: 3.7865

W0000 00:00:1730070638.129097   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.130321   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.131489   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.132696   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.134296   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.136608   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.138913   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.140493   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.142386   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.144027   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.146305   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.147854   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.149631   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.152386   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.154401   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.157389   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.159852   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.162679   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.164977   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.167091   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.169208   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.171299   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.173283   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.176753   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.180036   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.183731   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.188090   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.192277   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.195916   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.199929   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.203534   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.207857   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.211925   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.217794   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.223121   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.227452   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.233154   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.238573   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.252651   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.257543   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.263592   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.269955   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.278641   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.286844   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.293505   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.300050   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.309136   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.317986   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.327213   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.331944   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.340961   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.351466   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.356574   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.363834   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.370764   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.381070   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.388113   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.396124   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.403330   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.413830   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.421195   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.429288   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.435844   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.446332   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.455180   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.462635   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.470187   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.478476   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.487649   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.495475   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.505560   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.516757   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.527610   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.538085   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.550987   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.562015   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.573332   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.589988   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.616294   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.621548   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.624120   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.627599   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.630288   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.633191   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.635823   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.638621   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.641573   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.645177   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.648260   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.651692   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.654761   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.657863   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.661799   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.664916   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.667816   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.670556   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.673841   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.677671   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.680562   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.684107   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.687423   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.690644   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.694494   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.697445   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.701941   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.705410   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.708547   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.712533   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.716230   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.720467   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.724197   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.728903   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.733898   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.738316   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.744177   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.749551   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.754120   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.759932   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.774602   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.780058   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.784939   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.789412   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.794427   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.798930   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.803666   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.808316   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.813929   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.819151   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.823875   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.829537   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.834840   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.839793   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.845470   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.850802   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.854734   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.860709   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.867145   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.872417   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.876890   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.882776   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.889766   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.896444   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.902388   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.906958   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.913898   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.918501   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.925583   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.932418   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.939211   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.946571   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.956235   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.964905   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.972907   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.983927   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070638.993840   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.003552   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.012352   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.020875   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.044016   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.046532   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.048932   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.051966   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.054522   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.057181   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.060382   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070639.063153   15797 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced

46/46 ━━━━━━━━━━━━━━━━━━━━ 19s 218ms/step - accuracy: 0.5988 - loss: 3.7106 - learning_rate: 0.0100
Epoch 2/60

W0000 00:00:1730070641.855609   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.858356   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.860849   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.864219   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.867247   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.871270   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.876415   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.880245   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.883795   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.887867   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.895395   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.900889   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.908583   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.912081   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.923673   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730070641.935625   15790 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced

46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6684 - loss: 0.6828 - learning_rate: 0.0100
Epoch 3/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6630 - loss: 0.6686 - learning_rate: 0.0100
Epoch 4/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6759 - loss: 0.6411 - learning_rate: 0.0100
Epoch 5/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6668 - loss: 0.6323 - learning_rate: 0.0100
Epoch 6/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6544 - loss: 0.6478 - learning_rate: 0.0100
Epoch 7/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6573 - loss: 0.6396 - learning_rate: 0.0100
Epoch 8/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6757 - loss: 0.6432 - learning_rate: 0.0100
Epoch 9/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6914 - loss: 0.6204 - learning_rate: 0.0100
Epoch 10/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6570 - loss: 0.6441 - learning_rate: 0.0100
Epoch 11/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 129ms/step - accuracy: 0.6853 - loss: 0.6260 - learning_rate: 0.0100
Epoch 12/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6543 - loss: 0.6470 - learning_rate: 0.0100
Epoch 13/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.6798 - loss: 0.6371
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0019999999552965165.
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 131ms/step - accuracy: 0.6795 - loss: 0.6372 - learning_rate: 0.0100
Epoch 14/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 130ms/step - accuracy: 0.6793 - loss: 0.6282 - learning_rate: 0.0020
Epoch 15/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 132ms/step - accuracy: 0.6781 - loss: 0.6454 - learning_rate: 0.0020
Epoch 16/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 134ms/step - accuracy: 0.6804 - loss: 0.6292 - learning_rate: 0.0020
Epoch 17/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6701 - loss: 0.6341 - learning_rate: 0.0020
Epoch 18/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.6767 - loss: 0.6292
Epoch 18: ReduceLROnPlateau reducing learning rate to 0.0003999999724328518.
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6765 - loss: 0.6293 - learning_rate: 0.0020
Epoch 19/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6646 - loss: 0.6391 - learning_rate: 4.0000e-04
Epoch 20/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 132ms/step - accuracy: 0.6482 - loss: 0.6484 - learning_rate: 4.0000e-04
Epoch 21/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6693 - loss: 0.6348 - learning_rate: 4.0000e-04
Epoch 22/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6582 - loss: 0.6420 - learning_rate: 4.0000e-04
Epoch 23/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.6728 - loss: 0.6318
Epoch 23: ReduceLROnPlateau reducing learning rate to 0.0001.
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6727 - loss: 0.6319 - learning_rate: 4.0000e-04
Epoch 24/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6702 - loss: 0.6339 - learning_rate: 1.0000e-04
Epoch 25/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6712 - loss: 0.6322 - learning_rate: 1.0000e-04
Epoch 26/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6722 - loss: 0.6329 - learning_rate: 1.0000e-04
Epoch 27/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6504 - loss: 0.6468 - learning_rate: 1.0000e-04
Epoch 28/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6795 - loss: 0.6273 - learning_rate: 1.0000e-04
Epoch 29/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6780 - loss: 0.6277 - learning_rate: 1.0000e-04
Epoch 30/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 134ms/step - accuracy: 0.6597 - loss: 0.6410 - learning_rate: 1.0000e-04
Epoch 31/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6609 - loss: 0.6403 - learning_rate: 1.0000e-04
Epoch 32/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6754 - loss: 0.6310 - learning_rate: 1.0000e-04
Epoch 33/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6681 - loss: 0.6351 - learning_rate: 1.0000e-04
Epoch 34/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6656 - loss: 0.6369 - learning_rate: 1.0000e-04
Epoch 35/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 133ms/step - accuracy: 0.6742 - loss: 0.6309 - learning_rate: 1.0000e-04
Epoch 36/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 128ms/step - accuracy: 0.6525 - loss: 0.6474 - learning_rate: 1.0000e-04
Epoch 37/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 132ms/step - accuracy: 0.6672 - loss: 0.6369 - learning_rate: 1.0000e-04
Epoch 38/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6727 - loss: 0.6318 - learning_rate: 1.0000e-04
Epoch 39/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 132ms/step - accuracy: 0.6689 - loss: 0.6354 - learning_rate: 1.0000e-04
Epoch 40/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6738 - loss: 0.6294 - learning_rate: 1.0000e-04
Epoch 41/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6781 - loss: 0.6294 - learning_rate: 1.0000e-04
Epoch 42/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6571 - loss: 0.6426 - learning_rate: 1.0000e-04
Epoch 43/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 134ms/step - accuracy: 0.6931 - loss: 0.6189 - learning_rate: 1.0000e-04
Epoch 44/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6530 - loss: 0.6457 - learning_rate: 1.0000e-04
Epoch 45/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6759 - loss: 0.6291 - learning_rate: 1.0000e-04
Epoch 46/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 134ms/step - accuracy: 0.6465 - loss: 0.6500 - learning_rate: 1.0000e-04
Epoch 47/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6660 - loss: 0.6377 - learning_rate: 1.0000e-04
Epoch 48/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6666 - loss: 0.6380 - learning_rate: 1.0000e-04
Epoch 49/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6673 - loss: 0.6353 - learning_rate: 1.0000e-04
Epoch 50/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6373 - loss: 0.6562 - learning_rate: 1.0000e-04
Epoch 51/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6636 - loss: 0.6376 - learning_rate: 1.0000e-04
Epoch 52/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6813 - loss: 0.6260 - learning_rate: 1.0000e-04
Epoch 53/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6596 - loss: 0.6403 - learning_rate: 1.0000e-04
Epoch 54/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6570 - loss: 0.6428 - learning_rate: 1.0000e-04
Epoch 55/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6806 - loss: 0.6255 - learning_rate: 1.0000e-04
Epoch 56/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 136ms/step - accuracy: 0.6786 - loss: 0.6269 - learning_rate: 1.0000e-04
Epoch 57/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6679 - loss: 0.6350 - learning_rate: 1.0000e-04
Epoch 58/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6612 - loss: 0.6388 - learning_rate: 1.0000e-04
Epoch 59/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6731 - loss: 0.6303 - learning_rate: 1.0000e-04
Epoch 60/60
46/46 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.6756 - loss: 0.6302 - learning_rate: 1.0000e-04

In [25]:
# predictions
vgg_pred = vgg_model.predict(X_test, batch_size=1)

vgg_pred = np.round(vgg_pred)

  # model evaluation
confusion = confusion_matrix(y_test, vgg_pred)
print(classification_report(y_test, vgg_pred))
print(confusion)

784/784 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step
              precision    recall  f1-score   support

           0       0.61      1.00      0.75       475
           1       0.00      0.00      0.00       309

    accuracy                           0.61       784
   macro avg       0.30      0.50      0.38       784
weighted avg       0.37      0.61      0.46       784

[[475   0]
 [309   0]]

/home/alien/Programming/env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/alien/Programming/env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/alien/Programming/env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [27]:
vgg_model.save('./model_block.keras', overwrite=True)

: