In [1]:
import librosa
import matplotlib.pyplot as plt
import librosa.display
import os
import numpy as np
from tensorflow.keras import layers
from IPython.display import Audio
import wave
from datetime import datetime
from packaging import version

import tensorflow as tf
from tensorflow import keras
import pandas as pd
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt

2024-12-22 16:19:17.273433: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1734902357.284591   51527 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734902357.287886   51527 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-22 16:19:17.300742: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
# %load_ext tensorboard

In [3]:
df = pd.read_csv("../data_processing/sep28k-mfcc.csv")

In [4]:
df = df[df['NaturalPause'] == 0]
df = df[df['Interjection'] == 0]
df = df[df['Prolongation'] == 0]
df = df[df['SoundRep'] == 0]
df = df[df['Block'] == 0]
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
6,HeStutters,0,6,37251200,37299200,0,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
9,HeStutters,0,9,41417440,41465440,0,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
11,HeStutters,0,11,42928800,42976800,0,0,0,0,0,...,-3.798326,-6.705790,-1.544637,-6.356187,-0.987506,-3.107216,-1.422836,-3.615824,-1.171095,-1.937332

In [5]:
df = df.reset_index()
df.head()

,index,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,...,29,30,31,32,33,34,35,36,37,38
0,2,HeStutters,0,2,34809760,34857760,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
1,4,HeStutters,0,4,35721920,35769920,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
2,6,HeStutters,0,6,37251200,37299200,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
3,9,HeStutters,0,9,41417440,41465440,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
4,11,HeStutters,0,11,42928800,42976800,0,0,0,0,...,-3.798326,-6.705790,-1.544637,-6.356187,-0.987506,-3.107216,-1.422836,-3.615824,-1.171095,-1.937332

In [6]:
df = df.drop(columns=['index'])
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
0,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
1,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
2,HeStutters,0,6,37251200,37299200,0,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
3,HeStutters,0,9,41417440,41465440,0,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
4,HeStutters,0,11,42928800,42976800,0,0,0,0,0,...,-3.798326,-6.705790,-1.544637,-6.356187,-0.987506,-3.107216,-1.422836,-3.615824,-1.171095,-1.937332

In [7]:
df.to_csv("wordrep.csv",index=False)

In [8]:
import os

def list_files(directory):
    return [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]

# Replace 'directory_path' with the path to your directory
directory_path = '/home/alien/Git/DATA/mel_spects_wordrep'
# names_list = list_files(directory_path)
names_list = pd.read_csv("wordrep.csv")['Name'].values.tolist()
# full_names_list = ["/home/alien/Git/DATA/mfcc_images/" + img + ".jpg" for img in names_list]
full_names_list = []
for img in names_list:
    corresponding_sound = df.loc[df['Name'] == img, 'WordRep'].values[0]
    if corresponding_sound == 0:
        full_names_list.append("/home/alien/Git/DATA/mel_spects_wordrep/" + img + "_fluent.jpg")
    if corresponding_sound >= 1:
        full_names_list.append("/home/alien/Git/DATA/mel_spects_wordrep/" + img + "_stutter.jpg")



# Replace 'directory_path' with the path to your directory
directory_path = '/home/alien/Git/DATA/mel_specaugment_wordrep'
# names_list = list_files(directory_path)
names_list = pd.read_csv("wordrep.csv")['Name'].values.tolist()
# full_names_list = ["/home/alien/Git/DATA/mfcc_images/" + img + ".jpg" for img in names_list]
for img in names_list:
    corresponding_sound = df.loc[df['Name'] == img, 'WordRep'].values[0]
    if corresponding_sound == 0:
        full_names_list.append("/home/alien/Git/DATA/mel_specaugment_wordrep/" + img + "_fluent.jpg")
    if corresponding_sound >= 1:
        full_names_list.append("/home/alien/Git/DATA/mel_specaugment_wordrep/" + img + "_stutter.jpg")

print(full_names_list[30])
print(full_names_list[-30])

/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_141_fluent.jpg
/home/alien/Git/DATA/mel_specaugment_wordrep/WomenWhoStutter_104_22_fluent.jpg

In [9]:
def load_all(imagefile_list):
    data = []
    labels = []

    for imagefile in imagefile_list:
        print(imagefile)
        image = cv2.imread(imagefile)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (224, 224))
        data.append(image)

        if "fluent" in imagefile:
            labels.append(0)
        else:
            labels.append(1)

    labels = np.array(labels)
    data = np.array(data)

    return data, labels

In [10]:
X, y = load_all(full_names_list)

/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_6_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_32_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_1_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_1_8_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_1_98_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_1_107_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_1_193_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_1_195_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_1_228_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_1_256_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_14_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_43_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_88_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_118_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_149_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_165_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_170_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_171_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_182_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_2_184_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_3_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_3_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_3_33_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_5_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_6_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_28_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_31_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_4_37_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_42_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_43_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_67_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_78_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_82_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_86_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_116_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_5_122_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_5_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_25_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_40_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_48_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_78_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_104_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_105_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_113_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_120_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_126_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_135_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_140_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_143_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_159_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_176_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_189_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_193_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_198_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_204_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_220_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_232_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_239_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_254_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_255_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_261_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_268_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_275_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_276_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_286_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_6_292_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_12_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_17_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_18_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_38_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_7_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_5_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_19_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_114_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_132_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_139_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_163_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_164_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_166_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_172_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_194_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_195_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_8_197_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_3_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_7_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_10_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_9_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_10_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_10_1_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_10_8_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_10_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_10_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_10_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_10_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_10_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_45_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_62_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_67_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_73_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_125_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_128_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_150_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_181_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_194_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_11_204_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_14_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_18_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_27_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_31_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_68_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_79_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_80_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_101_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_114_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_125_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_133_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_143_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_165_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_178_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_202_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_12_207_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_13_3_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_13_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_13_13_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_13_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_13_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_13_31_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_13_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_14_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_14_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_14_19_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_14_25_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_14_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_14_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_14_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_28_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_59_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_91_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_103_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_139_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_149_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_164_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_187_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_15_188_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_16_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_16_187_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_16_189_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_17_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_17_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_17_7_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_17_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_17_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_17_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_17_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_17_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_101_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_115_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_136_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_153_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_168_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_18_212_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_6_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_41_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_42_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_54_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_59_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_66_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_69_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_71_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_100_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_109_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_126_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_134_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_145_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_159_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_19_173_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_32_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_37_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_66_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_82_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_94_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_127_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_147_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_186_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_232_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_20_249_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_13_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_31_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_33_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_46_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_57_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_76_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_85_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_86_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_106_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_125_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_127_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_129_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_158_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_163_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_174_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_204_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_21_220_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_22_3_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_22_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_22_68_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_22_144_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_22_147_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_22_163_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_22_193_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_22_206_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_8_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_75_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_80_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_91_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_116_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_142_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_23_210_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HVSA_0_30_stutter.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HVSA_0_69_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HVSA_1_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HVSA_1_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_wordrep/HVSA_1_35_fluent.jpg

In [11]:
print(X[0])
print(y[0])

[[[ 68  33  60]
  [ 96  28  68]
  [ 89  27  67]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 [[114  57  88]
  [166  57 117]
  [157  55 112]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 [[140  60  94]
  [190  55 118]
  [198  65 126]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 ...

 [[126  65 103]
  [194  56 123]
  [189  69 128]
  ...
  [ 29  13  72]
  [ 18   5  59]
  [ 21   6  57]]

 [[ 90  48 102]
  [145  31 116]
  [141  39 122]
  ...
  [ 26  18  68]
  [ 24  17  63]
  [ 27  19  61]]

 [[ 86  33  88]
  [122  36 120]
  [134  36 131]
  ...
  [ 23  14  63]
  [ 27  18  70]
  [ 26  14  66]]]
0

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=88)

In [13]:
print("x_train shape:", X_train.shape)
print("x_test shape:", X_test.shape)
print('y_train shape:', y_train.shape)
print("y_test shape:", y_test.shape)

x_train shape: (3364, 224, 224, 3)
x_test shape: (842, 224, 224, 3)
y_train shape: (3364,)
y_test shape: (842,)

In [14]:
print(len(X_train), len(X_test), len(y_train), len(y_test))

3364 842 3364 842

In [15]:
from collections import Counter
print(Counter(y_train))
print(Counter(y_test))

Counter({np.int64(0): 2700, np.int64(1): 664})
Counter({np.int64(0): 696, np.int64(1): 146})

In [16]:
print(X_train)

[[[[ 24  19  49]
   [  3   0  24]
   [  7   4  23]
   ...
   [184  61 127]
   [173  48 115]
   [110  29 135]]

  [[ 31  25  60]
   [  6   2  30]
   [ 15  12  34]
   ...
   [178  55 122]
   [174  51 117]
   [105  26 131]]

  [[ 29  22  64]
   [  6   1  36]
   [ 13   8  37]
   ...
   [175  54 123]
   [173  52 117]
   [104  27 128]]

  ...

  [[ 53  19 101]
   [ 39   3  86]
   [ 50  15  96]
   ...
   [ 60  18 105]
   [ 62  24 107]
   [  3   0  15]]

  [[ 22   8  48]
   [ 18   4  44]
   [ 23   9  47]
   ...
   [ 26   9  45]
   [ 26  12  44]
   [  3   0   5]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   2]
   [  0   0   2]
   [  0   0   2]]]


 [[[ 49  22  45]
   [ 63  23  68]
   [ 63  18  75]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[ 85  43  80]
   [107  41 110]
   [104  29 115]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[ 98  39  92]
   [126  40 125]
   [132  35 137]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  ...

  [[126  59  86]
   [185  54 117]
   [158  50 118]
   ...
   [ 31  13  78]
   [ 31  13  78]
   [ 31  11  75]]

  [[139  63  81]
   [203  62 113]
   [182  62 116]
   ...
   [ 43  18  91]
   [ 47  21  96]
   [ 49  19  94]]

  [[142  64  89]
   [204  58 107]
   [184  62 109]
   ...
   [ 41  13  90]
   [ 51  17 101]
   [ 51  18 100]]]


 [[[ 54  24  51]
   [ 74  19  75]
   [ 53  13  61]
   ...
   [  2   1   8]
   [ 10   6  38]
   [ 10   7  35]]

  [[ 87  45  88]
   [124  44 129]
   [ 92  29 104]
   ...
   [  2   1  11]
   [ 23  17  53]
   [ 23  16  56]]

  [[ 97  43 100]
   [125  32 135]
   [100  24 118]
   ...
   [  2   1  13]
   [ 25  18  60]
   [ 21  13  62]]

  ...

  [[ 96  44 102]
   [147  41 130]
   [113  37 129]
   ...
   [ 74   9  99]
   [163  52 130]
   [164  50 122]]

  [[ 78  37  96]
   [123  30 120]
   [ 86  24 116]
   ...
   [ 70   9  97]
   [163  51 130]
   [162  49 121]]

  [[ 82  39  95]
   [115  33 119]
   [ 90  22 121]
   ...
   [ 58  16  90]
   [158  45 127]
   [151  46 120]]]


 ...


 [[[150  41 126]
   [116  23 120]
   [116  30 130]
   ...
   [ 41  12  58]
   [ 90  26 119]
   [ 89  22 127]]

  [[163  55 140]
   [116  25 122]
   [122  37 137]
   ...
   [ 39  11  57]
   [ 90  26 119]
   [ 91  24 129]]

  [[165  57 141]
   [118  27 124]
   [118  36 137]
   ...
   [ 39  11  57]
   [ 90  26 120]
   [ 92  24 130]]

  ...

  [[ 56  15  87]
   [119  43 132]
   [132  36 139]
   ...
   [ 14   9  45]
   [ 43  15  88]
   [ 84  28 118]]

  [[ 26   8  43]
   [ 53  20  62]
   [ 60  19  65]
   ...
   [  9   4  24]
   [ 20   5  41]
   [ 40  13  54]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [  0   0   2]
   [  0   0   2]
   [  0   0   2]]]


 [[[ 75  18 128]
   [ 63  12 108]
   [163  73 117]
   ...
   [  4   1   2]
   [  2   0   6]
   [  3   0  14]]

  [[120  40 141]
   [117  45 133]
   [190  87 125]
   ...
   [  2   7   9]
   [  0   6   7]
   [  0   1   4]]

  [[137  33 127]
   [134  39 117]
   [196  78 113]
   ...
   [  5   5  22]
   [  3   6  12]
   [  0   2   0]]

  ...

  [[101  26 122]
   [105  27 131]
   [180  76 112]
   ...
   [ 96  21 128]
   [ 95  27 128]
   [ 72  14 109]]

  [[ 49  13  56]
   [ 46  14  56]
   [166  76  90]
   ...
   [ 40  13  59]
   [ 40  16  60]
   [ 27   8  49]]

  [[  3   0   4]
   [  0   5   0]
   [149  74  72]
   ...
   [  0   0   2]
   [  0   0   2]
   [  0   0   2]]]


 [[[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [ 81  31  69]
   [ 42  14  72]
   [ 35  15  61]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [141  62 123]
   [ 75  20 102]
   [ 72  23 107]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [160  54 129]
   [108  29 125]
   [101  27 128]]

  ...

  [[ 96  46  84]
   [136  41 118]
   [119  37 124]
   ...
   [175  51 109]
   [201  67 111]
   [197  66 115]]

  [[ 87  41  93]
   [123  33 126]
   [ 99  24 127]
   ...
   [163  38 114]
   [193  58 119]
   [191  60 116]]

  [[ 85  38  91]
   [118  33 125]
   [ 92  22 124]
   ...
   [148  39 117]
   [186  55 116]
   [182  54 110]]]]

In [17]:
from PIL import Image
IMAGE_DIR = "/home/alien/Git/DATA/mel_spects_wordrep/"

def get_image_dimensions(image_path):
    with Image.open(image_path) as img:
        width, height = img.size
    return width, height

image_path = '/home/alien/Git/DATA/mel_spects_wordrep/HeStutters_0_0_fluent.jpg'  # Change this to the path of your image file
width, height = get_image_dimensions(image_path)
print("Image width:", width)
print("Image height:", height)

Image width: 610
Image height: 450

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from sklearn.metrics import accuracy_score
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications import VGG19
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization, MultiHeadAttention
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dropout, Flatten, Dense, Input, AveragePooling2D, Attention, Reshape, TimeDistributed, Bidirectional, LSTM, GRU
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input, decode_predictions
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
# from tensorflow.keras.constraints import ClipValue
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import Layer, MultiHeadAttention
from tensorflow.keras.layers import LayerNormalization
from tensorflow.keras.layers import Input, ConvLSTM2D, MaxPooling2D, BatchNormalization, TimeDistributed, Flatten, Bidirectional, LSTM, Attention, Dropout, Dense

In [19]:
# def build_model(input_shape=(224, 224, 3)):
#     base_model = VGG19(weights='imagenet', include_top=True, input_tensor=Input(shape=input_shape))
#     # Get the output of the 'fc2' layer in VGG16
#     a = base_model.get_layer('fc2').output

#     # Add a Dense layer with 13 neurons
#     dense_layer = Dense(13, activation='relu')(a)

#     # Add a final output layer with sigmoid activation
#     output_layer = Dense(1, activation='sigmoid')(dense_layer)

#     # Define the model with VGG16 base and the added layers
#     model = Model(inputs=base_model.input, outputs=output_layer)

#     # Freeze the weights of the VGG16 layers
#     for layer in base_model.layers:
#         layer.trainable = False

#     return model

def build_model(input_shape=(224, 224, 3), use_float16=False):
    inputs = Input(shape=input_shape)

    # Convert to lower precision if specified
    if use_float16:
        x = tf.keras.layers.Lambda(lambda t: tf.cast(t, tf.float16))(inputs)
    else:
        x = inputs

    x = Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)
    
    x = Conv2D(128, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(128, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)
    
    x = Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = TimeDistributed(Flatten())(x)  # Flatten along the time dimension
    x = Bidirectional(LSTM(128, return_sequences=True))(x)
    x = Attention()([x, x])  # Self-attention mechanism

    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)  # Adding dropout with a rate of 0.5
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)  # Adding dropout with a rate of 0.5
    
    outputs = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=inputs, outputs=outputs)

    return model

In [20]:
  # base_model = VGG19(weights='imagenet', include_top=True,
  #                   input_tensor=Input(shape=(224, 224, 3)))
  # base_model.summary()

In [21]:
vgg_model = build_model()
vgg_model.summary()

I0000 00:00:1734902364.868147   51527 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7196 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:13:00.0, compute capability: 8.6

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 224, 224,  │      1,792 │ input_layer[0][0] │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 224, 224,  │     36,928 │ conv2d[0][0]      │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d       │ (None, 112, 112,  │          0 │ conv2d_1[0][0]    │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 112, 112,  │        256 │ max_pooling2d[0]… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 112, 112,  │     73,856 │ batch_normalizat… │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_3 (Conv2D)   │ (None, 112, 112,  │    147,584 │ conv2d_2[0][0]    │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_1     │ (None, 56, 56,    │          0 │ conv2d_3[0][0]    │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 56, 56,    │        512 │ max_pooling2d_1[… │
│ (BatchNormalizatio… │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_4 (Conv2D)   │ (None, 56, 56,    │    295,168 │ batch_normalizat… │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_5 (Conv2D)   │ (None, 56, 56,    │    590,080 │ conv2d_4[0][0]    │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_2     │ (None, 28, 28,    │          0 │ conv2d_5[0][0]    │
│ (MaxPooling2D)      │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 28, 28,    │      1,024 │ max_pooling2d_2[… │
│ (BatchNormalizatio… │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed    │ (None, 28, 7168)  │          0 │ batch_normalizat… │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional       │ (None, 28, 256)   │  7,472,128 │ time_distributed… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attention           │ (None, 28, 256)   │          0 │ bidirectional[0]… │
│ (Attention)         │                   │            │ bidirectional[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 7168)      │          0 │ attention[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 512)       │  3,670,528 │ flatten_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 512)       │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 128)       │     65,664 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 128)       │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 1)         │        129 │ dropout_1[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 12,355,649 (47.13 MB)

 Trainable params: 12,354,753 (47.13 MB)

 Non-trainable params: 896 (3.50 KB)

In [ ]:
vgg_model.compile(
  optimizer=Adam(0.001),
  loss='binary_crossentropy',
  metrics=['accuracy']
)

In [23]:
from datetime import datetime
# batch_size = 16
# history = vgg_model.fit(
#     X_train,
#     y_train,
#     batch_size=batch_size,
#     epochs=35,
#     callbacks=[
#         ReduceLROnPlateau(
#             monitor = 'accuracy',
#             factor = 0.2,
#             patience = 5,
#             verbose = 1,
#             min_lr = 0.0001
#         ),
#         EarlyStopping(
#             monitor = 'accuracy',
#             patience = 10,
#             verbose = 1,
#             restore_best_weights = True
#         )
#     ]
# )

# early_stop = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)
# reduce_lr = ReduceLROnPlateau(monitor='accuracy', factor=0.2, patience=5, verbose=1, min_lr=0.0001)
logdir="./logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

batch_size = 40
history = vgg_model.fit(
    X_train,
    y_train,
    batch_size=batch_size,
    epochs=60,
    callbacks=[
        ReduceLROnPlateau(
            monitor = 'accuracy',
            factor = 0.2,
            patience = 5,
            verbose = 1,
            min_lr = 0.0001
        ),
        tensorboard_callback
        # early_stop  
    ]
)

Epoch 1/60

I0000 00:00:1734902369.337905   51674 cuda_dnn.cc:529] Loaded cuDNN version 90300

85/85 ━━━━━━━━━━━━━━━━━━━━ 20s 132ms/step - accuracy: 0.7362 - loss: 0.6240 - learning_rate: 0.0010
Epoch 2/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.7936 - loss: 0.5384 - learning_rate: 0.0010
Epoch 3/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.7930 - loss: 0.5249 - learning_rate: 0.0010
Epoch 4/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.7953 - loss: 0.5052 - learning_rate: 0.0010
Epoch 5/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.8045 - loss: 0.5004 - learning_rate: 0.0010
Epoch 6/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.8121 - loss: 0.4734 - learning_rate: 0.0010
Epoch 7/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.8048 - loss: 0.4500 - learning_rate: 0.0010
Epoch 8/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.8023 - loss: 0.4232 - learning_rate: 0.0010
Epoch 9/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.8143 - loss: 0.3950 - learning_rate: 0.0010
Epoch 10/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.8510 - loss: 0.3453 - learning_rate: 0.0010
Epoch 11/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.8656 - loss: 0.3148 - learning_rate: 0.0010
Epoch 12/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 129ms/step - accuracy: 0.8993 - loss: 0.2486 - learning_rate: 0.0010
Epoch 13/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 129ms/step - accuracy: 0.9284 - loss: 0.1827 - learning_rate: 0.0010
Epoch 14/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 129ms/step - accuracy: 0.9481 - loss: 0.1432 - learning_rate: 0.0010
Epoch 15/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 129ms/step - accuracy: 0.9471 - loss: 0.1492 - learning_rate: 0.0010
Epoch 16/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9670 - loss: 0.0924 - learning_rate: 0.0010
Epoch 17/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9572 - loss: 0.1101 - learning_rate: 0.0010
Epoch 18/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9544 - loss: 0.1218 - learning_rate: 0.0010
Epoch 19/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9755 - loss: 0.0723 - learning_rate: 0.0010
Epoch 20/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9861 - loss: 0.0369 - learning_rate: 0.0010
Epoch 21/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9797 - loss: 0.0463 - learning_rate: 0.0010
Epoch 22/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9779 - loss: 0.0573 - learning_rate: 0.0010
Epoch 23/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9857 - loss: 0.0400 - learning_rate: 0.0010
Epoch 24/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9888 - loss: 0.0310 - learning_rate: 0.0010
Epoch 25/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9834 - loss: 0.0410 - learning_rate: 0.0010
Epoch 26/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9884 - loss: 0.0338 - learning_rate: 0.0010
Epoch 27/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9845 - loss: 0.0535 - learning_rate: 0.0010
Epoch 28/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9918 - loss: 0.0289 - learning_rate: 0.0010
Epoch 29/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9914 - loss: 0.0249 - learning_rate: 0.0010
Epoch 30/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9932 - loss: 0.0189 - learning_rate: 0.0010
Epoch 31/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9943 - loss: 0.0185 - learning_rate: 0.0010
Epoch 32/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9928 - loss: 0.0227 - learning_rate: 0.0010
Epoch 33/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9941 - loss: 0.0173 - learning_rate: 0.0010
Epoch 34/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9938 - loss: 0.0147 - learning_rate: 0.0010
Epoch 35/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9879 - loss: 0.0375 - learning_rate: 0.0010
Epoch 36/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9821 - loss: 0.0472 - learning_rate: 0.0010
Epoch 37/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9931 - loss: 0.0197 - learning_rate: 0.0010
Epoch 38/60
84/85 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.9894 - loss: 0.0346
Epoch 38: ReduceLROnPlateau reducing learning rate to 0.00020000000949949026.
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9893 - loss: 0.0347 - learning_rate: 0.0010
Epoch 39/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9963 - loss: 0.0163 - learning_rate: 2.0000e-04
Epoch 40/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9979 - loss: 0.0065 - learning_rate: 2.0000e-04
Epoch 41/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 1.0000 - loss: 0.0023 - learning_rate: 2.0000e-04
Epoch 42/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9999 - loss: 0.0023 - learning_rate: 2.0000e-04
Epoch 43/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 1.0000 - loss: 0.0019 - learning_rate: 2.0000e-04
Epoch 44/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 1.0000 - loss: 0.0011 - learning_rate: 2.0000e-04
Epoch 45/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 0.9988 - loss: 0.0020 - learning_rate: 2.0000e-04
Epoch 46/60
84/85 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.9993 - loss: 0.0014
Epoch 46: ReduceLROnPlateau reducing learning rate to 0.0001.
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9993 - loss: 0.0014 - learning_rate: 2.0000e-04
Epoch 47/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9992 - loss: 0.0013 - learning_rate: 1.0000e-04
Epoch 48/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 1.0000 - loss: 5.2385e-04 - learning_rate: 1.0000e-04
Epoch 49/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 1.0000 - loss: 5.8524e-04 - learning_rate: 1.0000e-04
Epoch 50/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 1.0000 - loss: 4.6849e-04 - learning_rate: 1.0000e-04
Epoch 51/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 0.9998 - loss: 4.0990e-04 - learning_rate: 1.0000e-04
Epoch 52/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 1.0000 - loss: 5.0527e-04 - learning_rate: 1.0000e-04
Epoch 53/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 1.0000 - loss: 3.9530e-04 - learning_rate: 1.0000e-04
Epoch 54/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 1.0000 - loss: 3.1844e-04 - learning_rate: 1.0000e-04
Epoch 55/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 1.0000 - loss: 3.8685e-04 - learning_rate: 1.0000e-04
Epoch 56/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 1.0000 - loss: 7.7995e-04 - learning_rate: 1.0000e-04
Epoch 57/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 127ms/step - accuracy: 1.0000 - loss: 4.5337e-04 - learning_rate: 1.0000e-04
Epoch 58/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 1.0000 - loss: 2.3965e-04 - learning_rate: 1.0000e-04
Epoch 59/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 1.0000 - loss: 9.4352e-04 - learning_rate: 1.0000e-04
Epoch 60/60
85/85 ━━━━━━━━━━━━━━━━━━━━ 11s 128ms/step - accuracy: 1.0000 - loss: 5.1026e-04 - learning_rate: 1.0000e-04

In [24]:
# predictions
vgg_pred = vgg_model.predict(X_test, batch_size=1)

vgg_pred = np.round(vgg_pred)

  # model evaluation
confusion = confusion_matrix(y_test, vgg_pred)
print(classification_report(y_test, vgg_pred))
print(confusion)

842/842 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step
              precision    recall  f1-score   support

           0       0.90      0.96      0.93       696
           1       0.73      0.47      0.57       146

    accuracy                           0.88       842
   macro avg       0.81      0.71      0.75       842
weighted avg       0.87      0.88      0.87       842

[[671  25]
 [ 78  68]]

In [25]:
vgg_model.save('./model_wordrep_AUGMENT.keras', overwrite=True)