In [1]:
import librosa
import matplotlib.pyplot as plt
import librosa.display
import os
import numpy as np
from tensorflow.keras import layers
from IPython.display import Audio
import wave
import pandas as pd
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt

2025-02-17 16:48:43.760452: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1739828923.771408  240910 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739828923.774678  240910 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-17 16:48:43.788824: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
df = pd.read_csv("../data_processing/sep28k-mfcc.csv")

In [3]:
df = df[df['NaturalPause'] == 0]
df = df[df['Block'] == 0]
df = df[df['Prolongation'] == 0]
df = df[df['WordRep'] == 0]
df = df[df['SoundRep'] == 0]
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
6,HeStutters,0,6,37251200,37299200,0,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
9,HeStutters,0,9,41417440,41465440,0,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
10,HeStutters,0,10,41861760,41909760,0,0,0,0,0,...,-2.898894,-6.209611,-3.659979,-5.923317,-2.773856,-3.547750,2.452112,1.432807,3.639793,2.238830

In [4]:
df = df.reset_index()
df.head()

,index,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,...,29,30,31,32,33,34,35,36,37,38
0,2,HeStutters,0,2,34809760,34857760,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
1,4,HeStutters,0,4,35721920,35769920,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
2,6,HeStutters,0,6,37251200,37299200,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
3,9,HeStutters,0,9,41417440,41465440,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
4,10,HeStutters,0,10,41861760,41909760,0,0,0,0,...,-2.898894,-6.209611,-3.659979,-5.923317,-2.773856,-3.547750,2.452112,1.432807,3.639793,2.238830

In [5]:
df = df.drop(columns=['index'])
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
0,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
1,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
2,HeStutters,0,6,37251200,37299200,0,0,0,0,0,...,-4.985494,-6.181957,-2.396787,-6.544606,-2.319257,-3.688410,-0.221778,-1.690031,0.664374,-0.303436
3,HeStutters,0,9,41417440,41465440,0,0,0,0,0,...,-4.798577,-6.274436,-4.889234,-5.795599,-4.400376,-4.176473,-0.957432,-3.210292,0.577023,1.042720
4,HeStutters,0,10,41861760,41909760,0,0,0,0,0,...,-2.898894,-6.209611,-3.659979,-5.923317,-2.773856,-3.547750,2.452112,1.432807,3.639793,2.238830

In [6]:
df.to_csv("interjection.csv",index=False)

In [7]:
import os

def list_files(directory):
    return [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]

# Replace 'directory_path' with the path to your directory
directory_path = '/home/alien/Git/DATA/mel_spects_interjection'
# names_list = list_files(directory_path)
names_list = pd.read_csv("interjection.csv")['Name'].values.tolist()
# full_names_list = ["/home/alien/Git/DATA/mfcc_images/" + img + ".jpg" for img in names_list]
full_names_list = []
for img in names_list:
    corresponding_sound = df.loc[df['Name'] == img, 'Interjection'].values[0]
    if corresponding_sound == 0:
        full_names_list.append("/home/alien/Git/DATA/mel_spects_interjection/" + img + "_fluent.jpg")
    if corresponding_sound >= 1:
        full_names_list.append("/home/alien/Git/DATA/mel_spects_interjection/" + img + "_stutter.jpg")

print(full_names_list[-2])

/home/alien/Git/DATA/mel_spects_interjection/WomenWhoStutter_109_35_stutter.jpg

In [8]:
def load_all(imagefile_list):
    data = []
    labels = []

    for imagefile in imagefile_list:
        print(imagefile)
        image = cv2.imread(imagefile)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (224, 224))
        data.append(image)

        if "fluent" in imagefile:
            labels.append(0)
        else:
            labels.append(1)

    labels = np.array(labels)
    data = np.array(data)

    return data, labels

In [9]:
X, y = load_all(full_names_list)

/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_6_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_10_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_32_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_103_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_107_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_178_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_195_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_228_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_1_256_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_14_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_43_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_52_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_88_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_118_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_170_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_180_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_2_182_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_2_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_4_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_3_29_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_5_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_7_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_10_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_31_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_4_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_42_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_43_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_67_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_75_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_86_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_5_116_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_17_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_32_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_40_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_77_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_78_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_102_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_104_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_105_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_113_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_120_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_126_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_135_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_140_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_143_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_146_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_156_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_159_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_167_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_176_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_191_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_198_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_199_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_220_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_232_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_239_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_253_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_254_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_255_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_256_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_261_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_268_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_276_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_286_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_6_292_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_11_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_14_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_17_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_18_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_24_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_38_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_7_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_5_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_19_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_58_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_132_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_139_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_163_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_164_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_166_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_172_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_195_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_8_197_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_3_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_5_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_7_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_9_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_10_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_29_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_9_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_0_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_8_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_13_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_14_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_20_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_26_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_30_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_31_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_10_36_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_25_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_62_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_67_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_73_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_106_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_118_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_150_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_179_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_181_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_188_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_194_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_11_204_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_0_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_12_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_14_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_18_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_27_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_68_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_79_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_101_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_105_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_114_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_120_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_125_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_127_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_133_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_141_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_142_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_148_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_158_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_165_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_178_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_201_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_202_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_206_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_12_207_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_3_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_4_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_10_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_13_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_25_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_29_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_31_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_35_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_13_36_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_12_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_17_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_19_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_33_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_37_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_14_39_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_91_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_139_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_140_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_164_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_15_188_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_56_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_186_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_187_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_16_189_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_1_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_2_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_3_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_7_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_11_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_12_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_22_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_24_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_28_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_36_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_17_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_11_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_20_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_22_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_37_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_57_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_58_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_59_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_60_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_77_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_84_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_101_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_115_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_136_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_153_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_168_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_174_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_184_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_201_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_212_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_18_215_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_6_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_15_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_16_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_21_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_26_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_34_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_41_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_42_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_54_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_59_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_67_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_69_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_71_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_79_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_80_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_81_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_100_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_109_fluent.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_122_stutter.jpg
/home/alien/Git/DATA/mel_spects_interjection/HeStutters_19_126_fluent.jpg

In [10]:
print(X[0])
print(y[0])

[[[ 68  33  60]
  [ 96  28  68]
  [ 89  27  67]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 [[114  57  88]
  [166  57 117]
  [157  55 112]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 [[140  60  94]
  [190  55 118]
  [198  65 126]
  ...
  [  0   0   4]
  [  0   0   4]
  [  0   0   2]]

 ...

 [[126  65 103]
  [194  56 123]
  [189  69 128]
  ...
  [ 29  13  72]
  [ 18   5  59]
  [ 21   6  57]]

 [[ 90  48 102]
  [145  31 116]
  [141  39 122]
  ...
  [ 26  18  68]
  [ 24  17  63]
  [ 27  19  61]]

 [[ 86  33  88]
  [122  36 120]
  [134  36 131]
  ...
  [ 23  14  63]
  [ 27  18  70]
  [ 26  14  66]]]
0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=12)

In [12]:
print("x_train shape:", X_train.shape)
print("x_test shape:", X_test.shape)
print('y_train shape:', y_train.shape)
print("y_test shape:", y_test.shape)

x_train shape: (1935, 224, 224, 3)
x_test shape: (484, 224, 224, 3)
y_train shape: (1935,)
y_test shape: (484,)

In [13]:
print(len(X_train), len(X_test), len(y_train), len(y_test))

1935 484 1935 484

In [14]:
from collections import Counter
print(Counter(y_train))
print(Counter(y_test))

Counter({np.int64(0): 1367, np.int64(1): 568})
Counter({np.int64(0): 331, np.int64(1): 153})

In [15]:
print(X_train)

[[[[  4   4   5]
   [  2   2   9]
   [  4   2  18]
   ...
   [ 66  22  67]
   [ 71  25  69]
   [ 72  25  67]]

  [[  4   3  11]
   [  5   3  18]
   [  8   4  27]
   ...
   [110  41 117]
   [120  50 124]
   [119  49 118]]

  [[  5   3  19]
   [  4   0  24]
   [ 13   8  39]
   ...
   [109  26 125]
   [116  31 128]
   [115  30 123]]

  ...

  [[ 13  12  41]
   [ 29  12  59]
   [ 26   3  56]
   ...
   [ 55  14 108]
   [ 58  16 113]
   [ 57  15 107]]

  [[  9  15  34]
   [ 24  17  51]
   [ 20   8  46]
   ...
   [ 53  15 107]
   [ 57  18 111]
   [ 56  16 107]]

  [[ 14  13  34]
   [ 18  12  48]
   [ 16   9  48]
   ...
   [ 53  15 103]
   [ 57  15 108]
   [ 59  16 108]]]


 [[[ 25  12  34]
   [ 32  11  54]
   [ 39  12  65]
   ...
   [ 31  11  61]
   [ 58  20  74]
   [ 57  20  65]]

  [[ 51  18  77]
   [ 66  21 106]
   [ 71  17 116]
   ...
   [ 56  17  91]
   [ 98  35 112]
   [104  37 119]]

  [[ 65  16  94]
   [ 88  24 127]
   [ 94  21 139]
   ...
   [ 79  18 115]
   [125  42 130]
   [129  35 128]]

  ...

  [[135  59  88]
   [199  55 124]
   [166  47 118]
   ...
   [ 34  13  69]
   [ 30   9  62]
   [ 28   7  64]]

  [[136  58  89]
   [198  54 124]
   [166  47 118]
   ...
   [ 47  16 103]
   [ 53  19 112]
   [ 57  19 103]]

  [[134  58  87]
   [190  56 120]
   [156  47 114]
   ...
   [ 48  14 100]
   [ 61  16 115]
   [ 62  16 109]]]


 [[[ 13   7  10]
   [ 11   5  26]
   [  9   5  34]
   ...
   [ 16   6  38]
   [ 58  19  68]
   [ 59  18  71]]

  [[ 16  10  25]
   [ 20  11  46]
   [ 21  14  58]
   ...
   [ 25   3  52]
   [ 99  41 113]
   [ 99  35 113]]

  [[ 26  17  49]
   [ 27  17  68]
   [ 26  16  73]
   ...
   [ 36   6  73]
   [102  35 124]
   [110  30 127]]

  ...

  [[161  76  89]
   [227  76 109]
   [211  81 105]
   ...
   [147  52 140]
   [140  43 136]
   [134  43 131]]

  [[146  68  89]
   [206  63 108]
   [179  57 107]
   ...
   [ 87  16 118]
   [103  28 136]
   [102  28 120]]

  [[135  61  88]
   [200  60 105]
   [171  49 115]
   ...
   [ 77  13 115]
   [ 99  28 129]
   [ 99  28 123]]]


 ...


 [[[ 66  32  50]
   [112  32  64]
   [ 88  31  59]
   ...
   [  2   1   7]
   [  0   0   0]
   [  0   0   0]]

  [[120  68  91]
   [169  54 107]
   [157  66 114]
   ...
   [  9   7  18]
   [  0   0   2]
   [  0   0   2]]

  [[146  70  93]
   [211  70 125]
   [185  66 118]
   ...
   [ 11   9  24]
   [  0   0   5]
   [  0   0   2]]

  ...

  [[182 106  93]
   [235 131 103]
   [255 158 117]
   ...
   [140  44 134]
   [104  29 130]
   [ 99  29 129]]

  [[144  60 108]
   [185  64 106]
   [213  78 108]
   ...
   [ 96  18 120]
   [ 72  14 126]
   [ 71  17 118]]

  [[134  52  98]
   [177  59 108]
   [212  70 112]
   ...
   [ 79  18 122]
   [ 69  15 118]
   [ 68  16 115]]]


 [[[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [ 18  10  47]
   [ 11  10  36]
   [ 10   8  32]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [ 40  19  79]
   [ 27  16  64]
   [ 26  16  63]]

  [[  0   0   2]
   [  0   0   2]
   [  0   0   2]
   ...
   [ 54  20 105]
   [ 41  15  90]
   [ 37  16  86]]

  ...

  [[  9   6  26]
   [  8   2  43]
   [ 17   6  61]
   ...
   [ 47  16  96]
   [ 41  13  89]
   [ 37  14  86]]

  [[ 25  12  51]
   [ 39  21  83]
   [ 40  18  92]
   ...
   [ 41  18  92]
   [ 42  21  90]
   [ 41  18  90]]

  [[ 28  18  55]
   [ 38  19  82]
   [ 44  18  99]
   ...
   [ 41  15  92]
   [ 40  16  90]
   [ 40  15  89]]]


 [[[ 31  12  40]
   [ 36   9  66]
   [ 25   7  47]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[ 39  18  61]
   [ 58  22 101]
   [ 37  11  71]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  [[ 42  18  77]
   [ 55  17 110]
   [ 41  13  86]
   ...
   [  0   0   4]
   [  0   0   4]
   [  0   0   2]]

  ...

  [[139  65  82]
   [199  57 120]
   [166  49 117]
   ...
   [  0   0   4]
   [  1   0   5]
   [  1   0   3]]

  [[136  63  87]
   [196  58 125]
   [162  50 125]
   ...
   [  0   0   4]
   [  0   0   2]
   [  0   0   1]]

  [[134  59  84]
   [189  54 119]
   [160  47 116]
   ...
   [  0   0   2]
   [  0   0   2]
   [  0   0   2]]]]

In [16]:
from PIL import Image
IMAGE_DIR = "/home/alien/Git/DATA/mel_spects_interjection/"

def get_image_dimensions(image_path):
    with Image.open(image_path) as img:
        width, height = img.size
    return width, height

image_path = '/home/alien/Git/DATA/mel_spects_interjection/HeStutters_0_0_fluent.jpg'  # Change this to the path of your image file
width, height = get_image_dimensions(image_path)
print("Image width:", width)
print("Image height:", height)

Image width: 610
Image height: 450

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from sklearn.metrics import accuracy_score
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications import VGG19
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization, MultiHeadAttention
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dropout, Flatten, Dense, Input, AveragePooling2D, Attention, Reshape, TimeDistributed, Bidirectional, LSTM, GRU
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input, decode_predictions
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
# from tensorflow.keras.constraints import ClipValue
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import Layer, MultiHeadAttention
from tensorflow.keras.layers import LayerNormalization

In [18]:
# def build_model(input_shape=(224, 224, 3)):
#     base_model = VGG19(weights='imagenet', include_top=True, input_tensor=Input(shape=input_shape))
#     # Get the output of the 'fc2' layer in VGG16
#     a = base_model.get_layer('fc2').output

#     # Add a Dense layer with 13 neurons
#     dense_layer = Dense(13, activation='relu')(a)

#     # Add a final output layer with sigmoid activation
#     output_layer = Dense(1, activation='sigmoid')(dense_layer)

#     # Define the model with VGG16 base and the added layers
#     model = Model(inputs=base_model.input, outputs=output_layer)

#     # Freeze the weights of the VGG16 layers
#     for layer in base_model.layers:
#         layer.trainable = False

#     return model

def build_model(input_shape=(224, 224, 3), use_float16=False):
    inputs = Input(shape=input_shape)

    # Convert to lower precision if specified
    if use_float16:
        x = tf.keras.layers.Lambda(lambda t: tf.cast(t, tf.float16))(inputs)
    else:
        x = inputs

    x = Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)
    
    x = Conv2D(128, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(128, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)
    
    x = Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2))(x)
    x = BatchNormalization()(x)

    x = TimeDistributed(Flatten())(x)  # Flatten along the time dimension
    x = Bidirectional(LSTM(128, return_sequences=True))(x)
    # x = Attention()([x, x])  # Self-attention mechanism

    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)  # Adding dropout with a rate of 0.5
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)  # Adding dropout with a rate of 0.5
    
    outputs = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=inputs, outputs=outputs)

    return model

In [19]:
  # base_model = VGG19(weights='imagenet', include_top=True,
  #                   input_tensor=Input(shape=(224, 224, 3)))
  # base_model.summary()

In [20]:
vgg_model = build_model()
vgg_model.summary()

I0000 00:00:1739828929.011462  240910 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6853 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:13:00.0, compute capability: 8.6

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 224, 224, 64)   │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 224, 224, 64)   │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 112, 112, 64)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 112, 112, 64)   │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 112, 112, 128)  │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 112, 112, 128)  │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 56, 56, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 56, 56, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 56, 56, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 56, 56, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 28, 28, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 28, 28, 256)    │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed                │ (None, 28, 7168)       │             0 │
│ (TimeDistributed)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 28, 256)        │     7,472,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 7168)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │     3,670,528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        65,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,355,649 (47.13 MB)

 Trainable params: 12,354,753 (47.13 MB)

 Non-trainable params: 896 (3.50 KB)

In [21]:
from tensorflow.keras import optimizers
vgg_model.compile(
  optimizer=Adam(1e-4),
  loss='binary_crossentropy',
  metrics=['accuracy']
)

In [22]:
batch_size = 36
history = vgg_model.fit(
    X_train,
    y_train,
    batch_size=batch_size,
    epochs=20,
    callbacks=[
        ReduceLROnPlateau(
            monitor = 'accuracy',
            patience = 5,
            verbose = 1,
            min_lr = 1e-7
        ),
        # early_stop
    ]
)

Epoch 1/20

2025-02-17 16:48:49.662849: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 291271680 exceeds 10% of free system memory.
2025-02-17 16:48:49.785641: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 291271680 exceeds 10% of free system memory.
I0000 00:00:1739828933.516142  241201 cuda_dnn.cc:529] Loaded cuDNN version 90300

54/54 ━━━━━━━━━━━━━━━━━━━━ 17s 161ms/step - accuracy: 0.5910 - loss: 0.7057 - learning_rate: 1.0000e-04
Epoch 2/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 116ms/step - accuracy: 0.7093 - loss: 0.5893 - learning_rate: 1.0000e-04
Epoch 3/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.7249 - loss: 0.5734 - learning_rate: 1.0000e-04
Epoch 4/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.7532 - loss: 0.5040 - learning_rate: 1.0000e-04
Epoch 5/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.8010 - loss: 0.4481 - learning_rate: 1.0000e-04
Epoch 6/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.8309 - loss: 0.4034 - learning_rate: 1.0000e-04
Epoch 7/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.8681 - loss: 0.2995 - learning_rate: 1.0000e-04
Epoch 8/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.9165 - loss: 0.2091 - learning_rate: 1.0000e-04
Epoch 9/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.9564 - loss: 0.1345 - learning_rate: 1.0000e-04
Epoch 10/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.9744 - loss: 0.0799 - learning_rate: 1.0000e-04
Epoch 11/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.9902 - loss: 0.0365 - learning_rate: 1.0000e-04
Epoch 12/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.9878 - loss: 0.0486 - learning_rate: 1.0000e-04
Epoch 13/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.9922 - loss: 0.0266 - learning_rate: 1.0000e-04
Epoch 14/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.9974 - loss: 0.0147 - learning_rate: 1.0000e-04
Epoch 15/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 116ms/step - accuracy: 0.9990 - loss: 0.0072 - learning_rate: 1.0000e-04
Epoch 16/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 116ms/step - accuracy: 0.9968 - loss: 0.0151 - learning_rate: 1.0000e-04
Epoch 17/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 116ms/step - accuracy: 0.9968 - loss: 0.0164 - learning_rate: 1.0000e-04
Epoch 18/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 116ms/step - accuracy: 0.9927 - loss: 0.0263 - learning_rate: 1.0000e-04
Epoch 19/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 116ms/step - accuracy: 0.9958 - loss: 0.0240 - learning_rate: 1.0000e-04
Epoch 20/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.9864 - loss: 0.0385
Epoch 20: ReduceLROnPlateau reducing learning rate to 9.999999747378752e-06.
54/54 ━━━━━━━━━━━━━━━━━━━━ 6s 116ms/step - accuracy: 0.9863 - loss: 0.0386 - learning_rate: 1.0000e-04

In [23]:
# predictions
vgg_pred = vgg_model.predict(X_test, batch_size=1)

vgg_pred = np.round(vgg_pred)

  # model evaluation
confusion = confusion_matrix(y_test, vgg_pred)
print(classification_report(y_test, vgg_pred))
print(confusion)

484/484 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step
              precision    recall  f1-score   support

           0       0.71      0.84      0.77       331
           1       0.43      0.27      0.33       153

    accuracy                           0.66       484
   macro avg       0.57      0.55      0.55       484
weighted avg       0.62      0.66      0.63       484

[[277  54]
 [112  41]]

In [24]:
vgg_model.save('./model_interjection', overwrite=True)

ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=./model_interjection.