In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
import whisper

model = whisper.load_model("small")
result = model.transcribe("/home/alien/Documents/1.wav")
print(result["text"])

/home/alien/Programming/env/lib/python3.12/site-packages/whisper/__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)

 I know of him and I've listened to him at work workshops, but I've never actually met him, no.

In [3]:
from transformers import pipeline

# Load the model for ASR
pipe = pipeline(model="justanotherinternetguy/whisper-small-sep28")

def transcribe(audio):
    # Process the audio file (assumes it's a .wav file or other audio format Whisper supports)
    text = pipe(audio)["text"]
    return text

print(transcribe('/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_109.wav'))

/home/alien/Programming/env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-12-29 21:04:32.756416: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1735524272.767062   11489 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1735524272.770360   11489 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-29 21:04:32.782465: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Device set to use cuda:0
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, 50259], [2, 50359], [3, 50363]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.

 I

In [4]:
root_fp = "../../DATA/ml-stuttering-events-dataset/"
CLIPS_DIR = "/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/"
df = pd.read_csv("/home/alien/Git/DATA/ml-stuttering-events-dataset/SEP-28k_labels.csv")
df.head()
df.shape

(28177, 17)

In [5]:
df

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,WordRep,DifficultToUnderstand,Interjection,NoStutteredWords,NaturalPause,Music,NoSpeech
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,0,0,0,3,1,0,0
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,0,0,0,3,1,0,0
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,0,0,0,3,0,0,0
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,0,0,0,2,0,0,0
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28172,WomenWhoStutter,109,35,25793600,25841600,0,0,0,0,0,0,0,3,3,0,0,0
28173,WomenWhoStutter,109,36,26168480,26216480,0,0,1,1,3,0,1,1,0,0,0,0
28174,WomenWhoStutter,109,37,3569440,3617440,0,0,0,0,0,0,0,3,3,1,0,0
28175,WomenWhoStutter,109,38,28479840,28527840,0,0,1,0,0,0,0,3,2,1,0,0
28176,WomenWhoStutter,109,39,29318080,29366080,0,0,0,0,0,0,0,0,3,0,0,0

In [6]:
df = df[df.PoorAudioQuality == 0]
df = df[df.DifficultToUnderstand == 0]
df = df[df.Music == 0]
df = df[df.NoSpeech == 0]
df = df[df.Unsure == 0]

In [7]:
df

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,WordRep,DifficultToUnderstand,Interjection,NoStutteredWords,NaturalPause,Music,NoSpeech
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,0,0,0,3,1,0,0
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,0,0,0,3,1,0,0
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,0,0,0,3,0,0,0
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,0,0,0,2,0,0,0
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28171,WomenWhoStutter,109,34,24781440,24829440,0,0,0,0,0,0,0,2,3,0,0,0
28172,WomenWhoStutter,109,35,25793600,25841600,0,0,0,0,0,0,0,3,3,0,0,0
28174,WomenWhoStutter,109,37,3569440,3617440,0,0,0,0,0,0,0,3,3,1,0,0
28175,WomenWhoStutter,109,38,28479840,28527840,0,0,1,0,0,0,0,3,2,1,0,0
28176,WomenWhoStutter,109,39,29318080,29366080,0,0,0,0,0,0,0,0,3,0,0,0

In [8]:
df = df[(df.WordRep == 0)]

In [9]:
df

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,WordRep,DifficultToUnderstand,Interjection,NoStutteredWords,NaturalPause,Music,NoSpeech
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,0,0,0,3,1,0,0
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,0,0,0,3,1,0,0
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,0,0,0,3,0,0,0
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,0,0,0,2,0,0,0
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28171,WomenWhoStutter,109,34,24781440,24829440,0,0,0,0,0,0,0,2,3,0,0,0
28172,WomenWhoStutter,109,35,25793600,25841600,0,0,0,0,0,0,0,3,3,0,0,0
28174,WomenWhoStutter,109,37,3569440,3617440,0,0,0,0,0,0,0,3,3,1,0,0
28175,WomenWhoStutter,109,38,28479840,28527840,0,0,1,0,0,0,0,3,2,1,0,0
28176,WomenWhoStutter,109,39,29318080,29366080,0,0,0,0,0,0,0,0,3,0,0,0

In [10]:
df.to_csv("filtered_for_whisper.csv", index=False)

In [11]:
import os
import csv

# Open the output CSV file where the results will be saved
with open('transcription_small_tt_nowordrep.csv', mode='w', newline='', encoding='utf-8') as output_csv:
    fieldnames = ['filepath', 'result']
    writer = csv.DictWriter(output_csv, fieldnames=fieldnames)

    # Write header row
    writer.writeheader()

    # Open and read the input CSV file (filtered_for_whisper.csv)
    with open('filtered_for_whisper.csv', mode='r', encoding='utf-8') as input_csv:
        csv_reader = csv.DictReader(input_csv)
        
        # Iterate over each row in the input CSV
        for row in csv_reader:
            # Get the values of Show, EpId, and ClipId from the row
            show = row['Show']
            ep_id = row['EpId']
            clip_id = row['ClipId']
            
            # Construct the file path: Show/EpId/ClipId.wav
            fp = os.path.join("/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/", show, ep_id, f"{show+"_"+ep_id+"_"+clip_id}.wav")
            
            # Check if the file exists before proceeding
            if os.path.exists(fp):
                # Transcribe the audio file
                result = transcribe(fp)
                transcription_text = result
                
                # Write the result to the output CSV file
                writer.writerow({'filepath': fp, 'result': transcription_text})
                print(fp, transcription_text)
            else:
                print(f"File {fp} does not exist.")

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_0.wav myself limiting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_1.wav and I challenge those beliefs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_2.wav  assertive when we change
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_3.wav the Rolls which

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_4.wav I explained to her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_5.wav  relations

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_6.wav to go on that course
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_7.wav in 2000

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_8.wav  yes but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_9.wav  people who still start to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_10.wav  they speak
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_11.wav that we deal with known as stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_12.wav the fluency
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_14.wav  I had so many

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_15.wav of the things that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_16.wav each time I avoided a trouble

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_17.wav  many ways that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_18.wav on word substituted

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_19.wav and so I was filled
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_20.wav it was a huge temptation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_22.wav and when I was a very young police
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_24.wav working with me every day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_25.wav prostatic devices
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_26.wav that I'm hearing from you now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_28.wav  half a century
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_29.wav  how much money

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_31.wav and after about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_32.wav let me see after about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_33.wav I vowed that I would never
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_34.wav but it all changed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_35.wav explain to you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_36.wav  increased to more than 300

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_37.wav well one person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_38.wav one situation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/0/HeStutters_0_39.wav your greatest fears
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_2.wav one understands that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_3.wav when you were younger
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_4.wav  and fight every single day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_9.wav  I was standing frail and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_14.wav that I like one those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_15.wav  actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_16.wav she is completely fluent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_22.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_23.wav and how do you think that she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_25.wav without a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_26.wav be there she actually spoke on to great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_32.wav  what was her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_33.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_36.wav and ask me to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_38.wav go to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_39.wav  so I ended up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_43.wav with him and she's like oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_49.wav  experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_50.wav  so she's been great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_52.wav married we said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_57.wav  change

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_59.wav  once so you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_63.wav  they're made there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_66.wav interfered with your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_67.wav and do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_70.wav do it and I'm not you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_75.wav  completely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_77.wav being a person who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_78.wav dutters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_82.wav  earlier
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_86.wav  itself and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_87.wav and after you become
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_88.wav  comfortable with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_91.wav  focus
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_96.wav  and we've had a few

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_99.wav message to get out there so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_101.wav thank you for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_103.wav  another high five and a hug
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_105.wav  and we have guys who are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_107.wav it just makes a really big
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_108.wav difference so I wouldn't say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_109.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_110.wav  out of now we don't really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_113.wav they found
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_116.wav  school there and one day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_118.wav  so yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_121.wav what was it that like changed your life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_122.wav whoa
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_125.wav  there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_128.wav  group and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_131.wav growing up but then I met all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_132.wav people who have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_134.wav it was nice to walk into

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_135.wav  they are doing like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_137.wav  that you wish

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_140.wav  privately for so long
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_142.wav  I watch all three of them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_145.wav  strength of these groups
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_149.wav  to grow and yell

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_150.wav  it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_155.wav  Fort Worth and had no idea

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_156.wav you have to get him to come
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_159.wav chapter and she ran into

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_160.wav  she ran into a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_161.wav  Stephen

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_162.wav Coffman
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_163.wav and then he found me in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_165.wav  at first
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_166.wav  that we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_168.wav structured group so I kind of like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_169.wav  change it we tend to talk about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_171.wav things we do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_176.wav comfortable but I was not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_178.wav  and how you could best
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_179.wav how you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_180.wav turned out it into a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_181.wav positive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_183.wav  kind of all over the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_186.wav people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_187.wav they had only been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_188.wav  spent quite a lot of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_189.wav I'm on that cuz they're dying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_191.wav  Howard was for them there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_192.wav they learned and all that stuff and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_195.wav Therapy which is something I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_196.wav with my speech I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_199.wav so I would have to like write my name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_200.wav and then my piece of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_201.wav  paper but then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_206.wav  terrible you just yell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_213.wav that kind of thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_215.wav  have done just to kind of like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_216.wav  it in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_221.wav great thing I would not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_225.wav  start over

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_228.wav that's not easy either
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_230.wav teachers were they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_231.wav  one group you know change my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_232.wav whoa life like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_233.wav portive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_234.wav  most of them were but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_237.wav when I would try to speak
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_239.wav  I'm mom and she came in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_241.wav  I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_242.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_244.wav couldn't even with it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_245.wav  wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_246.wav  did my mom the under
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_247.wav  Laughing at a kid who stutters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_248.wav  pretty much a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_249.wav  know where I would have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_254.wav hope for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_256.wav  I think that that's always going to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_258.wav  be there and I used to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_261.wav  I'm at the point where you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_264.wav helpful
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_265.wav that's not cool man you're not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/1/HeStutters_1_267.wav timmials
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_0.wav this can be found directly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_2.wav when he was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_5.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_8.wav  and you know this was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_14.wav not predisposed to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_15.wav stutter so you know they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_17.wav winds down

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_18.wav I had a long career with stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_19.wav what would you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_20.wav well I used to a worker
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_21.wav  has been one of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_22.wav on this stuttering journey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_30.wav  you know getting over

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_31.wav do you still have shame today
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_35.wav  young

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_36.wav people that might listen to this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_38.wav stuttering Journey cuz it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_43.wav that said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_50.wav brother's manager

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_52.wav well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_54.wav working with people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_55.wav  where and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_57.wav  make room for the daughter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_58.wav stuttering and it's also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_60.wav so that was my first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_63.wav with individuals with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_66.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_69.wav get my place
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_71.wav sitter stuttering to be a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_72.wav disability
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_75.wav ation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_77.wav free download on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_78.wav  and itunes today I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_79.wav person with their
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_80.wav  patient but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_85.wav disable you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_88.wav cuz you're communicating great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_89.wav effective communicator
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_93.wav but even now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_94.wav and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_96.wav going good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_97.wav  to Frank a Frank how's it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_99.wav was it like when you were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_100.wav working how did the client
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_104.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_106.wav  a few
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_111.wav supervisory staff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_112.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_118.wav and do you think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_121.wav yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_127.wav  yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_128.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_130.wav  I was involved with the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_134.wav what you do to keep yourself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_135.wav  busy well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_138.wav and did they have any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_139.wav her reince with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_141.wav  never got the sense that they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_145.wav my stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_150.wav shaping but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_155.wav well my name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_157.wav the client feel like they fell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_159.wav  gave you even though

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_161.wav  are you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_166.wav help you with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_168.wav I think they make the blind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_170.wav are you basically okay these days

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_174.wav stuttering in general
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_177.wav  bye

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_179.wav  sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_180.wav my speech even you know speaking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_181.wav what exactly do you mean by bad
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_182.wav bad times is it just the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_188.wav language
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_189.wav  is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_191.wav and you're speaking English
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_193.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_194.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_199.wav  I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_206.wav repetitions and Pearl
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_207.wav  wife is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_208.wav you know she's very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_211.wav well so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/2/HeStutters_2_215.wav busy guy what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_2.wav  and you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_4.wav  well I'm sure that you'll get
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_7.wav you know you just do it to Paul

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_11.wav duttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_16.wav feelings that came along with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_25.wav  they know that my speech is suckling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_28.wav confident and poised

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_29.wav I decided to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/3/HeStutters_3_38.wav stutter I was just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_2.wav well this has been a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_3.wav that we weren't sure where it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_5.wav an emotional affect
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_7.wav will you know things like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_8.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_9.wav  them you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_10.wav me that I have to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_11.wav I have to be more open about it basically

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_12.wav encouraging you to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_13.wav advertiser stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_14.wav  I was working there for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_15.wav get struck by lightning or anything

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_16.wav  see am I case
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_17.wav  I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_18.wav you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_19.wav listen to or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_20.wav other people's opinions might
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_21.wav differ so it sounds like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_25.wav the most
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_30.wav  it's other freely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_31.wav when do you think that will happen
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_32.wav and present has

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_35.wav and do you like the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_36.wav person that you are now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/4/HeStutters_4_38.wav  than I was years ago you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_0.wav hi everybody this is Pam

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_1.wav different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_3.wav because it has to do with looking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_4.wav inward and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_5.wav but I wanted to ask you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_6.wav  one more question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_7.wav  question if I may you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_8.wav that you're an inspiration
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_10.wav I've had a couple of nice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_12.wav I know I'm doing a good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_15.wav  oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_16.wav  you do to keep busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_17.wav well I work is I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_20.wav  guy me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_23.wav and I've been working here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_27.wav wow how did you find
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_28.wav the person who stutters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_29.wav it's a very interesting question pain I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_30.wav I've always worked in jobs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_35.wav  the blog make room for the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_36.wav stuttering which

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_38.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_39.wav  mentioned in addition to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_40.wav lecturing and you said to a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_41.wav their reaction

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_42.wav when you introduce themselves
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_43.wav when you introduce yourself to them and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_44.wav  Professor daughters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_56.wav  available as a download on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_57.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_61.wav  so have you ever had a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_62.wav  quit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_63.wav what question or doubt

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_66.wav  I'm so much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_67.wav  of course you feel under

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_68.wav presure to actually do the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_69.wav  job and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_72.wav and again everything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_73.wav and on the flip side

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_75.wav hey Grant how's it going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_76.wav when very well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_79.wav well what did he mean by that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_80.wav  being

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_81.wav have you ever had a student actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_83.wav  of your speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_86.wav in some ways I think it's the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_88.wav yet you can play me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_89.wav personality
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_90.wav my be will then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_94.wav one of the biggest reasons we found
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_97.wav Wari

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_101.wav seem to get fairly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_103.wav  fairly fast

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_104.wav what I really like pain
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_106.wav  of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_107.wav I should and you got
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_109.wav um less

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_116.wav very old stop
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_119.wav you get to see

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_120.wav a whole range of students
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_121.wav I'm experience

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_123.wav  pain also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_124.wav it's a very good thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_127.wav people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_130.wav so I see I shouldn't so I'll see

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_131.wav trolley
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_140.wav  perceived as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_142.wav is it the same as a disability
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_146.wav  it's up to the young individual

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_149.wav  in my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_152.wav you know we still have people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_153.wav  people that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_154.wav  Australia

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_159.wav  yeah what are you saying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_161.wav I consider them to be role models

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_165.wav right watch for example
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_166.wav  name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_169.wav you know and that will also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_172.wav that's like Canada

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_176.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_183.wav  Builder

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_187.wav courses like I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_189.wav  by Graham

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_191.wav it will not have a life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_192.wav  I mean it all comes down to you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_193.wav how we perceive ourselves
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_195.wav coffee and I started

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/5/HeStutters_5_196.wav or I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_0.wav I'm okay and well I'm very pleased

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_2.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_3.wav no let me try expand it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_4.wav and I wanted to say that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_6.wav  was so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_7.wav  speaking as I am not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_8.wav it's new for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_11.wav  so do you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_12.wav  that in sight of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_13.wav having realized that you're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_14.wav alone do you think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_15.wav druggled speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_16.wav  absolutely it's the main point

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_17.wav  understanding I'm not alone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_18.wav well that's tremendous for people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_19.wav but I guess I'm just too stubborn
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_20.wav impact that's huge

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_23.wav coming out of my first NSA conference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_24.wav hundreds of thousands of us out there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_26.wav  absolutely blown away by the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_27.wav by the quality of people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_30.wav  yeah I think that's what it's all about when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_31.wav  almost seems like a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_32.wav  statement doesn't it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_33.wav the same people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_34.wav they suddenly just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_35.wav  support and community does

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_40.wav people know because I started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_43.wav if you can recall which I'm sure you can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_44.wav  I think that I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_46.wav  only got enough the courage

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_47.wav  what to expect
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_49.wav  people stutter of course and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_51.wav  them to hide muster
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_52.wav  in 2012

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_53.wav  not start a need to start a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_55.wav  who speaks fluently and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_58.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_59.wav  be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_61.wav  is reduced or eliminated
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_63.wav  normal speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_64.wav  as a child I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_65.wav  21 I guess

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_67.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_68.wav total waste of time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_71.wav herby available in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_72.wav Israel

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_74.wav  think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_77.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_78.wav I advertised for the first time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_80.wav  one of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_81.wav  hospital is in Israel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_82.wav  bye

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_83.wav I understand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_84.wav personally I don't think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_86.wav therapy of any type
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_88.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_89.wav I have been to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_94.wav  two years ago

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_96.wav  for speech therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_97.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_99.wav reduction
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_100.wav I would probably like to explore that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_101.wav but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_102.wav  no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_104.wav and I think for many
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_105.wav people that's a complex story

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_106.wav evaluable experience to have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_107.wav  yeah it is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_109.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_113.wav and not have stuttering come up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_115.wav  career
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_117.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_118.wav came up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_119.wav came up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_120.wav stuttering is so much a part of me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_122.wav at this point in your life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_123.wav well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_125.wav I'm cautious

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_126.wav where I can start to do things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_127.wav without the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_128.wav  we are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_129.wav  approaching almost

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_130.wav  so I appreciate that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_134.wav but I would

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_135.wav do everything I came to hide it I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_136.wav out of my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_137.wav  I'm for so it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_138.wav  mind is always looking forward in the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_140.wav  to find substitutions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_141.wav for the words on which I imagine that I will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_142.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_143.wav  so people definitely know us that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_144.wav and then I moved to Israel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_146.wav in terms of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_148.wav and response was really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_149.wav enough overwhelming the positive and supportive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_151.wav  you surprised at their pot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_152.wav positive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_155.wav  I don't think I was surprised
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_156.wav surprised

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_159.wav list of people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_162.wav I've started

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_163.wav person who stutters I would imagine
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_164.wav  yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_167.wav  journey the path of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_168.wav  accepting myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_172.wav  response
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_174.wav now you mentioned that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_175.wav email
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_176.wav individuals about the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_177.wav opportunity to talk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_178.wav openly with any of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_179.wav  member
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_180.wav I'm very pleased with how I'm doing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_183.wav yes I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_186.wav  and of course only

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_187.wav all the stuttering support
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_190.wav two years later

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_191.wav  I feel better and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_192.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_198.wav and we sell all over the world
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_199.wav  I've been at the company for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_200.wav  49 years old
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_201.wav for a lifetime

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_202.wav to protect myself so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_203.wav  breaking it down

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_205.wav have you reached the point
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_206.wav doing some of that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_207.wav I like the term that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_210.wav  to do is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_211.wav is not allow that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_213.wav  I was not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_215.wav my level of stress goes down
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_216.wav that goes on in my head

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_217.wav for what seems to be forever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_218.wav have you ever experienced that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_219.wav only all the time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_220.wav a lot of speaking is required

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_221.wav and that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_223.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_225.wav  even sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_228.wav forgetting my name or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_229.wav  I get stuck
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_230.wav  begin with P

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_231.wav  I'm not going to say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_232.wav give me trouble because I don't really think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_233.wav can to that and that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_234.wav for me that was always very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_236.wav  I mentioned that here I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_237.wav  face it and deal with it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_239.wav  I was actually amazed when I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_242.wav humiliating

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_243.wav no you said you've met other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_244.wav people who stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_245.wav is real
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_246.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_248.wav  of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_249.wav of being able to handle

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_250.wav  change experience as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_251.wav have you been in contact with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_252.wav  daughter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_253.wav I had my first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_254.wav conversation with another person who start
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_255.wav not ordinarily do right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_256.wav  yeah exactly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_257.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_261.wav for me anyway it's a journey and it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_263.wav  talking over skype

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_264.wav be posted on the internet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_265.wav  shortly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_266.wav  over the phone type of thing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_268.wav I think it's more just the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_269.wav  and the conditions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_271.wav response

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_272.wav I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_273.wav  to cope and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_274.wav  I missed admit for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_276.wav  anxiety when we talk over the phone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_278.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_279.wav  about the exposure

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_283.wav other people men and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_284.wav  home it may have that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_285.wav impact but I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_286.wav  very similar stories to us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_287.wav yes I think that your choice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_290.wav yes absolutely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_292.wav  extremely stressful in fact mostly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/6/HeStutters_6_293.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_0.wav will Pam after many years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_1.wav yeah there's very few

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_2.wav for you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_3.wav yes Pam I had a lifetime of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_5.wav I think so permanent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_6.wav with some voluntary stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_7.wav so it's about phrasing and pausing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_8.wav I live in a little town called

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_9.wav 5 to 8 words per person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_10.wav to just change keys

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_11.wav make sure I have control
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_14.wav and that gives them a bit of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_15.wav there is something that can help them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_16.wav so it's all about seeing the evidence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_17.wav  you mentioned some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_18.wav practicing their breathing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_19.wav now drive away from Adelaide
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_23.wav doctor so lawyers is that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_24.wav now he came to the Melville
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_26.wav and kind of so much confidence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_27.wav  self-limiting beliefs
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_29.wav we worried about the judgment of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_30.wav Prime example job interview
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_33.wav by a self-help group

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_34.wav and you need to be brave
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_35.wav  try to think about what you're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_36.wav the challenges to maintain that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_37.wav  and you're passionate with us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_38.wav  I look that's my pleasure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/7/HeStutters_7_39.wav  you yes I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_3.wav but also it makes you human
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_5.wav will cuz I certainly am too

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_13.wav and for being so honest
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_15.wav butters she asks him

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_17.wav  to pull those funny faces and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_18.wav  stuff like that and so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_19.wav my knee because I didn't want to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_20.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_21.wav people change be more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_22.wav  what's the word

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_23.wav control as we're talking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_24.wav  we're talking now so it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_25.wav therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_29.wav  to control my speech but I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_31.wav  see you and I can still
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_32.wav  still remember

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_33.wav  program recently
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_36.wav  January 26th

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_37.wav very good and I'm excited with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_38.wav  opportunity to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_39.wav  my wife to actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_40.wav  order the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_41.wav coerce them to do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_46.wav  I couldn't say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_50.wav that was one way but not used it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_52.wav did this acting cause and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_55.wav  have a relapse I said what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_56.wav what can I do he said well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_58.wav  and it was great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_60.wav but you know in your heart that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_61.wav that they wouldn't do it so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_62.wav  I did this course I found

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_63.wav  I was amazed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_66.wav  really threw myself into the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_67.wav  program
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_69.wav but I also found that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_70.wav  silver
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_72.wav word together and not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_73.wav and not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_74.wav  being funny

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_76.wav  speeches
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_77.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_78.wav and what you do to keep yourself busy I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_80.wav  because before if any

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_81.wav  anyone laughed at me when I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_82.wav in the last pliode had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_83.wav  278
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_85.wav  it's great to have that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_86.wav get people to laugh at you it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_90.wav  people to laugh at you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_92.wav if you can take a light-hearted
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_95.wav  it that's piece of her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_96.wav  have a react to it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_97.wav moomba gas fields down to Adler

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_98.wav adoli and all was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_99.wav where we can really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_101.wav  did and I've heard a lot of people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_106.wav but you see we perceive it as a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_108.wav  like a remainder right story
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_109.wav  maybe have not found the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_110.wav  the support or the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_112.wav  comfortable

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_115.wav rehearsing or scanning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_116.wav  and did I have to worry about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_117.wav what word was I going to use so that I wouldn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_123.wav and all of a sudden I couldn't say Bob

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_125.wav  I don't believe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_126.wav so did you change your name again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_128.wav do you think that you're a different person now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_131.wav well here we've got driving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_132.wav you mentioned that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_133.wav  had always had a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_134.wav a chip on your shoulder
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_139.wav  work well yes it was because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_141.wav and it was your front that people wouldn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_142.wav  in the last

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_143.wav  12 13
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_145.wav  because as I said I can talk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_149.wav the Voyage the phone they don't like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_150.wav badly I would avoid it would you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_152.wav  those connections with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_153.wav people we don't get the chance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_154.wav Richard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_157.wav and of course as you know yourself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_161.wav  it's a catch 22 thing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_162.wav  get out in the open you won't there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_163.wav there is a 50-50
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_164.wav  you've gone in the shops empty

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_166.wav  order and a person walks in and you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_168.wav if somebody else walks in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_169.wav and religion that I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_172.wav  we give ourselves that much power

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_173.wav  or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_175.wav listen to somebody else who stutters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_176.wav what's it like for you listening to me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_177.wav  it doesn't face me because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_178.wav  change the twelve boys they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_179.wav when it's your turn you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_180.wav  you know where I'm coming from then I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_181.wav I can listen to anyone that started

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_182.wav  for you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_186.wav  used to do it and all you should

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_188.wav  into the football
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_190.wav  no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_192.wav  more than words
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_193.wav  do you believe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_195.wav  it is I think it's a mind-shit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_196.wav  I think that it's a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_197.wav it is a mind-shit that we get in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/8/HeStutters_8_200.wav  him know that it really bothered you no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_0.wav I tunes today has always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_1.wav  thing I ever did with my speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_2.wav  about the technique but basically
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_3.wav allow good speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_4.wav  logical which is something that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_5.wav  euphoria of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_6.wav the course I was unemployed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_7.wav put out an application

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_8.wav had called me my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_9.wav called the grand poo bar of a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_10.wav well confident boy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_11.wav when I got to the interview I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_12.wav  your life on a different course
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_13.wav  Toastmasters which is a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_14.wav  contest
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_15.wav  through a club competition

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_16.wav can individual clubs compete together
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_17.wav well congratulations

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_18.wav  look where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_20.wav I also had a dad who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_21.wav speak with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_22.wav  a lot of people who believe that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_23.wav and I still remember those
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_24.wav one of the points is that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_25.wav disadvantage from the point
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_26.wav all you could and when the subject

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_28.wav workshops for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_29.wav is well everybody in that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_30.wav it wasn't close
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_31.wav  you know 20 years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_32.wav what I can remember and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_33.wav  somehow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_34.wav and again I'm not sure what that did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_36.wav pretty much I just have to learn

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/9/HeStutters_9_38.wav so he recorded it and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_0.wav it was either Dallas or Houston I think it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_5.wav  of them as if
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_6.wav and I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_8.wav  I was so caught up from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_9.wav  problem

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_10.wav well I started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_11.wav and came out here cold

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_13.wav  by the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_14.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_15.wav  letter at times and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_16.wav  all for about 30 days and come home

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_18.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_19.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_20.wav my stuttering issues
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_21.wav  I don't know if you've ever tried to lose

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_22.wav  every point on the system
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_25.wav magnously been doing speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_26.wav a lot of them have tried
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_27.wav totally over control as a person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_28.wav and I need
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_29.wav getting to a place where I would allow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_30.wav allow myself to be spontaneous
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_31.wav which is still hard for me at times

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_32.wav but when you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_34.wav  I couldn't hit the damn wall

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_35.wav the book started out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_36.wav we need to have some other kind of act

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_37.wav and the title
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/10/HeStutters_10_38.wav I had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_2.wav  yes there might be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_7.wav  I would say and like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_8.wav  concerned about like a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_9.wav  appearance so like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_10.wav  like I've
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_12.wav  anything to do with the fact that you're just you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_13.wav you have a physical presence that people don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_15.wav oh wow I'm so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_18.wav tories she asks him
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_20.wav  that and become a entrepreneur

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_21.wav oh awesome what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_23.wav  come

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_25.wav  and then we had meeting every morning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_27.wav  with me like I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_30.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_31.wav  you made you said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_33.wav are you saying that like you thought
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_35.wav while I start to like code on out of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_39.wav was that an issue was it a challenge
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_42.wav  always patient with me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_47.wav  day personally I don't believe in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_49.wav  I think sometimes people who stop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_50.wav  we try to overcome say a little bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_51.wav  yeah like I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_52.wav you're right I just like you said I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_53.wav everybody does I think everybody has

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_54.wav  periods of disillusioned
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_56.wav can be a real challenge

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_57.wav what was it like for you growing up as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_59.wav oh yeah definitely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_61.wav before a few years ago if you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_62.wav  the blog make room for the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_63.wav stuttering and it's also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_67.wav will come back and then you will forget your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_68.wav you basically just introduce yourself and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_69.wav and I remember when I did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_70.wav  to overcome my fears
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_71.wav how long have you been in total

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_72.wav and yeah how long have you been involved
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_73.wav I've been involved in Toastmasters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_74.wav with work and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_76.wav  speech and attend the meetings so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_77.wav  things so I ended up just taking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_81.wav  again okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_83.wav  download on itunes today
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_84.wav  today I'm really excited to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_87.wav dancing with oh no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_90.wav  high flying stuff that you see in movies

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_92.wav  time movie Saturday Night Fever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_95.wav hip-hop stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_96.wav activity that was different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_98.wav  I guess

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_100.wav  real risk-taker
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_102.wav  stuff I mean all those things you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_104.wav the stuttering community who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_105.wav  who I have actually not met

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_106.wav confidence really right yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_111.wav  so sorry I'm back that's okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_112.wav  trying to help others
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_114.wav in a certain sense is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_115.wav  but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_116.wav  the did solely try to have fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_117.wav no actually I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_118.wav  play like games and stuff so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_121.wav  when I was younger and then like when I like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_122.wav  to also create change as well no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_123.wav well no do you know like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_126.wav  want to say hello to Henry

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_127.wav Henric how are you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_129.wav I guess

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_130.wav I'm with her full-time and I put my job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_134.wav be the you want to see

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_136.wav  like Gandhi did is you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_137.wav  create that change and be that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_138.wav like what you're all about and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_140.wav wanted to do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_141.wav  do one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_143.wav stuttering affect me less and less

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_144.wav  and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_145.wav right now I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_146.wav  would never allow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_149.wav  in any sense whatsoever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_150.wav that's great to have that attitude
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_151.wav and to just share information

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_152.wav and that's where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_153.wav  so then I pull the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_154.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_155.wav all and he did not start it all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_156.wav  wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_157.wav how does that feel for you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_158.wav for you to know that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_160.wav people's lives like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_161.wav that's like huge like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_162.wav  like do I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_163.wav I'm a very sensitive person I'm a very emotional
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_164.wav less helping other people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_167.wav  hers be night it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_168.wav  you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_170.wav  both Tuttering community
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_171.wav I've like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_172.wav  do attend the NSA conference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_177.wav  speech therapy I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_179.wav  in Grayschool and in high school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_180.wav  school but then I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_181.wav  a lot and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_182.wav and like when I take a bath

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_183.wav it doesn't really work that well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_185.wav that you could be fluent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_186.wav  what now so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_187.wav  so I'm really good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_188.wav to get us started could you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_189.wav now so that kind of brings us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_190.wav  communicator can be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_191.wav well like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_194.wav  to our concerns publicly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_195.wav today no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_197.wav  dialogue
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_201.wav and I'm wondering stand in the way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_202.wav do you think that there's any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_203.wav  fundamental differences between

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_204.wav  between men and women who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_205.wav  I don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/11/HeStutters_11_207.wav my name is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_0.wav today I'm excited to have the opportunity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_1.wav  okay oh wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_4.wav a lot of the work

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_5.wav when compared how effective
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_6.wav  they're interested in learning more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_7.wav oh yeah the good question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_12.wav I do yes so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_14.wav I'm sitting cross-legged in the latest position
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_18.wav when you're walking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_20.wav  guitar and I sing a bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_21.wav  you just learned

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_22.wav feel the sensations on your feet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_23.wav  if you search for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_25.wav  to accept their stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_27.wav  except it you're stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_28.wav  I would say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_29.wav  it's not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_32.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_35.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_36.wav that we've become I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_39.wav  go from feeling like it's something you just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_41.wav  so thank you so much for sharing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_45.wav  are probably the main important things about me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_47.wav how long have you stuttered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_48.wav  I've

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_49.wav always started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_50.wav  then it used to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_52.wav  this kind of setting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_53.wav  pretty much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_54.wav well food most of the time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_55.wav  very different story

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_57.wav  I guess
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_58.wav  having to study it sort of made me a lot more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_59.wav only Ali how are you doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_60.wav I'm very welcome how are you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_61.wav  about it does that mean you haven't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_63.wav open about your stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_64.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_65.wav when you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_66.wav open about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_67.wav  yeah so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_68.wav it was easier to try and hide it a little
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_69.wav but when I so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_70.wav  had you met other people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_75.wav enjoying a nice quiet

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_76.wav Sunday over here
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_79.wav have you and he ever talk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_82.wav  a little bit I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_85.wav  a lot of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_88.wav  that it was because of your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_90.wav  a speech therapist in Oxford

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_92.wav  just sort of help me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_95.wav  it was a really useful thing to be talking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_96.wav  and looking forward to watching the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_101.wav  realising that it wasn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_103.wav therapy as a child to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_104.wav I did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_105.wav to address
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_108.wav  as an adult was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_109.wav  similar to what you had done
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_110.wav  done when you were younger

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_111.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_113.wav do work around

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_114.wav the way that you feel about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_115.wav  football game later on tonight

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_117.wav you can stop to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_118.wav do things like cognitive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_120.wav  Anxiety and how you can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_121.wav  female

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_123.wav  my own
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_124.wav you don't some years that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_125.wav oh wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_127.wav  being in class

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_129.wav  been working with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_133.wav  have you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_135.wav  American holiday
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_137.wav  population you want to work with yet

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_139.wav  on in the course because people tend to go
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_141.wav  they realize that they really love working with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_142.wav with older patients
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_145.wav  know that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_147.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_148.wav  they must be by now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_152.wav do any of the other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_155.wav  Stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_157.wav  what's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_158.wav not in my class

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_159.wav  the previous year
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_163.wav  yeah it does seem to be the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_165.wav give back right yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_166.wav mindfulness and stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_168.wav some speed surface to use it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_169.wav  in the UK but there's not really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_171.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_172.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_174.wav  of ease the effects of stuttering on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_175.wav what you do to keep yourself busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_177.wav  yeah would have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_178.wav  maybe have not heard of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_179.wav  yeah sure so it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_180.wav  Origins in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_182.wav  it's actually quite a profound
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_184.wav  more objective about your experiences

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_186.wav  of relevance to stand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_189.wav what is that connection

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_191.wav  see you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_193.wav  who suggested that when you start to it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_196.wav  study speech therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_197.wav and about the feelings that come up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_200.wav and it's also useful in a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_201.wav it allows you to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_202.wav  really get to know what your body is doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_204.wav there's a way in which mindfulness can be used

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_205.wav  is great but there's not many
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_206.wav  therapies that let you really get into that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_207.wav  that moment of stammering when it happens
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_208.wav no do you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_209.wav  to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_213.wav yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_215.wav  sort of the most well-known
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/12/HeStutters_12_216.wav  like to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_0.wav hiding as much as I can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_1.wav a part of who you are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_3.wav  speech therapy twice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_4.wav but not in any way I recognize

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_5.wav  hmm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_6.wav  and it just it wasn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_7.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_9.wav  just leaving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_10.wav no you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_13.wav  his own with his

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_14.wav  the words of it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_18.wav covery of his quest

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_19.wav  yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_21.wav or so like a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_24.wav I would love to right now my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_25.wav platforms the Goodreads problem

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_29.wav and I looked around and thought
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_30.wav  books perhaps but then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_31.wav I won that didn't work out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_33.wav it was something that was always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_35.wav and twice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_36.wav  in events by other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_38.wav I'm speaking very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/13/HeStutters_13_39.wav  it or disclose it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_0.wav  definitely I mean I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_2.wav  different paths that we take in our lives

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_3.wav what advice would you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_4.wav that you need to overcome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_5.wav  and one of the best ways to do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_6.wav  thought I would say as well one of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_8.wav being here just now and you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_10.wav and this has been he

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_11.wav  and if I want to keep feeling this way then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_12.wav vivid memories of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_13.wav what are you from and what you do to keep busy sure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_14.wav  which therapist at the age of 16

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_15.wav  refreshing moment for me and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_16.wav  and so because I felt amazing I just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_17.wav  sorry during my time with the public speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_18.wav  and through that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_19.wav  I wasn't there for long enough to really experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_21.wav get the message that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_24.wav  of hard work to be able to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_26.wav  in space true

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_28.wav  resources that gave me concrete answers you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_29.wav  I would be less fluent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_30.wav  however I kind of see it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_31.wav  the funny story so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_33.wav  him and then I got a call from my mom like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_34.wav and I hope they do because I know it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_35.wav  you know I'm we're completely honest with her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_36.wav  about duttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_37.wav  hmm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/14/HeStutters_14_39.wav  of this year 2016 ice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_1.wav stuttering has taught you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_5.wav  a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_6.wav  a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_9.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_12.wav  although
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_16.wav  conversation I just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_17.wav  I just want to say and thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_19.wav  going to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_20.wav  inspire people that are listening
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_21.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_23.wav  pleasure and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_24.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_29.wav  twelve years right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_32.wav Yeah I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_33.wav  definitely improved on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_34.wav on the X

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_37.wav I also went to a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_39.wav  in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_40.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_41.wav so hey and how's it going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_42.wav  I'm doing good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_45.wav  after that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_46.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_51.wav  or less just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_54.wav taking some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_56.wav  about the day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_60.wav from and what you do to keep busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_61.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_64.wav  pretty accepting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_65.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_68.wav  or the most part
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_69.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_73.wav underneath that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_76.wav that takes a lot of courage

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_77.wav  I don't know if I would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_78.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_79.wav  I could do that at work and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_80.wav and I consider myself to be very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_81.wav I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_82.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_83.wav not just to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_85.wav  whole brick

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_86.wav  has anybody ever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_87.wav  oh wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_88.wav  it just goes to show people have their
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_91.wav positive about your stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_92.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_93.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_94.wav  there's always people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_95.wav people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_97.wav  of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_99.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_100.wav  always be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_101.wav  people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_102.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_104.wav  confident

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_105.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_106.wav  I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_109.wav  a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_110.wav teacher in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_111.wav nice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_112.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_113.wav I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_118.wav  wow well that sounds like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_123.wav  yeah still I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_126.wav  so we're kind of talking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_127.wav  been any opportunities because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_128.wav  because it's dodgering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_129.wav  or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_130.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_131.wav obviously I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_132.wav  oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_134.wav  you and I I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_138.wav I remember when we met

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_139.wav  met first on Stutter social
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_140.wav if I'm correct and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_141.wav  like we already knew each other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_143.wav  in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_146.wav  only
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_148.wav so what's it like with your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_150.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_151.wav  in my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_152.wav  those there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_153.wav  question

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_157.wav  did you get stuck with that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_159.wav  they probably just see it as normal right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_163.wav and what about your wife she
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_164.wav  in your life I'm guessing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_167.wav  bye
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_171.wav  of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_172.wav  of health issues
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_173.wav  dealing with health issues

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_174.wav that must be a real challenge
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_175.wav  yeah I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_176.wav  I actually first
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_181.wav  has

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_182.wav  how to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_183.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_188.wav  that's great to hear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_192.wav  in wind down mode

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/15/HeStutters_15_194.wav  uh... cosco
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_1.wav I was the only one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_2.wav  and it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_3.wav  incredible when I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_4.wav and was like wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_6.wav  idea

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_8.wav  for me because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_9.wav there were so many people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_11.wav second one okay I felt like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_12.wav okay so now I know what to do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_14.wav  I know that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_15.wav I'm home and I'm with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_16.wav  that because I was like crying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_17.wav like crying all the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_19.wav  takes us where I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_20.wav mind blowing that it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_21.wav it was happy tears but it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_22.wav  process so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_23.wav  it's just amazing when you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_24.wav  not have it so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_25.wav  yeah I'm glad you were so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_29.wav  only really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_32.wav  that in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_34.wav  stutters she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_47.wav  with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_53.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_54.wav get to know him a little bit so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_55.wav  little bit so I want to just say hey to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_56.wav  How's it happened I mean you said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_60.wav  to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_63.wav  that's really exciting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_65.wav doing what you want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_66.wav and obviously being happy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_68.wav that's what it's all about right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_70.wav  the inshama
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_81.wav  when I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_90.wav  more exclusively on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_93.wav  are you fell from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_98.wav  interfered with your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_99.wav  marketing your business

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_100.wav attracting fly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_101.wav  he was a thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_107.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_111.wav and what you do to stay busy yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_112.wav  yes absolutely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_113.wav  How are you at some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_127.wav  do that it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_132.wav  so like do you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_133.wav  like do you get most of your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_134.wav clients through like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_135.wav  like referrals and word of mouth
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_142.wav  play in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_147.wav  to fire me for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_148.wav  wedding

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_168.wav  or with me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_169.wav  well I would think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_171.wav  I am originally from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_177.wav  I would say that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_183.wav  This is so I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_186.wav like what would you say is like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_187.wav this is always a hard question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_189.wav  about being

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_190.wav in the starving community
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_193.wav  this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_210.wav  until I was 42
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_211.wav  to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/16/HeStutters_16_212.wav  in Mexico
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_1.wav and then assessing what's in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_2.wav  nullifies the possibility
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_3.wav  a little different

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_4.wav  just spread that message you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_5.wav  whenever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_7.wav  it's not something that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_9.wav like you I was very covered

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_11.wav what a journey has been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_12.wav we don't talk like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_14.wav and it didn't work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_15.wav  Hey Rob how's it going today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_16.wav  to the clinicians
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_17.wav issues wellness

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_18.wav  who are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_19.wav  um legitimately

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_20.wav well I think that we can role model that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_21.wav  so for me I really focus on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_22.wav  is that we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_24.wav scaled terms

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_25.wav looking at everybody not just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_27.wav  you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_28.wav  cuz I stuttered covertly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_30.wav  just about every

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_31.wav word
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_32.wav  situations quite a bit so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_33.wav  came to check on me no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_34.wav yes asking for help

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_35.wav just a little bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_36.wav  we need to help kids

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_37.wav as part of their IEP
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_38.wav  how to be prepared

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/17/HeStutters_17_39.wav  it's okay to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_0.wav  podcast series

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_2.wav two seconds that you have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_5.wav  anybody can hear me using it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_6.wav  at and if I stutter I don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_8.wav  professional

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_9.wav confidential I mean I've used it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_11.wav doing something for yourself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_12.wav  I mean I hate the idea I always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_17.wav  like that yeah I get it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_18.wav  so well thank you for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_20.wav  gotcha wow well that was pretty

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_22.wav it's not bad I mean I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_24.wav every state has a 180

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_26.wav  wow awesome well thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_28.wav  I mean I've been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_34.wav  yeah you're right well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_36.wav well thank you the same to you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_37.wav with an outside agency
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_38.wav or Salmon someone who doesn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_40.wav okay have you ever been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_46.wav  anyway you're lucky

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_48.wav  okay great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_50.wav Sara be it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_51.wav  you I basically
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_52.wav  interesting so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_53.wav you know when you talk about tolerating shame
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_54.wav  a good morning to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_56.wav the therapy that you're doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_57.wav and correct me if I'm wrong like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_58.wav some like counseling component to it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_59.wav  it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_60.wav in a way yeah I mean I'm basically
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_61.wav  one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_62.wav  because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_65.wav  laugh at me or they might walk away

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_68.wav  so you've experienced
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_69.wav if you have a flu fluently

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_70.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_71.wav  So, um, which

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_72.wav  see the techniques
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_74.wav hi Pam how are you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_75.wav  to hide your stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_77.wav at the age of 41

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_78.wav  they were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_80.wav  and then verbally challenged

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_81.wav why would you be teaching me things to just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_82.wav  it was to just stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_84.wav  really know how to deal with that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_87.wav it was fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_88.wav came back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_89.wav then I was beating myself up for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_90.wav  almost as if
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_91.wav the behavior of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_92.wav  should not be doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_93.wav it's so complex isn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_94.wav  is we send
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_95.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_96.wav  it's truly life-long
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_98.wav  as an adult

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_99.wav what made you decide
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_101.wav  avoiding and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_103.wav whisker
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_104.wav  to try to use

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_105.wav the techniques I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_106.wav  them for the wrong reason

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_108.wav as a way to almost
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_110.wav  won't really think it's that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_112.wav  sound a little bit different but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_113.wav but at least I won't have a real

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_115.wav booking and arrest information to the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_116.wav  I kind of worked with him

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_119.wav of the idea
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_120.wav  of the stuttering first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_128.wav  and you're you know like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_129.wav  feeling the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_130.wav the shame and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_131.wav reduction means

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_134.wav the those things and your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_135.wav four insects in the fingerprinting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_136.wav that sounds kind of cool for you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_140.wav that's awesome and how long have you been doing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_146.wav and it's so cool to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_147.wav  that you're able to have the session over

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_148.wav over Skype you know like you can be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_150.wav the group support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_152.wav  need a little bit of extra
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_153.wav about phone calls

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_154.wav and you shared with me something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_159.wav  and it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_163.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_166.wav his entire life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_168.wav Frank Hall
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_170.wav frights

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_173.wav he went to the FTC and he said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_174.wav  thing is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_177.wav or something that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_184.wav  of the conversation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_190.wav  clarify cuz I guess I'm not perfect
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_191.wav  perfectly clear so you call

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_193.wav conceal it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_199.wav duction and like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_201.wav you know and the person may not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_204.wav  hey you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_206.wav  oh wow and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_212.wav  before you even get to a live person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_215.wav and I didn't get the word out you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/18/HeStutters_18_216.wav to them if we have anything on file

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_0.wav  Hi Pam I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_1.wav the public to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_2.wav  more open
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_4.wav we don't want to be considered disabled

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_5.wav  well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_6.wav  wow this has been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_8.wav  if I'm talking to you and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_9.wav  and this has been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_10.wav  it's this is not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_12.wav  what I need it that I did and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_13.wav  that's not where I was come
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_14.wav  that sort of narrow minded

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_15.wav approach comes from place of insecure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_16.wav  right because I've never done that I'm not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_18.wav you know I don't think the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_19.wav  I definitely agree because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_20.wav  work on the physical stuff without
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_21.wav also addressing the psychological

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_22.wav  there you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_23.wav  they're so intimately

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_24.wav  just wasn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_25.wav you know I don't have strong

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_26.wav  memories of that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_27.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_28.wav was convinced by
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_29.wav  where you're from what keeps you busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_30.wav my name is Chris
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_33.wav  therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_34.wav I end up going to grad school for speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_35.wav  and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_36.wav I didn't originally intend
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_37.wav  enjoyed that process of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_39.wav  phd and now I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_40.wav  Now I guess I'm doing research

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_41.wav  think I thought it would be a job where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_42.wav my story and wouldn't get in the way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_43.wav  I think that's a good question.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_44.wav  I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_45.wav two things one was my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_46.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_47.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_48.wav as a field and as people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_49.wav  of our curriculum and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_50.wav the plan is is to have lab

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_51.wav  time that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_52.wav the less

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_53.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_54.wav people who started have a hard time letting them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_55.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_58.wav  and so it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_59.wav  it seems like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_60.wav a better explanation for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_61.wav  I felt that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_62.wav  I think that's a good point.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_64.wav  use different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_65.wav and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_67.wav  skills can be sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_68.wav in addition to having the stand-alone class

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_69.wav how do we make it easier for people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_70.wav  you once you free stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_71.wav from being necessarily bad
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_72.wav but it's simply something that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_73.wav  of social consequences
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_74.wav  then you can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_75.wav  I speak obviously
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_77.wav  stuttering from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_78.wav  I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_79.wav  Spannock

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_80.wav and I tried to sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_81.wav tie that into you know even though

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_82.wav  had that down
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_84.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_85.wav I don't know that it I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_86.wav  teachers teaching in that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_87.wav block of classes and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_89.wav you know like I said earlier

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_90.wav in addition to the social
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_92.wav to be and I think even though

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_93.wav  adult clients
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_94.wav  understand it almost instantly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_96.wav that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_98.wav  to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_99.wav  you know and they help
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_100.wav  she was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_101.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_103.wav stuttering was something bad and there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_104.wav duttering class or in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_106.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_107.wav I could tell that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_109.wav her relationship with the other students

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_110.wav manics that can ostracize you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_111.wav  you yeah and especially you know at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_112.wav  though cuz they're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_113.wav there's so in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_116.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_117.wav Sam is a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_118.wav  both how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_119.wav  stuttering is position

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_120.wav how we might
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_121.wav talk about stuttering differently so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_122.wav  sort of reimaginings of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_123.wav  meanings we make

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_125.wav client has Asia right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_126.wav  what it is that you had set out to do I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_127.wav I think it did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_130.wav  it initially

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_131.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_132.wav what we ended up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_133.wav with were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_134.wav  chapters have sort of touched every aspect

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_137.wav all those things are so intimate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_138.wav  sputtering self

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_139.wav help and group support for a long
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_141.wav  except and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_142.wav and they've been working on that acceptance
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_143.wav  are really treating

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_144.wav are learning to be tech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_145.wav I think starting becomes easier

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_147.wav  systems out there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_148.wav  I think it will take a lot more time than I thought it would take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_149.wav  of people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_150.wav but it's not like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_152.wav  research on self stigma

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_153.wav  this is an effect
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_155.wav  have to be that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_156.wav  had a list of that change right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_157.wav tuttering then that's a problem

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_158.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_159.wav I think no matter how you talk that has

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_160.wav and obviously
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_161.wav  for education

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_163.wav  conditions rather than
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_165.wav  everybody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_166.wav everybody needs to be more comfortable
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_167.wav and I think that's where

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_169.wav I think if people who start
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_170.wav try to do this is just a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_171.wav  arguments about whether we're disabled
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_172.wav  right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_173.wav and I think a lot of those are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_174.wav  and how I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_175.wav look at is whether or not you're to see what has
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_176.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_178.wav  treated differently
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_181.wav  do and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/19/HeStutters_19_182.wav  ideally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_2.wav  I don't know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_3.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_5.wav  police stutters a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_6.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_7.wav  be more education available

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_10.wav socializing and stuff
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_11.wav well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_14.wav  a girlfriend now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_15.wav I had one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_20.wav company
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_26.wav back to us and stuff like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_29.wav what it is and how you feel about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_30.wav  Well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_32.wav  I have made good friends
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_35.wav  you that they think that you're stuttering is cute

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_38.wav  first of all I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_41.wav  very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_49.wav what I have seen
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_53.wav well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_57.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_58.wav  basically I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_62.wav  want to be an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_63.wav  yeah that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_66.wav  children of your own
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_70.wav  great job I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_72.wav  level
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_74.wav in that case anyway

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_75.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_76.wav are men and how many are women

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_79.wav  choosing my job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_81.wav well it sounds like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_82.wav you are and what you're doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_84.wav sharing a little bit about you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_90.wav  we don't have any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_91.wav  woman stutter and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_93.wav are there any women that work there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_94.wav Curio

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_102.wav everythursday
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_104.wav we all start off

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_120.wav  I don't know all of our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_121.wav 29 years old

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_122.wav  and I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_124.wav imitating it had a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_125.wav  remember my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_127.wav  go up and I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_130.wav next interview with yourself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_134.wav engineering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_141.wav people that stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_142.wav  Will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_144.wav will need to get out of that habit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_146.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_147.wav  I already told you that I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_149.wav  there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_150.wav  like peaking the father
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_151.wav and even my age

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_153.wav  coming back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_155.wav a lot o m

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_159.wav but you also have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_163.wav yeah and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_170.wav  about touching a separate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_171.wav  I think you will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_173.wav  ring
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_174.wav  we went out and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_175.wav  opposite and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_176.wav  it was a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_177.wav  experience I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_179.wav be stuttering purposefully

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_181.wav workshop and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_183.wav  what if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_187.wav  oh
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_188.wav well if I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_189.wav  comfortable if I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_190.wav do that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_193.wav  help me out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_194.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_200.wav when you use your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_202.wav  doesn't discriminate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_203.wav one two three
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_204.wav and a dominant

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_207.wav with your tuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_208.wav  I have actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_210.wav  followed you rank my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_218.wav and after that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_219.wav  I try to maintain a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_221.wav  how does

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_222.wav  cause they started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_226.wav the techniques all of the time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_227.wav  absolutely and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_231.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_232.wav in India that don't stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_233.wav well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_239.wav  you know I don't know what to do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_241.wav right now in my list

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_242.wav  we have almost
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_243.wav just thought of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_249.wav  get it unless we tell them about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_251.wav  mother

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_253.wav  problem level
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/20/HeStutters_20_256.wav  proud of the fact that you're so involved

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_0.wav stuttering and it's also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_1.wav  and just kind of face your fears

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_5.wav face fear right in front of me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_6.wav and this organization

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_7.wav  tremendous impact on your life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_10.wav  hmm you know that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_11.wav  engine or you must be high whatever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_13.wav balance in your life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_21.wav  well you know that the really isn't our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_23.wav  the most important that's in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_25.wav it's okay to change what you want to eat
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_27.wav  16 you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_28.wav well I'm so glad that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_29.wav you sharing and being so honest and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_32.wav store directors
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_37.wav  you know I think my face is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_40.wav any particular reason why
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_46.wav how long have you stuttered

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_49.wav and then looking back you know didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_50.wav  agreeing to share with us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_51.wav so to get us started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_52.wav  my talking like this or what was going on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_54.wav  and it's even more with better
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_62.wav and I believe I went like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_65.wav what do you need to listen to myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_68.wav but it was good therapy and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_69.wav  me maybe let her know all of that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_71.wav what you do to keep yourself busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_77.wav  5 minutes you know I believe in therapy and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_80.wav but you don't kind of click and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_81.wav  cuz I've talked to a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_82.wav people and that just doesn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_83.wav you know from a lot of young
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_84.wav  people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_87.wav did it ever limit you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_89.wav  good friends good family support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_90.wav  you know around me was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_92.wav even though you were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_95.wav again in my 20s and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_102.wav this person that person for reason

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_103.wav and you know at times I would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_104.wav  wanting to speak or not wanting to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_106.wav but not always say what I wanted to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_110.wav in interfere

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_114.wav my introduction my name is Mike
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_116.wav could be a good friend of somebody and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_117.wav  think that's one thing that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_119.wav had to make it easier

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_124.wav  covered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_125.wav did you avoid other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_126.wav situations because you didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_127.wav  found out as a person who stuttered

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_134.wav  wine for the grocery stores
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_135.wav  hmm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_138.wav  it when it this instead of that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_141.wav and maybe we should black

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_143.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_144.wav  stuttering community

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_148.wav  and then just kind of show support for each other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_150.wav  bring up a topic that you talk about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_152.wav  are away back in 1984
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_153.wav and she passed away in November

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_157.wav  wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_158.wav was that the first time you met other people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_159.wav people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_162.wav  you know 456 people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_167.wav  sure does
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_168.wav  I didn't think you know of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_171.wav is it how do they say yes and a whole in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_172.wav  of that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_173.wav  so you agree that there's definite
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_174.wav experience their stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_178.wav yes so that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_184.wav getting together with other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_185.wav people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_188.wav  experience can like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_189.wav you know help pave the way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_190.wav did all bottled up inside

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_191.wav you know I can relate to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_192.wav it was the first time I had met other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_193.wav people who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_197.wav Members have known

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_198.wav  that we deal with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_204.wav so nervous shy intimidated whatever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_205.wav the National Organization
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_208.wav  you know I want to help out with awards

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_209.wav  cop and successful
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_210.wav well I love the way that you said that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_212.wav people to get so that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_214.wav  you said that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_217.wav the past couple of years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/21/HeStutters_21_219.wav  in order some stuff it sounds like there's a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_1.wav parking on this journey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_4.wav because a young

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_5.wav are starting off in their life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_6.wav  whether it's school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_7.wav finding groups
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_8.wav  and I know there in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_12.wav and when you get that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_17.wav so it's not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_20.wav and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_21.wav  be a touch with not so bad

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_22.wav  and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_23.wav  I never had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_24.wav well you know when I asked you the question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_27.wav  observing all the things all the cultural

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_30.wav and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_33.wav I wouldn't recommend it John

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_34.wav do you recall how that made
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_36.wav it's like you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_45.wav  downloadable on itunes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_46.wav today I'm excited and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_49.wav  my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_50.wav and it's a kind of a nice breakthrough way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_51.wav so like so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_52.wav  how much stuttering I wanted to talk better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_55.wav but your phone where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_57.wav the Stuttering home page

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_58.wav  the Judy Custer runs
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_60.wav same

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_61.wav I'm going to talk I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_62.wav  but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_64.wav  John hey John how's it going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_66.wav you know feel the deal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_69.wav  part of it was that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_71.wav one person saying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_77.wav it's sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_78.wav it confuses them big because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_86.wav  which is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_87.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_91.wav re-creational famous with the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_94.wav  into the staff cafeteria

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_95.wav and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_96.wav you can't eat here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_97.wav go back to your ward
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_103.wav the same thing but I think it's changing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_109.wav  so certainly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_111.wav  helped

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_112.wav somewhat
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_113.wav  have you know multi-channel

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_116.wav  isolation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_128.wav you should get over it to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_130.wav  outside world should get over it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_131.wav how did you find

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_132.wav all these people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_143.wav um why did you the name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_144.wav I'm speakable yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_146.wav  well I was going to go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_147.wav put the elephant the pink elephant
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_148.wav  by the sofa there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_151.wav  a huge change
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_152.wav and what did you learn about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_154.wav was a decision
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_159.wav what's the difference between a hundred and fifty-two

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_166.wav eliminated the dots
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_168.wav  part of yourself as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_172.wav because you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_176.wav who wants to stutter less

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_177.wav they come across as a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_178.wav it introduced the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_183.wav speaking with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_184.wav  make us fluent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_185.wav but you're right it take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_186.wav  sociology in the college

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_189.wav  my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_191.wav the mother I stop myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_193.wav through my thoughts fast enough
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_195.wav do you find that you can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_199.wav because you feel like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_200.wav judgment isn't there right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_201.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_202.wav seriously what would you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_203.wav younger people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/22/HeStutters_22_205.wav  graduate school about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_0.wav oh how'd you get involved in that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_1.wav  it was the moment that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_4.wav  stuttering as a condition
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_9.wav baggage that we carry around

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_10.wav  there's a whole
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_12.wav in those suitcases get really heavy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_13.wav what advice would you give to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_14.wav a high school kid

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_15.wav that you know is just trying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_16.wav  be life long

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_17.wav  it may not be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_19.wav hmm yeah because when you first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_20.wav  Yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_21.wav  yeah it happened a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_23.wav  you know but I had never taken those up for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_24.wav  causes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_26.wav but it is important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_28.wav  people whose daughter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_29.wav  off
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_31.wav you're so right and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_32.wav I appreciate you being so open and honest
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_33.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_34.wav  hold on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_35.wav  yeah and I think you'll be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_36.wav  you're going to inspire a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_40.wav  to the owner

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_42.wav but it will not be in a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_45.wav so you're saying that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_47.wav because they think that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_48.wav  was stuttering well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_49.wav  well not in that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_50.wav  8888

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_52.wav  they say anything that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_59.wav  experiences of people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_61.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_62.wav most of those experiences

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_64.wav  I can't really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_65.wav  I can't really remember specific

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_66.wav  or a get
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_69.wav I am not sure if it's you just me and my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_70.wav  ee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-wee-
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_71.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_72.wav  supposed to people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_73.wav  people overtly stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_75.wav Colinary Arts by any chance
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_76.wav  stuttering overtly and what a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_80.wav it seems like there's more and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_81.wav  people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_82.wav so that they don't have to actually talk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_84.wav and stutter with others

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_86.wav writing back and forth with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_88.wav email back and forth with each other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_89.wav and I wonder are people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_90.wav  people who stutter are they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_91.wav  is all the electronic stuff
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_92.wav taking the place of that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_95.wav  well there's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_96.wav  on stuttering community

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_97.wav they were the first four
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_98.wav  I think that's a good point.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_100.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_101.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_103.wav  oh
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_104.wav just from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_105.wav people who stutter over Skype
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_106.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_107.wav allowing other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_108.wav  people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_109.wav people to see the physical
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_110.wav  I had done my Skype session

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_111.wav  I don't know what exactly came
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_112.wav well there's certainly lots of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_116.wav have you ever had speech therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_118.wav benefit it from learning

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_120.wav so did it help
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_121.wav I can say that the Hollins communication

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_123.wav  but well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_125.wav but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_127.wav  about you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_128.wav where are there any other kids

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_129.wav  had a stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_132.wav how has stuttering in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_134.wav  yeah it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_137.wav  oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_140.wav  every one in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_142.wav  right it's like the pink elephant

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_146.wav rehearsing with words that I could
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_148.wav  what about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_150.wav  well I've always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_151.wav  group of friends

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_153.wav  current job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_156.wav and I mean how did that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_157.wav  first met like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_160.wav  she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_161.wav she was a bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_162.wav  she was a bit has a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_164.wav did your friend like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_166.wav she had pretty

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_169.wav told your girlfriend that you stuttered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_170.wav  it may have been a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_171.wav  sleep so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_173.wav  based on your stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_174.wav  I will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_175.wav what does she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_176.wav  think of it I mean it sounds like it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_177.wav  sounds like it's like a non-issue

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_178.wav  issue well she doesn't think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_179.wav  any thing and it is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_180.wav uh
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_182.wav  what you can achieve

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_183.wav I totally agree with you on that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_184.wav  you on that but I think a lot of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_185.wav people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_186.wav  why people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_188.wav  I don't really understand it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_191.wav  I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_192.wav  I mean I just think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_194.wav  that well when I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_196.wav are you involved with the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_197.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_198.wav  I mean I'm not really sure how to go about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_199.wav  on the NSA through

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_200.wav searching on the internet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_201.wav you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_202.wav stepping away from their Shadow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_203.wav  got to that point in your life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_204.wav  it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_206.wav  of your own

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_209.wav for your own acceptance
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_211.wav  that helped you you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_212.wav you know come to terms with who you are as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_213.wav like what what do you mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HeStutters/23/HeStutters_23_214.wav for instance if there's an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_1.wav class and I heard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_3.wav familiar to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_4.wav  to it was the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_7.wav that one kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_8.wav funner really cuz of my study cuz I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_9.wav  study cuz I've
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_11.wav  pretty young age

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_12.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_13.wav  Hello everyone and I'll welcome to the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_17.wav  so people knew
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_19.wav  much trouble for it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_20.wav  and reason
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_21.wav  reason that hit me so hard was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_22.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_23.wav  last time I got

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_25.wav 6 or so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_26.wav very young age and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_27.wav  and difference was back then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_28.wav  Hutton Valley starting Association

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_32.wav  many stars are familiar
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_33.wav with it from that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_34.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_36.wav  kind of hit me hard and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_37.wav and I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_38.wav  want to feel that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_40.wav  way and I especially
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_41.wav didn't want others

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_44.wav  way in my area
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_45.wav  so I just want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_46.wav  I think I have a couple of chapters and the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_47.wav  and the closest one to me was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_48.wav before I was away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_51.wav  I'm just gonna start off by partnering with the NSA

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_52.wav  like local trap do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_53.wav  I decided to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_55.wav  which
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_57.wav we sent mail to the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_59.wav  non-profit thing to make
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_60.wav but we got that sent back saying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_61.wav  starting Association what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_63.wav  done it correctly all that stuff and it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_64.wav and it turned out to be relative
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_65.wav  bank account and stuff like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_66.wav  that so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_68.wav  school that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_69.wav I was trying to make it and my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_70.wav  then a sister

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_71.wav assistant principal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_72.wav she talked to me and said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_74.wav  Valley Education
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_76.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_77.wav  do so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_79.wav and wondering if you wanted to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_80.wav  partner with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_82.wav  at work so I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_83.wav  was extremely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_84.wav I'm really excited about that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_85.wav  because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_87.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_89.wav what I was doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_90.wav  started in the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_92.wav it would help spread the word a little more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_93.wav  that's already in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_96.wav what they're doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_99.wav money and stuff so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_102.wav it means a lot to me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_103.wav  to me and the Hudson Valley

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_104.wav 2018 I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_105.wav  I'm probably starting Association

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_106.wav  I think that's a good question.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_108.wav  fantastic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_111.wav some camp I do with you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_112.wav  I highly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_113.wav recommend the camp for any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_117.wav  I highly recommend

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_118.wav  I still keep in touch with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_120.wav  his friends and they don't live anywhere

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_122.wav one person just started that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_123.wav I was reading something out loud in a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_124.wav idea and it turned into a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_125.wav nation wide thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_126.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_127.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_130.wav  any more to come our next
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_131.wav  our next podcast episode will be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_132.wav founder of say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_134.wav  and it's so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/0/HVSA_0_136.wav  in a class and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_0.wav hello everyone and a welcome to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_5.wav  I hate to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_6.wav  I hate to sound like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_11.wav  but um yeah all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_12.wav  yeah I've gotten

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_13.wav  adults who started themselves
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_14.wav and stuff like that so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_15.wav the difference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_16.wav Well that's a loaded question

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_17.wav  so I'd say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_18.wav members know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_19.wav  people who are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_20.wav are interested yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_21.wav  okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_25.wav  yeah thank you for having me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_27.wav Saturday June
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_28.wav  5 p.m.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_34.wav  concerns you can email us hv
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_35.wav  us at free stoning at gmail.com

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_36.wav  com and again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_38.wav  different just being more patient

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_40.wav  with my other friend I can be more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_44.wav  so I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_46.wav wondering and I've asked
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_47.wav  second episode of the Hudson Valley

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_48.wav  asked a lot of my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_49.wav and sometimes it's not too

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_50.wav  not too easy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_51.wav  so like what's that like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_58.wav  I would say frustrating
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_59.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_62.wav it takes time understanding
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_65.wav stuttering Association

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_70.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_71.wav  kid need a band-aid

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_73.wav  I don't think bandied was my first job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_76.wav  it but more importantly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_77.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_79.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_80.wav  I would want to be you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_82.wav  I mean I wouldn't want to be friends

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_85.wav  me if I were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_91.wav the other question I asked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_94.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_95.wav  don't know that much about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_96.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_100.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_104.wav  with that has us better I don't know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_105.wav  never picked up on but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_107.wav  what would you do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_108.wav  complete stranger

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_109.wav  I would definitely like if we were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_110.wav  I would find just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_116.wav  like another thing too cuz
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_117.wav every stutter has

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_118.wav  have been friends for about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_119.wav  about 5 or 6

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_120.wav  I'm starting like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_122.wav make eye contact

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_124.wav  As long as I know that like the push
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_125.wav  like your person is listening

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_126.wav  listening cousin
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_127.wav  cuz when you're having

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_128.wav when you're having a block and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_130.wav for me at least that's a little on the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_131.wav  little on the awkward side
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_132.wav but they were like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_133.wav but like every stutter is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_134.wav  as in like what they need

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_135.wav  all that stuff
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_136.wav  so am I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_139.wav it's difficult to know what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_140.wav I don't know it's it's weird

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_141.wav  What do I say I don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_143.wav  I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_145.wav  if you could
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_146.wav  like stuff like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_147.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_148.wav that is a very tough question

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_149.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_150.wav  I'm not sure how I would define it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_153.wav  This one's a holy ball
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_154.wav when you come

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_155.wav  know without enough experience I don't know how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_158.wav um what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_159.wav  got it moves
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_160.wav  Um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_162.wav  like a lot of people don't understand it I mean I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_163.wav  I mean I feel like people understand that it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_164.wav they kind of just like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_166.wav so you really like how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_167.wav  like it's still so like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_168.wav  respect and obviously don't take

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_172.wav  those words you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_173.wav  yeah um do you have any

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_174.wav do you have any questions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_175.wav  me about the podcast I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_177.wav itself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_178.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_180.wav like stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_182.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_184.wav  yeah well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/1/HVSA_1_186.wav fluent what's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_0.wav hello everyone and welcome to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_1.wav contact about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_9.wav  I think I did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_11.wav  thanks

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_12.wav  Travis it means a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_13.wav and a 2

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_16.wav  thanks have a good day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_26.wav  to work for say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_28.wav  working for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_36.wav  discussions

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_40.wav  fluctuating like more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_44.wav  is kind of that like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_47.wav  so when did you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_48.wav  how have you fell

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_49.wav felt or seen that it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_53.wav  you know as early as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_58.wav  Travis
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_59.wav you doing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_66.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_67.wav back to what you said about like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_68.wav  it sometimes and like embracing it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_69.wav  what's your personal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_70.wav on it like should it be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_71.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_72.wav should people like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_73.wav  not started like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_85.wav  and it was as hard as you are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_89.wav  Viewpoint

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_90.wav  of the Hudson Valley
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_91.wav  so that made him want to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_96.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_106.wav  yeah cuz I'm like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_107.wav  A lot of us
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_108.wav  like solid

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_112.wav  have that base they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_113.wav they can go to say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_114.wav  like it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_115.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_116.wav what are your roles in each
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_119.wav  yeah for sure I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_121.wav  have like something stuck in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_122.wav stock with you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_125.wav  yeah I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_133.wav  was caught cuz

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_143.wav about other people like you don't know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_144.wav  and like talking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_146.wav  it but yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_148.wav  yeah I'm so like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_149.wav fake
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_155.wav  like now I'm trying to explain what's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_161.wav  catching an experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_162.wav  own it'll be fine

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_164.wav sentences I got this and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_165.wav and then the lady said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_166.wav it was a mix of emotions at that time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_173.wav it becomes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_176.wav  to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_177.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_182.wav  Um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_183.wav impact did you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_186.wav  there have been a number of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_196.wav hazardous about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_197.wav what should they do or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/2/HVSA_2_199.wav  really great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_0.wav hello everyone and I'll
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_1.wav  your life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_7.wav which one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_8.wav  body

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_9.wav  you the most
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_11.wav for people who really don't know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_12.wav what's that are in and they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_14.wav that are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_18.wav  say to me is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_19.wav  that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_20.wav that one is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_21.wav  Centrel a by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_22.wav can imagine like how much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_24.wav make people who started mad

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_26.wav  Before
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_27.wav are we finished

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_29.wav  thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_30.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_31.wav  so um thanks
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_34.wav 5 p.m. at the American

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_37.wav  thanks
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_41.wav  that life changing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_47.wav it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_50.wav  I'm doing pretty well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_53.wav  for the show we could say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_59.wav  New York

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_60.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_65.wav  always like try to stay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_67.wav  interesting question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_70.wav  thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_71.wav  Before we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_74.wav  wow that's a lot to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_75.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_78.wav  pretty powerful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_79.wav  so it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_80.wav  called it our time right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_82.wav  time to say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_84.wav  yeah another great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_85.wav  we just did this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_88.wav  end of thanks for that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_90.wav awesome
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_91.wav  I'm so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_92.wav when did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_95.wav people like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_96.wav did it go from about like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_97.wav like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_100.wav  Evermind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_103.wav  and perform them and we would go to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_106.wav  so um you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_109.wav me to you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_111.wav  kid's lives
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_113.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_114.wav  I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_115.wav  I feel just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_118.wav  have 14
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_119.wav  there you go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_123.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_124.wav manage owner

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_130.wav  say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_132.wav open the door you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_139.wav  really profound
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_141.wav  to make your own

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_142.wav at that age is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_145.wav it's kind of like a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_146.wav good for him statement
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_147.wav but for people who started to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_148.wav  young of an age is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_155.wav  So

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_158.wav  say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_159.wav whoa as a kid

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_165.wav action so I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_170.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_172.wav  when I ask that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_177.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_182.wav  my life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_184.wav most of my life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_188.wav  so that we can all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_189.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_195.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_199.wav  much better so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_201.wav  that sums it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_203.wav  know as much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_206.wav  it'll be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/HVSA/3/HVSA_3_207.wav  hate it so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_2.wav  to laugh now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_5.wav what's odd is that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_6.wav  is that the teacher who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_7.wav  on it I think the issue was is that he was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_9.wav  I did not care I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_10.wav where I'm sure he was it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_11.wav  at school where I feel like things I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_12.wav  like things like that are much more content

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_17.wav I cannot pass you if I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_18.wav  of him and I'm separating it into two parts

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_20.wav like what my mindset was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_21.wav  24 kids

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_24.wav  right before thanks
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_28.wav  that was pretty it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_29.wav  so but there was one kid in with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_30.wav in particular who would always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_34.wav  field who is the creator of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_36.wav for people who stutter only David

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_37.wav  only David how are you sir
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_38.wav  sir I am doing great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_39.wav  no it's my pleasure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_40.wav  my pleasure

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_41.wav  very interesting and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_42.wav  I'd love it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_43.wav  love it if you would tell everybody about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_44.wav  it yeah so I guess let me give

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_46.wav  thing to begin with but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_47.wav with but then when I came in for the first read-through

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_51.wav  it's a whole process for like months
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_52.wav  and I didn't stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_53.wav  at all which was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_55.wav  the stuttering community and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_56.wav and beyond which I'll speak
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_62.wav  we did Bachelor

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_63.wav  holiday which is a one-act play
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_64.wav  Allen ball cool he's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_67.wav I can't remember what else but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_69.wav order than I cause I'm only

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_71.wav  and we have an audience of like 60
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_73.wav  thing I wonder how that happens

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_75.wav  see it's interesting because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_76.wav  when I was in high school I used

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_77.wav  school I used to do all the music holes in the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_78.wav  please and everything

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_79.wav  and I really never
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_80.wav with my stuttering at all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_81.wav  at all somebody wants into
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_83.wav  I'm playing somebody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_85.wav  I didn't stutter so I don't know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_86.wav  know what it is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_87.wav  but there are a lot of theories
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_88.wav  and you had to read something from a book

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_89.wav  did you stutter when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_92.wav  this excellent theater

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_93.wav  company
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_95.wav  how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_97.wav people well so when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_98.wav  I just want to congratulate you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_99.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_103.wav  for them but I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_105.wav  all of them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_107.wav and I got responses

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_108.wav  have the funds to like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_109.wav  to lay out so we have created a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_111.wav  see so we have to raise around $7
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_112.wav  within the next 11 days

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_113.wav  days which is tough but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_115.wav  I know that it can be done

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_120.wav  how they can find the page absolutely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_122.wav  ahead so I obviously can't read out in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_125.wav  walk-on Rolls wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_126.wav  walls wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_127.wav  would this be interested
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_128.wav interesting to people who don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_129.wav and that's where it all comes together which is why
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_139.wav  to this point

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_140.wav  bad my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_141.wav  very first memory

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_144.wav  to that point I was a pretty
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_146.wav  a retard and from that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_148.wav  like that's where a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_149.wav  a lot of my like avoidance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_150.wav  to talk well it wasn't that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_153.wav  him quite a bit of speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_156.wav  some crazy stories to tell about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_158.wav she gave me the amazing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_159.wav  to make things worse and like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_163.wav  quiet side and it definitely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_164.wav  affected my cell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_165.wav  Stubb during is one of those things that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_166.wav that like no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_167.wav  to speak or expected to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_168.wav  to communicate in some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_169.wav  much more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_170.wav  what's been interesting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_171.wav between like maybe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_172.wav seventh through a lemon
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_173.wav  So beer I would have double

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_175.wav minutes and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_176.wav  on every single

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_178.wav I recorded a very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_184.wav what are the more interesting things I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_185.wav  about stuttering is that it's not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_186.wav is that the severity is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_187.wav  I stuttered my speech has changed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_188.wav  change tremendously

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_189.wav  first got into high school I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_193.wav  to act right and you know I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_194.wav all I wanted life was just to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_195.wav  class and the teacher calls I mean it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/0/IStutterSoWhat_0_197.wav  long interview
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_0.wav process that I truly do not understand

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_1.wav defying the odds I'm going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_3.wav defi the odds

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_4.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_5.wav and I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_6.wav  I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_8.wav  or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_9.wav  who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_10.wav who have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_11.wav  said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_12.wav ice stutter but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_13.wav but the stuttering is not going to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_14.wav  I am as a person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_15.wav the stuttering is not going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_16.wav  man I want to thank

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_17.wav I'm becoming who I am or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_19.wav  life so I'm super excited I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_20.wav  I have a great episode
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_21.wav  coming up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_23.wav  like power he's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_24.wav  video editor

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_25.wav and a videographer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_26.wav  The Orlando magic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_27.wav  is life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_28.wav and actually he is changing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_30.wav  now if instant he's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_31.wav career that will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_32.wav Danny Lai Rossi
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_34.wav be even more on a regular

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_35.wav basis and I'm not gonna
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_37.wav  that career is you're gonna have to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_38.wav  my next podcast to find out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_39.wav  out really excited to speak

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_40.wav  speak with him
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_41.wav and that will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_42.wav my listeners also I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_43.wav  so I want to hear what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_44.wav  past
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_45.wav  let me know how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_46.wav  you want me to interview hey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_48.wav  did this good guess I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_49.wav I am open to I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_50.wav  ideas so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_52.wav  my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_53.wav  teaching

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_54.wav  listeners
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_55.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_56.wav  and I live there for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_57.wav  28 long years I'm now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_58.wav  I'm turning the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_59.wav the big 3 in April

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_60.wav  not too excited about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_61.wav  out but yeah I move down here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_62.wav  of this year
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_63.wav and I graduated

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_64.wav  language pathology
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_65.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_66.wav  so I moved down
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_67.wav  school district as a speech language

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_68.wav  language pathologist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_69.wav  specializing in doddering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_70.wav but unfortunately
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_71.wav danny E

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_72.wav his Pod
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_73.wav  in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_75.wav  I decided
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_76.wav  this is why I have this pod

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_77.wav  this podcast because I love talking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_78.wav  and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_79.wav  I'm also a host
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_80.wav  first daughter social

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_81.wav  much as a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_82.wav  eyes Google Plus

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_83.wav  so we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_84.wav chap face-to-face with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_85.wav people who stutter from around the whole
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_86.wav  so I love

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_87.wav  social hangouts are on Sunday
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_88.wav  Sunday nights 8

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_89.wav podcast is on his website which is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_90.wav  so feel free to check

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_91.wav  about this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_92.wav stuttersocial.com

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_94.wav  around the world so much fun
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_95.wav so that's a little bit about what I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_96.wav  do and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_97.wav  to do and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_98.wav I and a little
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_103.wav  life through

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_104.wav  through these pi
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_106.wav be sure to check that out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_108.wav and if you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_109.wav and if you'd like to learn

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_110.wav  the log on there and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_111.wav  and I log

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_113.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_114.wav  so I would encourage

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_115.wav  blog
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_116.wav and to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_118.wav  so feel free to post
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_121.wav and also feel free to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_122.wav  hard to cast
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_123.wav cast also if you want to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_124.wav  do it now as I said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_125.wav  said my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_127.wav  me my email is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_128.wav  Evan Evian that's my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_130.wav evan
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_131.wav Evan at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_132.wav at ice stutter so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_133.wav gowhat.com

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_134.wav  so I guess that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_137.wav my pod and cast

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_138.wav  idea of my podcast
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_139.wav is really about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_0.wav  here why don't you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_2.wav  times like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_3.wav  it's the small things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_5.wav people who stutter out there who are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_6.wav  whoo
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_7.wav  to achieving life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_12.wav  I'll think really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_13.wav  really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_14.wav  let me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_15.wav  this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_16.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_17.wav and it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_18.wav  the most important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_19.wav  people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_21.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_24.wav for the ones that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_26.wav and listen
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_28.wav book about it I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_30.wav give you a hard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_38.wav  pap dancing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_39.wav  it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_42.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_45.wav  When you first got into it I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_46.wav  it I wasn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_49.wav  wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_52.wav  interesting so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_56.wav  for it also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_61.wav  70

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_62.wav  wow I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_67.wav  really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_69.wav  the dances
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_73.wav  I used some Coleman which was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_74.wav a big one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_76.wav  Hey Jack Chambers

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_77.wav  it just a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_78.wav  it just to clarify

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_79.wav  it was separate so interesting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_82.wav  So you got on the show

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_84.wav what was everybody's reaction
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_85.wav  they really didn't know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_88.wav  I'm also an aircraft
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_94.wav  I'm sure

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_95.wav  yeah I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_101.wav  emails

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_102.wav  saying how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_104.wav  who's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_106.wav  find
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_107.wav  price

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_108.wav  really I wasn't you still
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_113.wav  they're not really ready

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_114.wav  so are you still involved in so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_115.wav  so are you still involved in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_126.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_129.wav  There too which is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_133.wav  run into other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_134.wav people who butter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_137.wav  and I'm yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_143.wav  there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_151.wav  work like is it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_152.wav  it mainly just like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_153.wav she just like a group of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_154.wav people to talking about stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_157.wav  hips and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_160.wav  I can make it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_163.wav have a really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_165.wav  about it because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_166.wav  ever since grade 5
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_168.wav  at school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_169.wav I was cool Captain which
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_171.wav  it was really good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_175.wav  and I just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_177.wav  so one eye

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_179.wav  Yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_180.wav  I was in school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_181.wav  was specifically in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_183.wav  time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_187.wav  are you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_192.wav  I hate to say it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_196.wav  it hasn't released
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/2/IStutterSoWhat_2_197.wav  in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_0.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_7.wav  you both

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_8.wav  telling us a little bit about your Pod
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_9.wav  your pod test that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_10.wav  is over years now huh yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_11.wav  huh yeah I just did simple

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_12.wav  have people leave messages
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_13.wav  and I play it just so I can play it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_14.wav  a lot of fun experimenting and all that it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_15.wav but yeah and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_16.wav  social is that right yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_19.wav  I think last year was one of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_21.wav  I think last year was the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_22.wav first time that I've met

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_23.wav okay so would you guys like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_24.wav it to other people you stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_25.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_26.wav  it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_27.wav  it was at the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_28.wav  NSA conference in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_29.wav  in Texas which was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_30.wav first met Dan and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_31.wav  else and it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_32.wav through that or like I first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_33.wav  first got involved with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_34.wav  with Stutter social and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_35.wav kid Dan was the one who I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_36.wav  Canadian stuttering is so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_37.wav  no no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_38.wav okay yeah so it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_39.wav kind of like a domino effect
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_40.wav  fact and you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_41.wav  hangouts as well right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_42.wav  right it's better social

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_46.wav  community
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_47.wav  one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_48.wav what are your hangouts on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_49.wav  mine are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_50.wav every other Thursday
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_51.wav  8 30 p.m.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_53.wav  Eastern there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_55.wav I have here with me today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_58.wav  all turn 8 every other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_63.wav minds are every

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_64.wav  me all right excellent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_66.wav  calm yeah and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_68.wav so involved in a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_69.wav  in a buttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_70.wav  Friday morning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_71.wav doing good him how are you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_72.wav  walk or something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_75.wav  Canada soon all there's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_76.wav  soon oh there's always something going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_78.wav  it's a 1k5

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_79.wav  speech and Stuttering Institute
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_80.wav which is a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_81.wav hopefully eliminated
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_82.wav  did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_83.wav  um higher P
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_84.wav  business my say is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_86.wav  yeah so have you bowed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_88.wav  for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_89.wav personally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_91.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_92.wav I've been involved to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_93.wav  Um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_94.wav some extent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_96.wav  basically helping it with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_97.wav  media here and there and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_98.wav  helping you like to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_100.wav  promote the walk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_101.wav that's really as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_102.wav  contributions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_105.wav you doing good thanks yourself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_106.wav  yourself I'm doing all right I didn't dress
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_107.wav  everybody has the internet so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_108.wav  that's a huge a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_111.wav  especially now that it's also expected

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_115.wav  oh yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_116.wav  am so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_117.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_119.wav  fall color so it's going to be a nice walk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_122.wav  you have breakfast now it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_126.wav  going to be a pleasant today for sure

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_129.wav  people can get involved
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_130.wav  can get involved or like how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_131.wav people can go about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_132.wav donating for the event

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_133.wav  event it's actually part of the Canadian
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_134.wav udder.ca walk that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_135.wav  walk that's the website for well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_136.wav  on the sponsors page great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_137.wav  great and you also have an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_140.wav  unemployment thing so I sleep in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_142.wav  Well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_143.wav  I've also heard yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_146.wav  who made a headline
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_147.wav  and there's a video of him so yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_148.wav  so yeah he's our walking by a sit or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_149.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/3/IStutterSoWhat_3_150.wav  of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_1.wav  disorders I just heard a nice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_2.wav  presentation yesterday on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_3.wav  there are a lot of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_4.wav  people out there who are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_6.wav  he said that a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_7.wav  yeah a lot of those are you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_8.wav something that can only imagine you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_9.wav  that I really it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_10.wav  yeah I mean slow rate you know you brought up the slow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_12.wav and as per my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_13.wav  Daddy is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_15.wav completed my B deck
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_16.wav and generating

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_18.wav computer science branch
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_19.wav and nowadays I'm searching

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_20.wav  two
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_21.wav I just want to say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_25.wav  actually I got
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_26.wav  research is paying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_27.wav because I'm sure that you are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_28.wav is gambling problem

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_32.wav the same
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_34.wav doing so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_35.wav  so by any patient
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_37.wav truly I'm a step

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_40.wav person then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_41.wav then you can do all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_42.wav  us to truly understand the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_43.wav  all about stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_46.wav gamin fear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_53.wav  just gone so I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_56.wav  except the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_57.wav  so nowadays

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_61.wav coordinate the meeting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_62.wav and there are some great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_63.wav and I'm so glad that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_64.wav I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_66.wav and actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_74.wav  guys so that you may also

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_76.wav  real pws
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_77.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_78.wav  so enjoy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_79.wav hello everyone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_81.wav in my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_86.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_88.wav situation like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_90.wav and after that we just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_91.wav concentrate on the work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_93.wav but basically I'm from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_94.wav  most relax
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_95.wav  stamping

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_104.wav  you know technique you can but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_110.wav take care see you once again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_111.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_113.wav  it too smoking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_115.wav no for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_116.wav  personally I truly don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_117.wav I have the choice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_118.wav of stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_120.wav  so that's why the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_121.wav  bad habit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_123.wav  listeners to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_124.wav  post their comments about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_126.wav  brought up is that you feel that stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_127.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_128.wav  I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_129.wav currently I'm living

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_130.wav  that imitation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_133.wav now I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_134.wav  questions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_135.wav  so today I have a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_136.wav as well aren't you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_138.wav  teaching in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_139.wav just of course and stuttering so it's wonderful
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_140.wav  the students really got

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_141.wav a lot out of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_142.wav that helps us all be better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_143.wav clinicians you yourself are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_145.wav put on by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_146.wav  all ages
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_147.wav all around the world I mean the flags that go up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_148.wav there's also needing to be more than
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_149.wav the normal types of repetitions going on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_151.wav is your man a girl
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_153.wav  interesting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_154.wav points about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_155.wav  his heels that he

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_156.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_158.wav  he's sort of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_159.wav  let me see how do I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_161.wav catch this to the hot drink

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_163.wav  have been attributed more to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_164.wav genetic reasons

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_166.wav  thank you for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/4/IStutterSoWhat_4_170.wav still the least well understood in some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_0.wav the stuttering life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_1.wav  speak confidently

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_2.wav lastly we have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_3.wav  to say it as soon as possible

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_4.wav  amazing thank you guys so much our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_7.wav  guess what he's doing it so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_8.wav individuals who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_9.wav Facilist Daniel Rossi Angela

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_11.wav  you have a speech impediment you may also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_12.wav  any strengths that you possess as a human being and with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_13.wav who is a stuttering coach
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_14.wav what's going on Pedro

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_15.wav  in life or your purpose in life think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_16.wav  a music producer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_17.wav now whatever that thing is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_18.wav his self-esteem is very fucking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_19.wav are you ready okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_20.wav or what kind of characteristics will you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_21.wav  on your purpose you started less
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_22.wav  recording from Toronto in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_24.wav  a lot more confidence in that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_26.wav  your thoughts

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_29.wav our next tip comes from a ram
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_31.wav you should know that stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_32.wav  it's not something that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_33.wav  history is something that can be solved

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_34.wav so our first tip comes from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_35.wav  the block and let it goes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/0/MyStutteringLife_0_39.wav  care our next tip comes from Aaron
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_0.wav  last time that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_1.wav  I just let him blossom as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_2.wav what happened in the aftershow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_3.wav  for him to say something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_4.wav I'm exhausted

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_5.wav  Christian would have to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_7.wav  we need to follow the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_8.wav the person in my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_10.wav  breakthrough but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_11.wav  on why Christian doesn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_12.wav the only

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_13.wav  don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_14.wav make a phone call

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_15.wav  absolutely not that me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_16.wav  ask us but if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_17.wav but if it's an adult
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_18.wav he doesn't you will never

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_19.wav  conversation with someone on the other end
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_20.wav everything is video chatting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_21.wav and I know that there's something behind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_22.wav  here and hold a conversation with you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_23.wav  that he's going to be a senior in high school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_24.wav and the techniques used

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_25.wav and that's why he doesn't acknowledge
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_26.wav  about four days ago

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_27.wav  in various positions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_28.wav  in this case now each case is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_29.wav the brain and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_30.wav  and also in college

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_31.wav the deck of course they were dealt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_32.wav for example we do not finish

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_34.wav  if he isn't a college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_35.wav  it does come out we're going to deal with it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_36.wav  the other way right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/1/MyStutteringLife_1_39.wav  So after my video

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_1.wav  good meeting to you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_2.wav  or that same first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_3.wav  if you just put
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_4.wav perfect we will have all those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_5.wav  fantastic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_7.wav  the subject as soon as possible but I'll

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_12.wav  that's very mint
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_13.wav  and I'm actually just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_14.wav unfortunately
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_15.wav  I'm anything from a store but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_16.wav  definitely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_17.wav the people who started possibly what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_20.wav was it helpful I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_21.wav  think about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_22.wav and then I am just on the couch
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_23.wav  it that will right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_26.wav  who would help me out and that would anger me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_27.wav to animals in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_30.wav  isn't that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_31.wav  a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_33.wav  I think it can be helped
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_34.wav and how did you do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_35.wav  things I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_36.wav  something that you're doing wrong so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_37.wav  that I do at work lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_38.wav  helping to understand other people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/2/MyStutteringLife_2_39.wav  life they're all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_0.wav  embrace the grind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_1.wav  great advice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_2.wav  sharing you are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_3.wav  Oh that's a great question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_4.wav  to just tell your story

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_5.wav  you know that was just a little rough
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_6.wav but what is the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_7.wav  effective
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_8.wav  like breathing so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_9.wav  super I did for it.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_10.wav  we would like practice playing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_11.wav your sentences okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_12.wav  because all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_13.wav  so not that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_14.wav  40

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_15.wav  Stutter I just focused on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_17.wav  obviously it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_18.wav  you had was it helpful
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_20.wav  take that time and so I just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_21.wav if you would like to learn more about me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_22.wav  I would love to talk to you right now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_23.wav you are in college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_24.wav  you are a tough

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_28.wav well let me tell you Andrew
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_29.wav  so I picture you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_30.wav  now what is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_31.wav your perspective on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_32.wav I could only see how it could help me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_33.wav and how did you do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/3/MyStutteringLife_3_36.wav  and his course
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_1.wav play well Callum this will not be our last

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_2.wav  will be because you can bet that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_6.wav  me that people were laughing at me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_7.wav do you have any advice for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_8.wav tell him Scofield

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_9.wav the heat jumped on me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_11.wav  I know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_12.wav because of this self-doubt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_13.wav and old life's stressors

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_15.wav after a couple of Roman Cokes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_17.wav  trend if you want to that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_18.wav  I have mine set
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_19.wav what you said they about every

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_20.wav  that gives you the little boost
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_23.wav my history before I turned 40

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_27.wav  for school years had you ever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_28.wav even though you're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_30.wav  name
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_33.wav  theater watching this movie you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_35.wav  and make your things better you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_38.wav  just a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/4/MyStutteringLife_4_39.wav  I could agree more with what you said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_0.wav  just kidding it's David Hooper from Big

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_1.wav  speak they had pulled me up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_3.wav well that if I could

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_4.wav to the military
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_6.wav  as a speech language pathologist thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_8.wav  what types of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_9.wav  do you provide for the family's well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_10.wav remembering to do things remembering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_11.wav  whatever their memory or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_12.wav  them and that capacity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_14.wav  you know and I noticed you did some breathing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_16.wav  been a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_18.wav do their chest area

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_19.wav  to take a deep breath so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_20.wav  as I exhale

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_21.wav  which is working with people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_22.wav my positive affirmations

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_23.wav  for me I totally agree with a positive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_24.wav  person that can sit for 10 minutes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_25.wav  that there's other things you can do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_26.wav  minutes so Guided meditation can be really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_27.wav  information because I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_28.wav  on what that person needs at the time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_31.wav  and for some people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_32.wav one new trishin because here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_33.wav well they could reach out to me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_34.wav  you that is awesome now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_35.wav  great thank you I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_36.wav  some people I want to connect you with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_37.wav  possible from my end of things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_38.wav  more like cognitive therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/5/MyStutteringLife_5_39.wav  so we're working on memory
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_1.wav the zone I learned

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_2.wav you're an organs are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_4.wav I'm so powerful that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_7.wav  I've been doing this all day and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_9.wav take out my phone you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_10.wav  accepting of themselves I think that I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_11.wav  so oh wow yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_13.wav  white German
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_14.wav  shipper dog and the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_15.wav  by Stuttering began and it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_16.wav  is it any of those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_17.wav  my limbs were heavy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_20.wav to go process

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_22.wav  turkey and you know I had never been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_24.wav  absolutely oh man that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_25.wav  i really haven't run into anybody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_27.wav  and things like that because I found you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_28.wav  and that's where I felt most
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_31.wav  that your parents you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_32.wav basically my heart was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_33.wav for telling you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_37.wav well Monday the job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_38.wav  I'm going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/6/MyStutteringLife_6_39.wav  office and I packed up my entire
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_1.wav  and inspiration and this will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_2.wav and this will not be our last
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_6.wav  Well first place

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_9.wav two years and eight months but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_15.wav  like that without any reason now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_16.wav  now have you ever had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_17.wav  speech therapy yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_18.wav  yes I have speech therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_20.wav  really nice she gives me a few

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_21.wav  a few things to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_22.wav  perfect

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_24.wav you know growing up all through school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_25.wav  school and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_28.wav  there be techniques and tips
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_29.wav  and tips to help me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_33.wav this is episode number
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_34.wav  you are really good actually no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_35.wav no you are in high school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_36.wav  so how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_37.wav  is high school life with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_38.wav with having stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_44.wav that is good to hear because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_45.wav  hear because many people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_46.wav supportive yeah that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_48.wav  like half an hour ago

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_49.wav  go and like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_50.wav  most of my people didn't know that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_53.wav  didn't know that that I have started and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_55.wav  Tell told them about that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_60.wav  me is title
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_61.wav the place and they're like oh my god is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_62.wav is he okay do we have to call
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_67.wav  fluency

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_68.wav  because they were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_70.wav  advice for teachers

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_73.wav  because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_74.wav  something that happened to me it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_75.wav  me it's just one teacher it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_76.wav  my friend and you know it's the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_78.wav  in front of my class
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_79.wav  less and she asked me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_80.wav if I have stado
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_81.wav  and that's a bad way to do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_85.wav  you know I can hear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_87.wav it's just crazy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_88.wav if and if there is a block now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_89.wav  walk now for me I will either

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_90.wav  wow no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_91.wav  no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_92.wav  weird one but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_93.wav  one but I hope

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_94.wav  if you stutter you don't really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_95.wav  don't really have a block because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_96.wav  about that okay like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_97.wav  like people is doing this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_98.wav  this but when I say to my clothes for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_100.wav  long time until when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_102.wav  to be a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_104.wav  like that I go with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_107.wav  95% fluency and it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_108.wav  and it was great like I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_110.wav  back I go to the speech therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_112.wav  I finished with him I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_114.wav  started this appeal again and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_115.wav  gain and like I had my body

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_117.wav  of the competition all of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_118.wav like I'm not used to it and like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_121.wav  for me my body is always tense
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_123.wav  lip because it is so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_124.wav who care about you and tell them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_125.wav  and tell them that way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_126.wav  off the light lock the door
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_127.wav  the door and just wait for the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_129.wav  because it happened
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_130.wav  it happened to me a lot but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_131.wav but I'm doing this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_132.wav  the first time because it's like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_133.wav  since I'm 2 years old
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_135.wav get it out that's when I tell them to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_136.wav  them to be patient and that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_137.wav  go to a restaurant okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_138.wav  okay and you have the menu
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_139.wav stuttering well yeah just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_141.wav  right oh my god
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_144.wav  you and sometimes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_145.wav react like I said no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_148.wav  right and even I had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_149.wav  that I was so angry and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_153.wav  it okay no do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_154.wav  way and I was so angry that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_156.wav  before I heard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_158.wav  that didn't happen to me but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_161.wav we didn't have mobile phones

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_162.wav  phones we had pager
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_164.wav  back in the day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_166.wav okay gal you are awesome
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_167.wav  so through the app I pay for it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_168.wav  for it go through the app and they come
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_172.wav  the family stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_173.wav no and that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_175.wav how do you cope with that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_176.wav  use it a lot and the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_177.wav  the menu with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_179.wav  how like yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_182.wav once I have to do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_183.wav you I'll tell you what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_184.wav  what and because like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_186.wav  love not they bully
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_187.wav  that like talk about it you know even

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_189.wav  about stuttering okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_190.wav  stuttering okay so you say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_191.wav  time physically emotional
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_192.wav  I actually feel you know I do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/7/MyStutteringLife_7_193.wav  you know I do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_0.wav  you know out of a block I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_2.wav  and tips in our tool box that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_3.wav that for me I just have to pick one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_4.wav  just take your time there's nothing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_5.wav  have a little speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_6.wav  impenitve my normal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_7.wav  called voice indiction and public

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_8.wav  has that ever happened to you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_9.wav  you with having a stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_10.wav  I feel your struggle cuz I've been there too
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_11.wav  funny thing is I could rap and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_12.wav and I've heard that before how people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_13.wav and doing speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_15.wav that will be coming out and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_16.wav knowing there's a hard word

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_17.wav  want you to do is recite
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_18.wav  that day when he told me that it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_19.wav  that it's like I have from that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_21.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_22.wav stuttering taught you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_23.wav  you it's taught me to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_25.wav  impediments it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_26.wav  support you know that we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_27.wav  I will give to them is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_28.wav  to Hammer home what I mentioned earlier

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_29.wav that you can say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_30.wav powerful amadvice and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_31.wav we all have issues no one is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_32.wav you know the world is not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_33.wav  have to move fast
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_34.wav  to hear what it is that they have to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_36.wav  the platform you know let's just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_37.wav and I was like wow like mom was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/8/MyStutteringLife_8_39.wav  are speaking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_0.wav this is Episode 26

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_1.wav  a person that cannot say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_3.wav  because you are damaged

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_4.wav  college is are not going to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_6.wav  this my entire life until

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_7.wav and cannot do in this life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_8.wav  care what other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_9.wav  going to care if they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_10.wav  and I'm tired

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_11.wav  weight was lifted okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_13.wav  prior to turning 40

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_14.wav  turning 40 I did not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_15.wav  it stuck on a word I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_16.wav  I don't want to be holding
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_17.wav  everybody wrong I wanted to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_18.wav how to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_19.wav  job interviews were just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_20.wav  the worst I would have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_21.wav  another position

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_22.wav  telephone panel job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_23.wav and when I did that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_24.wav  you know and I had a pretty similar
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_25.wav  I don't know I was very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_27.wav  so getting to Turkey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_28.wav  it taught me that we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_33.wav  you just everything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_36.wav  I want to push myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/9/MyStutteringLife_9_38.wav  to your website
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_0.wav  short legs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_1.wav  and thankfully the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_2.wav in the beginning

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_3.wav  and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_4.wav  when I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_5.wav  to speak you could not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_6.wav everything on all the confidence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_7.wav would speak
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_9.wav you are an outcast

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_11.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_12.wav what was helpful was speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_13.wav  jar and that would cure me well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_14.wav  continued with my speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_15.wav  I was walking home from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_16.wav from school and there was a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_17.wav who you are where do you live
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_18.wav  subject my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_19.wav  object myself to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_20.wav the shame the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_21.wav the embarrassment of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_22.wav  would always skip the first two days

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_23.wav  in as if nothing ever happened
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_25.wav and I went to processing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_26.wav  give commands because of my stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_27.wav and so I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_28.wav  from the hypnosis everything and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_29.wav and I passed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_30.wav and so it was really awesome
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_32.wav  of Pedro but as you listen

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_33.wav  alone you got Pedro so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_34.wav cast this took me two weeks to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_35.wav to prepare because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_36.wav  this podcast so I want to thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/10/MyStutteringLife_10_37.wav  want to thank you from the heart of my bottom
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_0.wav  a voice message or email me a day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_1.wav in because I believe that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_3.wav believe me I've been through it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_4.wav three years woo I'm 40
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_6.wav I could not go on a date

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_7.wav  job that I wanted heck
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_8.wav a couple of friends but as I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_10.wav and also the laws of attraction so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_12.wav  myself I was learning

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_13.wav something that I never
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_15.wav  around three times and it's going to come true well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_16.wav  I'm still in my 40s I'm 40
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_17.wav  and I've had so much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_18.wav  was at rest wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_20.wav so what I did is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_21.wav  now let's talk about timing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_23.wav it took me to turning for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_24.wav  me to do this at the age of 40
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_25.wav so here is an important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_26.wav thought to believe in the impossible
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_27.wav justing so if you have a win if you have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_28.wav  a success share it tell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_29.wav  let me tell you it's a huge win have a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_30.wav whatever you put out you get back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_32.wav  they could see me now and that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_33.wav on this powerful quote
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_34.wav at the moment that you believe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_35.wav the moment that you believe you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_36.wav you can you will the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_37.wav will the moment that you believe you can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_38.wav you can't you won't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/11/MyStutteringLife_11_39.wav  you so I want you to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_2.wav  if you have a T shirt you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_3.wav  Merch down the line
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_6.wav  if having a stammer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_7.wav  100% agree
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_8.wav  they did not have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_9.wav  let's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_10.wav 98% of the jobs were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_12.wav  interview without telling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_13.wav telling them that you have a stammer or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_14.wav because you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_15.wav  couple of words if I do get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_16.wav  with your parents that way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_17.wav  support you because you know we have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_18.wav  we have really bad days I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_19.wav  because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_20.wav  people to help me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_22.wav  day do you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_23.wav  so I'm curious
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_24.wav  other hot topic I mean this gets

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_25.wav  and that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_26.wav  I tell you I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_27.wav  should write books I know on a slide I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_28.wav  and all that and drama

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_29.wav  I didn't get accepted on my drama
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_30.wav it's just awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_32.wav  think she hit a button
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_33.wav oh my gosh what have I done

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_34.wav  wonderful but just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_35.wav  that I can do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_36.wav  was it helpful so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_38.wav the people around you have got to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/12/MyStutteringLife_12_39.wav  how cool now I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_1.wav because I was very introverted

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_4.wav  and that was the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_5.wav  is the only place in Hysterea

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_6.wav  yeah I'm ready to jump in that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_8.wav  they would always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_9.wav  feeling more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_11.wav  children who's daughter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_12.wav  that's why I think my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_13.wav  I want to touch upon these things for people that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_14.wav  speaking of careers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_15.wav it still is dancing for me so she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_17.wav  granted I got over it I got my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_20.wav  was the special one who needed and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_21.wav  that was taking place in my life did create
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_22.wav moving forward

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_23.wav was that the case
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_24.wav  I was preoccupied with did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_25.wav  be present in your life and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_27.wav  so I think this applies

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_28.wav  stuttering and blocking and not breathing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_29.wav  grow as a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_30.wav  right because you're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_31.wav  led you to what you do now so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_32.wav  to get more insight into my own
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_33.wav and she stopped

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_35.wav  so what has
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/13/MyStutteringLife_13_36.wav  who I am in my experiences so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_2.wav  and then for others I guess
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_3.wav it's realized that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_4.wav which I did not and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_5.wav the worst thing in the world

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_7.wav  I appreciate it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_8.wav way so yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_9.wav talking about your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_10.wav  questions you know let us know and we can help you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_11.wav  how I would cope with it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_12.wav you make a very good point

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_13.wav your stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_14.wav  that has helped me out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_18.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_20.wav my usual go to is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_21.wav  easy onset let
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_22.wav  and they also and but then there are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_23.wav  I just don't want to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_25.wav  that fight with that person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_27.wav oh damn it whether it takes us
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_28.wav but if I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_29.wav  I quote when I say the word normal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_30.wav  career no stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_31.wav  it's open up a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_32.wav  in a way starting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_33.wav  community so here we go
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_34.wav  there was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_37.wav  so I don't have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/14/MyStutteringLife_14_38.wav  and I did use it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_0.wav  wow I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_1.wav when people would tell him to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_2.wav  him to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_4.wav  speech therapy and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_5.wav  I have a lot of issues with my back to speech therapy and then I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_6.wav  the confidence behind their study

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_8.wav  as an argument for having both
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_9.wav  your life you are purely supportive and then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_10.wav  This is episode number 40
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_11.wav I can freshman year is now a friend of mine so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_12.wav  of mine so people can clearly change
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_13.wav  it's taught me so much and it's how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_14.wav  here and now people are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_16.wav  at create all these things for yourself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_17.wav  they don't really care if you study
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_18.wav like hi it's part of me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_19.wav  it's a finding those friends who are great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_20.wav  through your school years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_22.wav  but to me it's all about taking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_23.wav  have what's your most effective

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_26.wav and I'm here for my appointment
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_29.wav  speaking I'm fine

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_31.wav  almost ever and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_33.wav  for stutters so and so forth bigger

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_35.wav utter yeah so my L a grandfather
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_37.wav  I like a posh Ria

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/15/MyStutteringLife_15_39.wav  yeah no so he's the only one I know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_0.wav  all through grade school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_1.wav  you the one thing they want the most
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_3.wav  intense and that would anger me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_5.wav  rhythm of where to breathe within
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_7.wav  you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_8.wav  was a lot younger was a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_9.wav  year than what it is now but a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_10.wav you know just something like that in my hand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_11.wav because you know Glory

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_13.wav  like that helps me as well with my fluency cuz
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_14.wav  all the day we all have our priorities and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_15.wav  those present a little bit more of a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_17.wav  I'll tell you when a Beck

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_18.wav one ask them out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_19.wav hey Google turn on the bathroom light or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_20.wav  with those types of devices than anything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_22.wav  was good or bad and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_23.wav  where I'd go home and I was surprised
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_25.wav down the road because of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_27.wav  a lot of frustration with this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_28.wav  myself and now that there's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_29.wav  of okay just calm down you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_31.wav  me the big E empathy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_34.wav  that's powerful so okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_35.wav  advice I gave to parents and teachers if you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_36.wav  I would like to thank you for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_37.wav for spending time with me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/16/MyStutteringLife_16_39.wav  awesome she is and let m
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_0.wav  group presentation I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_3.wav  let me tell you I've had job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_4.wav  when they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_7.wav I could not do the telephone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_8.wav  the telephone right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_9.wav  that are not visible
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_10.wav  me go into

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_12.wav  that's interesting stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_13.wav  my cousin Benny

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_14.wav  it will let me tell you that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_15.wav  movie completely changed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_16.wav  law in school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_17.wav lifting you up cuz in a million

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_18.wav they want to pull you down and bring
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_19.wav  then my heart is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_20.wav  to move in a way that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_21.wav I get these emails I get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_23.wav  Do you consider your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_24.wav uttering was something that I mean we still

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_25.wav  no so this is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_26.wav when people finish my sentence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_27.wav  about well I don't want to pass out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_28.wav  because I applied last

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_30.wav  All right so I'm listening to my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_35.wav  people find more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_36.wav  and I'm going to go back to the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_37.wav  what you learned is that life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_38.wav  fantastic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/17/MyStutteringLife_17_39.wav  had created

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_0.wav  sort of deal with it and process it as it come
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_2.wav she had difficulty you know talking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_3.wav  cuz I don't know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_5.wav  for for settering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_7.wav  your year in high school I would check
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_8.wav was a stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_9.wav  so do you read
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_10.wav  like friends with everyone and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_11.wav  theater department and so as a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_12.wav  I enjoyed doing it and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_13.wav  maybe I can try to do this drama thing so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_14.wav where did I had a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_15.wav  and so I joined the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_16.wav my head the whole time however

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_18.wav  I cannot do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_19.wav  blocks and more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_20.wav  or poluancy for sure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_21.wav  I'm gonna say then my attention

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_23.wav go I would say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_24.wav  this very traumatic experience every week by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_25.wav  over to the policemen you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_27.wav  better right and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_28.wav  because life goes on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_29.wav  So what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_30.wav so what is your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_31.wav right did that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_33.wav  yeah that's just my life met
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_35.wav  having a bad speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_36.wav  off ever since I can remember be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/18/MyStutteringLife_18_39.wav that might also have a stutter no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_0.wav and when you take your time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_2.wav you think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_3.wav that's amazing Pedro good for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_4.wav let's talk about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_5.wav a career
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_6.wav because it wasn't about me not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_7.wav  and the speech therapist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_8.wav that's amazing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_9.wav  married now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_11.wav now we have all of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_12.wav I don't think it's hurtful for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_15.wav being loved by everyone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_16.wav and that it is whatever it is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_17.wav  it is that you want for yourself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_18.wav because I think that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_19.wav  and then it can lose its power

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_20.wav  any fluency phases
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_21.wav so I think that was always something that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_22.wav found method in this case for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_23.wav have a friend in common

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_25.wav with doing the del faro method
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_26.wav and that was something that for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_27.wav  without needing to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_28.wav  and then I would also always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_31.wav will not be my reality
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_32.wav and that is a quote from less

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_33.wav chair and the kid behind me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_34.wav it's about you claiming your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_35.wav since we're talking about people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_36.wav  yourself to think of the sentence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_37.wav do the steps that they taught you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_38.wav  to say the sentence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/19/MyStutteringLife_19_39.wav and then they're like oh okay sorry
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_0.wav  All right I have a special

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_1.wav okay all right that is really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_2.wav  life as a teenager who just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_3.wav  Nick yes all right so I'm creating
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_4.wav  will be extremely bright

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_7.wav  Christmas ornament
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_8.wav with my stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_10.wav 5 year old kid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_11.wav  but she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_13.wav  and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_14.wav  afterwards it was like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_15.wav  like for about 1
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_17.wav  years so I actually had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_18.wav 20 years of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_19.wav have you had speech there being

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_20.wav  yes actually I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_22.wav nurse knock on the door

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_23.wav  your family
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_24.wav  Hi, thank you for having me.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_26.wav it's that Jean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_27.wav  just you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_28.wav  kid so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_30.wav  I'm relaxed home and almost

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_31.wav and that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_32.wav  i am the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_35.wav talking I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_36.wav  coming down I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_37.wav  attempt but if I can't say it then I just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_1.wav they were extremely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_2.wav  in 10 years or 20 years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_4.wav  program for Reckoning Stutters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_5.wav me is strength
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_6.wav  will talk again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_7.wav  thank you so much Pedro for having me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_10.wav welcome mr. Seaball

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_11.wav  Hi Federal thank you for having me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_12.wav and I unconsciously

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_14.wav when speaking and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_15.wav and many many limiting beliefs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_16.wav  I'm in my mind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_17.wav  feeling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_18.wav and would spit and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_19.wav because you have to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_20.wav do all of the PowerPoint
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_21.wav  when I was that young as a toddler

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_22.wav pros and poetry
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_23.wav  I tried acting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_24.wav  you having great speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_25.wav just by Portrait

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_26.wav  and teachers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_28.wav  how would I describe it this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_29.wav  without stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_30.wav and how are you think I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_31.wav  leads me to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_32.wav they can just quickly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_33.wav and talk to people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_34.wav but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_35.wav  the most
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_37.wav you expand your covers on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/21/MyStutteringLife_21_39.wav you wrote a book
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_0.wav  got nervous when he stopped me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_1.wav  yeah people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_2.wav  felt what he was feeling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_3.wav reverse the vision it is I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_4.wav  it is eyes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_5.wav I stutter and oh well you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_6.wav  it and never stutter bit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_7.wav  It was much worse, sir. Yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_9.wav look over there what I get up and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_10.wav  over 20 years 20 okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_11.wav  okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_12.wav but in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_13.wav  that's fine I appreciate it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_14.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_15.wav my last two years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_18.wav  if you messed up she
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_21.wav I learned to talk so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_22.wav  did help make mine better
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_23.wav  I wonder if that didn't have something making it better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_24.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_25.wav  like you said drama

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_29.wav dr. Seuss to kids and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_34.wav  the three and four hundred people for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_35.wav  from 88 to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_36.wav  stuttered so but you know I just like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_37.wav the fear was God just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_38.wav  do it the better off you are I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/22/MyStutteringLife_22_39.wav  it was nerves but then I found that it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_0.wav she used the only resource

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_1.wav I can feel your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_2.wav  bright light I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_4.wav  and so I completely no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_5.wav how you feel cuz all my heart was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_6.wav in there and it just hurt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_8.wav stranger I feel

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_13.wav  job discrimination because of your stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_14.wav  stutter no I never really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_15.wav  our day you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_16.wav 98% would have on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_17.wav  us not stop ringing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_18.wav  I mean because had I done that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_22.wav  I think I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_23.wav welcome shirika Myers thank

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_24.wav thank you for having me do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_25.wav  was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_28.wav and just tell myself okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_30.wav  so here we go tomorrow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_31.wav  Yep
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_32.wav  yes now have you ever done this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_35.wav  and that's the only type that you.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_37.wav  a hypnotherapist

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_38.wav and so taught me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_39.wav  I take a deep breath in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_40.wav  in and in on the X
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_41.wav and so that way it would be my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_42.wav  my normal voice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_43.wav  I'm like wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_44.wav the power of the mine
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_45.wav  cry oh my I just called

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_49.wav  and I don't want to inflict that pain on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_51.wav to me has ever happened to you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_54.wav during my school days I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_55.wav  less than

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_57.wav  touched on a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_59.wav  I'm here on Earth because when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_60.wav when I was a teenager
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_62.wav I grab my dad's gun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_65.wav out of the house
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_66.wav down the street

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_67.wav and there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_68.wav there was an overpass

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_70.wav  Under the Overpass and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_72.wav it will be done

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_74.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_75.wav let me tell you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_76.wav  oof
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_77.wav when I think back

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_78.wav  it used to almost take me like about three to five
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_79.wav  about three to five minutes to see a sentence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_80.wav because there was a homeless man there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_81.wav  there and never

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_83.wav  hadn't ever seen a homeless man there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_84.wav  until that one night

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_87.wav I get it I am staying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_88.wav  did I have a purpose in life that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_89.wav  that we all have a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_90.wav that I have that was meant to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_91.wav  it to put out there because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_92.wav I put the gun back

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_93.wav woke up my dad and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_95.wav  from that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_97.wav  from who started oh wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_99.wav  knew that you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_100.wav  in your path for a reason
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_102.wav  he was put there for a reason

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_103.wav I mean I would not be here
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_104.wav  I would not be here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_109.wav  when my grandson stood in front of me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_110.wav  in front of me and he told me couldn't it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_111.wav  it was like a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_117.wav you are about that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_121.wav  I would never find
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_122.wav  here I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_123.wav the heart wants what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_124.wav other people who started so my gosh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_125.wav  gosh I skip
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_127.wav because once you get out the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_130.wav overcome and how did you do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_134.wav a deep question so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_135.wav so what has
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_136.wav as stuttering taught you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_144.wav  right yeah so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_148.wav  is making fun of you laughing just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_151.wav  self God made us all great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_154.wav  much a man that's awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_157.wav  someone because they started you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_158.wav you know I mean because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_161.wav  just because we can say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_165.wav when you've been beaten down as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_166.wav  hurt people yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_168.wav  back because we are creative

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_169.wav  we are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/23/MyStutteringLife_23_172.wav  because I'd love to quote Oprah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_1.wav the majority of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_2.wav if they call you on a money

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_3.wav  any of the books so listen
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_4.wav  so listen close

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_5.wav  building the Hyrie manager almost
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_6.wav  ask what are your thoughts on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_7.wav or if the admin person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_8.wav  is breathing is extremely important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_9.wav  in hell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_10.wav down I was the first one to speak

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_11.wav and I could see there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_12.wav  story after another

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_13.wav the other but as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_14.wav that I gave them I took it back

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_15.wav job interviews practicing my teeth
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_16.wav  and that has yielded

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_17.wav so in the job interview
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_19.wav so needless to say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_20.wav  job interview is I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_21.wav as with anything you learn

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_23.wav  come across like a kiss for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_25.wav  I said you on this interview I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_26.wav I Excuse myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_27.wav  so as I'm 10 minutes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_28.wav so it's a learning process so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_29.wav I feel a kink on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_30.wav  on the right side
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_31.wav  are after I'm discharged

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_32.wav  we all benefit it's a win-win so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_33.wav  me at my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_35.wav  anyone there just from Pedro these are not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_36.wav  these are not in any books

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_37.wav  I was in Human Resources
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/24/MyStutteringLife_24_38.wav  90s we would

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_1.wav no it does not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_2.wav  can I didn't say nothing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_3.wav  well of course I went
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_5.wav no buggies and horses

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_6.wav  was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_7.wav  the mother was nice and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_8.wav  cuz it took you so long to ask
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_9.wav  so that made me feel about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_10.wav  so ask this girl
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_11.wav  this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_12.wav  think about him saying that and I thought
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_13.wav  and most of the time they always thought

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_14.wav  and the for him to say that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_15.wav didn't have a no a great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_16.wav  and growing up you know there's always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_19.wav  he would say something like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_21.wav they will look at their watch
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_22.wav  as you are trying to ask

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_23.wav  there who care regardless
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_24.wav  regardless if you stutter or not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_25.wav  that if you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_28.wav you hear all these people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_29.wav  I've heard so many times
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_32.wav  have it okay what do you think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_34.wav  say I said well you know what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_35.wav  it and not worry about put people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_36.wav  demonstrates
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_37.wav  will come along and they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_38.wav we had caller ID and you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/25/MyStutteringLife_25_39.wav  and you would call and say like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_0.wav  This is episode
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_1.wav that they later got from the bank teller

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_2.wav I wasn't even thinking about the guilt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_3.wav  really thought about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_4.wav so I used to apologize
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_6.wav correlating to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_7.wav it made me less than
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_8.wav and that's when shame took over

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_9.wav cuz if you are a person his daughters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_10.wav an issue if you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_11.wav because at the end of the day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_13.wav I couldn't say my name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_15.wav a dark pack
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_16.wav and item that is not broken

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_17.wav  Stuttered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_18.wav turned the big for oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_19.wav let me tell you when I turned
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_20.wav I graduated high school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_21.wav I went to college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_22.wav can be in a relationship

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_23.wav I know you've had bad things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_24.wav because in our daily

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_25.wav I know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_26.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_27.wav because if I see
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_28.wav you can't be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_29.wav so here's what I'm going to do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_30.wav  you're not going to make it anyway

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_31.wav day is when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_32.wav for decades

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_33.wav and I realized
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_34.wav  game on bring it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_35.wav will I feel shame
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_36.wav  dog I'm going to do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_37.wav  checks
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_38.wav I'm walking into a bank

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/26/MyStutteringLife_26_39.wav it didn't realize
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_1.wav  wanted to be somebody else

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_2.wav because I wanted to expi
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_3.wav to have a day where

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_4.wav  I would love to have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_5.wav  and pizza and and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_6.wav  order so I would always ask my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_7.wav ask my buddy to order

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_9.wav one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_10.wav that I could have used

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_11.wav a good idea to compare
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_13.wav and embrace

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_14.wav my stutter I had to come to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_15.wav  wanted to be that person or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_16.wav I'm angry depressed and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_17.wav  yourself to other people cuz

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_18.wav rest and so when I turn
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_20.wav  done I don't care what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_21.wav tooty if they don't like me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_22.wav came to grips with ice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_23.wav  and I learned to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_24.wav I have a lot of good things going on for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_25.wav  all those emotions and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_26.wav  people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_27.wav because I wasn't who I wanted to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_28.wav control my life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_29.wav  40 Europe hero he don't care
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_30.wav like what Oprah says living your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_32.wav  my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_33.wav  inspiration

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_34.wav what they had that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_35.wav  that was good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_36.wav  look back my life no more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/27/MyStutteringLife_27_37.wav you were hearing you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_0.wav  perfect on the paper quarter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_1.wav  order so here I go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_2.wav  pit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_4.wav  and asked me to repeat it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_5.wav  she's so I pulled in the tape recorder
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_6.wav when I did that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_7.wav second time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_8.wav the person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_10.wav still said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_11.wav please drive up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_12.wav  point I dropped the tape recorder
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_13.wav that was an epic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_14.wav but it did not keep me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_16.wav from doing it again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_17.wav  and again because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_18.wav  what so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_19.wav  I can't leave a voice mail
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_21.wav I'll have a number for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_22.wav and I could not believe it came out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_23.wav  see me dancing in my car I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_24.wav  car I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_25.wav  drove up I got my meal I chomped

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_26.wav huge win
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_27.wav did you know that I bought

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_28.wav for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_31.wav  you didn't even stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_32.wav well it took me an hour and a half but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_33.wav  that was a win that was a huge win

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_35.wav do it and I will do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_36.wav  through the regular way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_37.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_38.wav drop a comment about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/28/MyStutteringLife_28_39.wav  celebrate every win
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_0.wav  what is up guys this is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_1.wav  that is my goal I want
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_2.wav that's not the case I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_3.wav I have my really bad days
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_4.wav  Hey, Pedro is exhausted

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_5.wav  it all day long I've been hissing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_8.wav physically my body

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_9.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_10.wav my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_11.wav  are just tents all day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_12.wav  person had asked me at the end

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_13.wav  at the end of the day what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_14.wav what do I do well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_15.wav  day and when I get home
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_16.wav well I stopped talking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_17.wav  just I relax
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_19.wav just relaxes and there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_20.wav and there are times when I'll be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_21.wav  brother cuz I'm hooked on big brother

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_22.wav fighting to be fluent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_23.wav and so at the end of the day you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_24.wav the moment you wake up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_25.wav the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_26.wav  exhausted so you just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_27.wav  just don't want to talk and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_28.wav that's my life that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_29.wav  so if you are like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_30.wav about your end of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_31.wav  as a person who stutters cuz I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_32.wav  others cuz I want to know cuz you are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_33.wav and help one another

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_34.wav  other so I want to thank you for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_37.wav on battle on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_38.wav fluent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/29/MyStutteringLife_29_39.wav  until the moment you lay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_0.wav so we are talking about having
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_1.wav the role of that love and support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_2.wav  I was ready for the next day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_3.wav  day I was ready for it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_5.wav that is there at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_6.wav  at the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_10.wav  system is to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_11.wav decrease your stress

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_12.wav and be there for you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_13.wav  system that will guide you and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_14.wav  you and teach you coach you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_15.wav ups you have your downs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_16.wav because in this life it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_17.wav  it's rough but if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_18.wav but if we have a good support
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_19.wav good support system

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_20.wav  we're going to be all right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_21.wav I'm all right because of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_22.wav all of the positive people in my life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_23.wav they are helping me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_24.wav so I hope you have a good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_25.wav  system as well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_26.wav because it batters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_27.wav  it batters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_30.wav  during the bad days and good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_31.wav  Good days and good days a good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_35.wav  that we need
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_36.wav there are some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_37.wav some awesome benefits of having
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_38.wav  help you better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_39.wav hope with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_42.wav life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_43.wav  because you know I'm everybody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_44.wav different you may

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_45.wav you may have some people who need a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_47.wav  had a awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_48.wav  small group of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_49.wav some all great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_50.wav but you have to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_51.wav  choose your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_52.wav support
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_53.wav  Wisely you only

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_54.wav  want positive people you don't want
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_55.wav magnet people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_56.wav because they will just drain
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_57.wav  they're constantly blaming me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_60.wav their mistakes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_61.wav  for their lack of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_62.wav  success
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_63.wav and those people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_66.wav good times and bad
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_67.wav there were I would say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_68.wav they're done they will move on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_69.wav and then the next time you talk to them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_70.wav  it will be the exact
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_71.wav same thing so would I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_73.wav  negative people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_75.wav  I worked with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_76.wav they're gone I don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_77.wav I don't need their

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_79.wav I only want a need
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_81.wav a caring person on the other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_82.wav listening to me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_83.wav  helping me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_84.wav  really lean on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_85.wav and they would be there to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_86.wav  advice to help me move on and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_88.wav support system

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_89.wav  you have people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_90.wav  you can easily contact

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_92.wav get their help
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_93.wav their guidance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_94.wav their support
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_95.wav  their support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_96.wav and that will help you in dealing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_97.wav  going through in your life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_99.wav anybody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_100.wav can be in your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_101.wav listen and help me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_102.wav  system group you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_103.wav you could have family
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_104.wav you could have close

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_105.wav  much he was a cockapoo
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_106.wav have Cocker Spaniel

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_107.wav poodle the day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_108.wav  that I was discharged

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_109.wav from the US Air Force
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_110.wav  Force I was in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_111.wav  I was in Phoenix
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_112.wav in Phoenix Arizona Luke Air

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_113.wav airforce base and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_115.wav  me and guide me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_117.wav for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_118.wav and so I wanted to get a dog

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_119.wav  because I was driving home
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_120.wav so I went to the dog pound

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_121.wav  and so I walked
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_122.wav around just hearing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_123.wav the dogs barking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_124.wav  barking and just looking at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_126.wav poo puppy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_127.wav he had been abused

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_128.wav from the cuts
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_129.wav  turns on his

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_130.wav legs and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_131.wav  and as I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_134.wav squatted down he looked
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_135.wav and I looked at him

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_136.wav and he came straight at me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_137.wav have the helper

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_142.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_143.wav from that moment on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_144.wav  go
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_145.wav this is my dog this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_146.wav is my dog and let
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_147.wav  dog and let me tell you driving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_148.wav he hugged me the entire way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_150.wav  so much love from that dog

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_151.wav and he was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_152.wav  system for being

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_153.wav because whenever I had a bad
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_154.wav  I would come home and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_155.wav and he would just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_156.wav he heard my vehicle

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_157.wav and so as I drove up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_158.wav  or he would just jump on me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_159.wav and after a hard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_160.wav stuttering in a meeting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_161.wav starting trying to order lunch
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_162.wav  because you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_163.wav and he jumped on me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_164.wav everything went away

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_165.wav everything went away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_166.wav and I had him for 16 years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_167.wav dog I've ever had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_168.wav and he was an awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_169.wav  system for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_170.wav because I would talk to him

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_171.wav about my day and he would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_172.wav  he would just look at me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_174.wav that I was telling him
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_176.wav and let me tell you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/30/MyStutteringLife_30_178.wav  rough you have your ups
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_0.wav this is Episode 15

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_2.wav as Oprah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_3.wav now to just put this out there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_4.wav there was no hesitation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_5.wav  to give this presentation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_6.wav and some of the people who knew me in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_7.wav best feeling in the world

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_8.wav thank you Mel Robbins thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_9.wav  and I thank you for the bottom of my heart

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_10.wav now in the book
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_11.wav  and I'll try again some other time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_12.wav  out of rejection
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_13.wav and every time I have used

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_14.wav now whenever I have to do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_15.wav and I know who I'm going to have a heart

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_16.wav when I count down
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_17.wav I do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_18.wav  maybe the next day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_19.wav  it's not going to happen

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_20.wav  according to Mel robin
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_22.wav that's my mind being blown

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_23.wav  or mind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_24.wav one end of the stage to the other end

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_25.wav  I think it's a bit believable how just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_26.wav that I know it's going to be a little difficult

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_27.wav  around hashtag just go home
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_28.wav 50

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_29.wav 50 people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_30.wav  cuz it's your boss

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_31.wav  Maybe I had some sweet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_32.wav bags under the eyes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_33.wav  so as it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_34.wav  and turn it into excitement

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_35.wav no let that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_36.wav  let that sink in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_37.wav  as a stutterer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_38.wav that are high on my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/31/MyStutteringLife_31_39.wav  excitement so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_0.wav this is Episode 14

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_1.wav if you are asked a question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_2.wav that before

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_3.wav  say it in your head three times
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_4.wav  and then you respond no I had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_5.wav but you know what I will try anything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_6.wav  thing because you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_7.wav because you know my goal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_8.wav  goal is to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_9.wav  have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_10.wav pulient

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_12.wav  respect and integrity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_13.wav  so if you want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_14.wav  so if you want to check out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_15.wav  you what are your thoughts

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_16.wav  your thoughts on this issue
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_17.wav  research on stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_18.wav and the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_20.wav obtaining the money to buy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_21.wav  whatever and so that way I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_22.wav  I could live my life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_23.wav  stutter I still live my life I love
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_24.wav I love me I have a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_25.wav  me I have a stutter and life goes on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_26.wav  cuz I cannot say my name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_27.wav  name so drop me a comment
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_28.wav  to get started

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_29.wav and the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_30.wav three

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_31.wav big areas
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_32.wav that have helped people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_33.wav  who's daughter have been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_34.wav  speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_35.wav  using electric current
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_36.wav  electronic devices

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_37.wav  and or drugs
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_38.wav  and I just say no thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_39.wav  I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_40.wav it didn't work for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_42.wav episode 1 for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_43.wav and we are talking about stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_44.wav awesome speech therapist who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_45.wav who have helped me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_46.wav  20 years and so that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_47.wav  speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_48.wav  be prior to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_49.wav  you could not understand

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_50.wav just one letter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_51.wav and I would be sweating

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_52.wav  times I would be crying cuz
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_53.wav  cuz I'm trying to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_54.wav  something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_56.wav my mind my body

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_59.wav and the magic pill
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_60.wav  now I have been receiving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_62.wav and I have also used
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_63.wav  breathing that's breathing from your belly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_64.wav because for years I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_68.wav  my test and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_69.wav and they call that shallow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_70.wav but when I learned

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_71.wav  to to breathe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_72.wav  through my belly my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_73.wav everything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_74.wav  change for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_75.wav  regarding how my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_76.wav  how my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_77.wav the better
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_78.wav now there are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_79.wav some children who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_80.wav  who outgrow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_81.wav  by the age of five
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_83.wav  I still have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_84.wav my stutter but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_85.wav my setter is called a near

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_86.wav caused by a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_87.wav traumatic event

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_88.wav obtained my stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_89.wav  Now I have been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_91.wav  cured well let me tell you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_93.wav and calls

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_95.wav  What is my reaction to Steve
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_96.wav  Steve Harvey's YouTube video

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_97.wav and so I didn't want to go into it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_98.wav because I want my podcast

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_99.wav to be inspirational
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_100.wav  type of controversy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_102.wav unfortunate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_103.wav he stated

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_104.wav that stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_105.wav  is...cureable

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_106.wav and it is not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_107.wav  there is no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_108.wav  pure first-editing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_109.wav it just isn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_110.wav there are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_111.wav  how to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_112.wav improve your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_113.wav polluency but there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_115.wav and you know I just had to speak
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_116.wav  speak up because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_117.wav to other people who stutter cuz
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_118.wav  better cuz he claims on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_119.wav  of this podcast but keep
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_120.wav but he claims that in one hour

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_121.wav  stop your stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_122.wav  stop your stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_125.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_126.wav  most

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_127.wav most therapist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_128.wav stuttered in their life so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_129.wav so how do they know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_130.wav what a child

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_131.wav the stress the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_132.wav  the Manger and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_133.wav my speech therapist they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_134.wav they have been so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_135.wav I'm instrumental in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_136.wav  improve my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_137.wav  I'm fluency
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_138.wav that is the cold hard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_139.wav  hard fact is that there is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_141.wav many of them stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_142.wav and so they understood that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_143.wav what I was going through now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_144.wav I could see both
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_145.wav and I'm lcdc now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_146.wav  now you would want
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_148.wav addiction to help you with your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_149.wav  with yours because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_150.wav  because I can't remember what I was doing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_152.wav  if you have an else IDC counselor that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_154.wav there is no magic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_155.wav drug and alcohol history
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_156.wav  they help you with yours so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_158.wav Amazing speech therapist out there and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_161.wav wonderful therapies to help

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_162.wav  you help kids who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_163.wav  stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_164.wav stutter there was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_166.wav talking about I believe there were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_167.wav  out of the tube the first one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_169.wav  which I do that anyway

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/32/MyStutteringLife_32_171.wav  magic pill they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_1.wav  different but for me this is what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_3.wav  have to practice for a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_5.wav  my bathroom mirror and let me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_6.wav mirror and let me tell you I did not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_7.wav  know that I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_9.wav  and it was an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_10.wav  have a block so as I would practice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_11.wav  mirror every day on average
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_12.wav my fluency now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_13.wav again here's some harsh reality
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_14.wav  skills to help improve our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_15.wav  are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_16.wav do yourself in the mirror now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_17.wav now I've been stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_18.wav pollution

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_19.wav puluancy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_20.wav one to the mirror I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_21.wav the mirror I am cognizant of my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_22.wav help us team

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_23.wav all right now I do have my good days
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_26.wav if you do this if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_27.wav  do this if you practice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_28.wav  in the mirror I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_29.wav  there are two ways you can do this number
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_30.wav number one there is a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_31.wav show notes where you can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_32.wav  send me a voice message and also

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_33.wav talking in front of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_34.wav and that is why we are here I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_35.wav  still learning and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_36.wav so as always you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_37.wav  from you because you are not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/33/MyStutteringLife_33_39.wav they go on the edge of the mirror and they have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_0.wav  body movements that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_2.wav who are associated with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_5.wav made by the stuttering Foundation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_6.wav worldwide stutter which is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_7.wav which is approximately
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_8.wav are all involved with stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_9.wav  anybody who tells you that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_10.wav  or I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_11.wav stutteringhelp.org and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_12.wav or I'm a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_14.wav anxious or I'm all stressed out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_15.wav  stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_16.wav  stutter so this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_17.wav tired lifetime that I was pulled over

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_18.wav and it was both
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_19.wav but this card it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_20.wav  beat up granted I didn't know I was going 80
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_23.wav but like I say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_24.wav  every single day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_25.wav I have to educate people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_27.wav  they will become empathetic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_28.wav the more they will be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_29.wav better so I will have the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_30.wav  this but I have a YouTube channel so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_31.wav  channel so I know there are a lot of people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_32.wav  I have a YouTube channel called my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_33.wav I hope you have value from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_34.wav we're all in this together we are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_35.wav there we are so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_37.wav and in red and bold

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_38.wav  what is stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/34/MyStutteringLife_34_39.wav like this prolongations

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_5.wav supplies
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_6.wav  I would always have to talk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_7.wav to get to where I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_9.wav  that ring is taught me to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_11.wav  person who stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_12.wav  it would be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_14.wav it's like my dream
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_15.wav  want to play at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_16.wav  and like those
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_17.wav things have come true

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_19.wav  probably said it is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_21.wav  the teachers like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_23.wav  for people's like 10 million right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_24.wav  any date to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_27.wav when you talk to someone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_29.wav  triumphs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_31.wav  guess what you get back up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_32.wav  never stop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_33.wav  and be well thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_38.wav  to do it but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_40.wav  the time like I just got used to it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_41.wav  that was the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_42.wav  to the restroom and wait until
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_43.wav  until my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_45.wav  I totally understand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_46.wav  as well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_47.wav  he goes after the first time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_48.wav  stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_49.wav  yeah so I can appreciate your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_50.wav  your fluency although

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_51.wav as you know there are a lot of people out there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_52.wav  it's you know that's crazy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_53.wav  now let me tell you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_54.wav broke it I'm into a glass of water

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_55.wav water and if the yolk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_57.wav this is episode number 46

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_58.wav  then I was cured but if the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_59.wav  not successful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_60.wav  oh wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_61.wav  so the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_64.wav impediment just to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_65.wav  it just so the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_66.wav  aware of it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_67.wav ask the students

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_68.wav  Society depression there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_69.wav they're afraid to be judged

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_70.wav  advice for parents and teachers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_71.wav a job wise did you ever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_73.wav  16 right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_76.wav the priori oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_79.wav  because I come
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_80.wav  in position

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_83.wav discriminated it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_86.wav  the one like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_87.wav  in the local newspaper
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_88.wav there were some awesome jobs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_92.wav because God knows that was not going to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_94.wav  by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_95.wav and like yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_96.wav  for spending time with me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_97.wav to share your story
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_100.wav  I still go through it but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_101.wav  it but I'm not as bad as I would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_102.wav  depressed to a point

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_103.wav because everything in which
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_105.wav I was blown away for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_107.wav  react
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_110.wav ready for and pike

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_112.wav  really helped
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_113.wav to get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_114.wav predence and like to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_115.wav cover so let's get started sweet

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_116.wav  started sweet let's do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_118.wav  damn touching

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_119.wav  home it back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_120.wav and you know like I have to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_121.wav  a ton of credit because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_122.wav my life in a way I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_126.wav  wow that's powerful
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_129.wav  we have like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_136.wav  come talk to her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_137.wav  it's like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_138.wav  we had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_139.wav she told me like I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_140.wav  I told her I can't afford to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_142.wav jump it was hard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_143.wav and I had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_145.wav  do this today I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_147.wav  I miss Clara
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_150.wav  thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_151.wav  it's like you like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_152.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_154.wav wow there are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_156.wav  this is what I believe there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_157.wav that are put in your path
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_158.wav  to help you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_159.wav  when I was a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_160.wav  didn't have any friends

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_161.wav and during high school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_162.wav and there was an overpass

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_163.wav and so you know I already
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_164.wav and so I walked under

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_165.wav this person was put
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_166.wav  put their

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_167.wav  the light and then I just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_168.wav kept on going fighting every

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_169.wav the mother of family members who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_173.wav  I'd be tempted to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_174.wav able to drink alcohol
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_175.wav  drink as much as I used to it's like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_177.wav  come true
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_179.wav your tone is nice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_181.wav  to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_184.wav  because that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_186.wav I'm Pedro and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_187.wav  are not worth my time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_188.wav oh yes I totally agree with that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_189.wav  so here is a head scratcher

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_190.wav  that you're okay so when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_191.wav  would it's like I'm the only person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_192.wav  my grandma apparently
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_193.wav  do you speak without stuttering the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_196.wav that is interesting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_197.wav all I can look at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_199.wav  what it wants
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_200.wav the heart doesn't care if you're stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_202.wav  so what if
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_203.wav there was a dating app for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_204.wav  territory it's a whole new frontier
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_205.wav  year

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_206.wav  for normal well yeah like I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_212.wav  the only person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/35/MyStutteringLife_35_213.wav  him how was school life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_2.wav they will tell me that they are going to call

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_3.wav so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_5.wav  so let's get started

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_6.wav  or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_8.wav and I've been walking like for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_10.wav  This is episode number 39
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_11.wav  at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_13.wav  around the store looking paranoid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_14.wav and I'm going to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_16.wav to say what I need to say and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_17.wav where I claim that I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_18.wav that I have lost my voice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_19.wav  product on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_20.wav  less than
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_21.wav can with the letter H

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_22.wav but I got it done
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_24.wav so I would approach the counter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_26.wav  phone and you know who you are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_27.wav in my case

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_28.wav now that 1%
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_30.wav  Again and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_31.wav a quote that I found
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_32.wav  I don't know where I heard it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_33.wav and you won't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_34.wav wherever that I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_35.wav and I can only speak for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_36.wav thing that's just Pedro my friend

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_38.wav  use your voice recorder on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/36/MyStutteringLife_36_39.wav  tell that just to give me time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_0.wav so vampires
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_1.wav I've had a lot of vampire

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_2.wav and the words that all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_4.wav  instant negativity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_5.wav and I was around those people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_6.wav  about vampire crams okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_8.wav and here's a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_9.wav the vampires all around me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_10.wav they were everywhere
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_11.wav  here we go again emotional

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_12.wav because from my stuttering worrying about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_13.wav draining my energy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_15.wav no more drained energy I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_16.wav and it was awesome because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_17.wav because 40 years old
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_18.wav I felt

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_19.wav I'm sure you have those people either
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_20.wav who are just constantly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_21.wav and these people don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_22.wav you to do great they want to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_23.wav  a bucket as you're improving in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_24.wav  bucket they want a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_25.wav  and again this is not a medical problem
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_26.wav those are vampires

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_27.wav  it and it has been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_28.wav and if you got crabs in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_29.wav the difference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_30.wav and have you ever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_31.wav but I have an awesome podcast
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_32.wav  and crabs in a bucket

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_33.wav  I did it and I feel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_34.wav in a bucket no more vampire

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_35.wav have you ever noticed the people around
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_36.wav  and let me know the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_37.wav did you get rid of those vampires and those
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/37/MyStutteringLife_37_38.wav in a bucket and we will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_2.wav and once I hit that stage it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_3.wav  in my heart because they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_4.wav because they took me in and they were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_5.wav  on the job because of your stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_6.wav and I had this one customer and I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_7.wav  Hello there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_9.wav  I mean that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_12.wav and so people were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_13.wav my name is Pedro Pena and when I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_14.wav  to get out of that robot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_16.wav  in my hypnotherapist that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_17.wav  so I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_18.wav  will come true
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_19.wav  bad speech day you know then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_22.wav  to cover so let's get started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_23.wav and they ask you for your name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_24.wav hard enough as it is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_25.wav the most difficult part

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_28.wav  you first began to stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_29.wav this is like super duper hot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_30.wav  with a stutter so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_32.wav that was it and so next

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_35.wav  wow that's so powerful
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_36.wav  things so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_37.wav so I'm very thankful for that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/38/MyStutteringLife_38_38.wav  powerful awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_1.wav  all of us kind of come together and just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_2.wav  shine like a light on that so people can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_3.wav  or find a friend that doesn't mind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_8.wav and a discussion is over

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_9.wav  even like Stutter less
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_10.wav  like you like looking back like growing up there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_11.wav  I did not answer the phone at all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_12.wav because that was easier than saying what I wanted

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_14.wav  right I mean I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_16.wav  worse so there was kind of like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_17.wav  like a balance and it wasn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_18.wav  and whatnot so I was able to start a left

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_20.wav  of any conscious
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_21.wav  principal after you get through something like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_22.wav  you know I'm after that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_23.wav  like every other year it was one or the other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_24.wav  see and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_25.wav  yeah it's just rough

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_27.wav like my nephew and I'll stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_28.wav  like in person stuff is kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_29.wav but at the same time that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_30.wav  see let's talk about the F4

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_32.wav like ordering and stuff when I was a kid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_34.wav  like payment

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_36.wav  speak to people and not have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_37.wav  Mr Jones or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/39/MyStutteringLife_39_39.wav  it's like heavy breathing
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_0.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_1.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_3.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_4.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_5.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_6.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_9.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_10.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_12.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_14.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_16.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_19.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_22.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_27.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_28.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_31.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_32.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_34.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_35.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_36.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_37.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_38.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/0/StrongVoices_0_39.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_0.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_1.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_2.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_3.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_5.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_6.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_8.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_9.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_10.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_12.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_14.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_16.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_19.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_22.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_28.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_29.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_31.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_32.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_34.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_35.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_36.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_37.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/1/StrongVoices_1_39.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_2.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_5.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_6.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_9.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_10.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_12.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_14.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_16.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_19.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_27.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_28.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_29.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_32.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_34.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_35.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_36.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/2/StrongVoices_2_37.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_0.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_3.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_4.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_8.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_9.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_12.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_14.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_16.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_19.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_22.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_28.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_29.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_32.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_34.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_35.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_36.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_37.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_38.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/3/StrongVoices_3_39.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_0.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_1.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_2.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_3.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_4.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_5.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_6.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_8.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_12.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_14.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_16.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_19.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_22.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_27.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_28.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_31.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_32.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_35.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_37.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_38.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/4/StrongVoices_4_39.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/5/StrongVoices_5_1.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/5/StrongVoices_5_2.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/5/StrongVoices_5_4.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StrongVoices/5/StrongVoices_5_5.wav does not exist.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_3.wav  the open mic at the end
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_5.wav  only their own change

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_6.wav  and I think there's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_7.wav pushed or quick people whose daughter and I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_8.wav  like best I get the sort of insight right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_10.wav  community where you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_12.wav it's okay to share and just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_13.wav it's just really okay to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_14.wav interacting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_15.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_16.wav bond with each other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_17.wav  for her private practice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_18.wav I think that this opportunity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_19.wav that she was having and it's a newer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_20.wav of a community
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_21.wav  order

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_22.wav  Warren
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_23.wav a different story

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_25.wav  person who daughters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_28.wav talking to another parent just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_31.wav  is a group activity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_33.wav  how to create that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_35.wav locally because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_36.wav somebody decided we had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_38.wav  of that yeah absolutely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/0/StutterTalk_0_39.wav  absolutely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_1.wav  a few stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_2.wav  more than what I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_3.wav I think that people can also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_4.wav  do you think you need to be with your stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_5.wav  I think that I be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_6.wav Pascal I've been fighting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_11.wav we have stutters it was just like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_12.wav  like well do you know if it happens

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_13.wav  a little bit more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_17.wav amazing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_21.wav  detain it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_22.wav  very universal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_23.wav emotion
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_24.wav  apart of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_25.wav  of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_28.wav  it was just you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_29.wav  important for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_31.wav  of these things are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_33.wav  that's just kind of it on Micah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_34.wav I come to surface

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_35.wav and even being
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_36.wav  how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_37.wav I don't think he ever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/1/StutterTalk_1_39.wav  going back even

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_0.wav  with my day-to-day with stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_1.wav  and accomplishing my goals

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_5.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_6.wav  you know and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_11.wav  of any other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_12.wav  of what I would do but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_13.wav in a way I'm getting ready for it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_14.wav one of the things that drove me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_15.wav college I had an internship at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_16.wav  because I know who that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_17.wav and there was a lot of attorneys in the room
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_20.wav  that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_21.wav  but just forcing myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_22.wav  I guess

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_24.wav  to I guess for me it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_25.wav not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_28.wav  that are mostly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_30.wav  authentic type of communication and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_31.wav somewhat easily without
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_32.wav  thing I think it's a realistic goal and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_33.wav and how much do you want to be able
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_34.wav  and so yeah I'm kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_35.wav  can't get sound to come out or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_37.wav  go too much further

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_38.wav getting involved in stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/2/StutterTalk_2_39.wav  I really hope that there's a way to make

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_1.wav people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_2.wav pipes associated

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_3.wav  translate economically
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_5.wav going on in the world right now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_7.wav absolutely amazing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_8.wav chapter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_9.wav  or when I attended the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_12.wav  book

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_14.wav eventually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_15.wav too seriously about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_17.wav  soda kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_18.wav  so it just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_21.wav letting your stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_22.wav  mechanics was better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_23.wav  just to play my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_24.wav  that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_25.wav  may
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_26.wav the acceptance thing I can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_27.wav put the seed was planted very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_29.wav  better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_30.wav  discouraging
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_32.wav  some people in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_34.wav put
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_35.wav about speaking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_36.wav  in New York
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_37.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_38.wav  same things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/3/StutterTalk_3_39.wav the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_0.wav  and searching for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_1.wav  brain depression and bipolar disorder

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_2.wav  condition of the brain
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_3.wav  who may stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_5.wav  other psychiatrists probably were thinking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_7.wav protections are put into place

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_8.wav but I'd rather have us not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_10.wav  make this a go to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_12.wav  a little bit likeopolis City since I took
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_13.wav  be able to show that this can be better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_15.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_16.wav  during a difficult time of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_17.wav  Not out there that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_18.wav  free diet and I know he's being helpful but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_19.wav  for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_20.wav  and then you know this is the deal was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_21.wav  researchers and for funding research I know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_22.wav  really focus on advocacy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_23.wav  also enhance the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_24.wav  was working

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_25.wav doctor means educator
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_26.wav  really and I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_29.wav both be any different than any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_30.wav  was all in stuttering there's another research group

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_31.wav as turrets that makes sense to the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_32.wav  want us to start thinking about that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_33.wav while stuttering isn't caused by the larynx
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_34.wav  and they've been able to fund

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_35.wav  the on July and defect is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_37.wav that we should really use as a model we are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/4/StutterTalk_4_38.wav  to improve so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_0.wav  that is a great honor to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_1.wav but you can sometimes know this is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_2.wav  opportunity there is for them to counter it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_3.wav  to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_4.wav and I'm older than you so I don't know about your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_5.wav I think it's a big

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_6.wav I've never played poker how do you play
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_7.wav  knowing just what a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_9.wav  $40 the same every time and it will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_10.wav  $10 because that's 10%

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_11.wav  or yes so I think we were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_12.wav the problem is if you just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_14.wav  for children over the age of 5
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_15.wav  after the child's been talking for sometime in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_16.wav  be different you want to add anything Katie
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_18.wav different and you know I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_20.wav  yes very much so another
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_21.wav  have maxed out the number

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_22.wav  it is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_23.wav  code that code pretty much always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_24.wav  I will say I mean advocacy I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_27.wav  of the Affordable Care Act this new

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_29.wav  network rate now it will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_30.wav some may have higher copays

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_31.wav  recovered for mental health therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_32.wav  to go see a psychiatrist for his R

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_33.wav  wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_35.wav using the creative diagnosis code

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_36.wav  versus angle shooting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_37.wav that would be where my first question

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/5/StutterTalk_5_39.wav what is interesting in the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_0.wav organizations and you're the legendary

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_1.wav stuttering and the DNA and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_2.wav and so I know that's not exactly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_3.wav the world has to sort of change
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_5.wav  to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_6.wav  to advocate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_7.wav  movements

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_8.wav and I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_9.wav  I think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_10.wav I think that human beings
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_11.wav  so miserable

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_12.wav and it's not just about the physical
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_13.wav and I just only see value in that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_14.wav I think that's all right and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_15.wav  to me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_17.wav  there in saying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_18.wav I want to change or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_20.wav Christopher Constantino who was another one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_22.wav  that's certainly true

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_23.wav  it so many times and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_24.wav that sort of what they say that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_25.wav that might not be how they actually feel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_27.wav  there's no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_29.wav  deconstructing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_30.wav the their life that goes on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_31.wav  talk to people online
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_32.wav there are definitely lessons that we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_33.wav for yourself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_34.wav it was inspiring I think that was like a really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_35.wav  commercials and films
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_36.wav  just to say we're out here and we exist

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_37.wav  that they wanted to work towards
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_40.wav like yeah it would be great to have someone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_43.wav  on a hit show
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_44.wav but I can't imagine what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_46.wav  specific goals like we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_50.wav  that others can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_51.wav say that in a very black and white
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_54.wav  I think that's a good question.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_58.wav  your home and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_59.wav and it had a very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_60.wav and that like it's not my job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_61.wav and I think his

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_62.wav  could get away with it so here's what very sad
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_64.wav  as a morpid nine psychiatric disorder

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_65.wav it was medicalized
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_66.wav  thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_67.wav  wow and I heard some screaming
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_68.wav  nuanced

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_70.wav  parallel between
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_71.wav his shame over being in the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_74.wav and the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_75.wav  the relative

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_76.wav uttering community
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_77.wav  and that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_79.wav  where his comparison was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_83.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_84.wav  like that it really can be done and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_87.wav  I want to talk about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_88.wav berry's keynote but let's jump into
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_89.wav  that we just heard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_90.wav that stuck out to me the most is how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_91.wav  way right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_92.wav  and I think that relates back to the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_93.wav  clip of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_94.wav  it not being
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_95.wav disorder that we have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_96.wav but feeling like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_97.wav  this is us and this is our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_98.wav  our rights and that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_99.wav it should be our place to change those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_100.wav  please
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_105.wav all of these great calls to action

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_106.wav chapchapchapters or groups
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_107.wav  on the ground like I need in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_108.wav as a communication disorder
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_110.wav  Brainstorm things

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_111.wav  so I know that there are going to be people that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_112.wav  political actions are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_113.wav  Fostering growing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_114.wav  Communion is the people who stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_115.wav  together
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_116.wav so Rochin to we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_117.wav  to look for cure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_118.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_120.wav  disability rights
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_121.wav  movement in our community

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_122.wav  your treatment is stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_124.wav  NSA aired

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_125.wav  in emotionally stirring
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_126.wav  world where risk-suttering doesn't exist

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_129.wav Sure yeah I mean I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_130.wav  that question

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_135.wav cheat someone that they can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_137.wav I don't know these two ideas

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_138.wav  the cure and we need a cure I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_139.wav  I think in some ways they can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_141.wav I'm just not sure if they should work together
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_142.wav  are in self-help

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_143.wav  and in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_144.wav  group is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_145.wav is to the harrow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_146.wav are in the really great times

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_147.wav but that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_148.wav  to fix or to cure

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_150.wav  word
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_151.wav  I think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_152.wav me a little bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_153.wav to try to link those things

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_154.wav  been thinking about it a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_155.wav and I feel like there's so much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_156.wav  so much work that we have to do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_157.wav  to remove the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_158.wav  you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_162.wav  you know I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_163.wav know that yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_164.wav  cuz I know what a lot of local

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_166.wav  know that a lot of local chapters are not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_167.wav incredibly active and I know that a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_168.wav  local chapters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_169.wav I just think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_175.wav I think it also feels like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_176.wav  feel a little bit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_177.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_179.wav  is just the fighting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_180.wav what I should do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_182.wav  wow it is really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_183.wav  it's more just having
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_184.wav  it doesn't have to be a large community

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_185.wav  organization
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_189.wav  the thoughts that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_190.wav deep in thought so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_193.wav  I mean yeah I'm thinking a lot about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_194.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_195.wav  yeah because I think it's all important things for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_197.wav  me and that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_200.wav  you know guys if you don't mind can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_201.wav  to be fixed by professional intervention
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_203.wav  you trying to get in do you have any comments

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_204.wav  No I would just say that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_205.wav  turn around

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_208.wav  until I heard you say that like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_209.wav like I can relate to those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_210.wav  believe that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_212.wav  speech therapist who were eyes to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_213.wav  to the occasion
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_214.wav and to vote their careers to stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_215.wav  that we have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_216.wav  perhaps in education

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_217.wav  about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_218.wav the stutterers experience of stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_219.wav  take that question to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_220.wav first I have to share

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_221.wav  the hat or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_222.wav talking about now yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_223.wav  will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_224.wav become clearer over time like when we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_225.wav  logical
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_227.wav  quickly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_228.wav and I want shutterers to have a voice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/6/StutterTalk_6_229.wav  from that pain

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_0.wav  just to kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_2.wav  what you say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_6.wav  know how much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_7.wav  real positive thoughts to the world

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_9.wav  to hit the nail in the head what do you think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_11.wav in an area where they're really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_12.wav would that be sufficient then to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_13.wav wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_14.wav  long and so it's really hard to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_15.wav I've heard from so many people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_17.wav  to identify
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_18.wav research stuttering and look at stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_19.wav  manage your fame when you're famous
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_20.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_21.wav  let's help
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_24.wav  of this thing that we call stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_25.wav or something we believe in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_27.wav  is is that should be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_28.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_29.wav  I don't think so but I also

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_33.wav  in a way and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_35.wav  top five or six things I'm talking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_37.wav umbrella not that they do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_38.wav at the beginning of the show

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/7/StutterTalk_7_39.wav  about disability theory
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_3.wav  an advocate for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_6.wav people to experiment with doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_7.wav  was doing that was telling a different story

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_8.wav  interested in playing because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_13.wav  that other people then start to tell about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_15.wav courage that kind of experimentation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_18.wav  to share with the listeners I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_19.wav I would say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_21.wav  story that you've been able

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_22.wav  able to share with our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_25.wav  changing our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_28.wav  techniques or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_29.wav  or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_30.wav  any of that aspect and really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_31.wav and adaptive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_33.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_35.wav  of telling stories I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_36.wav  ask you if
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_38.wav is a conference in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_39.wav  and the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_42.wav would even prefer not to call it counseling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_43.wav  I think the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_44.wav  we do focus on stories but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_49.wav some of the things that we covered this morning I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_50.wav  The depth of leadership is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_52.wav position of Authority or expertise
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_53.wav and the treatments for those or the solution for that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_55.wav conducted by a person with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_56.wav adaptive challenges

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_57.wav  I'm here today at the end of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_58.wav  the United States I'm here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_59.wav the questions to the problems are generally not known
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_60.wav  and the work to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_63.wav  and so there's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_64.wav in a position of Authority or expertise and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_66.wav technical and adaptive challenges
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_67.wav  use pullouts or continue

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_68.wav continuous foundation or something like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_69.wav  has that expert knowledge

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_70.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_76.wav  doctor Tony the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_78.wav opportunities for the kind of deep
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_80.wav reactions to trying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_81.wav I'm trying to change this that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_82.wav  so what you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_84.wav  what you referred to there in terms of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_86.wav  about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_87.wav and the idea of construct
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_89.wav gently active scientist

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_90.wav  an example so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_91.wav  we might develop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_93.wav they're a trustworthy person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_95.wav sciences and disorders he is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_96.wav he is the co-author of the textbook
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_98.wav we might see them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_99.wav we might see them out in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_101.wav and then that would be open to confirmation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_102.wav and so that's typically the way that we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_103.wav  a person or who are as a communicator and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_105.wav so in terms of changing and updating
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_106.wav  patients and so in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_107.wav invalidating experience tends to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_108.wav  constructs and we change them and update them but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_109.wav  them but as you get kind of high
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_112.wav  personal near your tips

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_114.wav  construct could really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_115.wav  imply significant

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_118.wav  given too much change
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_120.wav  keep it and instead of then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_122.wav construct of myself as an honest person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_124.wav so that it doesn't damage the whole system and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_125.wav  stuff and we do that in terms
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_126.wav so for people who started it might be that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_128.wav  of this doddering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_130.wav  so the title

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_132.wav  those are ways of explaining away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_133.wav experience that doesn't match

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_135.wav it's still be a deeper level
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_136.wav challenge core constructs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_141.wav kind of being told all the time about them so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_143.wav of unassortment

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_144.wav  stuttering kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_147.wav  embarrass yourself and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_148.wav  so any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_149.wav today was called

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_150.wav taking back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_155.wav in a therapeutic session what we're listening

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_156.wav  I was a person and what their life is like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_158.wav  right so for example

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_160.wav somebody told me that to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_161.wav move my chair cuz

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_162.wav  hair cuz I was in their way and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_163.wav being unassertive and just doing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_164.wav  I'm not going to do that and so that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_171.wav  okay well tell me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_172.wav  will tell me a little bit more about that it sounds like an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_175.wav  one of the first times I've heard about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_176.wav  change being
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_178.wav I'm the personal story

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_179.wav we look at change from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_181.wav today was how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_183.wav  of stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/8/StutterTalk_8_188.wav if I had to sum it all up in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_0.wav I came from a culture
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_2.wav even go to school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_3.wav men and people we have one point
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_4.wav that I stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_5.wav  I'm looking forward to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_6.wav struggle for me because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_7.wav even want to be in this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_9.wav go on to do college and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_10.wav metaphore did you feel like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_11.wav  before I always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_13.wav  see that's cultivated clearly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_14.wav so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_15.wav dutter I sought
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_16.wav  in front of people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_17.wav you are coming
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_18.wav because I was desperate yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_19.wav this beach was very hard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_21.wav and I started to talk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_22.wav all this shame all this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_23.wav it's not who they are does

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_24.wav  so gradually I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_25.wav teacher to in that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_26.wav even if you do not study
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_27.wav what was the hardest part of your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_28.wav  in two languages now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_29.wav maybe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_30.wav have a two-week program
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_31.wav attendees in that program

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_34.wav and talking about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_36.wav  has there been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_37.wav  who I am and I the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/9/StutterTalk_9_39.wav until you came here you have never

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_1.wav then there are a lot of words you could apply to her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_3.wav  you wouldn't have been able to convince me that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_5.wav two years old that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_6.wav are stuttering sort of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_7.wav actions in New York
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_8.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_10.wav  I don't know and I haven't recorded forever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_11.wav  hard the last

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_12.wav teaching a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_13.wav the class

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_14.wav but I'm not positive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_15.wav and I was there in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_16.wav  really like robust
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_17.wav quite the plan I would say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_18.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_22.wav  and it's really not black and white

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_23.wav it yeah I feel like I can't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_24.wav you are terrified to pick up the phone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_25.wav  Uncharted for me. Yeah, but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_27.wav  whole different thing but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_28.wav public relations and she
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_29.wav which is weird

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_30.wav and that she was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_32.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_36.wav  to me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_37.wav teacher who assumed she didn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_38.wav the people who think they're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/10/StutterTalk_10_39.wav  like she's just one person but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_5.wav  always making it there but still lose
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_6.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_10.wav  absolutely it strikes me that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_11.wav you know like this is me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_12.wav  I was at a school or Joe and a mom
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_13.wav and it can make

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_14.wav to connect
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_15.wav  just saying something doesn't have a lot of value

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_16.wav and how alone and different she felt I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_17.wav  out I was confused as to who she was and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_18.wav being covered in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_19.wav  eye contact to see if she go away

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_22.wav and vulnerability
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_24.wav that first it's terrifying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_26.wav  that at first you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_27.wav but then it starts to feel nice tonight

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_30.wav  want to stuff for yourself yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_32.wav trusting interaction and of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_35.wav then you have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_36.wav and to it makes it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/11/StutterTalk_11_37.wav  easy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_0.wav  I will feed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_1.wav I just help that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_2.wav  7 years old and when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_3.wav went to every convention
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_4.wav did and I hope to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_5.wav adult it still is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_6.wav being okay with the way I speak

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_7.wav  that department
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_8.wav there's been a progressive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_9.wav and knowing that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_10.wav  to some extent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_11.wav  stuttering will always be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_18.wav  a lasting impact

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_19.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_20.wav  to grow in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_22.wav  trying to like you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_23.wav  requires some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_24.wav  support to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_25.wav  for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_26.wav are and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_27.wav to make it part of a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_28.wav  you know I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_29.wav  can't remember his

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_30.wav can engine and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_31.wav in out can't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_33.wav  nobody wants to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_34.wav  transformation over time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_35.wav hoping to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_36.wav  see climbing it but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_37.wav  what I want to give back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/12/StutterTalk_12_39.wav and hit the hay and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_1.wav I'll connect with the fact that we started we still
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_2.wav and I remember a week

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_3.wav  normal just different norms
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_4.wav  and do all this stuff you said we just have to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_5.wav I'm like stuttering being
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_7.wav we all come across so many people on a daily lie

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_12.wav or new one might come up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_13.wav  that's so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_14.wav  the gate wasn't such a good like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_15.wav bombies I feel like that although I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_16.wav waiting till it to gain the confidence to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_18.wav  expect but I feel like that when I came back

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_19.wav I then I wanted to like to get up more and speak more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_21.wav I'm very proud to see

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_23.wav when I see
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_24.wav  excited to see what the rest of the day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_25.wav I turned around I didn't even know she knew my name
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_26.wav oh like I was just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_27.wav like I forgot that just by getting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_28.wav oh why no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_33.wav  I'm a did a bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_34.wav  during the past conventions and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_35.wav  too cuz I think that's so much happens
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_37.wav I'm like stuttering I think that any

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_38.wav amazing how we can all go from being
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/13/StutterTalk_13_39.wav  age group at any amount of experience

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_0.wav  grow up just like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_1.wav  like your peers grow up just knowing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_2.wav understanding
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_5.wav thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_7.wav I hope you enjoy the rest of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_8.wav  so I think we often forget

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_9.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_10.wav  has been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_16.wav a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_17.wav  the cat and whether I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_18.wav  you know as she grows up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_19.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_20.wav that I can help my daughter to know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_21.wav in high school and college

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_22.wav  that must have been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_26.wav  wanted to know when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_27.wav so we went up there and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_28.wav it's one thing where

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_32.wav I feel for her because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_33.wav that hasn't happened to her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_34.wav  go and embrace who they are and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/14/StutterTalk_14_36.wav I'm a little bit excited for you cuz I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_0.wav does it better happen
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_1.wav like why I think there's a difference between

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_2.wav that's not my business right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_3.wav that would be like a fluent person looking at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_4.wav we talk about that in an honest way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_6.wav station on this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_7.wav walls of ignorance and discrimination
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_8.wav and I think that's so convenient

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_9.wav we can tell our stories with a stop
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_10.wav I'm mostly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_12.wav if not us then who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_13.wav and maybe that's where the button comes in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_16.wav  it although I it's possib
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_20.wav I'm having fun talking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_22.wav if you can imagine
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_23.wav so you have four quadrants

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_25.wav where as an effortful speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_27.wav because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_29.wav  does that make sense
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_31.wav  well I think yeah obviously

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_32.wav this is sort of a new concept I'm working
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_33.wav if just the people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_34.wav so I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_38.wav  to try not to stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/15/StutterTalk_15_39.wav  I think it's important to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_0.wav  I think that it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_1.wav Cook comfort zone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_5.wav  I speak and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_6.wav and I realized
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_7.wav yes I did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_8.wav I am while speaking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_10.wav  talking openly about stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_12.wav comfort zone and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_13.wav  well at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_14.wav  haha how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_15.wav  annual for French

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_21.wav  it and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_24.wav openly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_25.wav  were realized that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_26.wav sister staying the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_29.wav picked up on anything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_30.wav  dating ticket where you will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/16/StutterTalk_16_36.wav are you getting from speech therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_0.wav  places where I don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_1.wav  would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_2.wav  from basically everyone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_3.wav I think it just depends on the person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_5.wav someone would

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_6.wav  myself as a my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_7.wav  pay to lgbt

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_8.wav  issues just in the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_9.wav I'm great I'm super excited to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_10.wav like seeing a whole family there was kind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_11.wav is that how you guys took it to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_12.wav  to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_13.wav  I think it was just a major

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_14.wav  either of them they're especially not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_15.wav  yet they don't say the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_16.wav kind of like struggling good generation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_20.wav knowing where the gaze

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_21.wav emails tend to come and go and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_22.wav  activity on it then you know like the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_23.wav and so really there's a lot of ways to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_24.wav  gave rights

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_25.wav  there I think knowing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_26.wav because you are gay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_27.wav years ago attending a speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_29.wav was oh I see you have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_34.wav  group so it's very much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_35.wav  you know is never

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_37.wav  accepting place to be and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_38.wav  are just the right to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/17/StutterTalk_17_39.wav and I always was so thankful
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_0.wav  that the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_1.wav  to be frontier or lines it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_4.wav  it doesn't you put so much on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_5.wav  you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_6.wav  something for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_7.wav  have a conversation with somebody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_8.wav  security

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_9.wav  help that much and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_10.wav  it was on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_11.wav  of saying I really do stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_13.wav  card starts and you can cut this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_14.wav  shirts that I pull out I wear them all the time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_15.wav  wow I mean there are a lot of options

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_18.wav that those are great points and the last
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_19.wav  has to be moved to the front of the line and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_21.wav  the best place to start
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_22.wav  are talking about stuttering is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_24.wav  work I got in touch with God I said you will enjoy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_26.wav  over there and there was nobody in it wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_27.wav you know the card really is a million
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_29.wav and we had an immediate bomb

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_30.wav  we learn from these people who have gone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_31.wav  help that's important it is important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_34.wav  which we think play such a crucial
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_35.wav  that person as an individual you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_36.wav  that's exactly what I'm saying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_37.wav  experience well I just think that's really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_38.wav  are you guys the first stuttering charity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/18/StutterTalk_18_39.wav  just knowing that there is some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_0.wav  I think we're going to be excited about Nazareth college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_2.wav  orders to get new members

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_3.wav  the cell the core remains
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_4.wav  in a really great manner

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_5.wav  use ourselves and you'll maybe say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_6.wav it really depends you know yeah oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_7.wav somewhat of an agenda and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_9.wav at the same time I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_10.wav  what you're aspiring to get out of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_11.wav  the moon okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_13.wav  on words that's when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_14.wav social change and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_15.wav 10s hundreds thousands
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_16.wav such a great change and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_20.wav  about Bill Murphy for a year
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_21.wav  I think the level of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_24.wav  rather than solely on the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_25.wav  it's not going to be the end of the world

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_28.wav  some really bad moments
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_30.wav and I couldn't help but notice that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_31.wav and a lot of them you know kind of a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_32.wav  to get to the point of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_34.wav I think it probably really depends
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_37.wav and I don't why it's and she says Daddy why

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_38.wav what are you all doing right there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/19/StutterTalk_19_39.wav  I don't know if it's possible that a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_0.wav  office and the bad experience was not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_1.wav personal as well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_2.wav touch upon it we touched
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_3.wav  surprised about that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_6.wav  ultimately you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_8.wav when that might not be what's needed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_13.wav  there if I didn't leave
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_15.wav when you know a few weeks or months later I can't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_16.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_20.wav  of medical school after college

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_22.wav social context
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_24.wav and they're talking a lot of the time and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_26.wav  so you grew up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_28.wav for cocaine for other kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_29.wav  and you know I mean they were always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_30.wav  are always bad interactions

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_31.wav  openly without talking about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_34.wav Perez

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_36.wav  about September 11
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/20/StutterTalk_20_37.wav  do with this information

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_0.wav  make of how Holti begins her book well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_1.wav well when I work with school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_2.wav  and therapy to tell me is this a good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_3.wav is this a good approach or is this an approach

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_4.wav  two or three hours right yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_5.wav  It's frustrating it can be yeah I think they do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_7.wav  of this book is that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_8.wav speaking supposed to be fun right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_10.wav and what she describes in her book so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_11.wav  it was based on that what I'm saying is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_12.wav like a lot of other parts of the book
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_13.wav as speech pathologist we want to support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_14.wav  so we run that program out of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_15.wav talk freely and also

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_16.wav  so get there stuttering out there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_17.wav  people who I've met

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_18.wav  met okay moving
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_19.wav  want to because I mean it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_20.wav  I mean it's fair a game
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_21.wav  it but I don't think he meant it I think he was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_22.wav  that now I've been a speech language
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_23.wav  stop don't talk like that and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_24.wav  I mean is that your experience to Craig no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_25.wav not bringing attention to it from the class

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_26.wav  yep I agree okay so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_27.wav  is better do you agree

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_28.wav  so for the child off of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_29.wav  read this comment and not get it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_30.wav is a child for flu and talking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_32.wav  I mean isn't that what self-help is doing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_35.wav  there which is you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_36.wav yeah I think that's a really good gauge of how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_38.wav  and it's not like their recovery rates
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/21/StutterTalk_21_39.wav  that you fact-checked his book with me today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_0.wav  therapy we have a problem
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_1.wav  and that problem needs to be addressed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_2.wav  told to find a speech therapist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_3.wav criticism I just quoted of you is fair

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_4.wav  to re-edit rate that you said earlier
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_7.wav it this just occurred to me now I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_8.wav and that was good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_10.wav I guess not being able

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_11.wav  oh boy wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_13.wav  so I guess that's you know is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_16.wav that's my in a nutshell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_18.wav  family

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_19.wav  to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_20.wav  a 10-year-old and this happens a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_21.wav part of stuttering is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_23.wav and you know you talked a little bit about not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_25.wav therapy that have a lot of the horse
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_28.wav but then to say that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_29.wav  appear to work just fine I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_30.wav I mean with all due respect you're not a person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_32.wav  and you know clearly there is a significant
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_33.wav  well respectfully that's not what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_34.wav  that you should teach your child to interrupt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_35.wav  what Brad

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_36.wav you know I'm so glad you brought that up cuz
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_37.wav I just don't think you're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_38.wav all those things before they're nine years old
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/22/StutterTalk_22_39.wav I don't really have a problem with that but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_0.wav you want well Peter yeah that's a great example
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_1.wav going the way that you would wish to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_2.wav word that speech language pathology
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_4.wav  represents the way that we wish to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_5.wav that's what I'm talking about when I talk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_6.wav probably nobody who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_7.wav  they exist intention
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_8.wav that we might not be able to salvage it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_9.wav would look at a term like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_10.wav what does it do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_12.wav  entire thing I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_13.wav more based on what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_14.wav  feel when speaking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_15.wav you know I think that that really probably

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_16.wav  to tame my unruly voice and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_17.wav  and speaking away that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_18.wav you have to be there don't you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_19.wav and she looked at me like I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_20.wav  the mountain seem pretty high don't a boy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_21.wav  boy they do Peter and I'm listening

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_22.wav  why are we mystified
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_23.wav  always possible for me to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_24.wav  of people who started yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_26.wav if we know that there's no cure for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_27.wav  force kids to be fluent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_29.wav  I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_30.wav  so does that answer your question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_31.wav yeah this I agree with you completely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_32.wav they literally see it as at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_33.wav  this voice that may be unruly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_34.wav  Hey I said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_35.wav  so are you talking slow because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_36.wav you know what I really think is that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_38.wav that would actually describe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/23/StutterTalk_23_39.wav and you know I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_1.wav piece what do you think I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_2.wav also that generally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_3.wav  a person stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_5.wav  feeling I still had some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_6.wav  let's say I still

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_7.wav then people in the audience maybe 50
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_9.wav  or let's say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_10.wav made you so fluent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_11.wav  it's positive to stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_15.wav  I appreciate her honesty and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_16.wav  a little bit similar to stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_17.wav  in some sort of way then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_18.wav  when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_19.wav  well wait for me means
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_21.wav  how should I call it to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_22.wav  I feel it is that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_23.wav  you would like to change something

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_24.wav there's something also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_26.wav you know from my perspective

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_27.wav  on the research task
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_29.wav  people identify

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_33.wav stuttering and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_34.wav  it was much more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_36.wav  so they could not hear themselves and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_37.wav  as a difference

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_38.wav problem or just the father
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/24/StutterTalk_24_39.wav  what I think of that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_0.wav  Hey Bob I Peter are you I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_1.wav and so then like let's just say for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_3.wav Open stuttering and easy onset
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_4.wav in a way that they might think is different the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_5.wav the teacher is already expecting a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_8.wav  career you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_9.wav  the mechanisms for getting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_10.wav  information out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_11.wav very very fluency
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_13.wav visual walk before we get into

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_14.wav  even get into that a couple quick
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_15.wav on carry over in the classroom so the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_17.wav  I think that there are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_18.wav the degrees of discretion

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_21.wav  not the teacher so and what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_22.wav  so and what's the message this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_24.wav you know the term speech cops was brought
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_27.wav  just do some business first so this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_28.wav so this is the end of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_29.wav  outside of the therapy room.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_30.wav  room. That I think can have some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_31.wav whether this particular

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_32.wav mechanism for doing that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_33.wav is quite as wonderful as their

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_34.wav  maybe the jury is still out on that I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_35.wav  I think that having some kind of a tangible

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_36.wav device to take with you outside
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_37.wav  of this therapy room

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_39.wav there's this expectation that they don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_40.wav that they don't stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_41.wav  being a kid who stutters in the school anyway
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_42.wav  well yeah I mean and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_43.wav she would come to the door my classroom
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_44.wav and you know she would

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_46.wav  people find the show so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_47.wav so Bob before we get into our big topic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_53.wav right you know I think that might be part of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_54.wav the notebook to say yep I just stuttered

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_55.wav you know contrast that with a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_57.wav  a rewind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_58.wav  couple of SLP's who don't stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_59.wav and so from their perspective

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_60.wav  idea
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_62.wav  I guess in some ways I'm not surprised

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_64.wav  because they probably had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_65.wav if they were lucky by one class and stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_66.wav  to use that speech tool I got
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_67.wav  tool I got to say my heart dropped

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_68.wav  post this podcast called Stutter talk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_69.wav and she paused for a second

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_71.wav  inhale
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_72.wav  whiteboard cleaner anyway

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_73.wav  probably be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_74.wav a little bit of no I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_75.wav  I think that gets into the sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_77.wav  one about making

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_78.wav making a bracelet with your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_79.wav strategy on it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_81.wav  that easy on sets
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_83.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_84.wav  and again I this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_85.wav  we listen to you all the time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_86.wav  him and I was like really touched I thought that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_87.wav  SLP's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_88.wav  put yourself in the shoes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_92.wav  are introducing yourself to them point

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_93.wav  point your bracelet okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_96.wav  how that makes you feel okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_97.wav  Now understand that you're not a kid of stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_98.wav  pressure off of that child well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_99.wav maybe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_102.wav for anything because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_103.wav  I don't know it doesn't happen every day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_105.wav  be it's going to lead to much more embarrassment than

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_107.wav times I stutter and that's okay and has
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_108.wav and has a space for the child to put their name
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_109.wav  the back it has tips for the classroom and so these

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_110.wav and so these tips are give me the time I need
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_111.wav what do you think of this idea it's good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_112.wav  idea it's good in the s that you are giving the person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_113.wav  better there's a new

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_114.wav  substitute teacher there's whatever it might be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_115.wav  going to play out okay does

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_116.wav does the person have time then to flip the card over
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_117.wav  the potential for that to have value and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_119.wav  work but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_120.wav and certainly at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_122.wav has more information that he would have had if they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_123.wav  of a stuttering if you listen to stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_125.wav  didn't have it with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_127.wav  grade teacher is out you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_129.wav into a classroom where there might be an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_130.wav be an autistic child or two

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_131.wav have a kid who stutters and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_133.wav  so he or she barely speaks English

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_134.wav  English and so this teacher is walking in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_136.wav 5 when kids arrive and try to hand the teacher

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_137.wav  to me it's really about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_138.wav an adult like a parent or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_139.wav  yeah did I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_145.wav  ideas that you might want to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_147.wav  about why they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_148.wav water would not be useful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_149.wav  I'm not trying to dis
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_151.wav  or these suggestions you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_152.wav abrevious way there often take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_153.wav the other was simple but unfortunately it just isn't right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_154.wav  isn't right so that's sort of what I said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_155.wav you're facing fear so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_156.wav be your so maybe if you're afraid of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_159.wav  be the approach to therapy I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_161.wav stuttering has gotten so much worse
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_163.wav when you read about somebody who would

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_164.wav  who would rather put a pencil through their
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_167.wav  of they presented

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_168.wav it's just not that peachy and it's not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_169.wav  know things are presented in a very sort of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_170.wav sound by superficial
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_172.wav  yeah I mean I think that you take these

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_173.wav  make it work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_174.wav  Stuttering acceptance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_175.wav  Stuttering acceptance
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_178.wav I'm in totally agreement with you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_179.wav  that when I first started to watch the show and it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_180.wav  that's just that's probably more of a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_181.wav conditioned reflex at this point
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_182.wav is there anything you want to ask me the child

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_183.wav me the child can explain why
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_184.wav  SLP's who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/25/StutterTalk_25_185.wav  who obviously do more than just work with kids who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_1.wav the child rated

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_3.wav the total impact score on the OAS
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_4.wav plicated case I ask for help absolutely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_7.wav  you know that can feel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_8.wav well bad for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_11.wav  person feeling like you're attacking them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_12.wav  him well I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_18.wav  does that change how you might respond
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_19.wav bond yes I think I might insist

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_20.wav  fully understand how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_21.wav  how situations can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_22.wav situations can change how we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_23.wav  I'm curious to find out how you handled that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_24.wav it was so long ago I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_25.wav it says oh it's okay I stutter to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_26.wav  to well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_28.wav therapy one on one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_32.wav  walking and you have to understand that stuttering is not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_33.wav  I don't want to be bothered

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_35.wav it's in Israel he's a person who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_36.wav he writes something that we've all heard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_37.wav  someone tries to finish our thought for us
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_38.wav  well you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_42.wav  because when we stutter that can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_44.wav  again don't they're not doing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_45.wav  in order to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_47.wav evil or nasty they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_48.wav as being pretty
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_49.wav advanced for lack of a better word

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_50.wav oh you don't really have to do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_51.wav is it well yeah I do because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_52.wav  better with stuttering then you really are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_53.wav  are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_55.wav you know like you say the three of us
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_56.wav  I think that's a fairly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_57.wav  I get my point across even though I still utter some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_58.wav  college you're not stuttering a lot I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_59.wav but that things are easy for you now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_60.wav  just because I'm not stuttering doesn't mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_62.wav let's start with you Bob
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_64.wav  in order to be unkind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_66.wav  who don't stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_67.wav give people a do stutter bad advice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_68.wav  they can and a situation that they're not familiar
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_69.wav  not familiar with and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_70.wav  by and they're in a major block so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_71.wav  so you're looking at them and it's like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_74.wav eyes and what do you do with your hands and we know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_75.wav  and well you know Peter is very interesting you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_76.wav  don't really understand stuttering or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_77.wav  really no stuttering you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_78.wav  rather hear me stutter than we've been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_79.wav you know we've been through the whole gamut

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_80.wav  sometimes and certainly I don't blame
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_81.wav  I don't blame her for reacting that way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_82.wav  minutes on just saying hello and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_83.wav  and finally this very well-known

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_84.wav  started her and started talking now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_85.wav now there's nothing politically correct

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_86.wav using to say it's my turn to talk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_90.wav what do you think of response like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_93.wav politically correct by any means
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_94.wav  I'm sorry Tacoma at a stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_95.wav  at the National Stuttering Association
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_96.wav  you'll never stutter again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_97.wav can well there's one particular
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_99.wav not too quick to dismiss device

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_100.wav  him since he was in the 7th grade and I worked
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_101.wav  and I worked with him when he was in June

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_102.wav apparently do get some kind of a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_103.wav proceivable effect in the sense that they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_104.wav  and certainly if you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_105.wav  you investing on these devices

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_106.wav you might want to believe everything you read on the internet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_107.wav  on the internet

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_108.wav  in community and she writes this here's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_109.wav here's a potentially

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_110.wav  say or because they're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_111.wav excited or something like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_112.wav  have discovered the joy of communication
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_116.wav  perhaps uses it too much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_117.wav  you know well when you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_118.wav reaction when people who stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_119.wav who stutter and getting therapy and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_120.wav  find that they are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_121.wav  they are less burdened than they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_122.wav  and the ability to be a good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_123.wav communicator not just a good talker
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_124.wav now that I don't do that anymore like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_126.wav  me trouble sometimes and I remember not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_127.wav  remember not this voting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_128.wav  at but I think it would you know that my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_129.wav  know that might rub me the wrong way you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_131.wav they're throwing off you know because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_135.wav  to the listener and you'll have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_138.wav  just better to just try to sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_141.wav  politically correct but certainly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_142.wav  and saying you know cut the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_144.wav  have to apologize for getting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_145.wav getting angry if people do something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_146.wav obsess us even if they do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_149.wav  that begin with D my entire life and that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_150.wav life and that's like a very disarming response

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_153.wav  where we are we know we want to say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_155.wav  it reflects upon Jews everywhere and I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_157.wav  a speech tool do you use it and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_158.wav use it and I and he's known me for years he's heard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_159.wav and commit to a phone call
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_160.wav because you know there's not going to be any

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_161.wav  that is he would say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_167.wav  until you actually have a chance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_168.wav  have a chance to see them and maybe sit down
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_170.wav that metaphor just does not sit right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_171.wav  me speech tools are clunky and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_172.wav  you know where you actually talk is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_174.wav  so it's not the same thing yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_175.wav yes it's definitely not the same

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_176.wav  so then where's that sense of agency and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_177.wav and tools are made of metal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_178.wav  wish to apply to speech normally when you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_179.wav  normally when you need speech tools they're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_180.wav you have to pull out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_181.wav and what's really interesting is that tool

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_182.wav  to focus on speech tools can really shift
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_183.wav  and really shift our focus has clinicians

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_186.wav  as much as anything else is what hinders every
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_187.wav  teachers everybody getting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_188.wav give the mom something to read and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_189.wav and it talks about how preschool

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_190.wav  they did the SSI for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_191.wav you know and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_192.wav  like we were talking about with a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_193.wav  about with the clinician and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_194.wav  and you know we are we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_196.wav stuttering while also correcting them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/26/StutterTalk_26_197.wav  them well I try to handle it lightly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_1.wav my stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_2.wav  Our chapter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_3.wav  I actually am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_4.wav with the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_5.wav  really enjoyed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_9.wav  for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_10.wav  just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_11.wav  well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_12.wav then to say something

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_14.wav  I think it's so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_17.wav  express

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_18.wav  I have always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_21.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_25.wav about something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_26.wav something a different in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_27.wav working on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_31.wav I blames

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_34.wav  yeah I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_35.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_36.wav the NSA
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/27/StutterTalk_27_39.wav  I'm sorry gosh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_1.wav  I guess what I'm saying that there's kind of an understanding
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_2.wav depending on the size of the group

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_4.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_5.wav and it was in Brooklyn cause

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_6.wav  and 45
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_9.wav  of everyone's experience is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_10.wav  is can be a really important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_11.wav  who's better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_12.wav the benefits of that are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_18.wav make a space where people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_19.wav  moment yeah that happens
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_20.wav  to 20 people present

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_21.wav  there would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_24.wav acted to activities now it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_25.wav  planned sometimes like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_26.wav like each group is so dependent on whose

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_27.wav like reader directing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_29.wav one of the most important things

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_30.wav  whatever speaking techniques we please we are here
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_34.wav we feel that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_35.wav  happens last question for you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_37.wav Holy with you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/28/StutterTalk_28_38.wav and I think that's important because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_0.wav  because you have people coming

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_1.wav  to hot button term yeah it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_2.wav turns or tools but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_3.wav the feeling of safety in a safe place
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_4.wav I think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_5.wav one of the things that I did was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_6.wav  of all their other differences you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_7.wav chapter I visited your chapter it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_8.wav  know and I really do value that I think it's kind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_9.wav  me to the people who run the groups.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_10.wav  go now you have a very healthy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_11.wav she said this is part of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_12.wav  they're not a lot of it's going to be new to them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_13.wav  and there are more fluency Central
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_14.wav and fluency tool

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_15.wav  think there's a quick fix and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_16.wav a strategy do you use it and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_17.wav  I do a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_18.wav  a long time ago maybe 20 years and it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_19.wav we certainly do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_20.wav  angle area and people that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_21.wav  know actually don't like to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_22.wav but the group that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_23.wav  find on sibling day and they're sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_24.wav relationship to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_25.wav one of the team said oh my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_27.wav sucks to be you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_29.wav but most of the time they just want to hang
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_30.wav so here in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_31.wav  help or support I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_32.wav it let me preface this with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_33.wav  that broadens your knowledge
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_35.wav because the cell

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_36.wav  of it is so hard to make good decisions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_37.wav what advice would you give to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_38.wav way to connect with other people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/29/StutterTalk_29_39.wav  think the purpose of the group is for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_1.wav  I'm in the other one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_2.wav  Uncle Sutter's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_3.wav  I'm the kind of story that you probably
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_5.wav  and that I have a speed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_6.wav  and everyday life so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_7.wav  another way of talking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_9.wav and they'll also just ask me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_12.wav  I'm not I'm sure that you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_13.wav  that you know about and is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_14.wav  much later after our lives headed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_15.wav  I'm suffering can actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_18.wav I'm dating or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_22.wav  with I'm embracing it as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_23.wav and express yourself and I think that makes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_24.wav  Intermedia
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_25.wav  so that's a little

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_27.wav I'm disability so I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_28.wav  always depend on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_30.wav  in some way that it adds
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_32.wav  or that person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_35.wav  the fact that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_36.wav  and so right now I'm trying to do some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_37.wav  you read David Mitchell's black swan green
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_38.wav  course I read

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/30/StutterTalk_30_39.wav  way of trying to find a person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_0.wav Emily Anderson is a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_1.wav  is going into a restaurant or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_3.wav  as always Jane thanks for coming on here today thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_5.wav duttering well when most people hear that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_7.wav I haven't really met many people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_8.wav  also stutter but what I've
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_10.wav  out of it but my brother and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_12.wav  so I never introduced myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_14.wav all life stuttering game play

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_16.wav  love to overcome the stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_18.wav cuz I had the choice to kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_19.wav  think that you know that applies to us all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_20.wav  to reiterate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_21.wav oh and by the way that stutter on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_22.wav  it's home and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_25.wav  I think another thing that I'm thinking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_26.wav  and you do stutter couple

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_28.wav  and he stuttered a great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_29.wav  he didn't start her with her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_30.wav  he was carrying around in French that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_31.wav  that it gives you just enough I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_32.wav  fascinating and I don't know the answer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_33.wav  and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_35.wav  as you know it's different therapies largely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_37.wav Doesn't it he's a professional stutterer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/31/StutterTalk_31_38.wav  and myself and when I do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_0.wav  a film a Peter great to be with you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_1.wav optube adults who stutter and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_2.wav be a person who is bothered by it or is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_3.wav for example a negative prediction
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_6.wav the presence of that trade will perturbed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_7.wav  then you could have when you were earlier on in your career
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_8.wav  when things don't work out the way everybody would do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_9.wav  has our journey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_10.wav it's not the way it unfolds and there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_11.wav  at a butterfly flying in the sky
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_12.wav as a trait stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_13.wav the state itself is characterized by
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_14.wav  appear over time that's common

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_15.wav and sometimes stuttering has zero
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_16.wav  future so let's talk about how we as professionals

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_17.wav  might think of responding to the very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_18.wav  listen to the underlying message what is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_19.wav  ask what are your thoughts because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_20.wav  fear and concern and by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_22.wav to speak normally start
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_23.wav  up with a simplistic answer our language

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_24.wav one yes that is so very true
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_26.wav  and I think that that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_27.wav that we're afraid it will be inadequate and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_28.wav  supposed to make the stuttering stop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_29.wav  that are not continue to have that tendency
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_30.wav it could be frustrated it could be humiliating

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_32.wav these are very humbling you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_33.wav  to hear great so Kelly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_34.wav such a great point and I'm going to say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_37.wav  around the age of 20 that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_38.wav the speech language pathologist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/32/StutterTalk_32_39.wav this mother heard that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_0.wav usually that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_1.wav  However

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_2.wav those are already
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_3.wav  that it's very effort

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_4.wav for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_6.wav  is beneficial anymore

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_7.wav did that make sense it makes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_8.wav to think about is it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_9.wav  see I'm just going to end up repeating my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_10.wav  stuttering for so long

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_11.wav and so my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_12.wav  stuttering or to openly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_13.wav daughter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_14.wav give up control

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_15.wav you have to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_16.wav have the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_17.wav confidence that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_19.wav  if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_20.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_21.wav however every time I get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_22.wav and yeah it doesn't make sense to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_23.wav do that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_24.wav you have to find what works best for you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_25.wav and that is a great place to leave

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_27.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_30.wav  better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_31.wav  so as I'm repeating these
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_32.wav and I decide

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_33.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_34.wav instead of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_35.wav  allowing her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_36.wav and what's happening to frustrated

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_37.wav me cuz I've after all she was really only
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_40.wav  way of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_41.wav I don't know lessening my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_42.wav  you want to watch it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_44.wav you go humbling myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_45.wav as I would block I could sort of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_46.wav predict when she would whisper to me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_47.wav smile when I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_48.wav think about it so if you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_49.wav  I think she's probably

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_50.wav in our 80s okay then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_51.wav  slipped

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_52.wav it the fact that other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_53.wav it sort of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_54.wav made the exercise even more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_55.wav with not having overcome it all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_56.wav on frankly the thing that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_57.wav was what I said at the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_58.wav beginning was the fact

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_59.wav  and I'll say to them that's what your student just did to you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_61.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_63.wav  Catholic community I think that's kind of cool
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_65.wav  or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_66.wav obtaining that forgiveness
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_67.wav and it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_68.wav it occurs in different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_69.wav maybe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_72.wav because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_75.wav  encouraging and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_77.wav face just tell the priest that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_79.wav it feels like cuz I often I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_81.wav that's really great to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_82.wav and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_83.wav  I would say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_84.wav ring in confession or during confession

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_85.wav  yeah absolutely but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_86.wav any scarier than like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_89.wav  I think that's a good point
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_90.wav I think as a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_91.wav  as a child
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_93.wav  better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_96.wav that yeah my family growing up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_97.wav  sibling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_98.wav and so it was never that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_99.wav  education having to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_100.wav  recite prayers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_101.wav  the course of the presentation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_102.wav  yeah you're right but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_103.wav I'd love to know what happened

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_105.wav  how much I worried about stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_107.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_108.wav that's possible actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_109.wav and I don't know if this is a coincidence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_110.wav but my youngest brother
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_111.wav who does not dutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_112.wav  wow a conspiracy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_113.wav ask the non sputtering child

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_114.wav to say Grace no I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_115.wav  I was telling you about the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_116.wav during the mass
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_117.wav  during the mass on Sunday

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_118.wav at the end
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_119.wav of the masses when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_120.wav  option not to stutter at that moment
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_121.wav  I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_123.wav and experience that I recently
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_125.wav Cern is really for the man or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_126.wav the woman who is the minister
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_127.wav  they weren't supposed to give me until I said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_130.wav in that moment
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_131.wav  of wondering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_132.wav what's happening
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_134.wav I could say it with much control

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_135.wav I could try but it was still going to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_136.wav  that it's going to be hard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_137.wav  it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_139.wav  I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_141.wav had with my fraternity brothers and sisters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_142.wav  me down the aisle

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_143.wav I think yeah I could probably
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_144.wav  be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_145.wav I've
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_146.wav had enough experience

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_148.wav Richard with stretches back to my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_149.wav  very severely and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_151.wav  to move my speech out in that moment
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_153.wav  I wasn't always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_154.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_156.wav phase where I didn't have anything

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_157.wav and talking to people who weren't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_158.wav other professional

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_159.wav  are you again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_160.wav started to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_161.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_162.wav to sort of set this stage

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_163.wav more active in my face again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_164.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_165.wav I stopped
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_166.wav my stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_167.wav  thing that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_168.wav part of me and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_171.wav you wouldn't otherwise know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_173.wav right I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_177.wav  so that it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_178.wav and I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_179.wav so if I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_180.wav try not to stutter here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_181.wav  were sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_182.wav as a I'm a fairly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_183.wav  I'm talking to on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_184.wav is fairly it's not giving them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_185.wav  isn't and thoughtful with others
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_186.wav yeah absolutely it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_188.wav  is to be discriminated against to be made
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_189.wav  fun of to feel like you can't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_190.wav not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_191.wav able to do something the way you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_193.wav  respond freely to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_194.wav  react in the way that you want to react

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_195.wav so I'm sorry I said I had that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_196.wav powerful but for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_197.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_198.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_199.wav I think that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_200.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/33/StutterTalk_33_203.wav  blocks and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_1.wav  not being able to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_2.wav  of this I think moments
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_5.wav  very uncomfortable with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_6.wav  listen but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_9.wav clothing and how the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_10.wav  At our listener
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_14.wav from last year's conference

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_15.wav  I just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_16.wav hole afterwards and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_18.wav  construct them and make them more positive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_19.wav  voice or if it's a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_20.wav so first we kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_22.wav  moment and we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_23.wav  Ha
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_24.wav  negative

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_25.wav  post that that was do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_26.wav from there I kind of moved on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_27.wav hundred May 20th
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_28.wav moment how there's always a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_31.wav and I think that we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_32.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_36.wav Dagnation involves
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_37.wav  I think has really helped me just thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/34/StutterTalk_34_38.wav think about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_1.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_3.wav  for sssl
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_7.wav wow we all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_10.wav  yes I did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_12.wav any ba ba buddy D else

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_15.wav  okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_17.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_21.wav  you and she said yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_23.wav  my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_24.wav  to be careful and yeah please
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_25.wav  I should think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_27.wav  but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_29.wav  I think we should have a more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_31.wav  the Noble one has I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_32.wav  for frustrated sh sh shins

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_35.wav and life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/35/StutterTalk_35_36.wav  expected to do a lot like it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_0.wav define how I describe what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_1.wav  I feel like a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_2.wav  newer and more effective
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_4.wav  in one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_6.wav  matter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_7.wav  particular cues but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_8.wav that it is caused by
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_10.wav and then on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_11.wav do you actually in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_12.wav that the anticipation of stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_13.wav in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_14.wav their overall that ranks

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_15.wav the number one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_16.wav  that they do and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_17.wav  of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_18.wav ticipation could be playing a role

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_19.wav therapies that do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_20.wav because it's being labeled

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_21.wav  have a strong evidence
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_22.wav  important to work on these things

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_24.wav believed at the biggest issue in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_26.wav  the whole goal of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_28.wav are usually not changes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_29.wav  stutter as well that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_30.wav the only goal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_32.wav yes I agree and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_33.wav there's any aspect of that I would not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_34.wav  begins all of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_35.wav patient drives the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/36/StutterTalk_36_38.wav  other than hope

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_1.wav we can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_2.wav we can talk to each other and we can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_3.wav  rather than
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_6.wav  magical things I feel about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_7.wav able to have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_9.wav bikes are Chris like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_10.wav  explain ourselves to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_12.wav may be if we can do that with the rest

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_13.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_14.wav my watch up this morning I called it naked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_16.wav  just started opening is to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_17.wav  at least I feel

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_18.wav very delicate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_19.wav each kid with disabilities

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_20.wav all right well thank you all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_22.wav  comfortable in that to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_23.wav tent to be able to make at least other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_25.wav  and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_27.wav  like naked stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_28.wav  kind of makes me a little

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_29.wav  and no shoes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_30.wav  breaking also there's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_31.wav  process for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_32.wav it was really great I got in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_33.wav  I still have two days
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_35.wav  listening everybody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_38.wav  being here to talk about the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_44.wav opinions was really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_45.wav really great and just that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_47.wav opening I didn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_53.wav  riffs
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_55.wav we stutter.org

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_57.wav touch my heart
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_60.wav  doctor

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_61.wav in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_63.wav  so I was very touched

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_64.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_65.wav that's it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_67.wav  for me today was the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_68.wav the workshops so a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_69.wav  with young people and we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_72.wav and Aaron

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_73.wav talk about like challenges
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_75.wav the community and bring them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_76.wav second workshop I did was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_81.wav within and destroy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_82.wav  the story I had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_83.wav  so much and I was able to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_85.wav  there's a great experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_88.wav help help

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_89.wav leader and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_90.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_91.wav it was on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_92.wav masculinity and stutter and how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_93.wav  are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_94.wav are traditional

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_96.wav  was found race and we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_97.wav we gave this Workshop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_99.wav  one of our takeaway messages was that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_101.wav  can use stuttering to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_102.wav be intimate with others that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_103.wav  be about 10th conference time really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_105.wav we can sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_106.wav level jump in relationship so are we can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_111.wav it was a Asian Art Museum
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_113.wav  one of the women who worked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_114.wav piece of art we were looking at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_115.wav and when we start a stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_116.wav she immediately
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_117.wav and alcoholism and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_118.wav the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_120.wav  it was incredible we had just talked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_121.wav  we had just talked about how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_122.wav  stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_123.wav  of has this ability to do that and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_124.wav  that and then we got

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_125.wav the first person that we speak to all the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_126.wav all of a sudden we know them better than

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_127.wav  before it would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_131.wav  other all day long

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_133.wav  does anybody have a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_139.wav  courage like those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_140.wav  was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_141.wav  your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_142.wav  or 10 year olds
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_143.wav they stood up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_144.wav  out to tell Josie
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_145.wav they can do that you can do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_148.wav people of any age can be a romano right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_149.wav Owen wise

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_151.wav  I also really enjoyed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_155.wav  Breakout session that was incredible

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_157.wav  difficult but it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_160.wav  any clear idea of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_161.wav weather or not I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_165.wav what we're doing and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_166.wav  even more than that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_167.wav  about what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_168.wav what are you doing why are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_170.wav  do we need to rip

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_171.wav before we hear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_173.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_174.wav brother Athens Georgia
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_176.wav pick that apart for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_178.wav pragmatically
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_180.wav  if thinking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_181.wav oh
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_182.wav am I tensing up like this because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_183.wav and if thinking like that we've got
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_184.wav  that regardless if that one is true

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_187.wav  other than ugly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_189.wav  grapple with and I think it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/37/StutterTalk_37_190.wav is powerful that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_4.wav are what the kids have to say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_5.wav joining me on this fine
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_6.wav  Workshop that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_8.wav  the difficulty
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_9.wav talking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_10.wav  by the perceptions of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_11.wav world as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_12.wav  better make some of the best
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_14.wav Cellable at a time I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_15.wav stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_16.wav across the globe and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_17.wav  the NSA support groups
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_18.wav  podcast here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_19.wav stutter to take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_20.wav conferences over the last

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_21.wav we have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_22.wav that you've gotten

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_23.wav  to spread awareness
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_24.wav  program

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_26.wav pushed me to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_27.wav we simply

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_31.wav  I think where we can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_32.wav  that was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_35.wav  about our stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_37.wav me too any

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/38/StutterTalk_38_39.wav  a conference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_1.wav  that would be called under the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_2.wav it's only natural to avoid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_3.wav  avoid a word successfully

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_4.wav because if you do not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_5.wav  will be loaded and will be pump a the second that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_6.wav  that's how stuttering works with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_7.wav  theory about this that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_8.wav  the cause of the disorder
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_9.wav to try to know the cause because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_10.wav  over it comes again and I'm helpless so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_12.wav  the point we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_14.wav well those are two
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_15.wav right now what might you think of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_16.wav  stuff trying to prevent it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_17.wav  ever Johnson did and that he said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_18.wav I cannot agree with that all over
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_19.wav  got a lot of ideas that was helpful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_20.wav but anyway going back to the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_21.wav  will I think Dean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_22.wav  it's not part of a mountain chain
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_23.wav  people who have a role

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_25.wav the very important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_28.wav and I said they could take that and blow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_29.wav sort of uncertain thing to be depended
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_30.wav  and I've been very aware of them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_31.wav  stopage of picture of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_32.wav  sound and everything you could see the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_34.wav  pull the string back together again and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_38.wav but I remember the visit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/39/StutterTalk_39_39.wav and then about 1926
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_0.wav about speech therapy and I got this sense

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_3.wav did that reduce your stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_4.wav  and I'm very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_5.wav I'm very fortunate that I grew
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_6.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_7.wav I would believe so much in myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_8.wav okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_9.wav taking some of the risks that I've taken
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_10.wav  started thinking about this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_12.wav when I think about it I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_13.wav work went into my speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_14.wav a paradox when I was a kid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_15.wav and so I would try and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_16.wav  trying to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_18.wav like I said I had a very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_19.wav it's a little I think some people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_20.wav I started having a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_21.wav that you know if I had problems with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_24.wav and my hair

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_25.wav part of me that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_26.wav other people were telling me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_27.wav  beginning I don't remember
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_29.wav  just you know we just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_30.wav no matter what went on at school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_31.wav I spent most of my time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_32.wav  that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_34.wav that was very much what I found

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_35.wav but it made kind of casual
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_36.wav  someone else would have that effect

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_37.wav uses or here's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_38.wav there is a part of me that does

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/40/StutterTalk_40_39.wav and but I like to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_0.wav  recently that I really just can't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_2.wav because that's a condition that I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_5.wav you know get an idea of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_7.wav and so you can sit here
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_8.wav and I'm going to share this and you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_9.wav  has been it's still all about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_10.wav yeah I think it's a tricky thing because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_11.wav and trying to piece together what makes them uncomfortable
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_13.wav  one of the universities that I was working with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_14.wav  that means less than far less
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_15.wav  board recognized specialists

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_16.wav it is something we should be aware of I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_18.wav from a training perspective

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_19.wav  whether it's in graduate class whether it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_20.wav or that's what people choose to target

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_21.wav  hours it's virtually nothing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_22.wav new clinician and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_26.wav where people can access that information
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_27.wav  working with on Monday not let me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_28.wav  let me wait till the next convention is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_29.wav  or a number of reasons

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_30.wav  anybody who's very comfortable so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_31.wav  I mean the greater okay so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_32.wav  being too generous because there's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_33.wav  I agree with you so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_34.wav  talking with 10 adults who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_35.wav  which was the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_36.wav and unanimously we said none
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_37.wav  deal with it in that particular moment

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_38.wav and I was in a very tough place with my stuff
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/41/StutterTalk_41_39.wav and I said you were well could it also

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_0.wav can you give an example
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_1.wav  you know if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_2.wav  this to Peter I think my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_3.wav  then I really think we need to get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_4.wav and then I think we could talk about training
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_5.wav undue in your speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_6.wav that's a new answer I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_7.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_8.wav  that client that family share with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_9.wav  yeah you know like I think there is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_10.wav  second year on the board is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_11.wav  is that you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_12.wav  really have a lot of you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_13.wav  of you know for lack of a better term

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_15.wav  slow down a little bit sometimes that it helps me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_16.wav  work at night on the weekends I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_17.wav we've had consumer advocates in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_18.wav  go on and on of area

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_19.wav are journals in this area and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_20.wav  pretty strong

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_21.wav  other professions are out there that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_22.wav you know they're not falling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_23.wav  under the surface you know it's not a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_24.wav  yeah you know like I think stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_25.wav  kinds of things that will just kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_27.wav  us and or maybe you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_29.wav I think interesting thoughts if there's a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_30.wav what in the state of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_32.wav that they can get all the services
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_33.wav you know quite that distuttering I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_35.wav that would be a way to get those hundred and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_36.wav  so yeah we're having a great conversation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_37.wav  Christian Camel those people can't read
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_38.wav which do that going into the field

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/42/StutterTalk_42_39.wav interested in just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_0.wav I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_1.wav  I would most certainly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_2.wav welcome that interdisciplinary

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_3.wav Dan's other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_4.wav it feels simply aren't interested

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_5.wav  other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_6.wav  feels really start

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_7.wav  evaluating and treating people who start
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_9.wav a fifth maybe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_10.wav  yeah I was going to say 5%
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_11.wav  and treating ear infections

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_12.wav would we feel good about that field
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_14.wav  others work

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_15.wav with speech therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_18.wav  being a much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_19.wav  with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_23.wav most could be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_24.wav good therapists
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_25.wav  final thoughts on this topic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_28.wav have I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_31.wav attempting to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_33.wav  I hope brought out a great conversation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_36.wav  speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_38.wav  so while I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_39.wav  a lot of those students are probably receiving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_40.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_42.wav duttering treatment and then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_43.wav these are the conversations I have all the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_44.wav so how do we digest this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_45.wav I think you're right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_46.wav  are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_47.wav nervous when it comes to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_49.wav sort of collapsing the oldest order to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_50.wav that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_51.wav  her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_52.wav  fundamentally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_54.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_55.wav if they're punitive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_56.wav and I'll start our association of friends

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_57.wav well I've been doing that for 17
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_60.wav do you think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_61.wav is more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_62.wav  up a really important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_63.wav point about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_64.wav  speech however

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_67.wav  maladaptive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_68.wav  happening when people who sort of don't have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_71.wav often
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_72.wav  Pressure to be fluent in the therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_73.wav room I don't think is above and be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_74.wav  I think you see those exact same

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_75.wav strategies to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_76.wav it could be many different things

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_77.wav  So
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_78.wav we went being deployed by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_79.wav  the therapy is actually making that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_80.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_81.wav  struggle
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_83.wav if that is the case

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_85.wav stuttering treatment situations
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_87.wav  in order for research to be meeting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_88.wav before you have to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_89.wav  so they're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_90.wav for you've already sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_91.wav and so yeah your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_92.wav you're suggesting that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_93.wav  that yes therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_95.wav well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_96.wav can be should be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_97.wav  saying that they might
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_98.wav I think a lot of times

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_99.wav  something to cope on their own that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_100.wav  in ways it doesn't always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_101.wav  is at least
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_102.wav giving the child a place

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_105.wav mostly what I get in trouble
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_106.wav for is missing signatures

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_107.wav  a lot of the commission's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_108.wav don't really know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_109.wav how's there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_110.wav doing because they're not being supervised

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_111.wav  bye
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_112.wav somebody who's properly trained

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_113.wav  studies and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_114.wav even as cool as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_116.wav because let's take something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_117.wav and they don't really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_118.wav  see
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_119.wav their worthiness

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_121.wav  are either
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_123.wav  speak and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_124.wav I can tell you that at the end of therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_126.wav don't necessarily ever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_127.wav the doddering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_128.wav  guess what I'm saying is that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_129.wav  is an appropriate goal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_130.wav and my our field except

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_131.wav  I think it's a little
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_133.wav  B for example

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_134.wav some people whose daughter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_135.wav will become

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_136.wav  on is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_138.wav  the child is already in a situation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_139.wav where there's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_140.wav  want to achieve that with everybody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_141.wav  boy that is such a big question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_142.wav say and you won't stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_143.wav are we that confident that we've
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_144.wav because of they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_145.wav if I stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_146.wav to go to this place and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_147.wav be cured
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_148.wav  anymore what do you think Chris

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_150.wav  improvement
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_151.wav  however I see

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_152.wav  fluency
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_153.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_155.wav bias within our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_156.wav  for I've worked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_157.wav with them there's a difference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_159.wav funny because usually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_160.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_161.wav I understand that we're providing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_162.wav is often
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_163.wav helping more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_164.wav folks who've never had to do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_166.wav  problem with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_167.wav the person just very anxious the person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_168.wav we know it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_169.wav  isn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_171.wav  person who stars

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_175.wav the sound that you're trying to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_177.wav how it is that we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_178.wav  goes on but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_179.wav from my experience working in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_181.wav in the way of our speaking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_182.wav  who face stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_183.wav and being blown away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_184.wav that when I receive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_186.wav something like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_187.wav  And so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_188.wav  I completely am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_190.wav but when I see the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_191.wav they seem to have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_192.wav  scrappancy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_193.wav maybe those therapists aren't even working on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_194.wav  talk with that much stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_195.wav and somebody raised their hand and said are you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_198.wav  difficult and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_199.wav when I've received
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_200.wav I think without empathy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_201.wav your student
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_204.wav fine with stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_205.wav of course he also said that he doesn't want to start
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_206.wav he's uncomfortable

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_207.wav any smart enough to say oh I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_209.wav I think it's perfectly reasonable for a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_210.wav  sure I agree with that but what do you think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_211.wav if we're talking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_212.wav longstanding
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_213.wav  research and clinical

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_215.wav studying and working with people who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_216.wav  the daughter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_218.wav ordered to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_219.wav  in their academics teacher

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_220.wav  decided they wanted to pursue therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/43/StutterTalk_43_221.wav  those students tend to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_1.wav wasn't as invested in that class as much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_2.wav  the swarming class and I think that yes that is definitely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_3.wav  wasn't anything surprising
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_5.wav  with this conference that old

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_6.wav we wanted to offer this to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_7.wav  social affective cognitive aspects of it and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_8.wav  now and then offer some advice off
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_9.wav you know I just said well you just said it right there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_10.wav  limitation what we've been doing is that you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_11.wav  is that we wanted to be voluntary on their

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_12.wav  they and basically looks at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_13.wav now I have to say it as a disclaimer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_14.wav  we're trying to expand our geographical scope
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_15.wav  guys are pretty well received I'm sure yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_16.wav  sometimes they're in the dark with that and so you know it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_17.wav  yes and you know I unfortunately

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_18.wav  some private practice generalist you really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_19.wav  you really have a problem working people who stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_20.wav  Bill Wilkerson Center
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_21.wav let me ask you this so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_22.wav  love that comment and I agree with it I think you know there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_23.wav  that's a great question and it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_24.wav give it my best shot while also searching for help
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_28.wav  on geographical and economic reasons and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_29.wav improve on those services but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_30.wav optimally it would be great if we had you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_33.wav but in certain school districts in certain areas you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_34.wav  treat my articulation students

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_35.wav  I'm thinking nobody would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_36.wav and so what we're hoping to do is help empower those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/44/StutterTalk_44_37.wav one thing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_3.wav  providing inadequate treatment

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_4.wav they do the right things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_5.wav get positive results from it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_6.wav Bob what do you make of that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_7.wav  be pushed a critical point in time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_9.wav requirements and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_10.wav the knowledge of the mechanism

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_11.wav to work with people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_12.wav  is not going to be the whole

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_13.wav don't feel we have enough time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_14.wav and just to add into

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_16.wav  if training in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_18.wav detriment I think the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_19.wav called by the number of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_20.wav the low ratings were primarily because he stuttered

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_21.wav  Well if you can't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_24.wav  and generally it's like you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_26.wav but the kid is not going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_27.wav  say and the person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_29.wav and again I look at this in the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_31.wav control you know what I think you know what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_34.wav  apology came to mind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_35.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_36.wav yeah final thoughts on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_37.wav all that qualified to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/45/StutterTalk_45_38.wav and he said I just went to Subway
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_0.wav  again so what advice do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_1.wav  open stutters and I don't know what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_2.wav  I'd buy them a great deal I did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_3.wav  into treatment I mean is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_4.wav  as a young adults I would have taken it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_5.wav  at this point I don't think I take it because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_6.wav well I have two young children

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_7.wav I get to live my life and do stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_9.wav  I did do truly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_10.wav Colonel finally used clinical practice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_11.wav  in those days wanted kids

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_12.wav  a great role model for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_13.wav Ace's civilian job I found

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_14.wav  duties
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_15.wav  moving around yes it's challenging but it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_16.wav started as a cadet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_20.wav  have any said how'd that go and so we talked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_22.wav it's a truism the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_27.wav cuz I'm someone who's always said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_31.wav  of an instance where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_32.wav  it's going to keep any stutterers out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_34.wav  I always gave it my all and someone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_35.wav  I was in four branches of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_37.wav  might not stutter when he acts I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_38.wav  I think that's absolutely true

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/46/StutterTalk_46_39.wav  cold for the first time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_0.wav  experience difficult thoughts and feelings

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_1.wav  us live life the way we want to live do the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_2.wav and from there sit with that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_3.wav  too much of an oversimplification
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_4.wav  actually and it's very different

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_6.wav  emphasis and so rather than trying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_8.wav  act treatment that we're looking for or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_12.wav  it fit and take it where you will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_14.wav  so I think that working on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_15.wav acquire a sense that it's wrong to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_17.wav  more flexible in the way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_18.wav if that's what they want to do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_20.wav  as a therapist I don't know the answer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_21.wav  living your life the way that you choose to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_27.wav  children have you is used with kids as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_28.wav  come with to be honest and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_29.wav  I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_33.wav and if I were to give your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_36.wav that's always pulling us back

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_38.wav  interesting energetic and gay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/47/StutterTalk_47_39.wav  probably going to ask about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_0.wav so much and I'm time speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_1.wav  so I guess our interest

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_2.wav changed in any way by a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_3.wav speech language and communication

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_4.wav  for the developing speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_5.wav  language system

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_6.wav  you feel about living
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_7.wav living with your stutter I would complete a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_8.wav  stuttering and so they didn't meet other people you studied
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_10.wav  help and make people feel positive what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_11.wav what about this and this might sound
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_12.wav  execution

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_13.wav ability to look at control study
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_14.wav  evidence that this could cause memory loss absolute

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_15.wav  loss absolutely not no I think this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_17.wav but I think in terms of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_18.wav I've kind of fluent mode of speaking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_20.wav  and let me know if I got this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_22.wav of engaging that network
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_23.wav  order yeah so I guess

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_25.wav  so it'd be interesting to see where that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_29.wav  yeah those are all excellent points

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_30.wav  exactly the same for the two groups
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_31.wav  it at home as you mentioned earlier

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_33.wav  as a stuttering intervention in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_34.wav  isolation from anything

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_37.wav  gave a sense he would like them to have the best
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/48/StutterTalk_48_38.wav  transcranial direct current stimulation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_0.wav  in the sense that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_1.wav like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_2.wav to help someone with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_3.wav  life to achieve

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_4.wav  head most of the time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_5.wav and then at some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_7.wav you know then you're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_8.wav that introduces this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_9.wav insane other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_10.wav my mom said something about having kids the other day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_11.wav  so much that was like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_12.wav  yeah there was some cute off

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_14.wav  like almost never
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_15.wav  cuz I lived in a new place

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_16.wav with my to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_17.wav  yeah I mean there's definitely a thing on the show

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_18.wav and talking about how hard stuttering is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_20.wav kind of like separated into

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_22.wav  I don't and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_25.wav  suddenly felt myself like I don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_26.wav  I'm just reiterating that people are still
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_28.wav  it's I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_29.wav there has been a lot of periods
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_30.wav  how you can get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_31.wav you are very ashamed of it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_32.wav I kind of just thought that makes sense

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_33.wav everyday but I do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_34.wav  it takes a lot out of you to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_36.wav  I don't feel proud that I like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/49/StutterTalk_49_38.wav  is you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_1.wav and then at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_2.wav  the congregation I'm speaking to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_3.wav  there's something really great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_5.wav my last two sentences which

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_6.wav which I knew would probably have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_7.wav  out so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_10.wav  manage but I still to this day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_12.wav I'm sure people who don't study

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_13.wav it seems to me like we as people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_14.wav  been doing stutter talk so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_15.wav  failure in those situations that we sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_16.wav ting happened we all had our speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_17.wav because by the way it City Hall
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_19.wav all what we were talking about it was like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_20.wav but it was a really good experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_22.wav and where's the inclusive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_24.wav  maybe are a little bit more subtle that aren't really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_25.wav  minutes as did everyone else and it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_26.wav  if this person is getting extra time then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_28.wav  said was a person who started I think I should be allowed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_29.wav  just kind of bumbling around
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_30.wav  is where's the cutoff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_31.wav  or again I'm using the time because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_32.wav  is not weird it didn't feel

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_33.wav doing something to help me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_34.wav  stuttering it's not very easy at first but you do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_35.wav  and in my experience certainly personally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/50/StutterTalk_50_38.wav  I was speaking to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_0.wav right that's correct great so there's this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_1.wav that bring us together

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_3.wav  either too rapid or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_4.wav  because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_6.wav and of course we have a keynote panel on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_9.wav  so I'm very much looking forward to that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_12.wav  what I'm looking forward to as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_14.wav  see the value of 3

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_15.wav  because there's just so much oh yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_18.wav  the way the Congress is set up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_20.wav 480 posters each day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_21.wav are with Doctor Charlie Adams

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_22.wav  city Cultural Exchange Center
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_24.wav  going to talk about that one but I will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_25.wav  so it looks like Saturday
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_26.wav take part in a camono experience

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_27.wav which
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_28.wav  of healing or bases of healing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_29.wav  details will be on the website
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_30.wav  intent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_33.wav this is not designed to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_34.wav  about the joint World Congress

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_35.wav  that sounds terrific
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_37.wav  that way fantastic so when we get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/51/StutterTalk_51_38.wav on episode 644 will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_0.wav that is a very fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_1.wav  Consult
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_2.wav consultations per week

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_3.wav  communicators and there are people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_4.wav but there is a lot of communication but there is a lot of communication
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_5.wav  more acceptance and we hope that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_6.wav but clients who come to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_8.wav awesome so Katie

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_10.wav  per day where the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_11.wav we needed a name and we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_12.wav discussing that topic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_13.wav  sort of took that and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_16.wav home work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_17.wav we view those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_19.wav how the voice works
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_20.wav tensive and intermortem

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_21.wav  for adults
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_22.wav people may choose to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_23.wav  start and intensive since I went through
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_24.wav  Everyone I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_25.wav  maybe has gone to a couple of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_26.wav conferences or has gone to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_28.wav opportunity to bounce
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_29.wav  can be kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_31.wav  they've been through
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_32.wav  has a focus

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_33.wav where you might be spending like an hour or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_34.wav  studying under Mann-Rotter and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_36.wav  kind of drawing on all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_37.wav  all of those things helped me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_38.wav  but I've gotten that a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/52/StutterTalk_52_39.wav  enough that it has been something

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_0.wav  finding that you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_1.wav what we consider stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_3.wav  that the experience of stuttering is about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_4.wav people famous people have even written if I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_5.wav fluent inside that they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_6.wav  and as parents we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_8.wav stutteringcenter.org and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_9.wav org and Seth let me ask you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_10.wav and I don't agree with that set doesn't agree with that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_13.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_14.wav experience stuttering is actually like so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_15.wav  cuz it will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_17.wav emphasetic I think is a very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_18.wav and speech pathologist

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_19.wav  in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_20.wav asking people stutter it's been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_21.wav physically and emotionally it dates
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_23.wav you're still somewhat prevalent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_25.wav  and they're very comfortable
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_26.wav  that tells us something to write

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_27.wav  that we is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_28.wav understanding

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_29.wav  have a better understanding of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_31.wav  of the vast majority of research

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_32.wav  who's that don't participate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_33.wav in self-help or support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_34.wav got my refinding with this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_37.wav  is reaching those people who aren't typically

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_38.wav  aren't already commonly represented in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/53/StutterTalk_53_39.wav  people living with this condition

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_0.wav  little brother and the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_1.wav support groups is such that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_2.wav  like and anything that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_3.wav  I think of it too I love it think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_8.wav  of cuz I really am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_9.wav  it does kind of make you feel

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_11.wav  someone instagram me from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_12.wav  being so open and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_13.wav  about stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_16.wav  with someone who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_17.wav and when that happens except
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_18.wav measure eyes at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_19.wav  for me it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_20.wav someone asked me if I was drunk and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_22.wav  what and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_23.wav  like I don't know it wasn't for me I liked being

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_24.wav feel the dude anyway
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_25.wav  and it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_26.wav which you mentioned you said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_27.wav letting somebody know hey

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_28.wav  share with me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_29.wav  a lot of people are not comfortable with I don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_30.wav and then I kind of thought wall
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_31.wav  or I think they kind of picked up on it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_32.wav  if it's like the first thing it's like almost like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_34.wav  yeah I think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_35.wav  intrigued and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_36.wav  every person's way that they're going to advertise

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_37.wav  to bring back with you you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_38.wav  story it speaks more than

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/54/StutterTalk_54_39.wav it like just make
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_0.wav I am carry and Rooker at my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_3.wav  I'm not sure fluency isn't really something that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_4.wav  line become mature it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_6.wav if that's too long is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_8.wav  might be stuttering come to a health

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_9.wav start offering services
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_10.wav but if the parent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_11.wav  the parents
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_13.wav elit can program and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_14.wav which approach to take although
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_15.wav oh yes oh my goodness

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_16.wav that was a time I was trained and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_17.wav and I would think hmm you know that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_18.wav  early intervention is crucial
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_19.wav  by and watch their child struggle

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_20.wav  us 70 years ago
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_21.wav if a child is for example struggling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_22.wav and he said no you trot me out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_25.wav and also a parental rating

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_26.wav  children in everyday situations
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_27.wav and I will talk about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_28.wav  that will be a struggle yeah so yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_29.wav  in which you do that is well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_31.wav  I've actually called
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_32.wav  to your clinician who's going to help me she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_33.wav in rocker down in the Netherlands
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_34.wav I think what you really giving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_35.wav  amazing results and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_36.wav the children whose data were more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_37.wav and the analogy I use is these
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_38.wav if you take away the burden

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/55/StutterTalk_55_39.wav I want to say you're a highly intelligent mature
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_0.wav  today we talk about the physical

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_1.wav  that we see in the disorder it's also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_4.wav  absolutely everything

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_5.wav  and behavioral aspect of startling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_6.wav  using to study the brain

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_9.wav  physical aspect if yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_12.wav I think is a common case

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_15.wav  yeah dr.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_18.wav  how many research has

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_23.wav  contributing to the research yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_26.wav I think that we're going to find dynamics

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_27.wav type of study though because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_28.wav so we're collecting the data right now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_33.wav for us to Taylor any treatment to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_35.wav  at because of a gene mutation or whatever I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/56/StutterTalk_56_39.wav underpinnings of developmental stuttering it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_1.wav the same

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_4.wav for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_5.wav all our task

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_7.wav but if you have a did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_8.wav  include both

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_11.wav those people are very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_12.wav  because I talk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_13.wav you know in America you get
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_16.wav it might be true that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_17.wav  that was when I was 16
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_18.wav like out of control my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_19.wav disclose my I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_21.wav  surprising but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_22.wav why I started or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_23.wav  yeah I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_24.wav I don't think of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_26.wav  I mean that was not fully

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_29.wav  baby
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_30.wav  sf is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_31.wav they are where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_32.wav  I have to be ch-ch-challenged

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_33.wav so overall they have a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_36.wav right after that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_37.wav  or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/57/StutterTalk_57_38.wav  during

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/58/StutterTalk_58_2.wav yes well that's right I started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/58/StutterTalk_58_3.wav  at nine because the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/58/StutterTalk_58_5.wav  what I actually did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/58/StutterTalk_58_10.wav  I also have the feeling that it's kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/58/StutterTalk_58_12.wav  have 5000 people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/58/StutterTalk_58_32.wav  trouble you say that is I mean it's a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/58/StutterTalk_58_37.wav  welcome John thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/58/StutterTalk_58_38.wav thank you Tom thank you yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_0.wav  still open if
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_1.wav that we're producing so very exciting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_2.wav  so it will start off by
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_4.wav  I'm collaborating with Stutter talk to bring

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_5.wav  what we want to do you know beyond
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_6.wav  it can get lonely it can get very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_7.wav I don't know what the word is for it but it's nice to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_8.wav I'm pleasantly surprised

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_9.wav  comes with dr. Bernstein rattner there's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_15.wav  speech pathologist or stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_18.wav  this group really do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_19.wav I just want to say that means a lot because of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_20.wav are more generalizable to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_21.wav we got it sorry first I'll explain what we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_22.wav  and not any other communication disorder.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_23.wav  that's a great question that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_24.wav drew me to that specific area
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_25.wav I self a clinician

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_26.wav priority in the field
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_28.wav you know so I'm going to keep

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_29.wav a speech pathologist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_30.wav  you know life is certainly always better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_32.wav  that is sets primary research area
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_33.wav  and facilitate that conversation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_34.wav  researchers who are informing the clinical
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_35.wav  it's really important for us to be able

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_36.wav  that when you're really in it might help to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_38.wav is going on right now and it's really awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/59/StutterTalk_59_39.wav result looking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_0.wav  film about stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_1.wav that's a hundred percent correct he has like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_2.wav  and I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_3.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_4.wav  at a certain dimension to my life that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_5.wav  you on behalf
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_7.wav  John again hire a thousand thank yous to you I really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_8.wav it so when gale was talking about the emotional
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_9.wav John Gomez works as a speech pathologist

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_10.wav well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_11.wav  for and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_13.wav you probably a lack of sleep
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_14.wav  you I be facing in your life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_15.wav  not much of a social life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_17.wav and again not to diminish the other words that we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_22.wav  we just they didn't understand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_23.wav  with him and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_24.wav the film the crux of the film is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_25.wav like you know hey Gomez he's like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_26.wav he's like you're in speech pathology right now right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_27.wav  interview him and we were always going to talk about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_28.wav you know read it and I'm gonna
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_30.wav  all right cuz we're not dealing with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_31.wav  is one of the most apropos things because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_32.wav so I had this is the first class I had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_33.wav couple weeks ago teaching again I had a real
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_34.wav  interviewing people it took me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_35.wav they're thinking what can I do to help
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_36.wav  film and the learning that you've done

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_37.wav  through the process that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_38.wav  absolute part on your students

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/60/StutterTalk_60_39.wav he asked me to go out and shoot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_0.wav even in the presence of stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_1.wav  a caterpillar crawling on the ground similar
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_2.wav  similarly many people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_3.wav  In fact my friend the founder and host
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_4.wav  but largely because of it and you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_6.wav  as you are in mind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_7.wav but challenge is not in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_8.wav so challenge can be a good thing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_9.wav it is that determination

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_10.wav  that was a great word but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_11.wav you are correct yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_13.wav not only do we gain understanding
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_15.wav so the impact of stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_16.wav  potential of each human being we need
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_17.wav  and since our relationships extend far

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_18.wav  says out of the thousands of characteristic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_19.wav instead of saying I'm stuttering terribly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_20.wav  with increased freedom after
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_21.wav  feel better and function better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_22.wav  focuses on what is not normal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_23.wav the magic sauce is designed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_24.wav this is exactly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_25.wav  that I was a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_28.wav doctor's and some think that it's their job to tell me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_29.wav  and others and the ones that I'm particularly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_30.wav  in this kind of work of helping others
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_31.wav  form so I know many such people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_32.wav  while stutter or not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_34.wav  part of what we do not a side act you've worked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_35.wav  doing being told to do an exercise
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_36.wav and each person may have done it somewhat differently

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_37.wav that they need permission
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_38.wav and how you set up your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/61/StutterTalk_61_39.wav  first feeling good about yourself and able
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_0.wav weather near or far

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_2.wav  through and it gives
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_5.wav  parents

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_6.wav  at the departure today just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_8.wav  thanks so much for joining me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_9.wav  two days ago
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_10.wav  nurturing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_11.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_12.wav  differs from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_14.wav  we can also allow you know that extra
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_15.wav I'm feeling very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_19.wav and I want every child to have that opportunity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_20.wav we couldn't do a two week camp

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_21.wav who cares so deeply about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_24.wav  throwing up as someone who's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_27.wav  West Coast
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_32.wav  final thoughts I love

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_33.wav I love everything that you just said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_36.wav  the weekend that we've just gotten

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/62/StutterTalk_62_37.wav  and I really have to say thank you to the team

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_0.wav  Thank you so much for watching and I'll see you next time.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_2.wav  upstairs and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_3.wav  past open door
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_7.wav  wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_9.wav our whole class was in it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_11.wav what was going on then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_14.wav speaking of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_15.wav and what do they want to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_20.wav Molly Davis is an 18 year old
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_21.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_26.wav  and I'm funny
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_27.wav tite and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_28.wav and like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_29.wav  and it hurt like a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_30.wav yeah wow that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_31.wav did it have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_33.wav  that I've been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_34.wav like one of the most

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_37.wav cut and control it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_39.wav that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_44.wav your voice was silenced
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_45.wav  stuff it's like I'm trying to be her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_48.wav  make clear not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_50.wav  Plenty of a positive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_52.wav cause like I'm not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_54.wav what was used to make a decision

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_55.wav  about what you had to say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_59.wav  can't control it and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_62.wav number one for being so brave to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_63.wav  Sandy Hook shooting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_65.wav  stop to think about that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_66.wav  me like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_70.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_71.wav  So something else

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_74.wav  smaller than my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_75.wav  smaller than my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_78.wav  hide in our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_80.wav people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_81.wav which I think has helped like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_82.wav happened and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_85.wav help me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_86.wav  just utter and all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_87.wav wow so for some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_88.wav  Nervous and to just like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_90.wav and that helped me like tremendously
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_92.wav yeah everyone's nervous

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_93.wav  something to your thing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_94.wav knowing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_95.wav  how did that come to be I mean like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_98.wav after what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_99.wav  stuff like this shouldn't be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_101.wav what happened in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_103.wav  because I thought
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_104.wav  of it probably has I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_106.wav have you met other people who said her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_107.wav  I haven't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_109.wav person who also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_110.wav  completely understand like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_112.wav  code being
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_114.wav  our support thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_115.wav  Yeah absolutely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_116.wav now I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_118.wav before shooting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_119.wav  happened and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_120.wav the public side of politics and like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_123.wav find like a way to like for this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_124.wav  just like the side of politics it's more like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_125.wav public appearances and like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_126.wav  actually being a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_128.wav  more geared in that direction

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_131.wav  inspired by
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_132.wav do you see

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_134.wav  more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_138.wav  events that have happened

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_139.wav thank you yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_140.wav  for today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_141.wav  but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_142.wav  I call

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_149.wav where he talked about how it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_155.wav  close to home for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_157.wav so the silence
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_158.wav  the government to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_159.wav stand up for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_160.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_161.wav the silence of the government to stand up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_164.wav  I am a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_166.wav  agree with that whole
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_168.wav that think care about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_171.wav  talk yourself out of things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_172.wav  wow yeah so not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/63/StutterTalk_63_173.wav Texbox and start my math
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_0.wav second with me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_1.wav it is a lot of what we've added
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_3.wav we try to cover it up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_4.wav  it up we tried to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_5.wav  fight against it the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_6.wav  the five things were that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_7.wav  you talked about rap

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_8.wav uttering but actually the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_9.wav  the more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_10.wav authentically we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_11.wav  childlike

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_12.wav like the more innocent that you're suffering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_16.wav way of forward-moving communication

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_17.wav  and so that helps
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_19.wav  and I think I'll

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_20.wav  stuttering is such a loaded word
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_22.wav  much so I use it all the time and therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_23.wav  it's always okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_24.wav  it's always okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_25.wav  taking the time to join
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_26.wav  join me it's been a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_27.wav Jadrin has
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_38.wav a lot of the ways we trap ourselves

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_42.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_43.wav those techniques

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_44.wav work sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_45.wav  times and so if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_46.wav  if I'm a person who stutters why
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_47.wav  and my technique has not worked I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_48.wav I really have no option right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_49.wav I'm stuck restarting a phrase and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_50.wav and I don't know what to do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_51.wav  if I'm a clinician why is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_52.wav techniques can be a trap is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_53.wav I've taught my student

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_54.wav  ways of speaking I think help them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_55.wav  with me today I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_56.wav and they seem to do them one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_57.wav wonderfully in the therapy room

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_58.wav if I'm a parent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_59.wav  what do I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_60.wav  stuck other than
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_64.wav that's not really what we talked about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_67.wav it's almost how to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_69.wav  know I think one thing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_70.wav you said we're working
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_74.wav but that's not what we're saying that's it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_75.wav  I'm wondering a port
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_78.wav  I think a big

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_81.wav in that moment where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_84.wav in that moment you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_85.wav you have lost
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_86.wav the volitional movement of your speech right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_87.wav  pattern
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_88.wav and if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_89.wav  if we're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_90.wav we're ever going to break out of that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_91.wav  SLP is today and I wanted
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_92.wav  and I want to toss this out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_95.wav  start saying I right say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_96.wav  saying I'm it's you saying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_97.wav and then you're back in control
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_98.wav  that we want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_99.wav you want to be showing our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_100.wav  there's started runs away did they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_101.wav  that they can grab that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_103.wav  so you highlighted Chris the word

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_104.wav  very empowering to everybody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_106.wav  was whether

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_107.wav weather shuddering is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_109.wav and I certainly think it can be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_112.wav it can be fun can be enjoyed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_114.wav  at their

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_116.wav 5
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_118.wav  principles of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_120.wav  that oh yeah I think are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_121.wav really good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_122.wav  I was somewhat
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_123.wav  Campbell and their work at Camp

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_125.wav  learned about the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_126.wav five things that great communicators

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_127.wav  and practitioner of act
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_130.wav  I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_133.wav  hold a what is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_136.wav  we seem to very strongly say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_137.wav stuttering is okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_138.wav and then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_139.wav we hear sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_140.wav  that raised the point of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_142.wav  you very much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_143.wav and is there a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_144.wav that Stuttering is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_146.wav  what you say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_147.wav and the reason
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_148.wav I say is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_149.wav  using
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_150.wav a big part of what I was talking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_151.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_154.wav  us from childhood

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_155.wav  like we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_156.wav came out of the room free

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_157.wav but that's not like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_158.wav a natural stuttering pattern and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_159.wav that there's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_161.wav way to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_162.wav  throwing it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_163.wav  bad but it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_164.wav and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_165.wav in terms of my starting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_166.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_167.wav  SLP's in the room and the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_168.wav and the parents is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_169.wav I'm never trying not to stop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_170.wav I'm never trying to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_171.wav  I think it's a bit of a sluant

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_174.wav  can to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_176.wav  for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_177.wav whatever reason
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_178.wav the more openly I display my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_179.wav  happens
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_180.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_183.wav  better my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_184.wav my experiences have been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_185.wav  really frustrating about stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_186.wav  whether you're the person doing the stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_187.wav the more I let myself stutter the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_188.wav  the less it happens

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_190.wav  to cuz you can't go
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_191.wav going to it with that goal in mind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_192.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_193.wav  I don't think my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_194.wav  from you know it's just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_197.wav speaking becomes more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_198.wav natural and I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_200.wav  there's less

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_202.wav  disorder
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_203.wav  it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_204.wav is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/64/StutterTalk_64_205.wav feeling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_0.wav  Ian's vision and Ian is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_1.wav  important for them to know before we sign off

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_2.wav  we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_4.wav  not alone that they have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_5.wav or saying we don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_6.wav when one of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_7.wav osing candidates
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_8.wav call into question his ability

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_10.wav  onto this very nice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_11.wav I want for us to talk today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_12.wav  stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_13.wav in early 2018

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_14.wav  school children
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_17.wav  talks to their

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_18.wav to their students so during
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_19.wav it appears that you were the one who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_20.wav offer that to the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_24.wav  we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_27.wav  a background of a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_29.wav  each other positively

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_30.wav cause teachers of course have such a great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_31.wav  times and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_32.wav  perhaps it is a dropping ocean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_34.wav  wonderful that you've been able to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/65/StutterTalk_65_38.wav so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_1.wav Friends is a community

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_3.wav there are people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_6.wav it was so inspiring

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_8.wav I remember
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_10.wav and they're always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_11.wav and it's hard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_13.wav  hiding

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_15.wav can't hear the stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_16.wav the collective like desire

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_17.wav enjoyable and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_18.wav  I guess

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_19.wav open up and admit that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_20.wav through this process of change

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_21.wav  coming rather than changing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_25.wav we were talking with our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_30.wav shopping mall and we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_31.wav we approach people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_32.wav proactivity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_34.wav for us to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_37.wav and see
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/66/StutterTalk_66_39.wav  me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_0.wav what is the change that you actually want
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_1.wav from within and there may not be a change

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_2.wav  about the idea of the science room
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_4.wav beast actually able to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_5.wav  to is that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_7.wav  it's not able to grow off of just the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_12.wav  yeah and you had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_13.wav  vulnerability and acceptance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_14.wav what types of things a person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_16.wav so let's actually get started right there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_20.wav  in the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_22.wav  just don't want them to have that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_23.wav commited over
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_24.wav be able to look at that and they out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_25.wav  analogy like that bottom part
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_26.wav  kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_32.wav the you know the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_34.wav  you've been involved

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/67/StutterTalk_67_35.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_0.wav yeah of course so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_1.wav  this thank you for all that you're doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_3.wav yeah it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_4.wav that was great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_5.wav  with the staff and that would be awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_6.wav  yeah that would be awesome and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_7.wav  at your lines upon and how as soon as my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_8.wav  is my adorable child who sleep at the moment
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_9.wav  share with our listeners

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_12.wav I would just like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_14.wav  I think over the past

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_15.wav I'll say 45 is but even
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_16.wav  years as well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_17.wav yes if anyone you kind of stuttered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_18.wav  sources

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_19.wav you know and yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_20.wav  if you want to look at it to you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_22.wav  as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_23.wav yeah just kind of keep on going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_24.wav  calls all the time for something but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_27.wav you love your who support your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_28.wav  yeah and for a lot of people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_30.wav  it just opens up the door

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_31.wav to life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_33.wav  cheers thank you it's great to be on the show

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_38.wav  that's cool as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_40.wav that may have been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_41.wav  given the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_42.wav given the licorice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_45.wav  very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_49.wav  not work for them you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_50.wav  you know I'm supposed to going through
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_52.wav  so I'm not really del

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_53.wav you know so can I say this to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_55.wav so you know so yes what happens

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_56.wav where they are yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_57.wav that will never say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_58.wav  fine
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_59.wav get they you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_60.wav  children who stutter I remember when I stood
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_64.wav  in America of his camp

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_67.wav  know that you're not on your own
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_68.wav when we did our first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_69.wav what happened you know just come as you are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_70.wav  and enjoy and have fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_73.wav  to start you in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_74.wav which is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_75.wav  that no speech therapy can do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_77.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_78.wav did not interrupt you near and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_79.wav and there is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_82.wav influence the work that you're doing now yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_84.wav  yeah I want to give kids

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_85.wav that option I want to give kids
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_86.wav  of me you know I can remember

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_88.wav me and other people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_89.wav  you have an old like we keep on saying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_90.wav to have those people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_91.wav who you can talk to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_92.wav which is moving away from a lot of data
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_93.wav  you can Facebook and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_95.wav want to give the option to kids
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_96.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_99.wav but it never cut and done
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_101.wav  and so yeah the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_102.wav  yeah like you put it like a group of people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_103.wav  you had any pushback starting to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_104.wav get say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_105.wav  that is going to be a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_106.wav the difficult kind of process
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_109.wav  it wasn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_111.wav contact with again so you know if there is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_112.wav I think what we're introducing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_114.wav  yeah that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_115.wav been kind of tricky I think it's been kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_116.wav  kind of trick you for a lot of the family
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_117.wav it's quite cool

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_123.wav Stadiums all around Australia
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_124.wav  Tom Hall's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_125.wav  ask film video about the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_126.wav the basic question yeah on what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_127.wav  awareness of what we're trying to do here as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_130.wav  I also got 35 and total

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_131.wav no so that was being
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_132.wav  yeah that's been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_133.wav  vocal or you know to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_134.wav shout stuttering out loud

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_135.wav  Australia can you speak a little more to that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_137.wav  really seems to be shifting the tides

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_138.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_139.wav and I hope so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_141.wav you know they kind of funny just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_142.wav and in a mall

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_143.wav  you have the more it sets in Manor as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_147.wav then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_148.wav you know and I'll ask the question why
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_150.wav  start to bring about change

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_151.wav fingers cross hopefully well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_154.wav speaking of spreading awareness can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_155.wav  there's like a program where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_156.wav which was created in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_159.wav my case specific page
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_160.wav for I said yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_161.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_164.wav  you was at your country with any

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_165.wav any tips
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_167.wav yeah I came away from that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_168.wav  of that confidence
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_169.wav you know just to go out there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_170.wav  you know hopefully
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_174.wav  something meaningful like spreading awareness

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_175.wav yeah cuz I think it's like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_176.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_177.wav the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_178.wav  yeah I think it's like what we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_180.wav  so yeah it's no different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_185.wav  congratulations again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_187.wav  we've only just started so yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_188.wav and we're excited for what's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_189.wav I'd love to learn more about that yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_190.wav yes sure so the mice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_191.wav  piece of art and that you showcase
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_192.wav but the kind of premises is that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_193.wav  copy so if I was into a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_194.wav a superhero and I did a sea

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_195.wav we're asking about kids if you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_196.wav  yeah if we are young person who says

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_197.wav the kind of time is touching so when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_198.wav  you try to extract from that is like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_199.wav what are the elements from that sea
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_200.wav we did a short play about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_201.wav  scuba diving
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_204.wav and then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_208.wav  you want to stand up on stage and just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_210.wav then that's cool as well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_211.wav  by yeah I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_212.wav  in this process every you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_213.wav  every child is different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_214.wav  to get on stage could be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_215.wav it could be life-changing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_216.wav  expression and creativity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_217.wav wow this is all such wonderful work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_218.wav  you know it's just focuses on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/68/StutterTalk_68_219.wav  you know that moment of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_1.wav  all eugenics

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_2.wav the gene for the disability
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_3.wav  politically we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_4.wav we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_5.wav right and so it looks like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_6.wav people who have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_7.wav power it's been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_9.wav we are worth
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_10.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_11.wav current of accept me as I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_12.wav in the culture

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_13.wav well if there can be a death game why can't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_15.wav I remember just in the last

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_17.wav and maybe it's cuz I had Amazon's essay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_18.wav  inviting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_19.wav if it can just be about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_20.wav run out of air and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_21.wav  to be people who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_22.wav  So

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_23.wav  sound like me at my most disfluent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_24.wav  on society to accommodate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_26.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_27.wav have any different sexuality

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_30.wav  notion of challenging clock time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_31.wav I am speaking to somebody who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_32.wav I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_33.wav are political capacity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_34.wav until we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_35.wav discrimination and all I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_37.wav but if we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_38.wav is actively being done

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/69/StutterTalk_69_39.wav behavior patterns
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_0.wav a lot of these

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_1.wav and said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_2.wav that was awful like you did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_3.wav I just didn't do good work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_4.wav as I mentioned before

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_7.wav kids so they can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_8.wav  successful somebody is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_10.wav  old 7 years old 8 years old
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_11.wav more publicly it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_13.wav circle navigate around this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_14.wav and do truthful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_15.wav and I haven't found it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_16.wav live your own truth

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_18.wav  rewarded
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_20.wav  in the media or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_21.wav  present
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_23.wav was poked fun of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_24.wav  mentioned it wasn't talked about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_27.wav it's just not there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_28.wav going into this business
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_29.wav is a truthful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_31.wav with in our own
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_32.wav on house

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_33.wav these are actors
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_34.wav like sometimes a lot of these

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_35.wav  stage
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_36.wav upon the idea that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_37.wav  bikes boasting that vulnerability
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_38.wav  absolutely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/70/StutterTalk_70_39.wav hopefully stutter and people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_0.wav how okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_1.wav  I strongly recommend
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_2.wav I strongly recommend

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_3.wav health self-care step
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_4.wav  Instagram

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_5.wav  can remember
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_6.wav just going on my stuttering journey

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_7.wav both started this off
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_8.wav you awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_9.wav  right Peter I did and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_10.wav and I wanted to highlight that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_11.wav has been hugely important to me so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_12.wav girl friend or boyfriend or whatever it's a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_13.wav  of talking and to be clear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_14.wav the next one that comes to mind is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_15.wav  the lives are now on hold and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_17.wav this as a time for things to be on hold

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_19.wav that's a great question Peter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_20.wav  suburban I bring it up because in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_21.wav  talking more with your neighbors and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_22.wav  friendly to everybody being

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_23.wav included
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_24.wav fantastic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_25.wav and so it was the first time I thought oh
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_26.wav to your point Peter although

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_27.wav  where I am do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_29.wav I do know that the NSA

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_30.wav  meaning that we had a opportunity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_31.wav  a opportunity for speech language

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_33.wav  service anyway so we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_35.wav  that we would have to separate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_37.wav  Peter wow that is so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_38.wav and that'll be a great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/71/StutterTalk_71_39.wav  journey was to work on my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_4.wav somewhat embrace this time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_5.wav  as part of our overall
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_6.wav  experience

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_7.wav  important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_8.wav I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_9.wav we have a really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_10.wav  it's a really special time right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_11.wav  right now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_12.wav I wouldn't encourage people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_13.wav  stutter obviously to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_15.wav  to kind of be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_17.wav be willing to listen
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_18.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_19.wav  surround myself with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_20.wav  with healthy people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_21.wav and that being said I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_22.wav  hope that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_24.wav  that's a great thought
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_25.wav  much for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_28.wav  what do you have to say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_29.wav that's the stuff we all know but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_30.wav but to me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_31.wav  healthy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_33.wav our experience is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_36.wav  I really focus on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_38.wav  our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_39.wav how do I say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_40.wav  our issues
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_43.wav  or whatever that looks like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_44.wav with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_48.wav  of that question because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_49.wav  it really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_50.wav  gives me an opportunity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_51.wav heal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_52.wav and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_53.wav  I'll say that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_54.wav  treatment program

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_56.wav  by checking out and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_57.wav and I did that with alcohol I did that with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_58.wav  the way that I was but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_59.wav but what that brings me to is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_61.wav news who is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_68.wav who we are and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_69.wav who were meant to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_71.wav we are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_73.wav  how many of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_74.wav some of the things that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_76.wav  really help you with that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_77.wav getting in touch with ourselves

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_79.wav during this time when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_80.wav  as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_81.wav  in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_82.wav shame

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_83.wav of anything and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_85.wav  stuttering support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_86.wav nice to also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_88.wav and this is a different time that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_90.wav  to share our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_91.wav  the most moving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_92.wav  memories that I had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_95.wav  other people and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_96.wav  I you know that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_97.wav  get into a flow state

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_99.wav  like just buzzword
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_100.wav but what it means is that we get to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_101.wav  political statement
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_103.wav then by the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_104.wav by the fourth Myler show I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_105.wav  times we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_107.wav we have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_108.wav what we've

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_110.wav  is how to different point in their
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_111.wav  journey I'm straight

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_112.wav as were in this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_114.wav something ever honestly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_115.wav  bit better prepared
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_117.wav  experience that's going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_118.wav  going on right now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_119.wav  I think a lot of us are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_120.wav it's interesting as I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_122.wav engineer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_124.wav  basis the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_126.wav tuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_128.wav  to feel like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_129.wav hey

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_130.wav it's all great stuff
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_131.wav  working on shuttering and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_132.wav mean occasion
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_133.wav and how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_134.wav  much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_135.wav transferred to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_136.wav whatever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_137.wav situation may be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_138.wav we consider
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_139.wav what do you think Sam

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_141.wav  I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_142.wav taking in everything you're saying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_143.wav  really marveling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_144.wav  at how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_146.wav  to let go of this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_147.wav idea that it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_148.wav  go back to is that in my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_149.wav  that in my work

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_150.wav my work with people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_152.wav  really benefit from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_153.wav  from sharing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_154.wav  of stuttering is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_156.wav  on the backburner when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_157.wav when the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_158.wav so I really wanted to talk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_166.wav sharing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_167.wav juries
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_168.wav  I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_169.wav  country but it's actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_170.wav word this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_171.wav  this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_172.wav challenge that we're going through right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_174.wav  community and perhaps
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_175.wav  a lot of healing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_176.wav  has a community perhaps
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_177.wav  Sam about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_178.wav healthy things that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_179.wav  as a nation perhaps even as a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_180.wav  world
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_185.wav  of fear my voice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_186.wav  comes from a different place
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_191.wav uttering and with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_192.wav with ourselves
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_193.wav  really awesome thought

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_196.wav thank you so much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_197.wav  we may have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_198.wav have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_199.wav I'm trying to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/72/StutterTalk_72_200.wav make
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_0.wav so if you get those symptoms

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_2.wav  you it was hard to get a test
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_3.wav but so we were starting to sort of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_4.wav  be on the lookout for the virus and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_5.wav  her a lot of folks I would

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_6.wav  in a few days we had maybe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_7.wav  days from what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_8.wav  of the COVID-19 pandemic before
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_9.wav  before we begin I wanted knowledge that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_10.wav and to see that rapid escalation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_11.wav  hospitals are doing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_13.wav  over the past
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_15.wav as best that they can our hospital is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_16.wav  thanks for having me Haye
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_17.wav  this I told my friend this other night

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_19.wav  rolling in and we had two patients
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_20.wav  cardiac arrest and our I see you with this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_25.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_27.wav the risk for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_28.wav you know this virus is very contagious
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_29.wav  they won't have access to health care so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_30.wav can respond to people's needs
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_31.wav some way shape or form yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_33.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_35.wav  in terms of supporting health care

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_36.wav to yourself yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/73/StutterTalk_73_38.wav and the first two weeks

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_0.wav for inviting me back on stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_1.wav  improved

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_3.wav  side but from others as well and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_4.wav  Got plans for a multi-center study

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_5.wav  are still exploratory and if
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_7.wav  about to test it in a larger group

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_8.wav  everybody can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_9.wav  all of these I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_10.wav  subjects I work closely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_11.wav  application called a lurt

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_12.wav  a parent and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_13.wav  didn't see it I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_15.wav  to submit to the FDA to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_16.wav  for people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_17.wav the response from one person was like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_20.wav  we need advocacy we need better treatment

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_21.wav  let's see
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_22.wav did was exercise yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_23.wav  can be found at we stutter.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_24.wav  kid why just we didn't have any of it no we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_26.wav and have those different tools out there if you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_27.wav  out there if you will permit me just one last

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_30.wav  community I appreciated
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_34.wav  the treatment of a tour

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_35.wav  so that's a different mechanism
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_36.wav  should not be associated with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_38.wav we've studied through
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/74/StutterTalk_74_39.wav do imaging scans and through

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_0.wav charvare and there's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_1.wav she literally fixes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_3.wav monuments you know these like Mark
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_4.wav  know I like love films

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_5.wav  started this project have kind of like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_6.wav how do you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_7.wav  born who she was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_8.wav  they're Jewish or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_9.wav if listeners want to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_10.wav  thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_11.wav yeah it's made me a lot more conscious
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_13.wav  might be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_14.wav you know I a permanent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_15.wav  there's like a better way to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_16.wav the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_17.wav  is just awesome to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_19.wav journey that I was on for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_21.wav but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_22.wav should know like what it is by now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_23.wav totally yeah you know we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_24.wav  your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_25.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_26.wav yeah you know it's interesting to kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_28.wav the Holocaust

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_30.wav when I was a kid like asking her if we could
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_31.wav go to Charv

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_32.wav  her family was rounded up in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_33.wav and when she came back

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_34.wav she and her family had ever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_35.wav  I think it's a clever lip there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_38.wav when I got to her hometown
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/75/StutterTalk_75_39.wav  sit at her Monument

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_0.wav  I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_1.wav health care workers and our mental health

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_4.wav people that have a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_6.wav and we are recording

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_7.wav  I'm not really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_12.wav  you know a car

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_14.wav  based on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_15.wav but like having an

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_16.wav  any kind of family dysfunction
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_17.wav  me is that like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_19.wav  There's just infelix
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_20.wav I just didn't feel like there was so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_22.wav  just like human nature in a way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_23.wav but in Karen's case

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_24.wav may be like six years ago
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_25.wav  guess that sort of makes sense

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_26.wav but I guess okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_27.wav I like that yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_28.wav plus editing would take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_30.wav  it she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_32.wav typical disfluid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_33.wav you know just kind of the nature of like this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_36.wav  stuff
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_37.wav uh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_38.wav and I'm working in the hospital yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/76/StutterTalk_76_39.wav and I'm just I go through as I'm sure

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_0.wav  sign up for that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_1.wav  to anyone is listening and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_2.wav  it is so true and so important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_3.wav you know physical what is it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_4.wav there are ways that we can you know be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_5.wav  you know be there for each other and support each

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_7.wav  I wasn't totally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_8.wav  Manhattan chapter is I think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_11.wav  resources as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_13.wav  key

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_19.wav  do kind of feel anxious about it or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_20.wav not feel like it's going to be as meaningful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_21.wav you really well how are you doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_22.wav  sometimes more meaningful than like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_23.wav  with really understood to like you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_28.wav  actually gave me an

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_31.wav  Poison
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_32.wav  you know share in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_33.wav  It started with me like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_34.wav tutter talk in the last

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_37.wav  it's all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_38.wav b a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/77/StutterTalk_77_39.wav  and virtual
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_1.wav  active

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_2.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_4.wav but then when I got into the business

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_5.wav you know I began to learn more from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_6.wav either participating in our research

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_9.wav  quality control the scientific
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_10.wav  it will help draw attention

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_11.wav  in their work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_12.wav  but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_13.wav  So really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_14.wav  This is almost storage disorders

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_15.wav  tend to be expensive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_17.wav  in neurological diseases

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_19.wav so why do endosomes get
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_20.wav that leads to the problem of these

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_21.wav and that idea is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_22.wav now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_25.wav  side of a female and you put
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_28.wav but you can walk and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_30.wav it's not the sort of thing but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_31.wav  using genetics or there's no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_32.wav no really good way I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_34.wav fect therapy outcomes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_36.wav  that one program okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_37.wav  then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/78/StutterTalk_78_38.wav  things like that a few
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_0.wav  mutual friend of ours

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_1.wav well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_2.wav  and see

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_4.wav that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_5.wav  you know I'm a big proponent and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_7.wav  of Cognitive or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_8.wav  I would agree with that point Chris thank

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_9.wav  with a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_10.wav personal challenges more so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_12.wav  personal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_13.wav  rendered me frozen and foggy I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_14.wav  mostly I hate it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_15.wav bumble over my broken words

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_16.wav  to close out that terrifying talk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_17.wav so in fact when I read your book and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_18.wav and I read through that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_19.wav  I think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_20.wav  I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_21.wav  possibly understand it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_23.wav  just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_24.wav Sputtering can be a lot of fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_25.wav speech therapist are intimidated
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_26.wav  for me but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_27.wav  but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_28.wav having decided to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_29.wav C6
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_31.wav  therapy where

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_33.wav  I think when somebody is able
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_35.wav reader which would probably be there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_36.wav in your book something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_37.wav  it's important to not rush the process

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_38.wav I really liked your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutterTalk/79/StutterTalk_79_39.wav  I think it's a good question
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_1.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_6.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_9.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_12.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_27.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_31.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_32.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_34.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_37.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/0/StutteringIsCool_0_39.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_6.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_8.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_10.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_12.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_14.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_29.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_35.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_36.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_37.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_38.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/1/StutteringIsCool_1_39.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_3.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_4.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_5.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_8.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_27.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_29.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_31.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_32.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_34.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_35.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/2/StutteringIsCool_2_36.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_0.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_1.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_2.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_4.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_6.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_8.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_9.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_10.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_14.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_16.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_19.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_22.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_27.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_31.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_34.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_35.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/3/StutteringIsCool_3_38.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_2.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_3.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_5.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_9.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_10.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_12.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_13.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_31.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/4/StutteringIsCool_4_38.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_0.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_1.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_2.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_3.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_4.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_8.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_9.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_10.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_15.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_19.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_22.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_28.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_31.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_33.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_37.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_38.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/5/StutteringIsCool_5_39.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_1.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_2.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_3.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_5.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_6.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_7.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_8.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_10.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_11.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_16.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_17.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_18.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_19.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_20.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_21.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_22.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_23.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_24.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_25.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_26.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_27.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_28.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_30.wav does not exist.
File /home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/StutteringIsCool/6/StutteringIsCool_6_32.wav does not exist.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_0.wav okay sure so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_8.wav and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_9.wav  I said a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_12.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_24.wav then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_31.wav you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_34.wav  11
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_36.wav  it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_39.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_45.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_46.wav  everybody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_49.wav it must have made you more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_50.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_51.wav  comfortable you're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_53.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_55.wav it helped

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_56.wav to be able to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_59.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_60.wav it's a lot of work for you to have a long
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_63.wav  something for next year

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_71.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_72.wav  somebody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_77.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_78.wav  to put on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_82.wav other like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_87.wav and it's been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_92.wav  there happen
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_105.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_109.wav  five
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_110.wav  we were all just talking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_111.wav  about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_112.wav  and our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_119.wav  people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_124.wav  Stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_128.wav  it so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_134.wav  special for yourself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_135.wav Carolina it's been so good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_141.wav hello everybody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_144.wav  they will do it every
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_147.wav and I got my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_148.wav like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_149.wav  are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_152.wav I didn't say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_156.wav  really trying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_158.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_161.wav Carol Lena

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_163.wav  steps
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_166.wav  time just stepping

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_169.wav I also started to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_172.wav ind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_185.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_186.wav when I join my other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_187.wav  church
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_193.wav  why did you get this like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_196.wav God's asking that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_197.wav Tax Ontario

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_215.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_216.wav we're an awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_218.wav what part of India did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_222.wav okay that's a very poor part

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_230.wav  couple that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_232.wav  can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_235.wav family
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_240.wav  red

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_248.wav  it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_249.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_250.wav but also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_259.wav  joy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_260.wav  like it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_264.wav  I'm about to turn

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_265.wav  30
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_268.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_270.wav  see
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_275.wav  there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_281.wav  I actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/0/WomenWhoStutter_0_282.wav  just started a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_0.wav already be up on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_1.wav  and that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_3.wav  that stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_5.wav  you know support and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_6.wav  and just talking about it and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_9.wav just talking about it just like you said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_13.wav for having me back on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_14.wav  and I wish you a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_15.wav  self but I'm more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_17.wav  your ups and downs

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_19.wav  speak up and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_21.wav  like with disabilities and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_22.wav and a lot of them they do stutter too
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_24.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_25.wav  a little bit less that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_28.wav  we used to do a lot of breathing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_29.wav  exercises
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_30.wav  excuse me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_31.wav  or you know now I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_34.wav  exercises and just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_35.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_36.wav wonder what would be really special

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_37.wav  some University
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_38.wav can we go to the clinic's or program

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_39.wav  in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_41.wav  that do you feel like you need to better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_42.wav  better your speech cuz
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_43.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_46.wav  up and down
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_47.wav  you know some days at work

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_48.wav  really bad
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_49.wav but when I'm feeling calm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_50.wav  fast
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_52.wav  that way since I was younger

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_53.wav  that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_54.wav  do they know they stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_58.wav  you know they think is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_59.wav you know it's normal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_60.wav but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_61.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_62.wav we don't talk about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_63.wav we talk about like other stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_64.wav  developmentally disabled
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_65.wav individuals that you work with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_67.wav  we very rarely run into
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_68.wav you know that many people that stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_69.wav buttering with a couple
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_70.wav even though like you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_71.wav and so it was just kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_74.wav  I stepdaughter and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_76.wav  experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_77.wav  yeah I like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_82.wav  but I don't think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_83.wav  you're working in the office and you deal with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_84.wav  people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_85.wav  that you started how do you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_86.wav do that how do you advertise
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_87.wav  I just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_88.wav  if they have any problems or you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_89.wav  or you know they cannot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_91.wav like that because I know a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_93.wav  and what I like to do in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_94.wav you know so it's good that you feel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_95.wav comfortable enough doing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_96.wav  because I've always thought that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_97.wav  that my speech was you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_98.wav  way and is because you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_101.wav  association and you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_103.wav  accepting my starting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_104.wav  and what I wanted you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_105.wav wow that whole thing just gave me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_106.wav  worried about him stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_107.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_109.wav  and when he started to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_110.wav but he doesn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_112.wav  the case to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_113.wav  you know because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_114.wav  to stay active

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_115.wav  I like to you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_116.wav  he doesn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_117.wav  so it's good but he knows I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_119.wav when he hears

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_120.wav  how does that make you feel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_121.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_122.wav  you know I think it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_123.wav you know I think it's funny when he

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_124.wav  you know and I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_125.wav  me feel good that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_126.wav  he doesn't make fun of other people because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_127.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_129.wav  have they made fun of her in a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_131.wav  can you hear me better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_132.wav  you know the house mostly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_134.wav  and I thought that I was very brave of him

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_135.wav you know to go in front of millions of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_136.wav thought that was you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_137.wav  very brave and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_138.wav  and I wish I could do something like that but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_139.wav  him doing that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_141.wav you know it made people more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_143.wav American Idol and it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_149.wav when I was younger

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_152.wav place are you at with your stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_153.wav  during Journey

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_154.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_155.wav and you're not treating the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_157.wav  tip typical of people that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_158.wav people that's daughter and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_159.wav hopefully you know this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_160.wav  for him just because he stutters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_161.wav  No
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_165.wav  I think it's a little

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_168.wav  a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_170.wav  and you know say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_171.wav  just like you know a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_172.wav  a sympathy vote you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_174.wav  me I was okay with it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_175.wav  that we know they were always bullied

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_176.wav  you know and we all have like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_177.wav  and you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_178.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_179.wav  for stuttering and some of us are still

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_180.wav working on things that we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_181.wav I loved the way that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_182.wav put that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_183.wav  one last question as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_184.wav  and he was stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_185.wav  was important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_186.wav  I need a support
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_187.wav  I think that's a good point

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_188.wav  support from your family
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_189.wav  any support from your peers you that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_190.wav  you know support from other people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_191.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_192.wav  alone and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/1/WomenWhoStutter_1_193.wav  I think I was going to therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_3.wav  in New York City
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_8.wav yeah you're showing people how it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_9.wav you're set to change lives
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_12.wav that you want to continue to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_13.wav  should do so I've
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_15.wav  trusting other people and just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_16.wav getting together and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_21.wav a national stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_23.wav to me listening to you at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_24.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_25.wav well I think this is a good note
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_32.wav  working on for almost three

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_33.wav a great job and for sharing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_34.wav  and this has been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_35.wav men who stutter our stories
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_37.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_38.wav he like you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_40.wav and that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_42.wav you know have to give to that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_43.wav Catherine and I do and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_44.wav you know that's a big part of that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_49.wav  can do so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_51.wav first of all what's the name of the play
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_52.wav the name of the play is tough cooking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_53.wav  women
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_54.wav Catherine plays

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_55.wav  of life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_56.wav  life a coach in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_57.wav  two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two two
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_58.wav Mama thinks that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_60.wav so who wrote the play
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_61.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_62.wav  I can't read
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_63.wav like elsewhere and this is what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_65.wav  us and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_66.wav  he went and found

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_67.wav  play oh okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_68.wav no is this play was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_69.wav chosen with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_70.wav with people who stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_71.wav  to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_72.wav  substitute

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_73.wav  she chose
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_74.wav  comedy because it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_75.wav  I'm not sure if he's with you cats
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_76.wav and recently I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_77.wav telling me that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_79.wav she told the audience that you were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_80.wav people stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_82.wav all already knew

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_83.wav  so during
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_84.wav  yes I did stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_85.wav I started you know not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_88.wav  school-based speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_89.wav and language pathologist with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_92.wav  so I didn't stutter in the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_93.wav dutter you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_95.wav  for the first time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_96.wav made my acting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_97.wav  is there merit to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_98.wav  what you just said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_100.wav but it is true of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_103.wav actually on stage
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_104.wav the play

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_105.wav  well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_106.wav  well on the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_107.wav on the first night I thought we did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_110.wav  was it was in the beginning of the play so for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_111.wav  so for the first 23 pages
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_115.wav  No, how was the play

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_116.wav  our churches and we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_119.wav  that was so great Pam

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_121.wav but I wanted them to have fun
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_123.wav  Laughing at your stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_126.wav but also they were people that knew us
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_127.wav you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_128.wav don't laugh in front of other people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_129.wav  her formants yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_130.wav yes course
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_131.wav the proceeds go to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_133.wav what became of the money that people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_134.wav  to well it's paid

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_136.wav  such
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_137.wav busy lives and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_138.wav  us in the beginning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_141.wav and then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_142.wav I believe for the theater
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_143.wav and we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_144.wav  for that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_146.wav to get a ticket but a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_148.wav  that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_149.wav changing experience for you all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_150.wav it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_151.wav and we're like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_152.wav  like we can't do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_155.wav  can actually do right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_156.wav  right and I've directed was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_157.wav  typically hear about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_161.wav  would only listen to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_163.wav  that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_164.wav  so it seems like you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_165.wav  you all really like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_166.wav like Rose above it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_167.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_168.wav  yeah do you think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_169.wav do you think the director Kathy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_170.wav buttering that she didn't already know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_171.wav I don't think she knew anything about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_172.wav  us was enormous
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_173.wav  and that was inspiration

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_174.wav  me you know so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_175.wav about and how it began

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_176.wav  Catherine
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_178.wav  think this project was successful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_183.wav  back from our people and also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_187.wav that will be show night net

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_189.wav oh awesome maybe I can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_190.wav  the clip to this episode

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_192.wav  well the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_193.wav the people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_194.wav  you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_197.wav  you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_199.wav and Sue
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_200.wav  and Sue what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_201.wav your involvement
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_202.wav well I looked at it as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_203.wav  way you said that taking on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_204.wav brave things because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_205.wav  and not only have you all three
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_206.wav  done that you've shown

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_207.wav  to do it yeah and that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_208.wav and that's pretty amazing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_210.wav  you know and then we're causing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_211.wav  chapters to like get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/2/WomenWhoStutter_2_213.wav  that I'm moved
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_0.wav and so the rest

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_1.wav well I went to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_2.wav about what's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_3.wav it's just marvelous to hear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_4.wav thank you so much Pam

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_6.wav at least when I went to school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_7.wav the last I would hurt

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_8.wav  friends in 2010
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_9.wav  disclosing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_10.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_11.wav and hoping that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_12.wav it absolutely changed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_13.wav I went there I sat in the front

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_14.wav and then I heard people talk about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_15.wav I had gone to the conference

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_18.wav ask you about stuttering and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_19.wav work in government

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_21.wav that can be so liberating
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_23.wav I first disclosed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_24.wav I said it just like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_25.wav  we are a service

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_26.wav and there's no residual there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_27.wav in my professional life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_29.wav and then now I'm doing podcast
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_30.wav was move towards

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_31.wav the situation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_32.wav so I was brought up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_34.wav according to the ADA
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_35.wav as I've come to terms with my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_36.wav I also want
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_37.wav  Rachel and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_38.wav  opportunity to educate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/3/WomenWhoStutter_3_39.wav it sounds like you have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_0.wav I went on about four interviews a day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_1.wav  over there they call it flatmate not a roommate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_3.wav  so I ended up coming back to New York
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_4.wav  it sounds like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_5.wav  and see
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_6.wav and seeing that all these people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_7.wav well first of all when I got to college is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_8.wav  go in the library and check

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_9.wav  out that's why I was able to say just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_10.wav but even in this conversation now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_11.wav  there's a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_12.wav  you why what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_13.wav  have this passion for it and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_14.wav  it really well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_15.wav  there's a focus on me having to you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_16.wav I've only been to three meetings so far

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_18.wav and then I went to work at an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_19.wav just because we quote Stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_20.wav  be in because we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_21.wav and so then that of course

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_24.wav  way and things happen when we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_25.wav  mistakes and you got to let it go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_27.wav to not think about ourselves and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_28.wav  know mostly what I'm trying to do is just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_29.wav  is just slow down with my breathing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_30.wav from the transformational speaking Workshop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_31.wav  is with what I thought was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_32.wav meant anybody who would talk to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_36.wav  for fear that their kids will pick it up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_37.wav that's really interesting I mean do we have time for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/4/WomenWhoStutter_4_38.wav to be heard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_1.wav and she said Amy the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_2.wav  your mother though
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_4.wav  and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_5.wav  I will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_7.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_8.wav  so up until I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_11.wav my mother kept

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_12.wav people who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_14.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_16.wav  services I can actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_17.wav and I'm too

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_18.wav  have it's there and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_21.wav  How do I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_24.wav and I understand it of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_27.wav  9th through 12th

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_29.wav your comfort at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_30.wav  I guess do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_32.wav human nature
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_33.wav like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_35.wav fear it's like I just don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_36.wav  all I know is the life I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_37.wav  do you feel proud like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_38.wav  I feel proud

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/5/WomenWhoStutter_5_39.wav  not just for people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_0.wav Rachel hey Rachel how's it going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_1.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_9.wav  afterwards

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_13.wav  remember it even all these years later
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_16.wav the most important thing is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_17.wav  and accomplished
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_18.wav I like that you said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_20.wav  I would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_21.wav that sounds like so much fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_26.wav  follow I'm struggling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_33.wav  hmm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_34.wav  what is the most important thing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_36.wav thank you so much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_37.wav  I don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_42.wav  other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_43.wav  people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_44.wav  people so thanks

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_57.wav  have you had any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_59.wav  Hello Pam I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_63.wav  so far I am not sure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_64.wav  so artistic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_66.wav  like that you express yourself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_70.wav  dancing is definitely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_79.wav what you do to keep yourself busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_80.wav  Of course

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_82.wav  I do feel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_83.wav  totally understand

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_84.wav  stuttering and get
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_85.wav  get where you're coming from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_87.wav  Definitely do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_89.wav circle all the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_90.wav  yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_94.wav  support group for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_95.wav  Stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_96.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_98.wav  find one here in Los
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_102.wav I never met in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_103.wav  of my family
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_104.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_108.wav  Association
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_109.wav  pop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_117.wav  grateful
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_118.wav  to become a professional

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_119.wav cancer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_121.wav  do you change the way you see things

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_122.wav  it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_123.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_124.wav did you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_129.wav my experiences was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_132.wav  you over the conference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_133.wav  my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_139.wav I know one of my favorite parts of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_143.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_144.wav and so you and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_145.wav  as well as dancing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_151.wav okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_155.wav  this and have the same feelings

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_162.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_165.wav  yeah well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_167.wav  exactly what I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_172.wav yeah I was like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_173.wav  Yes and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_174.wav  right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_176.wav  same thing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_177.wav  that it's important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_178.wav  not have to deal with that fear it just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_179.wav it's really a freeing feeling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_185.wav  them eliminate some of that fear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_187.wav and I bet that that will help

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_193.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_195.wav  I'll start this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_200.wav she
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_203.wav  participation is going to help other people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_207.wav  speech
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/6/WomenWhoStutter_6_210.wav  I actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_0.wav  those things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_2.wav  women who stutter our stories

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_3.wav  legal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_4.wav passionate about which is real

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_5.wav how do you manage it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_6.wav  not always come up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_7.wav wary about bringing it up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_11.wav  the person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_12.wav  I can so totally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_14.wav  lot going on what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_16.wav  whether it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_17.wav we can process things together

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_18.wav  in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_19.wav for lack of a term promotion

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_20.wav  during conferences
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_21.wav and the great thing about it is that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_22.wav  it be because I think that it comes from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_23.wav  for me that it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_24.wav  and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_30.wav you guys

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_33.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_34.wav  but I hadn't really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_35.wav I think it will take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_36.wav and I think it will take

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/7/WomenWhoStutter_7_37.wav  from time to time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_0.wav web site it actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_4.wav like a bit so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_5.wav come

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_8.wav class
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_9.wav  Seattle Washington

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_10.wav what was your purpose in going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_13.wav  sounds like that might involve a lot of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_15.wav  so I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_16.wav  case

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_18.wav okay terrific and what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_20.wav  we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_23.wav  him
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_24.wav  I don't think I did but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_27.wav drinking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_28.wav and like I just want to like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_36.wav  there was a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_37.wav confidence in my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/8/WomenWhoStutter_8_38.wav wanted to ask you so you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_6.wav look just like a cookie

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_7.wav  till 1980
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_9.wav  things that if I could speak blue in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_10.wav I said I would want to talk to you about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_11.wav thing and he put

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_12.wav stuttering and those two
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_13.wav  many people who stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_14.wav buttering arena
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_15.wav  also notice that you also

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_18.wav  understanding the behavior
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_19.wav  something that I like to do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_20.wav  plant they had me to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_21.wav  enjoying my Saturday mornings so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_22.wav I decided to take that step
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_24.wav so I was so terrified

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_29.wav and it was because I spoke like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_30.wav  mental abuse and mental abuse so I felt

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_31.wav who I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_32.wav yeah well that's so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_33.wav when I am talking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_36.wav  walking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/9/WomenWhoStutter_9_38.wav  I have to read allow it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_0.wav privilege to chat

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_1.wav well I guess the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_2.wav  very simple advice is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_5.wav  actually meet people well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_8.wav it sounds like you have had a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_9.wav you and it's been good for the NSA
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_13.wav  wonderful experience

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_17.wav  much harder because I started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_18.wav I'd be learning how to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_21.wav when I was 16 I met
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_24.wav could do it too

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_25.wav  needed to realize that I could really do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_26.wav no was she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_27.wav  be a teacher so then I'll
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_28.wav  and Debbie Nicolai actually who was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_34.wav it certainly is how long
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_35.wav  well so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_36.wav second-year working

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_38.wav I'm going to Sarah hey Sarah how's it going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_39.wav oh good thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_40.wav  really that's a challenge
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_42.wav what grade do you teach

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_44.wav these are little kids yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_45.wav yes definitely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_46.wav  stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_50.wav but so with my older students I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_51.wav  I mean sometimes someone will mention
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_52.wav  as of my older students usually I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_53.wav I tell them that I stutter and I say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_56.wav you know laugh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_58.wav maybe not intentionally but you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_59.wav oh good things how are you pan

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_60.wav  students where they're just like you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_61.wav  like you know they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_62.wav  but they just did like kind of like a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_63.wav don't know what to do kind of laugh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_64.wav with them and are they supportive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_66.wav  it's kind of a mix I'm really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_69.wav and so like when I interviewed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_71.wav  than in my building

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_72.wav  I've talked to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_73.wav  explaining my stuttering story but like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_76.wav  people just know I don't have to worry about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_77.wav now how did you get so involved

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_78.wav thanks for being a guest
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_80.wav that you're on the board

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_81.wav  board well so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_82.wav  part

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_83.wav parts of the kids programming
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_84.wav why are you so involved with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_85.wav  with the organization
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_86.wav the organization

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_87.wav well I think I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_91.wav and hear their different experiences

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_92.wav when you were younger
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_93.wav well to be honest like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_94.wav  speech made fun of me and I was just like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_98.wav for having me Pam

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_99.wav  like I've gone for a while
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_100.wav  and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_102.wav  name Christian until
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_103.wav  high school and it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_108.wav  I was able to really accept stuttering and like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_111.wav well I don't know whether it was necessary

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_112.wav  maybe sound silly but like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_113.wav  so I feel like anyone who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_114.wav  am now you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_115.wav and how did you find out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_116.wav the rapist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_117.wav yes I did actually so I had been going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_118.wav and what you do to keep yourself busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_119.wav  Great okay so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_121.wav that's how I found it and I guess
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_122.wav did your parents go with you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_123.wav well so this is actually a funny story
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_125.wav  that if I went with someone that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_128.wav you'd go to one without her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_129.wav well I think that part

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_130.wav you doing your thing with the kids
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_131.wav  program

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_132.wav  well so a lot of times
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_133.wav  we've become close with over the years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_134.wav  do you have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_135.wav and what does she think about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_136.wav  all this wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_137.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_138.wav she would like to be invited
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_139.wav which is just south of Boston

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_140.wav  wow you so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_141.wav  I feel like this is like my thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_143.wav like I guess I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_144.wav but I guess I don't know I'm maybe it's that I'm not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_145.wav where up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_147.wav  I don't know it's nice that it's been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_149.wav do you and your sister ever talk about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_150.wav we know I mean like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_151.wav  she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_152.wav  do who don't start if that makes sense
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_153.wav so like I've talked to my sister before but it's not like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_154.wav  family I have five
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_155.wav siblings four sisters and a brother

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_156.wav  even become an open
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_157.wav  issue until

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_158.wav people that get it you know so yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_162.wav  get involved with that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_164.wav was helping out with the older
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_166.wav  so much on the girls are just like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_168.wav  that you do in school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_169.wav like some of the same children yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_171.wav  school before so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_172.wav okay and girl

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_173.wav  boring girls and women is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_174.wav  is that correct it definitely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_175.wav girls coming is just this really positive things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_176.wav thing for the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_178.wav  build their self-esteem and their
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_179.wav confidence and believe that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_180.wav who stutter would choose
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_181.wav  Well so I ever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_183.wav it definitely does it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_184.wav  about your stuttering to the girls so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_185.wav so it's pretty much the same kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_189.wav  years ago I worked for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_190.wav for an after school program
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_193.wav  if there's any young

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_194.wav girls listening to this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_195.wav  their first NSA

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_196.wav conference but are scare
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_197.wav what advice would you give them what would you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/10/WomenWhoStutter_10_198.wav  to be a teacher and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_0.wav hi Pam I'm doing well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_1.wav  over the years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_2.wav talking that they talk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_4.wav you know because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_5.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_6.wav before when I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_10.wav when did you start

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_11.wav  your therapist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_12.wav back and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_13.wav that's really exciting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_16.wav  with me because I just had these

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_18.wav communication
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_19.wav conference this year

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_20.wav  I am I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_21.wav  so thank you again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_22.wav  Thank you so much, Pam and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_23.wav as a guest I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_24.wav  and I always felt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_25.wav you know I think that was the sort of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_26.wav  of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_27.wav I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_28.wav  people do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_30.wav  like it would really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_31.wav  try to maintain eye contact
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_32.wav and I'm okay with it so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_33.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_34.wav but it's not too late to all right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_35.wav  if I did have to talk to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_36.wav purposely change words

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_37.wav cause I don't know I mean I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/11/WomenWhoStutter_11_38.wav in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_0.wav  it's coming I do believe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_3.wav  exactly yeah well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_6.wav self and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_7.wav when you're working

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_8.wav  role model for the kids to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_9.wav  yeah now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_10.wav  that you work with do any of them stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_11.wav but connect that level

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_12.wav  work with I mean is it always the same
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_13.wav person that you work with or do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_14.wav  their own
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_15.wav it sounds like it's just a perfect fit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_17.wav  of the places that sound
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_18.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_20.wav and he
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_21.wav  decide to go to conference

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_22.wav  I was attending those
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_23.wav  feel comfortable how did you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_28.wav works at a world market
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_30.wav  and people don't seem

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_31.wav to mine and so when she told me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_32.wav  positive things about gil yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_33.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_35.wav  about that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_36.wav that I'm okay the way I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_37.wav and that I can still be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/12/WomenWhoStutter_12_39.wav  hands on and I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_0.wav my name is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_1.wav  one great thing about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_2.wav the program is that they offer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_3.wav and then speaking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_4.wav other techniques as well like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_5.wav  I'm very lucky
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_6.wav it definitely echoes and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_7.wav  it's just nice to be able to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_11.wav  hmm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_14.wav  okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_16.wav and it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_17.wav speak about things and I think after
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_18.wav trying to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_20.wav love speaking to people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_21.wav  be able to have great conversations

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_24.wav I used to go once a week
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_25.wav that was prolonged every period of time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_27.wav okay quite interesting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_28.wav I wasn't a worthy person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_29.wav  what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_30.wav love hearing about people's background

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_33.wav a community
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_34.wav Friday why didn't I go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_36.wav she hasn't been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_38.wav not letting it to find me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/13/WomenWhoStutter_13_39.wav I think one of the main
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_0.wav  at www.stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_1.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_2.wav and just going to visit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_5.wav  well thank
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_8.wav  very confident do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_9.wav  you feel like do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_10.wav do you feel like you're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_11.wav confident person at this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_12.wav  and I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_13.wav it's taking time and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_15.wav  if they wanted

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_16.wav  to you to have that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_19.wav  exactly and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_21.wav  yeah now if
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_22.wav  if there's young girls

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_24.wav okay I advise
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_25.wav  advice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_26.wav  I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_29.wav  people he's found that and it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_31.wav  of speaking and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_33.wav  come out of it and he's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_35.wav  can do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_36.wav  and it just takes a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_37.wav my name is help and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_38.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_40.wav  evenings right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_43.wav  got to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_44.wav  keep breathing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_46.wav  I've got a child

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_47.wav  to clients and customers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_48.wav all day so you just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_49.wav customers. You Stammer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_51.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_52.wav  you know if I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_55.wav hey Natalie how are you today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_56.wav  I am I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_58.wav each day and that helps

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_60.wav just pause and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_71.wav try my best

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_74.wav about do to keep yourself busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_76.wav  program is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_80.wav  it from the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_83.wav  and just take

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_84.wav each time I speak
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_85.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_86.wav  each time I speak I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_87.wav  have to pause

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_88.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_89.wav  talk a little more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_91.wav  I have to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_94.wav and I'm a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_97.wav to contact each day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_98.wav and it's quite

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_99.wav interesting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_101.wav  it and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_103.wav people take a step back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_106.wav meaning to bath all of us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_109.wav I enjoyed it and it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_116.wav had an opportunity to meet

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_117.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_119.wav  it isn't bad but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_121.wav men
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_122.wav  asked is that that seems to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_123.wav  common in whatever type of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_124.wav because there's fewer women that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_125.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_126.wav which a male or a female

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_127.wav  it was a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_129.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_131.wav  again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_133.wav  I may be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_135.wav  third time and now that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_143.wav and for the first couple of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_144.wav  I kept taking a step back but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_145.wav but this time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_147.wav  can you catch and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_148.wav and it's good to have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_149.wav  by them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_150.wav did you get involved in doing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_151.wav but well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_153.wav yeah that should be actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_154.wav  work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_157.wav  had to give it another go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_158.wav  to help me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_159.wav something to others

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_161.wav  and I wanted to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_163.wav  by the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_167.wav  so they helped
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_169.wav it didn't really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_170.wav  an interest in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_171.wav  improving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_172.wav  and so when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_174.wav  told me about and it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_176.wav  into a kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_177.wav  I've been asking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_178.wav  about your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_181.wav  it's been a bit of time but I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_182.wav it was hard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_183.wav  I have few

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_184.wav I've become my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_185.wav  at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_186.wav  speech and my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_187.wav  at times because I couldn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_191.wav or I couldn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_193.wav what people don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_194.wav  the war and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_197.wav  part of my English

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_203.wav  and yeah I just couldn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/14/WomenWhoStutter_14_204.wav what do you like to do for fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_1.wav  for a month
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_3.wav what advice would you give her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_6.wav a child with a stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_8.wav  experience do you think it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_9.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_11.wav  I use

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_16.wav  has she done therapy to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_19.wav  yes and so you're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_20.wav  people at work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_22.wav  with other musicians

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_30.wav  No
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_31.wav the association

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_32.wav  between
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_33.wav what do people think of stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_35.wav because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/15/WomenWhoStutter_15_36.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_2.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_5.wav I've been able to do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_9.wav I wasn't laughed at either
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_12.wav okay so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_13.wav  I feel like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_16.wav what if I do don't worry about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_18.wav to say hey it's okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_21.wav  in a group when everybody already knows

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_23.wav  that was a nice opening but then I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_24.wav  we have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_25.wav once we go some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_27.wav  but we just don't have a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_29.wav what was it like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_30.wav  Well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_33.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_35.wav your favorite memory

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_37.wav  I guess that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_38.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/16/WomenWhoStutter_16_39.wav  moment there were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_0.wav  so soon they are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_2.wav for their first time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_6.wav and boy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_7.wav going to one of these
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_8.wav was amazing it quick

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_9.wav  I would say that I have a lot of experience with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_10.wav  of the lessons that I've learned

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_11.wav  here in Maine so yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_12.wav  ways that it has changed me just persist

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_13.wav  actually in high school I went
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_16.wav um it's actually not bad at all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_18.wav you've had therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_20.wav  I didn't have really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_21.wav I could stutter a little bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_22.wav  we've been covert

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_23.wav  you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_24.wav cure curiosity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_25.wav I was actually home schooled for as long as I was I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_28.wav Does anybody else in the family stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_30.wav  up crying a little bit more sucking it up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_31.wav  was really cool I had actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_32.wav  so good I'm glad
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_34.wav in the first one I had met

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_37.wav  and that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/17/WomenWhoStutter_17_38.wav how did that feel when she came up to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_1.wav  ask it from a many
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_5.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_8.wav or are there more males
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_9.wav yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_14.wav  early
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_15.wav can you just tell us your name again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_16.wav meetings under one of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_20.wav  I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_21.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_23.wav  been in Sweden for the last year

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_24.wav people and when I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_25.wav not actually an hour

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_26.wav  because your daughter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_27.wav  really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_28.wav we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_30.wav but I was so really proud of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_33.wav thera therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_34.wav advice that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_36.wav  you feel a better
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/18/WomenWhoStutter_18_39.wav  6 7

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_0.wav  pop
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_2.wav  only grapes that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_5.wav  really help connect
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_6.wav people to each other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_7.wav  definitely because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_8.wav man the Taylor

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_10.wav  this stage in your life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_11.wav  I am at a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_13.wav  Comfortably stage
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_14.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_15.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_16.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_17.wav challenge
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_20.wav her as she's kind of coming along

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_27.wav set your ring
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_28.wav baby they look after or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_29.wav or something else maybe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_31.wav  psyche palm I've

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_33.wav  podcast
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_37.wav  work with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_41.wav  11 years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_42.wav that's quite a range

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_43.wav  it is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_44.wav  that you enjoy working with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_45.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_47.wav imagine it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_48.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_51.wav I'm good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_54.wav  hmm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_55.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_59.wav  have been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_60.wav  So people are different and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_63.wav and what about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_64.wav patient

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_69.wav  play Me As I Work With
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_70.wav oh I am delighted that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_71.wav thank you very much for having me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_73.wav  easier

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_74.wav  hmm that's a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_75.wav with people outside of work

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_76.wav I had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_77.wav  a bit of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_78.wav  I have a look back so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_79.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_80.wav 5 or 6 years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_81.wav you sound very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_82.wav  skin right now because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_85.wav  why would

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_90.wav  Christine from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_91.wav  so yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_92.wav  I am quite confident
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_94.wav  in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_96.wav  13
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_100.wav  Was to help

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_105.wav all their hobbies I enjoy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_108.wav  better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_109.wav changers in your life has been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_111.wav  bye

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_112.wav cook yes and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_113.wav toy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_114.wav  control my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_115.wav  will voice get too dry

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_116.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_117.wav to show you the results so far

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_118.wav does it go up and down a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_120.wav because I have been on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_121.wav  a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_122.wav  more time to myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_123.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_124.wav  reading lesson to music

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_125.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_126.wav  be done for you emotionally

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_129.wav I wouldn't talk to nobody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_132.wav that's wonderful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_133.wav  I really had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_135.wav  and it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_136.wav  each time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_137.wav  Everyone is just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_138.wav  kind of never
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_139.wav changing life and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_141.wav  hope to have 12 people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_143.wav but in June we had only

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_144.wav  and things like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_145.wav All right awesome it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_146.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_147.wav  have centers and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_148.wav  me at a kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_149.wav  clogging up with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_150.wav  more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_151.wav  every day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_153.wav  want to start your own support group
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_154.wav  I wanted to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_158.wav  all the people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_159.wav  we have the same

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_160.wav  people who stammer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_162.wav yes that's right pom

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_163.wav  yes and I don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_165.wav  do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_169.wav  wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_170.wav  wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_172.wav  There's food happen because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_173.wav  real

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_176.wav  it definitely is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_177.wav  and it's been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_179.wav  of my own
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_183.wav  rubbish

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_184.wav  definitely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_185.wav  it's central London

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_186.wav they help and support people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_187.wav people who stammer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_190.wav overwhelming because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_191.wav  I've met

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_193.wav  it's just amazing sodas
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_197.wav  interviews and to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_199.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_200.wav  groups yes I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/19/WomenWhoStutter_19_203.wav  no sorry and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_0.wav  I'm not talking on that right now again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_1.wav  first ever anything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_2.wav my daughter am I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_3.wav  and my world now is with stuttering almost
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_7.wav  mind is I've been meeting so many people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_8.wav  catching up with you a bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_9.wav  self-doubts and because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_10.wav if you asked me if I liked it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_11.wav  I found myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_12.wav  years ago with the NSA I remember
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_14.wav  well my name is Annie

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_15.wav many years so imagine
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_16.wav and if I go back even further my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_17.wav  where you're going soon
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_18.wav but he

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_20.wav  not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_21.wav he was going to go into a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_22.wav  and he be one of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_23.wav  true highlights was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_24.wav  as I called myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_25.wav  I called myself an old-timer this was my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_27.wav people of all ages
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_28.wav  like no time so it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_29.wav a little bit of old and new and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_32.wav  On so many levels

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_33.wav  personal best cuz all the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_37.wav right you know you can just say yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/20/WomenWhoStutter_20_39.wav  I like a long time and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_1.wav I am the best at them if

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_3.wav  did they get the answers they were looking for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_4.wav  ask them if they want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_5.wav  friend
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_7.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_8.wav  sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_9.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_11.wav  listening to everyone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_12.wav  kind of like this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_13.wav it seems like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_14.wav it just kind of evolves

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_15.wav go with the flow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_16.wav now for most of the conversation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_17.wav when you talk about this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_19.wav  putting me in front of people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_22.wav  I don't think I would give up if I could
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_23.wav so if somebody offered you a pillow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_24.wav  shaped the person I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_25.wav and without it I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_27.wav  Mm-hmm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_31.wav spired by your story

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_32.wav  I really hope so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_33.wav  well I just want to thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_34.wav how long have you stuttered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_35.wav  I don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_36.wav 3 or 4 years old
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_37.wav and did you ever have a speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_38.wav  for like a couple of months
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_39.wav but I felt that the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_40.wav it was as an adult
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_41.wav it was actually a couple of years ago

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_42.wav  so I can certainly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_43.wav understand when you say that it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_45.wav make it less
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_46.wav and I wanted to get some exposure

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_47.wav  children and teenagers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_48.wav  there are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_49.wav  they're not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_50.wav they're not always just focused on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_51.wav  strategy department
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_52.wav okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_55.wav available they need to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_56.wav  look for them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_57.wav as people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_58.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_59.wav  I think people are yet to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_60.wav  that changing nowadays

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_62.wav that made fun of you and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_63.wav Bullied you yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_65.wav what was high school like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_66.wav  No I think for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_67.wav easier because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_68.wav I started getting more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_71.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_74.wav advertised

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_75.wav  yeah I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_76.wav  with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_77.wav  Good afternoon or good morning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_78.wav you've got family that stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_79.wav okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_80.wav  so in your case it runs in the family

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_81.wav  pretty much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_82.wav  dozen male or female

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_84.wav with your brother and cousin
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_86.wav the term covert stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_87.wav  no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_88.wav people were going to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_89.wav judge me for the way that I spoke
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_90.wav  experience and your stories

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_91.wav  we're going to help you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_92.wav  stuttering goes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_93.wav I first
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_94.wav we started having like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_95.wav weekly every
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_98.wav  terms of being comfortable with the specter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_99.wav we're pretty sure that there are other people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_100.wav people were very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_101.wav we're very eager to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_102.wav  able to do that is just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_103.wav it's fulfilling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_105.wav  and from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_108.wav  came yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_111.wav which just yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_114.wav  it's not as scary as I thought it would be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_115.wav he was 8 years old

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_116.wav  after a couple of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_117.wav  of the gatherings with us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_118.wav that he was being made fun of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_119.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_120.wav he said that a couple of kids
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_121.wav kids were picking on him

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_123.wav  gathering when you've got
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_124.wav somebody as young as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_125.wav even if they start to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_128.wav not achieved what they want to at you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_130.wav  younger people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_131.wav  exactly spot on yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_133.wav  around
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_134.wav who has the group been going on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_135.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_136.wav  community

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_137.wav that's just so inspiring to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_138.wav you hear about and learn about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_140.wav  people that show up I would say maybe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_143.wav reaching us because I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_144.wav that's very true yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_145.wav  yeah so what are some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_146.wav and running this group
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_148.wav I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_149.wav  how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_150.wav any small test

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_153.wav comfortable then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_155.wav  you feel like we are alone on this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_156.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_158.wav  people better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_159.wav in my city
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_160.wav and it would be open about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_161.wav talking about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_162.wav  I think that's just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_163.wav that's something that goes on great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_165.wav that's really special

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_167.wav what are you seeing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_170.wav  if you're calm you don't have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_172.wav did they know that you stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_173.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_174.wav  pathologist to attend
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_175.wav  yes we do have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_176.wav  how best to approach it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_178.wav  having speech pathologist there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_179.wav  they find it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_180.wav  and we're kind of creating that link

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_181.wav we don't offer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_182.wav  especially since you've got

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_183.wav different people represent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_184.wav  such a short time really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_186.wav even when they're in front of a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_189.wav  kind of opened it up a little bit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_190.wav just so they get to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_191.wav which their comfort zone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_194.wav  wow no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_195.wav where does the group meet

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_196.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_198.wav round the table kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_199.wav  right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_200.wav and how long are the meetings

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_201.wav  it depends
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_202.wav wow it just seems to be working

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_204.wav how does that become part of the group
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_205.wav the name of the group yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_206.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_207.wav it's not as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_209.wav how do you end
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/21/WomenWhoStutter_21_210.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_0.wav what's hard about it well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_2.wav do you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_3.wav oh very exciting well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_5.wav who have this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_6.wav  this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_7.wav  I'm in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_8.wav  I'm in to also have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_10.wav  children that they might

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_11.wav  How long have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_12.wav I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_14.wav had you know like a really hard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_15.wav  it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_16.wav going and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_18.wav  to try to hide your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_21.wav an issue or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_23.wav  okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_27.wav the hardest thing for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_30.wav  if we could be confident

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_31.wav  speech day yes I told
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_32.wav  you in any regard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/22/WomenWhoStutter_22_36.wav  you totally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_0.wav  about five or six months ago

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_1.wav  I might have to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_2.wav because I can't say what I want to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_3.wav  I don't remember what I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_5.wav  introduce people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_7.wav what was the difference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_8.wav  dammers

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_9.wav is a quote that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_10.wav  whatever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_13.wav yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_14.wav thank you I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_16.wav how long have you stammered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_18.wav have you had any as an adult

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_19.wav  or even 20
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_21.wav after you've completed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_24.wav of course but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_25.wav  picking that up correctly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_26.wav  I've always been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_28.wav we could be talking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_29.wav yeah it sounds like you're a different person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_30.wav do your friends and family notice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_31.wav yes I think they have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_36.wav merce for a round

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/23/WomenWhoStutter_23_39.wav  Did you have a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_0.wav  unforgettable

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_1.wav  and when I hear her voice it just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_2.wav no I it has been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_3.wav are people that are listening I'm sure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_5.wav  therapy and that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_7.wav  research now I'm not sure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_8.wav  trying my very best to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_11.wav  so I just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_14.wav  it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_15.wav  and that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_17.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_18.wav  patient and then I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_19.wav very rich

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_20.wav style logist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_22.wav the audience laughing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_24.wav well it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_26.wav see you for a patient who was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_27.wav whereas she
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_28.wav no I haven't seen a pattern

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_30.wav  and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_31.wav  whatever I can to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_33.wav and I think it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_34.wav  I really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_35.wav talk to her about that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_37.wav  Washington D.C.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_38.wav  wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/24/WomenWhoStutter_24_39.wav second one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_0.wav  I'm sure yeah so I'm my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_1.wav and well what does that entail

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_2.wav  you know yeah wait
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_3.wav  feeling it you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_5.wav  they you know they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_6.wav who stutters to and then we had like this great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_8.wav  so that was really good yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_9.wav  and how long have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_11.wav in my life yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_12.wav you know a fluent speaker

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_13.wav therapy as a kid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_14.wav and then I had some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_16.wav  yeah I don't know well yeah it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_18.wav like a alleviation where is this new

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_19.wav  rather than trying to like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_22.wav  kind of figure that that I wanted to help

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_23.wav you know like underlying goals
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_24.wav getting involved in the stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_25.wav  Well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_26.wav  Association

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_28.wav  is just you know like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_29.wav like obsessing over how I sound

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_31.wav the best sort of stutterer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_32.wav  familiar with disability theory

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_33.wav like expectations
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_34.wav  made me really kind of like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_36.wav ification exchange that we have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_37.wav people don't really want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/25/WomenWhoStutter_25_39.wav for like other speakers definitely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_1.wav  Kelly so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_3.wav pilly so it may be hard for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_5.wav are a lot of women in the field

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_7.wav absolutely refreshing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_11.wav again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_12.wav  put that right out there in the open
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_14.wav  First of all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_15.wav even the small
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_17.wav  hard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_19.wav parents were not very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_20.wav  yeah actually there is some kind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_22.wav yes actually I have done
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_25.wav are you involved in any therapy now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_27.wav here that if they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_30.wav and things are lot more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_33.wav 22 years and now I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/26/WomenWhoStutter_26_37.wav  don't get in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_2.wav what's your dream job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_4.wav  thank you yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_6.wav  lot of communicate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_7.wav and how I don't think it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_10.wav  you know or we talk about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_13.wav  does involving that but it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_14.wav  it's something with those
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_16.wav and that was a great thing to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_17.wav he has been yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_18.wav  around up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_20.wav um it kind of came out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_24.wav it was part of me so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_25.wav where was it posted
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_26.wav  to hear about it and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_27.wav so I tried to hide it well I try
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_28.wav  found it yeah no of course

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_31.wav  therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_34.wav maybe you think you don't need to be fixed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_35.wav didn't want to live like that anymore
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_36.wav  I said for that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/27/WomenWhoStutter_27_39.wav you kind of run the show I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_1.wav  to change and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_3.wav  know so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_4.wav and to at least

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_6.wav from what can we do to fix our child
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_7.wav  you know I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_8.wav  our chat yep on the bus
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_10.wav  there for some adults with stutter and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_11.wav you don't know what you're looking for because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_12.wav  your background isn't speech therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_13.wav mystery
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_14.wav  knew him well and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_15.wav he was such an active
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_18.wav  maybe this will help you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_21.wav okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_23.wav so there was just this making thing in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_24.wav  did you could
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_25.wav so we would take you out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_26.wav to get him talking again you said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_29.wav and I hope that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_31.wav  junior college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_33.wav and it's important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_34.wav I just sat back and said now what do I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_35.wav is there just this idea that this is evidence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_37.wav and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/28/WomenWhoStutter_28_39.wav  up around that is breath taking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_0.wav or a blog where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_1.wav boardpress.com

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_5.wav I don't know how it's gonna work out but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_6.wav  I wish people see it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_7.wav I don't care as long as people see it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_8.wav  Stuttering Camp and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_10.wav  I would have some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_11.wav when did you start stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_12.wav  the road
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_13.wav work and all that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_15.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_16.wav it was pretty much a study

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_18.wav they had a rough time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_19.wav getting me in there because of me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_20.wav his name was Ronnie
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_21.wav everybody at work and at home

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_22.wav  knowledge and I'm studying for that program
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_26.wav regurally talk to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_27.wav  had a stutter but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_28.wav pian

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_29.wav  Peep
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_30.wav  associate myself with those type of people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_31.wav  captain with my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_32.wav in this class you doesn't need to be in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_33.wav  it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/29/WomenWhoStutter_29_34.wav register at work

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_1.wav  I mean am I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_3.wav confident

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_4.wav  oh yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_5.wav oh the boys know you stammer right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_9.wav have you got your eye on any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_10.wav special boy yet

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_11.wav no not yet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_12.wav good luck with that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_13.wav  thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_14.wav over 13 and Stammers

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_15.wav  I would just say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_16.wav to college then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_19.wav that's terrific
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_20.wav and be yourself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_21.wav and that you deserve to be heard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_22.wav  yes now yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_24.wav and like you're being heard today
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_25.wav  yes is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_26.wav  anything else you'd like to share
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_27.wav  Mary

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_28.wav before we close down our
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_29.wav no okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_32.wav thank you so much to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_33.wav  begun that process have you applied

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_34.wav  oh no not yet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_35.wav doctor do you want to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_41.wav  years of school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_42.wav  so how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_43.wav  school are you a good student
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_44.wav  yes I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_47.wav taking subjects
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_51.wav lot of language classes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_53.wav languages do you speak
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_54.wav  I speak

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_57.wav it's helpful when you start college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_58.wav  yes it is so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_59.wav  communicating how to stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_60.wav effect you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_61.wav  yes actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_64.wav when you were younger

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_65.wav  yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_66.wav  you growing up with a stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_67.wav in fact it was so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_71.wav when did you start stammering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_73.wav  thank the word they supportive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_74.wav yes they were but did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_75.wav will be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_77.wav  to give it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_79.wav  you were younger or when you were in school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_80.wav  oh yes I did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_82.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_83.wav how did you handle that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_86.wav did you ever try to stand up to that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_87.wav  make them feel bad

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_88.wav no actually I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_89.wav is it easier now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_90.wav yes now it is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_91.wav  I'm very good thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_93.wav don't care sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_97.wav you have a lot of best friends

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_100.wav  speak so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_101.wav  even if I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_102.wav even if I summer I don't care
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_103.wav differently or privately

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_105.wav  do it and be yourself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_107.wav to do that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_108.wav yes you sound
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_109.wav to having you share your story

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_110.wav thank you so much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_111.wav and your English is beautiful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_112.wav  oh thank you so much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_115.wav  have a beautiful laugh too

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_116.wav  Thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_117.wav what else do you do beside school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_118.wav are you involved in any other activities
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_119.wav  no actually I don't have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_120.wav  exam and I have to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_121.wav  to get a good mark in it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_122.wav  do you spend most of your time studying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_124.wav what do you do for fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_125.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_126.wav and study that's good to hear

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_128.wav are you interested in boys yet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_129.wav  actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_130.wav and what you do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_131.wav  Okay.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_134.wav  that's comfy then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_137.wav  school all girls

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_138.wav  no we are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_139.wav  Boys and girls

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_140.wav okay all right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_141.wav well you've got lots of time for that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_142.wav do you have any brothers and sisters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_144.wav are they older or younger

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_146.wav oh so you're the baby of the family
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_147.wav  yes I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_148.wav  okay hi my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_149.wav you your older sister and brother

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_150.wav yes they are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_151.wav  Does anybody else in your family stammer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_152.wav  yes my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_154.wav  yes she does

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_156.wav yes she did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_157.wav as a young woman who Stammers

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_158.wav yes that's right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_159.wav  to meet other people who stammer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_160.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_161.wav  you're still a student and you're too busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_162.wav  yes it is but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_164.wav yes right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_165.wav  beside your grandmother
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_166.wav  yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_167.wav  actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_168.wav one of my classmates

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_169.wav  about doing once you finish high school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_170.wav  actually I just want to be a back

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_171.wav  the same
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_175.wav  friends even though you both stammer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_177.wav  women who stammer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_178.wav tell me about that and tell

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_181.wav because it kind of gives us hope right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_182.wav  yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_183.wav yeah why did you join
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_186.wav why did you join the group

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_188.wav you want to be a what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_189.wav  youngest member in the group right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_190.wav  yes I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_193.wav that you're pretty inspiring to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_195.wav  is going to inspire
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_197.wav people are going to be happy to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_198.wav and stammering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_199.wav openly any time that we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_200.wav  so I just want you to know that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_204.wav relationships

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_205.wav okay what do you mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/30/WomenWhoStutter_30_206.wav  Um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_1.wav home it was weird
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_2.wav it will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_5.wav only one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_6.wav  maybe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_7.wav at them when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_8.wav are you going to college

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_9.wav hi bachelors
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_10.wav  Utah State

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_11.wav  I'm my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_14.wav all the time I'm just like you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_15.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_16.wav  and I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_17.wav  will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_18.wav  out of me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_20.wav you're the NSA I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_21.wav  so many

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_23.wav  fine with two
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_26.wav  school and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_27.wav this field because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_28.wav herb is doesn't know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_33.wav and I feel like I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_35.wav  you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_37.wav  Cutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_38.wav  and you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/31/WomenWhoStutter_31_39.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_1.wav  she's kind of a little

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_2.wav powerhouse I bet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_3.wav judgment never helps anybody move

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_4.wav  some of us like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_6.wav could have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_7.wav  that makes any sense
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_9.wav caring so much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_10.wav tation like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_11.wav  with my focus

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_13.wav  or whatever you can only kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_14.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_15.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_16.wav patient with me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_17.wav career
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_18.wav we like to do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_19.wav  mix with writing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_20.wav tunity there so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_22.wav teachers which would ask them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_23.wav animal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_24.wav I don't know just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_25.wav teens and early 20s

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_26.wav  experiences just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_27.wav eventually you know everything

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_28.wav that's whatever so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_29.wav situations

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_30.wav  you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_31.wav grade myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_33.wav I haven't really spoken to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_34.wav any of them that much just you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_35.wav girl
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_36.wav she's probably about three in this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_37.wav assuming that they're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/32/WomenWhoStutter_32_39.wav let's see here

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_0.wav  why would you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_1.wav  source of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_2.wav it's just a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_3.wav that happen

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_4.wav but it made me stronger
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_5.wav in the four years that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_8.wav I haven't had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_9.wav so I thought

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_10.wav the theropist who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_11.wav and then my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_12.wav it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_13.wav  basically we wrote a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_14.wav isn't cookie cutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_16.wav  I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_17.wav  support as you did in undergrad
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_18.wav not quite

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_19.wav  cool you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_20.wav  course

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_21.wav  that went off
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_22.wav  skilled nursing homes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_23.wav  I mean that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_24.wav  and it's hard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_25.wav yeah kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_26.wav but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_27.wav three why would you even tell me that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_28.wav me 216

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_29.wav something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_30.wav I ended up my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_31.wav but I wouldn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_32.wav like our supervisor

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_33.wav vacations
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_34.wav  cool

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_35.wav oh wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/33/WomenWhoStutter_33_36.wav happening

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_2.wav 3
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_4.wav opening

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_5.wav  a little
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_6.wav walking with children

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_7.wav  so there wasn't much stuttering going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_8.wav  also in therapy for stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_9.wav and I was stuttered openly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_10.wav  that it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_11.wav okay to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_12.wav  use voluntary stuttering a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_13.wav yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_14.wav  mm-hmm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_15.wav I tried to yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_16.wav buttering yes I do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_19.wav  and so and how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_20.wav  that I'm able to have more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_21.wav control
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_22.wav yeah I agree with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_23.wav ring a little bit right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_24.wav  yeah and do you ever tell

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_25.wav news that you'd like to share with us
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_26.wav on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_27.wav not really that I could think of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_28.wav  very hot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_29.wav so I'll be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_30.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_31.wav thank you for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_33.wav  been going how's the interviews gone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_34.wav I haven't gone on any interviews yet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_35.wav have you been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_36.wav practicing your interview skills
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_38.wav conference

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_39.wav advertising your stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_40.wav opening

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_41.wav opening
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_43.wav so what's changed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_44.wav  I really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_45.wav openly now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_46.wav  you know when I go
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_47.wav it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_48.wav what we did was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_50.wav different groups

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_51.wav and we went around ball some more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_52.wav  Stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_53.wav openly as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_54.wav the Band Aids are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_55.wav or you know just ask a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_57.wav person who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_58.wav  together
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_60.wav other people in your group

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_61.wav no they kind of stay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_62.wav at a distance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_63.wav when we did it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_65.wav  what was the purpose of this workshop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_66.wav  mostly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_67.wav as well okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_69.wav it's going good how are you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_70.wav  to speak to people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_71.wav people when you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_72.wav in a normal setting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_73.wav but you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_74.wav this of yours that you attended

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_75.wav  that was my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_77.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_80.wav  I attended
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_81.wav the 20-somethings introduction

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_83.wav and that's really all I can remember
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_85.wav what's that like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_86.wav  I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_87.wav that time yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_88.wav so to get us started could you formally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_92.wav  lot of lives yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_93.wav now would you say that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_95.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_96.wav there are a few times
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_97.wav um that I still become

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_99.wav what happened yesterday
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_100.wav um I got

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_102.wav the door to my house
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_103.wav the lock was stuck

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_104.wav and there was nobody else at home
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_105.wav use their phone to call somebody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_106.wav and I was completely covered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_107.wav what you do to keep busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_108.wav okay well hi
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_109.wav allow yourself to stutter in front of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_110.wav  neighbor
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_114.wav when talking to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_115.wav  know me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_116.wav  and I guess

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_119.wav yes they are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_120.wav and have they reacted

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_122.wav so this is like friends and family
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_123.wav  yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_125.wav  like you have a good support
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_126.wav system

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_127.wav barrest when you're stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_129.wav my name is Briana

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_130.wav pipkin and I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_131.wav  sometimes not with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_132.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_133.wav I pretty much just thinking the back of my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_134.wav  dang it I wish I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_136.wav isn't that a Taylor Swift song

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_137.wav  of it you know yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_139.wav  Changes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_140.wav well I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_141.wav  I'm so excited from college

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_142.wav I worked
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_143.wav  about two years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_144.wav about a year and a half to years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_145.wav  working as a speech assistant

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_146.wav  so those were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_147.wav  from

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_149.wav  speech pathologist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_151.wav oh no that's just where I was going to school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_153.wav  so do you still live at home
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_156.wav  by myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_157.wav but as for right now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_158.wav  I like being at home

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_159.wav how many siblings do you have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_160.wav I'm only child you are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_162.wav oh well then I can imagine that you'd like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_163.wav  us are all a year apart

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_164.wav so we were very close in age to each
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_165.wav that I wish I did have siblings

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_166.wav because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_167.wav on with somebody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_168.wav well you must have that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_169.wav  wolf okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_170.wav and I would just really like to be in a school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_171.wav who are close in age to me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_172.wav so they're kind of like siblings
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_174.wav  so you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_175.wav and how is that with your stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_176.wav  that was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_177.wav to people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_178.wav did that bother you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_179.wav it didn't the beginning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_181.wav you're a better person than I am because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_182.wav because I don't want the kids laughing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_183.wav  yeah I understand

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_184.wav  announcement
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_185.wav but then we had some other people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_188.wav  actually nervous about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_189.wav  another

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_190.wav something new
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_192.wav  another thing that we had to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_193.wav do over the intercom
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_194.wav  page manager

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_195.wav and they wanted us to say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_197.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_198.wav  mine yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_199.wav is silly because obviously we can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_201.wav  I had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_202.wav their P

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_203.wav and I also had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_205.wav she went supervise

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_206.wav and she had other assistants
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_207.wav once a week

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_209.wav no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/34/WomenWhoStutter_34_210.wav oh okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_1.wav client in the past
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_4.wav association after death

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_5.wav  must feel very good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_7.wav who are going to work to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_10.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_11.wav to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_20.wav tell me that I am not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_21.wav  you don't have to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_22.wav what about me or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_23.wav situation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_36.wav  that's how I felt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/35/WomenWhoStutter_35_37.wav now did you meet other women

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/36/WomenWhoStutter_36_10.wav I can understand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/36/WomenWhoStutter_36_13.wav I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/36/WomenWhoStutter_36_14.wav I feel that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/36/WomenWhoStutter_36_15.wav  completely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/36/WomenWhoStutter_36_19.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/36/WomenWhoStutter_36_32.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/36/WomenWhoStutter_36_35.wav  of sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/36/WomenWhoStutter_36_38.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_0.wav that provides
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_1.wav  another person who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_2.wav  participation in the NSA
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_3.wav  a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_4.wav not a reality
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_5.wav as well as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_6.wav next with an amazing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_7.wav group of people stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_9.wav with people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_10.wav  the same avoidances that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_11.wav some of his clients
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_12.wav you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_13.wav the National Stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_14.wav  that is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_15.wav  party my journey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_16.wav I grew up here and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_17.wav  a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_20.wav horological based but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_22.wav  at Austin when I was growing up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_23.wav stuttered but she understood

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_24.wav  it's a job that I'm really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_25.wav piece of the puzzle did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_27.wav human being who had a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_28.wav  in my journey I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_31.wav are contributions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_33.wav handicap in the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_34.wav a couple or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_35.wav a few but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_36.wav her stories just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_37.wav  my speaking voice about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_38.wav 10 12
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/37/WomenWhoStutter_37_39.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_0.wav  sounds actually pretty
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_1.wav  crazy like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_2.wav well be in it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_3.wav very success

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_5.wav  oh yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_6.wav  women who stutter our stories

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_7.wav and what you do to keep busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_8.wav  sure so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_9.wav  working on it every single
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_10.wav  they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_11.wav  two or three
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_13.wav mom who I feel

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_14.wav that obviously is on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_15.wav  me feel like okay well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_16.wav  sure was you know teased in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_17.wav  you started to care

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_18.wav  same time actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_19.wav a couple of years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_20.wav when I was in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_21.wav my mom and I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_22.wav  talking in this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_23.wav and I was just tired of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_24.wav  research I was you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_25.wav  the program is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_27.wav just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_28.wav not on you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_29.wav  so it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_30.wav cool calm and just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_31.wav I just went on there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_32.wav accepting and embracing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_35.wav  can tell you that I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_37.wav  people think like oh well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_38.wav  if I'm not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/38/WomenWhoStutter_38_39.wav  they kind of you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_1.wav so going to fly to stairs
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_2.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_3.wav and a cat's can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_5.wav  and the cat's game came

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_7.wav  so it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_10.wav  degree oh my gosh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_11.wav  wow yeah did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_12.wav  and where it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_13.wav was not any good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_15.wav because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_17.wav walk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_19.wav  and do it subconsciously now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_20.wav  So
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_21.wav so that was like kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_22.wav okay let's get
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_23.wav  right wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_24.wav wow you have been through so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_27.wav which to do with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_28.wav  nose I found out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_30.wav  without any pain that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_31.wav  because I wanted to stick to my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_33.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_35.wav  yeah so I'm the only
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_39.wav have a nice day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_40.wav but I don't think it does
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_42.wav  I there's a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_45.wav  I have no idea what I was talking about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_49.wav had the chance to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_52.wav and it makes things like my fingers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_54.wav play step by step

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_56.wav I do good in situations like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_57.wav trying to think about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_59.wav  I did have to use the phone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_60.wav I got

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_62.wav  no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_64.wav the phone ring

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_67.wav that was frustrating yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_68.wav cuz you're a wonderful communicator

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_70.wav  getting their stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_71.wav  Journey

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_74.wav  that you find interesting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_76.wav  sit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_78.wav I'm starting to tell people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_80.wav that I needed to hide

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_81.wav  and I've always been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_83.wav embarrassed about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_86.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_87.wav so that's why I've always hit it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_88.wav  I decided to do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_92.wav  speech therapy yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_93.wav what about as an adult have you had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_94.wav in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_95.wav  I'm really just trying to take care of it myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_97.wav  I just couldn't get used to it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_98.wav  they're really expensive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_99.wav  yeah it was $5

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_100.wav  but it's still works
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_102.wav  does that affect your stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_103.wav  I don't think it does I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_104.wav because I had to present it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_105.wav  In high school I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_107.wav I'm currently

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_108.wav something out loud
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_109.wav then I would like leave the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_112.wav  always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_115.wav stuttering in front of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_116.wav  cuz everybody would look and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_119.wav it's slowly been like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_120.wav  in the past
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_122.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_124.wav  Okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_125.wav I was talking to my mom about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_126.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_127.wav  trying to stay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_129.wav and where's the support group
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_131.wav okay well maybe you'll have to start

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_132.wav it's something that you can't change
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_133.wav so you can't change your name although

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_134.wav can't get it out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_135.wav quickly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_138.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_140.wav  the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_141.wav  I think it's a little bit more of a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_142.wav since I was 14

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_144.wav  25 so that's about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_145.wav  I started in high school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_146.wav where I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_147.wav  any

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_148.wav  stuff like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_149.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_152.wav that continued and progress
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_153.wav  through high school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_154.wav and after high school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_155.wav  when I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_157.wav  nice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_158.wav that was like my new

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_159.wav  besides heroin
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_160.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_164.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_166.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_167.wav  that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_168.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_169.wav  cared more about himself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_174.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_181.wav  we have a great relationship
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_182.wav what did you say his name was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_183.wav overdose multiple times
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_193.wav who I'd become I didn't know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_194.wav  know who it was anymore
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_195.wav  in the mirror I just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_196.wav drugs and drinking so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_197.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_198.wav  yourself and working on staying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_199.wav healthy yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_201.wav it was just a mess
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_204.wav  multiple times

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_205.wav I haven't been back to him
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_206.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_207.wav night
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_208.wav  move

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_211.wav to get away from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_214.wav  chaos

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_215.wav  I wanted
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_216.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_217.wav and you said that you go to a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_218.wav  so where I really wanted to get

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_222.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_224.wav I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_226.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_230.wav so that I don't stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/39/WomenWhoStutter_39_231.wav  and I've done that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_0.wav cuz I've heard people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_1.wav  certainly feel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_5.wav  it's a negative

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_6.wav  I didn't want to talk about it with anybody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_7.wav they're great and I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_9.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_11.wav  I'm at a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_12.wav  so I didn't tell them at the beginning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_13.wav  there is a stigma

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_14.wav  coming out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_16.wav but I don't know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_17.wav like out in public
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_19.wav  Chicago and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_20.wav and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_21.wav  you never discussed it with me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_23.wav  I'm not sure that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_25.wav that I felt like I had to the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_26.wav may have helped me at the time and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_27.wav  So

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_28.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_29.wav  whatever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_30.wav I still feel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_31.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_32.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_33.wav  about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_35.wav no she's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_36.wav right I mean how did that come about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/40/WomenWhoStutter_40_39.wav  calendar or their
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_0.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_1.wav  definitely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_2.wav  thanks for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_4.wav I have actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_7.wav cause is faculty

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_8.wav he actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_11.wav like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_12.wav  it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_13.wav  think I am because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_14.wav  as is every
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_15.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_17.wav contin play did it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_20.wav Sandria

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_21.wav  Cares actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_22.wav  cuz that cuz

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_23.wav toes I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_26.wav minus trade of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_27.wav programs and everything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_29.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_30.wav phr
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_36.wav I've actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_37.wav and it's taking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_38.wav therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/41/WomenWhoStutter_41_39.wav  it is also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_0.wav stutter rock star.com

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_1.wav your effort what you've done
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_3.wav master Masters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_6.wav communicator manual
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_8.wav and I skipped 8 and 9

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_9.wav  give the things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_10.wav that I wanted to say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_11.wav 89
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_13.wav visual aids and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_14.wav don't really like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_17.wav  I've been looking at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_18.wav  it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_20.wav social work to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_24.wav professional career
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_26.wav  actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_28.wav find their own solutions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_29.wav and so to me the word

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_30.wav a good persuader
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_32.wav action type of thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_33.wav but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_34.wav  just doesn't fit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_35.wav my approach
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_36.wav are they supportive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_38.wav  the beginning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_39.wav and certainly when I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_40.wav  yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_43.wav  internal struggle and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_45.wav when I was traveling with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_47.wav she asked a lot of questions

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_49.wav and help me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_51.wav cuz I didn't know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_52.wav and what is that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_53.wav  time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_54.wav time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_56.wav over me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_59.wav in addictions and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_60.wav  it to anyone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_63.wav you've ever come across
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_65.wav  person who stutters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_67.wav slam poetry
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_68.wav because I can do that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_69.wav peep and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_72.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_73.wav  I feel and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_75.wav lucky really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_77.wav as you mentioned
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_78.wav  I think I got a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_79.wav  them talking to me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_80.wav  instead of me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_81.wav Jennifer gives you an opportunity to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_82.wav got to educate her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_84.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_85.wav if you could offer a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_86.wav that person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_88.wav  scary

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_89.wav  bye
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_90.wav  oftentimes we don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_91.wav the credit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_92.wav of acceptance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_93.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_94.wav  our fears are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_95.wav  of things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_96.wav I started

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_97.wav solutions to them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_98.wav so it was a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_99.wav I'm closest to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_100.wav um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_101.wav which was a huge hurdle
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_102.wav and it takes time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_103.wav but it's whole worth
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_104.wav and authentic life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_105.wav  it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_107.wav you can do for yourself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_109.wav for being a guest on today's show
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_110.wav thank you for this opportunity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_111.wav you're welcome and you've been listening
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_112.wav women who stutter our stories

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_114.wav  social worker
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_117.wav work to my benefit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_118.wav  unintentionally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_120.wav I started smoking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_121.wav have something in common
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_124.wav going really well today down

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_125.wav artist things that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_126.wav make your job so much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_127.wav  amount to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_128.wav their life being in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_129.wav  cool so do you miss it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_130.wav oh absolutely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_134.wav for yours okay and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_135.wav place I worked was in the Yukon

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_137.wav or deal with your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_138.wav duttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_139.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_140.wav you know about a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_143.wav thank you so the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_145.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_146.wav hiding not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_147.wav decided at 16 that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_148.wav I just wasn't going to talk very much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_149.wav  with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_150.wav explaining myself or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_151.wav of course I was still in high school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_152.wav and I just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_153.wav it worked rather well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_155.wav and just start over
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_156.wav but certainly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_158.wav and started looking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_159.wav totally isolated myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_160.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_162.wav being part of this community

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_163.wav it's deep learning curve
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_164.wav so to get us started could you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_167.wav  lot to learn
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_169.wav  just so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_170.wav amazed at how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_171.wav open and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_172.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_173.wav welcoming people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_174.wav  seems
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_175.wav stupid you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_176.wav  come out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_177.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_178.wav I can't think of anything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_179.wav specific

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_180.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_181.wav and what keeps you busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_183.wav other than
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_185.wav harder to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_186.wav to use those tricks
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_187.wav in the sense that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_188.wav why am I expanding this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_189.wav I think part of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_190.wav was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_191.wav facilitated by learning about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_192.wav  self
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_193.wav in the sense that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_194.wav  I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_196.wav and how do you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_197.wav  I can be as myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_198.wav and not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_199.wav in Saskatchewan
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_200.wav in the middle of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_202.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_205.wav true

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_208.wav it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_209.wav feels a lot better not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_210.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_213.wav  before I answered a question

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_215.wav they thought I was really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_216.wav you know concentrating on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_217.wav and to keep busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_219.wav meant something different than

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_220.wav we develop those
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_221.wav tactics and they become

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_222.wav  almost
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_226.wav when I was telling them you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_227.wav this didn't go away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_228.wav my mother

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_230.wav  geez
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_231.wav you could have said something you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_234.wav  better
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_235.wav  they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_236.wav it's always been they talk more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_238.wav  usually just filled with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_239.wav doing things around my house
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_240.wav what's Masters is about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_241.wav I can try
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_242.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_243.wav when I first went I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_244.wav  your high school teacher mentioning it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_245.wav and I thought
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_247.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_248.wav it really surprised
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_249.wav  you know feel comfortable with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_250.wav  and the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_251.wav have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_254.wav  one and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_255.wav it's really up to you how quickly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_256.wav  process
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_257.wav you learn things that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_258.wav what did you retire from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_259.wav I was a social worker

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_260.wav I can't really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_262.wav  it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_263.wav if it's like this everywhere
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_264.wav there's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_265.wav you know 15 to 20
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_266.wav  large city

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_268.wav say as much or as little as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_269.wav you get to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_270.wav write your speeches which
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_271.wav  unexpected perfection

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_272.wav what could be better
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_276.wav don't feel that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/42/WomenWhoStutter_42_278.wav  the arctic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_0.wav open and accepting of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_1.wav  question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_2.wav if you could offer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_3.wav it would be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_4.wav  but challenging

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_5.wav  and just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_6.wav as easily and gently

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_7.wav deficult to handle
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_8.wav  our hearts out so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_9.wav more the focus now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_11.wav  kind of serious

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_12.wav portive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_13.wav good majority of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_15.wav  about it as opposed to how I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_16.wav  not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_17.wav being a parent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_18.wav  and I can continue to do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_19.wav  much in the last
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_21.wav  so no other way to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_25.wav  people who love
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_26.wav  heard that's a wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_27.wav  and I think it's a great way to get started with the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_28.wav  and don't even really take

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_29.wav what were you looking for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_30.wav I didn't want to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_31.wav  kind of little struggle
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_32.wav  the negative thoughts into something

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_33.wav  gotten easier
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_34.wav  and it's no better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_35.wav open to the idea of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_36.wav  negative way it will just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_38.wav  exposed to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/43/WomenWhoStutter_43_39.wav  and so that's how I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_1.wav  wow perfect way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_2.wav how are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_3.wav  so it is different but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_5.wav  speech impediment but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_6.wav  guessing I will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_7.wav and I've played tennis my whole life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_8.wav  I'm in the classroom or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_10.wav I probably should but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_11.wav you played most of your life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_12.wav and what you do to keep busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_14.wav outlet available
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_16.wav you should have speech therapy when you were growing up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_17.wav a special education teacher
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_18.wav and also I had a 10

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_21.wav painting and that's actually where I met
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_22.wav grownup in that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_23.wav perse time and I've been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_24.wav well ever since

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_26.wav  really well we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_27.wav  you were speaking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_28.wav  never stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_29.wav  hmm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_31.wav Bash a lead
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_33.wav I do I feel like I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_34.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_35.wav either way so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_36.wav Jeopardy that you went to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_37.wav  yeah actually my twin

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/44/WomenWhoStutter_44_38.wav he didn't but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_3.wav developing with a mobile

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_7.wav and like a practice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_11.wav up your feedback sort of thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_15.wav I lived there for you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_19.wav 5 in the morning oh my goodness

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_21.wav  thanks for having me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_23.wav if you don't try like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_26.wav reminder stuff like you're not alone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/45/WomenWhoStutter_45_36.wav  directly like in both

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_0.wav  anthropology in the first place
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_1.wav well psychology I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_2.wav  so it's clothing able to cross reference I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_6.wav well I know some people stutter more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_7.wav  cool what do they call stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_8.wav  oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_10.wav  know what types of things do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_11.wav I have system system was a singing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_12.wav  they were like 670 or 10 or whatever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_13.wav so what was the panel that you were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_15.wav I'm so happy to have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_16.wav  say yes I am

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_17.wav it should be is one of our board members used to be on it but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_19.wav  building up so yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_22.wav  living since this is our third time doing it now so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_23.wav  that's awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_28.wav like you're at a point
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_30.wav cyclic also

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_32.wav  don't ask about it either
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_33.wav psychology and the anthropology

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_34.wav  about it do you know if there is an Italian stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_35.wav what do you do for fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/46/WomenWhoStutter_46_37.wav  not very well anymore used to be better at it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_0.wav  here it was great talking to you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_2.wav  I live with his
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_3.wav  it until I was a lot older I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_5.wav  my mom posted on a community
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_6.wav do you feel it helped

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_7.wav  that I could kind of live like a happy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_8.wav sure so my name is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_9.wav  that year that I stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_11.wav it went really well overall

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_12.wav like they didn't have to feel comfortable
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_13.wav hitter c class and other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_19.wav  be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_20.wav cuz I thought that it would

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_21.wav it would kind of make me seem well-rounded
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_22.wav but I felt good telling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_24.wav  so I like to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_25.wav  have question

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_26.wav question that about you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_27.wav I had a lot of parent meetings last year

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_30.wav you not to take it personally because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_31.wav  I believe maybe not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_33.wav so when did you go to your first
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_34.wav I went to my first conference

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_35.wav  formative experience they would be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_37.wav that you can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/47/WomenWhoStutter_47_38.wav  old-timers I guess you could call it people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_0.wav  people who stutter how do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_1.wav  five years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_3.wav what a perfect ending

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_6.wav  where is it today and just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_8.wav well what a great way to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_9.wav well and you're held Emily I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_11.wav  giving me tools so I will

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_12.wav  you're from and what you do to keep busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_13.wav like else

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_16.wav  like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_21.wav  of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_22.wav  what I'm trying to avoid but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_24.wav  Perfection

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_25.wav what's it like when you come
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_30.wav looking forward to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_31.wav you don't recognize how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_32.wav  until you struggle with it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_34.wav become better listeners
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_35.wav Ford Cedar Crest

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/48/WomenWhoStutter_48_37.wav basically throughout that speech is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_1.wav  form a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_2.wav  it is a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_3.wav absolutely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_4.wav  who also stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_6.wav  with other people who stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_8.wav  we did of a child daughters so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_9.wav  children pretty

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_10.wav  for children that stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_11.wav  at the NSA store yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_12.wav and this has been women who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_13.wav  again

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_14.wav  well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_17.wav I love how you say that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_18.wav  do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_21.wav disabilities we have some with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_26.wav  sure well my name
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_27.wav  on these different characters

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_28.wav  children
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_29.wav  or really excited about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_30.wav yes I mean this is not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_31.wav  side projects or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_34.wav and what's the name of it again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_35.wav have access to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_36.wav  that Stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_37.wav yes I have and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/49/WomenWhoStutter_49_39.wav  thing yet but I've heard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_4.wav from the throat where

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_5.wav when we start
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_8.wav because compared to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_9.wav 5 days ago
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_10.wav  I just felt

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_21.wav  sharing my journey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_24.wav and I thought

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_27.wav and I thought what is he doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_31.wav mensions it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_32.wav  I'm interested in that whole
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_35.wav  move away

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_39.wav  so I joined in your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_42.wav  community so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_43.wav  really enjoy giving
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_44.wav  I'm currently a member of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_51.wav but what did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_53.wav  in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_55.wav  helping me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_64.wav  involved in doing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_65.wav well about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_68.wav that I was inadequate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_73.wav  me because of it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_79.wav what an

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_83.wav three years ago
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_84.wav  I heard about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_88.wav and I no longer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_98.wav do you feel as if you've

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_99.wav no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_103.wav and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_106.wav even though I feel great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_109.wav  I haven't really been using my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_110.wav  back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_113.wav  again but this time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_125.wav and no longer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_129.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_132.wav and I thought how are they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_138.wav  so I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_147.wav  yes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_150.wav the transition

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_160.wav  much from her actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_161.wav you really help me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_193.wav  so I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_214.wav going to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_217.wav when I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_226.wav well it seems like you have a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_227.wav  great communicator
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_228.wav  thanks yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_231.wav  34 years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_238.wav I really love

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_244.wav but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_250.wav  decided

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_251.wav  go ahead with it and I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_252.wav  doing it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_256.wav  since then every
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_258.wav absolutely not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_259.wav absolutely not that's great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_260.wav off often

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_261.wav I enjoyed it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_264.wav  think it's like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_265.wav  is your goal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_266.wav to overcome stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_273.wav  a lot more than I go out and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_274.wav who about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_276.wav  dependent on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_286.wav that's fantastic I think that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_287.wav  and to enjoy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_288.wav speaking like everybody else does

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_289.wav  is all about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_290.wav speaking and enjoying it and getting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_293.wav  what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_295.wav  with their stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_307.wav it's nothing to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_312.wav to an hour sometime

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_315.wav do occasionally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_317.wav what a beautiful way to wine

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_318.wav it must be really exciting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_321.wav times when it's been a real

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_322.wav but to be able to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_325.wav  to do public

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_326.wav speaking what exactly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_329.wav  about my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_331.wav you say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_332.wav they run monthly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_335.wav are involved with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_339.wav think as well but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_341.wav  Mom
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_342.wav invite someone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_349.wav  great organization for women
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_354.wav so king right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_361.wav  well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_363.wav that you speak to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_364.wav  most
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_366.wav I appreciate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_367.wav and some of them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_369.wav a lady came up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_370.wav  me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_372.wav but in her mind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_373.wav  helping such as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_374.wav  finishing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_376.wav looking away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_377.wav said actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_378.wav well from my experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_380.wav thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_381.wav someone is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_384.wav  mm-hmm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_386.wav my audition
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_387.wav I was putting this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_388.wav  of the groups that you've spoken to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_389.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_391.wav  chain store in the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_392.wav  one was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_393.wav is to remember
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_395.wav  maybe when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_398.wav not mine over
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_400.wav what you do to keep busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_402.wav selved teacher
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_403.wav  so a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_404.wav my mind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_409.wav  so even at age

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_410.wav  I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_411.wav something that was bad

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_412.wav and was saying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_413.wav  was anxious about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_414.wav  that's amazing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_418.wav and I was sat

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_419.wav the doctor
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_422.wav I live in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_424.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_425.wav  it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_426.wav okay and when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_432.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_433.wav  and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_438.wav but I couldn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_441.wav  therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_480.wav what was it about it that you think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_482.wav the impact that it did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_492.wav  that's what really helped me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_495.wav and just not being
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_500.wav  to normal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/50/WomenWhoStutter_50_502.wav  public speaking and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_1.wav somebody in the health care

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_2.wav and really how it would help
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_3.wav what do you do for fun

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_5.wav I do weight training for fun
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_6.wav  has ultimately

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_8.wav  for being a guest on today's show
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_11.wav  just the issues hormonal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_13.wav how do people react
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_14.wav  alliance

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_19.wav  Ontario
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_20.wav because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_21.wav so to get us started could you formally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_22.wav  learning

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_23.wav  pretty well in my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_24.wav  life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_25.wav  therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_27.wav  thought about it but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_30.wav because stuttering is a part
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_33.wav like I said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_35.wav  have to remember that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/51/WomenWhoStutter_51_36.wav my speech that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_1.wav  thank you thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_3.wav  and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_8.wav ha moment that you had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_10.wav but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_11.wav two weeks of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_13.wav to say it but I'm thinking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_15.wav  and then just doesn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_17.wav  to eventually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_18.wav require any
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_20.wav  my friend those two people are the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_22.wav  it's because of study
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_24.wav this is the same that she's really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_25.wav take a little babysit but your little
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_27.wav  overreaction myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_30.wav  cuz I will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_31.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_32.wav you know the best place for you to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_33.wav  through the 9th of July

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_34.wav you can apply for a scholarship
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_35.wav  make it affordable

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/52/WomenWhoStutter_52_37.wav  lots of other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_0.wav how are you today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_4.wav  and I really appreciate the fact how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_8.wav  make you feel when you're at that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_11.wav  I actually have a stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_13.wav  I am doing well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_14.wav all right wow how did you get into that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_15.wav  important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_18.wav  actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_19.wav I think it was more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_21.wav  hmm and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_22.wav only recently have chapters opened up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_23.wav  well I must say I love your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_24.wav yes I think so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_25.wav  so I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_26.wav I told you just sort of new and upcoming

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_27.wav and the reason that I asked
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_30.wav just did one for like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_31.wav  and we don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_32.wav then recently when the article about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_35.wav but I think it's alright
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/53/WomenWhoStutter_53_38.wav  more uncomfortable about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_0.wav something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_5.wav perfect

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_7.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_10.wav when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_12.wav never met at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_13.wav fair bit of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_14.wav  fear a dumb what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_18.wav  lots of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_19.wav  So I very quickly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_20.wav  rap

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_24.wav what you do to keep busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_25.wav buying some satellite data

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_27.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_28.wav  by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_30.wav okay I'm not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_31.wav  by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_35.wav  as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_36.wav  hope and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/54/WomenWhoStutter_54_38.wav I've heard other people say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_4.wav  publicly and I like to create

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_7.wav seeker who has a stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_8.wav  of our other sites and who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_10.wav  Maybe I could email her and tell her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_11.wav  hired you I knew you had a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_12.wav  I think it's like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_13.wav  about one thing and I knew

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_15.wav  a pretty negative comment but for the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_18.wav  hear that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_19.wav film premiere thing he did on his
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_21.wav  do I do that because of my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_23.wav  and has been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_24.wav  has been really that's what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_26.wav and our friend telling me pretty soon after I fell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_31.wav differently some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_33.wav  duttering so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/55/WomenWhoStutter_55_35.wav  create with the creative writing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_1.wav  community
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_2.wav  Um so because I just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_9.wav  go attend a stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_10.wav show with her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_14.wav  prefer to have that sort of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_15.wav I'm solidarity you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_16.wav  uniquely special about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_17.wav  about having that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_19.wav  another
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_21.wav I'm our community so it's like a long

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_23.wav I'm because for almost a decade you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_25.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_26.wav  A lot more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_27.wav  thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_29.wav  trying to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_30.wav  part

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_32.wav  a lot of people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_33.wav um we're actually kind of a small

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_34.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_35.wav a book about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_36.wav maybe 10
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_37.wav I'm ten other people on our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_40.wav  how all of my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_44.wav I'm not I've written

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_45.wav  where
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_46.wav  everyone's already kind of read like my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_50.wav  so you've done
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_51.wav able to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_52.wav the new job
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_54.wav  and kind of how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_56.wav  because she would ask you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_58.wav  like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_62.wav and publication first you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_64.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_65.wav who write and pitch
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_66.wav  I'm creating nonfiction you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_68.wav some contacts there but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_70.wav have the publication you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_71.wav the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_72.wav I'm editor who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_73.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_76.wav  today because I think it's going to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_78.wav I'm soloist
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_79.wav I'm soloist column

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_84.wav up in the piece ran on like Tuesday
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_86.wav  that was yeah I remember

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_90.wav and that it makes my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_93.wav  or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_94.wav more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_96.wav I'd love to wear you know reds and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_97.wav  know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_98.wav I'm all the colors of the rainbow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_99.wav  to try
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_100.wav I'm hide my stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_101.wav and hide my stutter somehow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_104.wav  you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_106.wav  just embrace it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_108.wav I'm like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_111.wav I'm informed in myself you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_112.wav I'm philosophical kind of way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_114.wav helling to embrace
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_118.wav  your physical

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_119.wav stuttering or your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_120.wav  piece that you had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_121.wav what are you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_122.wav  write about this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_123.wav  yeah I'm not tired
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_130.wav I'm disability

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_131.wav  hard to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_132.wav come to have your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_133.wav I've ultimately
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_134.wav I'm coming out the other side

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_135.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_141.wav  I really have problems

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_142.wav  perspective had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_143.wav and value to it you know and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_144.wav I'm so very entrenched you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_145.wav  women stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_148.wav I have strong feelings about this I guess
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_154.wav Coreers you know just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_155.wav  writing is how I try to gain
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_156.wav I'm visibility you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_157.wav you that well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_161.wav you know that my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_163.wav  I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_164.wav  versus

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_165.wav I'm a P style you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_166.wav I'm Teenage self

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_167.wav how can I be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_168.wav  lost on topics like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_172.wav I'm dating and you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_175.wav and how to be a woman

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_176.wav  don't get much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_177.wav  reflection or much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_178.wav  speak up and speak out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_180.wav and then I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/56/WomenWhoStutter_56_181.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_0.wav as always available

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_2.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_5.wav for you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_6.wav  excellent advice excellent
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_7.wav  with attendees

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_8.wav  well I tried
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_9.wav  trying to discuss

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_13.wav changed and how in the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_14.wav  therapy has

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_15.wav  tried to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_16.wav roach

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_17.wav chose and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_18.wav for about 11 years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_19.wav I've had various sororities
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_20.wav  about that a bit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_23.wav  Spares people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_24.wav  conference

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_26.wav an application
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_27.wav and that's at our web

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_28.wav tripper.ca
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_29.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_31.wav  to pack into it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_33.wav  I know people are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_34.wav  how other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_35.wav areas and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_36.wav thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_43.wav  can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_45.wav  by different people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_46.wav and I urge everyone to go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_47.wav and it's kind of a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_50.wav coming up in October

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_52.wav the association website
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_54.wav  you today Lisa

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_57.wav the pleasure.
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_58.wav  yes how did you find it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_59.wav well actually I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_60.wav so as in the 19th

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_61.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_62.wav  and when I moved to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_63.wav Toronto I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_65.wav in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_71.wav members
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_72.wav well we have I think we're out of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_74.wav and what you do to keep busy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_75.wav  well hi everyone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_76.wav  200
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_81.wav true

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_83.wav  are a lot of young
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_84.wav  people involved in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_85.wav organization
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_86.wav  friends who we had a good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_87.wav a couple of words
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_92.wav  so wilder

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_93.wav  I grew
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_95.wav  parents

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_96.wav deal with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_99.wav together in the family

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_101.wav  meetups
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_103.wav  support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_108.wav we do need to work on that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_111.wav grew up in Ottawa

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_113.wav  part of the national
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_114.wav stuttering association

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_115.wav  support
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_116.wav tunities to those that needed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_118.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_122.wav train

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_124.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_126.wav  team

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_127.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_129.wav  Canada

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_134.wav holistic attitude about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_135.wav  which is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_137.wav  I don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_138.wav  think it helped you much at least

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_140.wav people I've met have been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_142.wav order

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_146.wav  stuttering as I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_148.wav  cool and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_149.wav and that you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_150.wav people gave you the benefit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_151.wav  knowledge as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_154.wav good friends and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_156.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_157.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_158.wav  I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_159.wav that I've been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_161.wav have therapy as an adult
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_164.wav  it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_167.wav  I guess I find the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_168.wav it can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_170.wav it's uncomfortable it can be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_173.wav to make that a leaf and make that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_175.wav beria and sing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_176.wav and a attitude

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_178.wav the biggest difference of all I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_179.wav  absolutely I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_180.wav  to have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_181.wav  my true

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_182.wav  fluency
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_183.wav  techniques and strategy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_186.wav  on the other side
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_187.wav  so yeah you're right that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_188.wav I'm a little biased
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_189.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_190.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_191.wav what kinds of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_192.wav  with being a person who stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_196.wav fires

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_198.wav  if that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_199.wav  is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_200.wav  not be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_202.wav chins in life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_204.wav  18 years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/57/WomenWhoStutter_57_205.wav I've been involved in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_1.wav  listeners are going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_2.wav  be so inspired by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_3.wav  well and this has been a women
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_4.wav talking and communicated

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_5.wav when I first started
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_6.wav help did anybody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_7.wav  it's so important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_9.wav when you were younger too so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_10.wav  to trying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_11.wav  it a little bit easier for our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_12.wav  okay sure and so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_13.wav and so we have quite a few different

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_14.wav did you meet other women who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_15.wav when I did meet

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_16.wav while we're all different we share some
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_17.wav  and experiences

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_19.wav  and enjoy it because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_25.wav  people about who Stama people who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_26.wav  best itself and it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_28.wav  universities and house Society

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_30.wav and people against fraud
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_31.wav  I was wondering as you were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_32.wav  they have a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_33.wav  being able to do that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_35.wav  yeah oh my goodness it's just it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_36.wav it's just amazing what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_37.wav where I do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/58/WomenWhoStutter_58_38.wav  on people that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_0.wav  kind of creeping along you know it's like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_3.wav the invaluable

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_4.wav  today thank you I'm going to be crying again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_6.wav  little girl came in who is a kinder and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_7.wav is a gl
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_8.wav  of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_10.wav it's just wonderful to see and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_12.wav  special opportunity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_13.wav for a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_14.wav been married almost 30 years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_15.wav  one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_16.wav  find us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_17.wav  No
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_18.wav I'm hoping that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_19.wav be starting out on their journey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_21.wav  wonderful whirlwind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_23.wav people are gonna think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_24.wav  you know I've been a keynote speaker

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_25.wav  Annie the other any the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_26.wav  I still work on myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_27.wav thing to overcome for me to stand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_28.wav those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_31.wav A lot so I'm yeah I'm nervous and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_33.wav I am you know they say if you have just a few good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_34.wav  being vulnerable I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_35.wav strikes a cord in most

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_36.wav  see and hear somebody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_37.wav  that will be there for their first time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_38.wav  your first time hearing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/59/WomenWhoStutter_59_39.wav  I thank you and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_5.wav  that much
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_6.wav  this yeah we all know about that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_7.wav  in now it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_9.wav  I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_10.wav it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_13.wav you said which is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_20.wav  so you're like in a more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_21.wav conferences I know they had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_22.wav  the next world
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_23.wav community I see you in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_24.wav  other way and I found that group yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_25.wav you kind of were like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_26.wav a role model for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_28.wav is something about it though like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_30.wav  coming up behind us
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_31.wav  talk about with each

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_32.wav  yeah but we didn't and we talked about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/60/WomenWhoStutter_60_35.wav  feeling that he was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_2.wav  is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_3.wav  like 18 or 19

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_5.wav are you gonna go to Fort Lauderdale
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_7.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_9.wav  yeah so about every
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_10.wav talk to people and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_13.wav  them that hey we're all different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_15.wav and you are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_16.wav they're so cool like what
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_17.wav  like when you went to your first meeting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_18.wav Currently I work for the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_19.wav  decide to like want to go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_20.wav  about it house changed so many
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_21.wav  get there on Wednesday

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_22.wav  the first-timers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_23.wav  youthful and there's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_24.wav from all different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_25.wav it was exhausting and it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_28.wav  like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_29.wav may react

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_30.wav  it not only helps them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_31.wav it always like helped me feel less

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_32.wav  so you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_33.wav you guys also

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_34.wav  none of us were
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_35.wav  your feet like all the time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_37.wav  out the most for you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/61/WomenWhoStutter_61_39.wav  like if the patient has a problem

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_0.wav  eye-tunes today has
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_1.wav  accomplished that I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_2.wav I think going into 6th grade or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_3.wav did she like want to go to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_5.wav  was there like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_6.wav  the moment for you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_8.wav always remember like besides those
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_9.wav was there like a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_11.wav  like kind of sums up what the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_12.wav  up what the conference meant for you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_14.wav  and I was like oh my god like there if this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_15.wav  if this is just one person then this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_16.wav this is real and that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_20.wav  and go back into a speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_21.wav  therapy for the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_22.wav day's at the conference

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_24.wav  so I mean at that point had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_25.wav  so how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_26.wav how would you what advice would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_27.wav  you offer to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_28.wav a younger woman maybe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_29.wav was just like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_30.wav starting their journey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_31.wav  confronting stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_34.wav  meeting new people like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_35.wav  like I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_37.wav do something you think you would not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_38.wav what you're capable of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_39.wav  wow so well put
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_40.wav  stuttering I actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_41.wav and sharing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_42.wav  parts of your story because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_43.wav  about my story
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_47.wav  I actually did not and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_49.wav and I did go back into speech there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_51.wav  so going back to my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_54.wav  read people I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_55.wav  I like to think like probably

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_56.wav  better than the average person
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_57.wav  kind of used the people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_58.wav  surprise puzzle
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_59.wav  burned reaction so yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_60.wav  do you ever like address it with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_62.wav and like many Alaska

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_63.wav talking to professionally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_64.wav I have before

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_65.wav  good talking about it more and kind of like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_66.wav  like letting people know right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_67.wav  like advertising and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_68.wav  disclosure as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_70.wav break the ice a little bit with somebody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_72.wav  do that it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_74.wav it wasn't until
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_76.wav kind of saw that there's like groups and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_80.wav  yeah and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_82.wav  so each day is a little different

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_83.wav yeah or such a huge state
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_84.wav  wow and did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_85.wav  how many people came
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_86.wav it was the same group as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_87.wav  right so like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_88.wav so before you kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_89.wav in Anchorage that Stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_90.wav so far only know of to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_91.wav  talk about it and as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_93.wav  journey on their own

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_95.wav  own time right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_97.wav you found the NSA you're thinking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_98.wav  Can you trip and do what so we're gonna
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_99.wav but we're going to do a water

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_100.wav  your first conference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_103.wav once I got like a little bit of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_105.wav but I'm not a very like spur the moment
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_106.wav and plus you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_107.wav  Didn't really have like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_108.wav when did you arrive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_109.wav I came the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_111.wav what did you think like when you were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_113.wav well I was told that like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_114.wav  wasn't like that warm and fuzzy thing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_115.wav  thing I guess
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_116.wav I guess it was just being

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_117.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_122.wav  similar to what you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_125.wav  get it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_126.wav  for me it was very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_127.wav  a bit raiding to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_128.wav  just be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_129.wav  be me because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_130.wav  I don't always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_131.wav  give myself that permission
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_132.wav  sometimes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_133.wav even though after
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_134.wav where you know I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_135.wav  I do try to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_136.wav do try to be as fluent as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_137.wav  so like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_138.wav what did you do like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_139.wav  you to do this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_140.wav  so I have a Bachelor's of Arts

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_141.wav combination of both or probably
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_144.wav but never a moment

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_146.wav  so quickly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_147.wav  with doing a jog you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_149.wav and 10 of us and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_150.wav and I was scared we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_151.wav  to go to the first-timers
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_152.wav workshop yep I did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_155.wav orbal and what they were saying just like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_156.wav  like man

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_157.wav  at the courage and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_158.wav and the fearlessness

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_159.wav and you know to see
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_160.wav kids who stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_161.wav one with people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_162.wav from the tribes that's a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_163.wav eagerly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_164.wav  the future of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_165.wav  of our stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_168.wav did you have a favorite workshop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_169.wav let's see oh yes my favorite
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_170.wav  in the workplace and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_171.wav  hearing how other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_174.wav  was for living

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_175.wav  and she stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_176.wav  physicist yeah it's like it's freaking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_177.wav it's freaking amazing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_179.wav now do you talk about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_180.wav  don't stuttering with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_181.wav co-workers I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_182.wav own scary it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_183.wav it kind of works in my favorite

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_184.wav  I do now I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_187.wav  I was gonna ask that and like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_189.wav  so I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_190.wav  sometimes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_191.wav  I think it's really important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_192.wav  particularly women who stutter too

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_193.wav  better to be kind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_194.wav  be kind to ourselves

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_195.wav  we are like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_196.wav  feeding ourselves up you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_197.wav let that go and move on and know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_199.wav like each person has like a different

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_200.wav  yeah so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_201.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_202.wav Avenue of how they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_203.wav  express it or talk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_205.wav everybody has a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_207.wav  deal with in a very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_208.wav in a very different way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_209.wav  as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_210.wav as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_211.wav  stuttering con France I know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_213.wav  stutter too so she was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_214.wav was a great role

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_215.wav  we hate hearing she
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_217.wav  because she

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_218.wav  kind of taught herself to stop
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_220.wav  I know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_221.wav like how long have you stuttered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/62/WomenWhoStutter_62_222.wav I have stuttered so I'm 27

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_0.wav  to gain whilst they work
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_1.wav  so well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_2.wav joining other young
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_3.wav strangers that sounds

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_4.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_5.wav was deemed a round

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_7.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_8.wav you were going around very shy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_9.wav  especially a group on that size
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_11.wav  find themselves

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_12.wav July was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_13.wav in was my third

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_14.wav  speak into a mic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_15.wav  reform

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_17.wav say your name and especially
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_20.wav  so really myself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_21.wav connecting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_22.wav authentically and actively

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_23.wav that's so true and I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_26.wav at some point in the future so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_27.wav and I said I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_28.wav a course in counselling and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_29.wav  course I really hope I'm able
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_30.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_32.wav  person is she okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_33.wav that is something that is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_34.wav  um so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_36.wav because you've taken the time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_37.wav enough of us that know that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_38.wav we will always be moving in the right direction

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/63/WomenWhoStutter_63_39.wav  I'm the only ways up really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_1.wav  your story when we share

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_2.wav something that you've said so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_3.wav and yours is like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_4.wav but thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_5.wav  exactly is sand script

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_7.wav  of texts
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_14.wav  to a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_15.wav  so if like the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_16.wav  my god it sounds

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_18.wav that just popped into my head
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_19.wav  well first of all this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_20.wav like it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_21.wav  designed to like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_22.wav  in some way so I know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_23.wav oh my gosh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_24.wav  and storytelling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_25.wav and to see

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_26.wav telling sort of way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_27.wav  because when I first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_29.wav  stutter that you can use your voice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_30.wav and like it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_35.wav  they couldn't you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_36.wav  you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_38.wav selph in pose their own
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/64/WomenWhoStutter_64_39.wav  your hopes and your dreams and what you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_2.wav and I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_3.wav worry about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_4.wav  so just to kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_5.wav we have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_6.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_8.wav  for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_9.wav who wants
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_12.wav  He

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_14.wav  down
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_16.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_17.wav all that subject
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_18.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_19.wav  facing things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_20.wav and we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_21.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_22.wav  have always had to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_24.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_25.wav I return

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_26.wav  and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_27.wav  saying which

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_28.wav  that's okay because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_29.wav well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_30.wav oh young people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_33.wav but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_34.wav  really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_35.wav  two

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_36.wav for the first time that we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_38.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/65/WomenWhoStutter_65_39.wav  who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_1.wav  it has so much more to do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_2.wav that self-discovery
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_3.wav okay with like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_4.wav time you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_6.wav  being a guest today this was awesome

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_9.wav  out there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_10.wav  not very supportive or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_12.wav chosen to I mean that makes a big
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_13.wav  Thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_14.wav so like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_15.wav  and it did help me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_16.wav to be who I am
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_17.wav  I was 21

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_18.wav  the international one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_19.wav  I was overwhelmed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_20.wav go someplace and decomprive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_21.wav you feel like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_24.wav and that makes a big
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_25.wav  just don't get that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_26.wav  yeah so I guess the reason
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_27.wav  like a trip up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_30.wav look back at my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_31.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_33.wav experience it and be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_34.wav  is welcoming

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_37.wav  describe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_38.wav what would they be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/66/WomenWhoStutter_66_39.wav  second word
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_0.wav but as a woman

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_5.wav  do it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_6.wav are you still doing it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_9.wav  women who stutter our stories
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_13.wav  with which are things

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_16.wav I just can't do this anymore
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_17.wav  I just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_18.wav  who stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_21.wav  have to hide anymore

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_23.wav  small talk skills
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_24.wav situations out of fear

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_27.wav  we miss out on so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_29.wav I asked one of my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_33.wav when I sort of reached maybe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_34.wav it's just a process it's a life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_35.wav  of shame is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_36.wav in the human experience for a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_37.wav depression
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_38.wav those are things that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/67/WomenWhoStutter_67_39.wav you know it's unbelievable
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_1.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_4.wav  like I always to test
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_7.wav but sometimes you just have to like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_8.wav  into about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_12.wav  after which is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_14.wav  but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_15.wav automatically assumed that you don't want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_16.wav I met Grace and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_17.wav and I knew her as Gracie

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_18.wav percation and it seems like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_19.wav and I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_23.wav  he had
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_24.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_26.wav  and how she can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_27.wav  first friends to I think it's pretty cool

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_28.wav how can I be better at getting people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_29.wav  find the individual who

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_30.wav response video and for those
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_31.wav  notes with this up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_33.wav I it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_36.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_38.wav I'd have heard of friends as a guest
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/68/WomenWhoStutter_68_39.wav  Grace

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_1.wav  people who stutter it kind of like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_2.wav  fresh perspective and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_4.wav  them and sometimes you just not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_6.wav you're saying that you called

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_7.wav just like that amazing like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_12.wav  you know not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_13.wav run away from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_14.wav  so what kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_15.wav  Told you that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_16.wav  to say to a young person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_18.wav just so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_20.wav and I've had a total of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_21.wav which it did so which is good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_22.wav and then they about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_24.wav  it's just part of you yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_25.wav  really yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_26.wav Thout out yet so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_27.wav very big support

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_30.wav  that are already
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_31.wav  people who's.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_33.wav dog is one of my favorite
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_34.wav what do you have what's up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_35.wav what's that conference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_37.wav  musical theater

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/69/WomenWhoStutter_69_38.wav  was in the beginning of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_1.wav I came back to America

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_2.wav  I then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_3.wav good question

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_4.wav  spoke English I felt like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_6.wav in the Middle East

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_8.wav talking to their neighbor and I can tell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_9.wav  it you know it kind of like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_10.wav  more up front just because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_11.wav second graders

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_12.wav  more like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_14.wav correct some of those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_15.wav  University a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_16.wav incompetent we're not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_17.wav I'm prepared you know we simply
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_18.wav my what is a 80

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_19.wav posing cons on each
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_21.wav a letter and then I brought that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_23.wav  college I was thinking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_25.wav  thought you know that you could benefit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_26.wav and they didn't really see a problem
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_27.wav come out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_29.wav so did you ever meet another
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_30.wav when I joined the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_31.wav  of like fresh air and I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_33.wav I met him and his wife and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_37.wav goes to work with people who stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/70/WomenWhoStutter_70_38.wav but I think it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_0.wav  self
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_1.wav  and so it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_2.wav  of my shell
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_3.wav  yeah so do you think you've done

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_4.wav  for like my post college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_5.wav people who also have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_7.wav  my sister in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_11.wav  if I like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_12.wav Aileen hey how are you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_14.wav  like of course I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_15.wav  so I think that where I am now is just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_17.wav  huge

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_18.wav  the feeling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_19.wav  each other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_21.wav options since we last talked
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_22.wav  coming with me to a one day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_24.wav  or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_25.wav  friends

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_27.wav amazed and inspired by
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_28.wav changes that I'll be able

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_30.wav  then my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_32.wav  Richman

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_33.wav and there's just so many
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_34.wav  like stuttering isn't part of those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_38.wav my senior year of college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/71/WomenWhoStutter_71_39.wav  going on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_0.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_1.wav documentary

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_4.wav  have something else that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_5.wav  where my weakness of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_6.wav  change one like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_7.wav  like practice for speaking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_8.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_9.wav  only one issue that I have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_10.wav but after getting like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_11.wav  getting like the adult

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_12.wav  group in Tokyo I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_13.wav when I was the 24

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_14.wav  the everything
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_16.wav  cannot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_21.wav  speaking skill set it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_22.wav when he hired new person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_23.wav  you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_24.wav  yeah this is one of my aspect

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_25.wav  so as you can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_28.wav  you know when everybody's curious about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_29.wav  confident with your co-worker
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_30.wav  about my startling

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_31.wav  you stutter more because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_32.wav  yeah start doing the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_35.wav  can contribute to the future
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_36.wav  I'm actually like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_37.wav that is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_38.wav  Thank you yeah so it's great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/72/WomenWhoStutter_72_39.wav  to the future yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_1.wav  I don't stutter and you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_4.wav like middle school and it was like I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_5.wav  available on the blog

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_6.wav  with because it was you know no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_7.wav and for the most part that was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_8.wav  half years and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_11.wav  really been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_12.wav  been really interesting seeing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_13.wav you know how people react or they don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_14.wav because first of all like you already
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_15.wav not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_17.wav  is like it almost you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_19.wav  your phone and what keeps you busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_20.wav the therapist said was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_21.wav on nobody else cares nobody else

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_22.wav  about it after the fact like we're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_23.wav  like where everybody is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_24.wav  how it sounds recorded
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_25.wav it's just a thing people don't expect to hear

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_29.wav where you just said you know this is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_30.wav about two months after I turned 30 I started

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_31.wav you know it wasn't a put down it was a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_32.wav  striving for fluency and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_33.wav so it was kind of like I had a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_34.wav  and you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_36.wav  Life is so much more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/73/WomenWhoStutter_73_37.wav  and I appreciate that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_2.wav and he
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_3.wav  his method was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_5.wav  then as you inhale
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_7.wav it didn't work

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_10.wav  do not do any exercises
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_11.wav  I just speak

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_12.wav  regardless if I block
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_14.wav  experiences they had some kind of a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_15.wav you know less than positive
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_16.wav  choice to make because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_17.wav  yeah because if I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_19.wav to 13 and then went into high school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_20.wav  school my teachers they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_23.wav  so thank you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_24.wav  thank you for just being your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_25.wav  attentional choices and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_26.wav I'm happy that you shared with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_32.wav  So my first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_34.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_35.wav  I didn't want to sit at the desk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_36.wav  system and started grade 8 and love
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_38.wav  you said you live in Connecticut right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_42.wav that's quite the commune isn't it it really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_43.wav  it it really is but my passion

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_44.wav for like 20 years and then but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_45.wav  but I really am near

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_46.wav  girl
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_47.wav  yeah so wow so the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_48.wav  I love to travel
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_49.wav  there's so much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_51.wav  young people and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_54.wav reaction to you stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_55.wav  you stuttering I mean or do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_56.wav do they even know all they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_58.wav  definitely a challenge and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_59.wav  and I don't really think it's just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_60.wav  going in as a person who's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_62.wav and I don't take things personal but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_64.wav  and letting them know I do stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_65.wav  day one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_67.wav  now I think it's October
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_70.wav  international

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_71.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_73.wav I start and they're like yeah we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_74.wav  conversation you know yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_76.wav  like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_79.wav just holistically
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_80.wav  how we really treat

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_82.wav  is definitely more than just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_84.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_85.wav  I probably had a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_86.wav  incident in the past where

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_88.wav  Cation correct
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_91.wav  have no idea it's not right and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_93.wav that's a lot about who you are but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_98.wav  sometimes in our minds

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_100.wav  because I'm open about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_102.wav  I will share

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_103.wav  I will share the names after
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_104.wav you know I'm a super hero and they're like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_105.wav  like you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_106.wav  can you help us out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_107.wav  shy away from those type of things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_108.wav  that is such a great question because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_110.wav  to let the nose stutter or how
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_111.wav  of people coming at us so I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_112.wav  so I think because of that we have become
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_113.wav a community so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_114.wav  so obviously that's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_116.wav  begin to get involved

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_118.wav I would say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_119.wav  I mean adults whose daughter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_121.wav  right now because I believe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_123.wav probably in the New York school system

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_127.wav  shapes me white and today
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_129.wav  as people who stutter to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_130.wav  as you said to educate other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_131.wav  the kitchen

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_135.wav  life of yours okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_137.wav  and then make up come back

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_138.wav  can
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_139.wav  like trying to fell skin

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_140.wav  skin care products
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_141.wav  such amazing customers and return

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_144.wav  helping the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_147.wav talking to people and you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_148.wav  and you know again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_149.wav  I went to the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_150.wav  to the president to beg him
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_152.wav  no I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_153.wav  on things and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_155.wav  I think I'm going to turn myself out there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_156.wav has opened up so many doors for me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_158.wav  wow so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_162.wav  stutter particularly women
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_163.wav men tend to let the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_164.wav  by you just going
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_165.wav  just going after what you want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_170.wav  so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_171.wav  me a long time just in my name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_173.wav so nine out of ten times I can say my name
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_176.wav  want and I'm speaking to a young lady

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_180.wav she's very scared of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_183.wav but yesterday I spoke to a woman maybe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_184.wav  woman maybe 30 seconds
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_185.wav to my table at the event

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_186.wav  and we don't know each other we've never
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_187.wav  comfortable enough to be able

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_190.wav my professor I blocked on every single
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_191.wav  or you know like a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_192.wav  like a verter eyes or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_193.wav acknowledged out I think it's pretty cool

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_194.wav  yeah me too I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_195.wav  on your speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_196.wav  wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_198.wav  here us in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_204.wav  after the two years I told my mom
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_205.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/74/WomenWhoStutter_74_206.wav I don't know if I could say the name
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_0.wav  a new life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_1.wav  enjoyed it that much for that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_2.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_3.wav to grow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_4.wav  yeah that was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_5.wav  Lots of experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_6.wav  one women

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_7.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_8.wav where they come

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_9.wav so it sounds like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_10.wav  you know is thinking about speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_11.wav  there but when you do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_12.wav  what I'm doing as a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_15.wav and no water
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_16.wav  all the taxes or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_17.wav  the teachers they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_18.wav where you open about your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_19.wav there are good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_20.wav  how involved you are your family

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_21.wav  yeah then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_22.wav yes so I'm in a school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_23.wav  so I got it from both
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_24.wav  Besides

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_25.wav it will go away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_30.wav in Germany we had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_31.wav  learnings from
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_32.wav  questions

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_33.wav  interviews
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_36.wav  that's right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_37.wav  as a woman who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/75/WomenWhoStutter_75_39.wav well as it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_2.wav  so I mean from what I've understood
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_3.wav  presented to us and then also like it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_4.wav  like it's very important for the board
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_6.wav  look I might tend to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_8.wav what is your plan to get the word out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_10.wav  we should share

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_11.wav information with each other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_12.wav and literally came out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_13.wav and came out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_14.wav and make you create a sort of like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_17.wav  working towards this social model
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_18.wav  diversity and inclusion because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_19.wav  programs that are already happening and just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_20.wav  belief about diversity and inclusion

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_21.wav  should be to not need them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_22.wav or just to the point where

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_23.wav  specializing into the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_25.wav  language barriers

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_27.wav  totally agree
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_29.wav  to help others exactly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_33.wav you know we're stronger people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_34.wav  in conversations

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_37.wav  I really appreciate that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/76/WomenWhoStutter_76_38.wav and this has done women

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_0.wav empowered in so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_1.wav  online and just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_2.wav who stutter our stories
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_4.wav I went through periods where I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_6.wav well I definitely need a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_7.wav looked at my linkedin profile

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_8.wav  you ask me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_9.wav stuttering so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_10.wav pornetics and they do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_11.wav  control

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_12.wav they're stuttering and not
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_13.wav  tier platform or like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_14.wav  so I definitely do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_15.wav today so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_16.wav  of hiding my stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_17.wav that I show and I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_18.wav the gist of avoidance
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_19.wav the cognitive space and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_20.wav the more you allow yourself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_21.wav  I'm not sure I explained that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_22.wav  situations that are scary
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_23.wav  and they obviously did not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_24.wav oh I love her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_25.wav  part or did you do individual

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_26.wav  from where I live is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_27.wav I'm super excited to go to the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_28.wav is that sound more familiar it does
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_29.wav it's very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_30.wav yeah sure so it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_31.wav  that I still have to learn but that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_32.wav  I like that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_33.wav with intent

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_35.wav  also comes to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_36.wav  goal I think that a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_38.wav  miskey ones that you truly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/77/WomenWhoStutter_77_39.wav  it's exciting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_0.wav  realize is that a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_2.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_3.wav that's been one of my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_6.wav the effects that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_7.wav  now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_9.wav  South Carolina State

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_12.wav I needed the job because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_14.wav it was trying to be fired

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_16.wav  I think it interfered
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_17.wav  those moments but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_19.wav side of that box
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_21.wav cuz that's what we have to do you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_23.wav  sometimes I think it's just important to take a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_24.wav  step back and let other people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_28.wav my self-worth was in the toilet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_29.wav  but then when I started to finally

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_33.wav  said
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_36.wav  much lighter because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/78/WomenWhoStutter_78_37.wav  for this community with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_0.wav  available as always

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_3.wav  used to have an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_4.wav right because true you know we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_5.wav  it's something it's really power
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_6.wav I'll just type things out in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_7.wav where are you going what's your goal what do you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_8.wav  a better writer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_9.wav  yes and no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_11.wav  that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_12.wav  yeah wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_13.wav  really chicken and I just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_15.wav  want to speak even if I stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_17.wav  right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_18.wav are not super busy then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_19.wav and then you study worse

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_22.wav  therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_23.wav  I think that the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_24.wav  all the time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_26.wav  for a class or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_27.wav  need it to deal with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_31.wav  who stutters all the time I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_32.wav  you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_33.wav when they ask you for your name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_35.wav  okay well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_37.wav that are brain

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_38.wav  interrupting is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/79/WomenWhoStutter_79_39.wav  right if we're listening

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_0.wav  the part of the experience
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_1.wav you've listened to a lot of the podcast

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_2.wav  are listening today
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_3.wav  voice so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_4.wav  a lot of different things and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_5.wav  at you know people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_6.wav  you know people will make a comment on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_7.wav like wow is anybody listening

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_11.wav  why did you choose this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_17.wav 3 I think they're out doing all right yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_18.wav  career so but you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_23.wav and using this technique

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_24.wav  yeah so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_27.wav  with colleagues or friends

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_28.wav  yourself covert anymore
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_29.wav  No I think I would consider

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_32.wav  a little bit like avoidance reduction but when you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_33.wav  ever what do you think of voluntary

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_34.wav  research and a whole bunch of other things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_37.wav  people at the international

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/80/WomenWhoStutter_80_39.wav  making friends from other countries
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_0.wav  Hey it's going pretty

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_2.wav  volunteered or do you get paid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_4.wav we're hired on as a counselor

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_6.wav  okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_7.wav  thing called stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_14.wav  when I have a little
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_15.wav have these gases that come through

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_17.wav  been great honestly it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_22.wav  for worried about being

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_25.wav  A stutter so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_27.wav how to like children

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_29.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_30.wav I mean it's our kids as

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_32.wav  yeah sure thing so I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_35.wav  I found that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_37.wav  like okay and kind of accept that as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_43.wav  I'll hopefully

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_44.wav a bit different and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_45.wav I haven't had a lot of problems with it honestly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_46.wav and other people do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_47.wav well you're very lucky so it sounds like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_49.wav in every aspect of our lives and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_52.wav  I like to go hiking go camping

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_55.wav like once I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_61.wav  she definitely kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_64.wav  through therapy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_67.wav  and so my college offered

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_71.wav  such experience I learned a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_72.wav  techniques to kind of a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_73.wav  study in college my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_74.wav my degree is wildlife and wild land

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_76.wav  University in Utah all right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_77.wav  Stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_78.wav  so I don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_79.wav  really remember a lot of the offense

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_80.wav that led to me kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_81.wav  remember it happened

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_82.wav December after my first semester
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_83.wav and we were at my aunt's house and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_86.wav  this thing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_88.wav  with me all of these years because of how

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_90.wav I sell but it's been really hard and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_91.wav  I think we should have a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_92.wav a part that was kind of a bidding
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_93.wav what got you interested in that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_97.wav  did that make
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_98.wav  I don't want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_99.wav  I think it's been me a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_100.wav  I think it's made me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_101.wav  I think it's made me a better person for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_102.wav learn to treat

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_105.wav  was taught to me I think by having
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_106.wav  A stutter for sure yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_107.wav  stutters so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_108.wav  yeah I think it's a real good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_109.wav  how you talk
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_110.wav does that kind of resonate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_111.wav yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_112.wav  I figured like well I don't really know if I want to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_113.wav  I bet anymore right so we're gonna work with animals

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_115.wav  insult me by
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_117.wav being in a place now where

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_118.wav my hurt feelings
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_119.wav people mock me and say hey

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_122.wav and you have to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_123.wav  to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_125.wav right so what's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_126.wav  did something in particular

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_128.wav  help you get to where you're at now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_129.wav  for sure and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_130.wav and that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_131.wav at time of my life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_135.wav what's the internet and the search like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_139.wav  at hundreds of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_140.wav  basically go to the conference every year
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_141.wav  A little of both

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_143.wav what was that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_145.wav went to one of those and then I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_146.wav  August of last year I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_150.wav  in a few weeks we're going to try to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_151.wav  To start that pack up again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_155.wav  chapter yes there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_158.wav  ask a question in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_159.wav  in our chapter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_160.wav in our chapter we've experienced
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_162.wav  I'm pretty cool yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_164.wav I saw
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_165.wav on Facebook that it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_166.wav  was hiring this one here
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_167.wav Campalabana and so that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_169.wav  place honestly I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_171.wav  who's that are is an amazing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_173.wav  that's not in my favorite
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_175.wav what's so special about this

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_177.wav  through
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_178.wav the same things that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_179.wav  like a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_180.wav  person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_184.wav  to sit and listen and wait for them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_187.wav  wow so it sounds like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/81/WomenWhoStutter_81_188.wav or has that been a challenge
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_0.wav I'm doing really well thanks for having me today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_1.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_5.wav stand fat and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_7.wav division using
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_8.wav  hold me back or keep me from doing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_9.wav I get really nervous sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_10.wav decided to spend on Arabic was gone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_11.wav Arabic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_12.wav about stuttering in relation to Arabic

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_13.wav  I'm a therapist so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_15.wav  I think it's a good question.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_17.wav and then saying that's okay
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_18.wav  love everything enough and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_19.wav  it yeah so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_21.wav wow like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_22.wav who am I to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_24.wav like I mean I think we were useful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_26.wav even if I do it as a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_27.wav yeah I think I have it doesn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_28.wav  doesn't mean that sometimes I'll
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_29.wav or maybe you're just surprised and you realize

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_33.wav that they haven't shared
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_34.wav my presents

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_35.wav but there was so many gaps in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_36.wav unique perspective on the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/82/WomenWhoStutter_82_38.wav and I do struggle sometimes with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_0.wav  of disturbed by like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_2.wav  figuring that out I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_3.wav  shine I guess is the word but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_5.wav confident and like some people I don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_6.wav  I don't know like don't like it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_7.wav  like anymore or like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_8.wav I think because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_11.wav  time and it's also exciting so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_12.wav  family

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_13.wav  just huge for a first one but like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_14.wav  that's really been it like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_15.wav  so I it was emotional
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_17.wav  only for me the hurt is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_19.wav  and just promote
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_20.wav for a very short time one of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_22.wav for corporation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_23.wav  guest speaker for the day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_24.wav  and you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_25.wav  I heard that you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_26.wav  actually received
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_27.wav  I'm still and now I'm able to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_28.wav  tour I think it's because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_29.wav  yeah so we're asking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_30.wav  lady she was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_33.wav  made to what like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_34.wav  like you could tell they want to finish my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_35.wav  is different now are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_36.wav everything around us also changes the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_37.wav  and I think sometimes people don't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/83/WomenWhoStutter_83_38.wav your circle
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_0.wav make room for the stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_1.wav so I've had like you know practice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_2.wav you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_5.wav  yes and no like I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_6.wav  I can control it it seems

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_7.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_8.wav  feel uncomfortable or anything

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_9.wav your speech pattern as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_10.wav what you do to keep busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_11.wav  is it just for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_12.wav this other lady is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_13.wav does it like very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_16.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_17.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_18.wav  yeah well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_19.wav friends online
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_20.wav  good

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_21.wav first conference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_24.wav  because I wasn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_26.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_27.wav  did you do it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_29.wav  turn the it was like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_30.wav  it was just like insane like everybody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_32.wav  directly because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_33.wav it to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_34.wav  discuss like the benefit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_35.wav  so that would probably be something that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_37.wav  a teenager
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_38.wav I did not have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/84/WomenWhoStutter_84_39.wav those that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_1.wav  that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_2.wav that isolation is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_3.wav  10 or 28 fold

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_7.wav  that yeah this is going on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_8.wav on connecting with someone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_11.wav  number of confirmed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_12.wav  really ramped

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_14.wav  with anxiety and pressure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_15.wav  and therefore you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_17.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_18.wav  be afraid it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_20.wav  family and friends
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_22.wav  almost to our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_23.wav unprecedented times
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_24.wav  so I thought it would just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_25.wav  just realize
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_26.wav  feel less alone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_27.wav  children so this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_30.wav  I'm going to do a test of all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_31.wav  A couple of just brief thoughts
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_32.wav and self-compass

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_33.wav  panic to make this phone call or you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_34.wav  or you know the world is closed

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_35.wav  I think practicing self care
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_36.wav  always felt ice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_37.wav  so you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/85/WomenWhoStutter_85_39.wav  truly are not alone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_1.wav um yeah we're alone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_2.wav because we're physically facing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_5.wav  to just voice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_8.wav you know that whole concert

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_9.wav you know that whole concept of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_13.wav  other starting some dial

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_14.wav  questions
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_15.wav  how are you feeling what are you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_16.wav  through this process
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_18.wav and I've seen more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_19.wav opportunities for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_20.wav  you another short

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_22.wav  for a video chat
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_25.wav  I think it's also really important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_26.wav  talked about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_27.wav  brief

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_28.wav being what it is that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_29.wav  feeling for many of us and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_30.wav and at first I kind of was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_31.wav no one that is close to me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_34.wav  I think that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_35.wav  all grieving normal

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_38.wav compare to the stark
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_39.wav  some ideas for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_40.wav or perhaps what we could do to get
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_41.wav  isolated

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_42.wav  it with opportunities for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_43.wav  imaginations to run wild

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_44.wav  so I was happy to actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_45.wav  that article

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_46.wav and I'll post the link to it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_47.wav  interested

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_48.wav but yes we are grieving
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_49.wav  the loss of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_50.wav  smart dependable
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_51.wav  leadership and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_53.wav  not having somebody have our back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_56.wav but I think for the stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_59.wav  a little bit more smoothly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_60.wav  I had shared some of my feelings with you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_61.wav for me I tend to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_62.wav  a very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_64.wav grieving that but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_65.wav  that but I think that we're all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_67.wav  leaving the collective
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_68.wav  collective spaces that we have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_70.wav  in the US
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_72.wav chop your meetings and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_73.wav there's a real sense of loss there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_74.wav at the same time people are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_75.wav  are you know maybe many for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_77.wav  I think we're all craving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_79.wav  for trying to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_80.wav  in addition to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_84.wav  situation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_85.wav my partner at the time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_89.wav but I was so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_90.wav  ambulance without

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_92.wav  in that situation was my mom
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_94.wav  she really understood

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_95.wav the gravity that I was placing on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_98.wav  situation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_99.wav  and so she did she
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_100.wav  in the place that I was at

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_101.wav  a specific life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_102.wav  life or death choice

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_103.wav  cough by the fear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_105.wav get out what I need it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_106.wav  it thankfully since then I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_110.wav  self but I think that was a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_111.wav  stark moment
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_112.wav  needed to be made immediately

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_114.wav locked behind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_116.wav  process

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_117.wav  and then you know move
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_118.wav  struggling alone but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_120.wav  is worth
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_122.wav  glimmers of hope

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_125.wav  so I just wanted to just take another
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_127.wav  you know brief

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_128.wav being alone together
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_130.wav  that really we're not alone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_132.wav  I haven't been out in days
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_133.wav  and it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_134.wav  it just really feels
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_138.wav  emotions particularly the one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_139.wav  forward and making it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_142.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_143.wav  so you know continue to reach
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_144.wav  reach out and support each other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_145.wav  other continue
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_146.wav it's okay to feel all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_148.wav  and try to you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_149.wav  put names to those

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_150.wav something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_151.wav  when it's concrete

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_153.wav  okay so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_154.wav  so you know look

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_156.wav  so I wanted to just kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_159.wav  of checking in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_160.wav  and making sure that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_161.wav  like we're alone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_162.wav  Thanks for listening and this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_163.wav  who's daughter our stories

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/86/WomenWhoStutter_86_165.wav  today about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_1.wav  in for the book is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_3.wav  they should be asking the world
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_4.wav underworld should a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_6.wav  You know it kind of reminds me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_7.wav  is indeed value in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_8.wav  you in different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_9.wav  Realized that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_10.wav  it's just another variation of difference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_13.wav it can be very connecting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_15.wav  Sam like it just has this like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_16.wav ripple effect

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_17.wav  right yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_19.wav  guess it's just been a delight

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_20.wav  Thank you for a great time
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_23.wav  that time so that was a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_25.wav  in so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_29.wav  and so what an issue it would become

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_30.wav  just move through life as I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_32.wav but things didn't quite turn out like that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_34.wav  so I found out very hard in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_35.wav  in first year beginning to become

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_36.wav  really hot periods just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_37.wav  just adjusting to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_39.wav  Hi everybody this is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_40.wav  just adjusting to being more open to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_43.wav  yeah so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_45.wav  more into their reactions than they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_48.wav  going Patrick I realized that you stammer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_49.wav  be a problem

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_51.wav  train a training to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_52.wav  become a little

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_53.wav  of stammering and we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_54.wav  and we know that stammering is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_57.wav  how we manage it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_59.wav Hi everybody this is Pam and you're listening to my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_62.wav  question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_64.wav  isn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_68.wav  I mean I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_70.wav  I think it's a little bit more of a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_73.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_74.wav we have the opportunities and the possibility

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_75.wav  and I think you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_77.wav  guys it's so nice to have you on the show today
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_78.wav  Thank you for having me Sam

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_80.wav well I was interested because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_81.wav  discover what I need it and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_82.wav  it and seek it out elsewhere
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_83.wav  it's a bit like you pump even

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_84.wav what you would say is good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_85.wav  and myself and it was only

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_86.wav  only later on when I was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_88.wav  so that sense of this is my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_89.wav  I'm probably going to sort of talk about that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_90.wav  that I really got that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_91.wav  still often missing from even
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_92.wav  been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_93.wav  help somebody deal with you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_95.wav  that like here in those states to become

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_97.wav  many SLP students
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_98.wav may have to take one clap

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_99.wav  it's great to be here
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_101.wav  and the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_102.wav  the physical
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_103.wav it's so wonderful for me to hear

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_105.wav  on it there is a very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_106.wav  definite

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_107.wav things don't have to be that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_108.wav  that medical model of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_109.wav  can be as you just said Patrick I have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_110.wav  I have a voice and it's okay for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_112.wav  so it's becoming like medical
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_113.wav  social model right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_114.wav  yeah so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_115.wav  and Sam has been talking about this for a lot

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_120.wav  we'll start with you Patrick
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_122.wav  there is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_125.wav  construe difference we don't have to look
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_128.wav  of the population

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_129.wav  meet both of those criteria
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_130.wav  and so the medical model

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_131.wav  the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_134.wav  really into the society around me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_135.wav  me and so the problem is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_140.wav  attitude towards my speech so it took

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_143.wav  really interested in stammering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_144.wav  a completely different way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_146.wav  which is also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_147.wav  you know kind of fostered discussion

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_149.wav  I think it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_151.wav  right so I became

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_152.wav  on stuttering gain
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_154.wav like oh my gosh this is amazing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_156.wav collaborate it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_157.wav  correct on a book

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_158.wav yes I'm afraid and prejudice yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_163.wav  I think it's a precedent summary and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_168.wav  the house of Lords but I make
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_173.wav  I said yes it was a really interesting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_174.wav  interesting different approaches
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_178.wav  make this happen and then he just you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_179.wav  just you know like bowed out and said it might be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_182.wav did do one together

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_183.wav  I can't I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_184.wav has been a really big process

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_186.wav  to be the co-presenter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_187.wav  her because he has such

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_191.wav right and you mentioned the word
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_192.wav  um has the book gone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_193.wav  the book going Mainstream or is it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_196.wav  audience for you both

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_197.wav  both but in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_198.wav  to main take

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_199.wav  take a ways that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_201.wav  I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/87/WomenWhoStutter_87_202.wav the two take away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_1.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_2.wav  can easily tie into
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_3.wav  we can work on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_5.wav will be talking about
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_6.wav  I think that's a good point.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_7.wav stepping out of your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_8.wav  or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_9.wav maybe go
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_10.wav going you know the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_11.wav the troubles a phone call
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_12.wav and talk to them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_14.wav  and our shoes you know just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_16.wav I was one of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_17.wav the only
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_18.wav we had a really positive

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_19.wav  response
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_21.wav combine and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_22.wav my group
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_26.wav  short time

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_28.wav enjoy my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_30.wav  a lot of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_32.wav other people like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_34.wav really well free

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_36.wav maybe there was a small
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_37.wav  that's my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_38.wav a small part of it that like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_41.wav my decision

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_42.wav but and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_43.wav or what not but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_44.wav  I'm but then I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_45.wav I'm going to be interpreting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_46.wav and so that means
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_47.wav  it like with a certain

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_49.wav and Sharper
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_50.wav there is an

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_54.wav the same thing with the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_55.wav program and then

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_56.wav now is just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_57.wav is just the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_58.wav completely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_59.wav it's completely different

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_62.wav  my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_63.wav my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_65.wav there's a lot of stuff with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_66.wav like your facial expressions

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_67.wav  with us and she
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_68.wav makes it find alarm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_70.wav kind of weird because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_71.wav one of my class is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_72.wav she had us pick a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_74.wav speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_75.wav the I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_77.wav I took out sheet of paper and I start riding

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_79.wav and I started doing I realized
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_81.wav I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_84.wav  didn't forget my name
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_85.wav  hmm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_87.wav you know people they really don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_88.wav have that in their mind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_90.wav and they walked into their room you're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_92.wav that's a really good way of looking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_93.wav  know about it till we open our mouth
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_96.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_100.wav  probably about for
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_101.wav four years ago I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_102.wav  would like to have a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_104.wav JC penny

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_106.wav  that whole week it was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_107.wav it was utterly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_113.wav and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_115.wav I ain't yet come to terms with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_116.wav like my emotions when it came
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_118.wav like a lot of the emotional bag

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_119.wav it came along with it it just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_120.wav it just wasn't quite very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_121.wav this guy was so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_122.wav I don't know if he was mean and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_123.wav  to have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_124.wav may be problems communicating with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_125.wav  pick up the walkie-talkie
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_126.wav and project my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_127.wav  entire storm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_129.wav  oh my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_130.wav what a horrible
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_131.wav what's very next day

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_132.wav like cuz
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_139.wav her mind was oh my god

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_143.wav  to try to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_144.wav  actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_145.wav use my sputtering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_146.wav did she apologize

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_147.wav I'm yeah she actually came
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_152.wav they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_154.wav it was actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_157.wav was this is a really long

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_159.wav  I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_162.wav  the form the word hello

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_164.wav  as an inspiration
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_166.wav so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_167.wav emergency room
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_173.wav 4 the next

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_174.wav they came out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_175.wav to a person who stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_179.wav I don't know I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_181.wav I don't know if I was really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_183.wav has trouble communicating
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_184.wav in a different way so I figured

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_185.wav and I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_187.wav we think of how to form words

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_191.wav  I believe you mean soda
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_192.wav no I mean pop

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_196.wav  you know type of state and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_197.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_198.wav I think towards the end of the week I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_202.wav what is your name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_204.wav  but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_207.wav you know words can

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_211.wav in Texas it was just we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_212.wav there were so many people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_213.wav there in experience in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_214.wav in Arizona

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_215.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_217.wav without us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_218.wav coming back
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_219.wav you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_220.wav we do kind of a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_221.wav I mean we can do a different type

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_222.wav what it is we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_224.wav  kind of just want

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/88/WomenWhoStutter_88_225.wav actually get through school and actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_1.wav lang language

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_6.wav but you have to the summer more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_10.wav  I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_11.wav Goddess time or make sure
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_12.wav like you're part of that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_14.wav it was last year
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_15.wav  paper yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_16.wav well I was a bit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_17.wav  yeah was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_22.wav  from a very young age
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_24.wav what's worked for you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_26.wav taking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_27.wav and did that ever

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_28.wav I finished college
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_29.wav some days like today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_30.wav  yeah it's amazing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_35.wav the words are down on paper

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_36.wav  my head
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/89/WomenWhoStutter_89_39.wav  animals

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_0.wav with her stuttering like from what you've learned
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_1.wav and that they embrace that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_3.wav I think that they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_5.wav  out of you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_9.wav  the percenting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_10.wav I'm saying my name

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_12.wav and I have a little
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_15.wav in my household

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_16.wav  so I first
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_18.wav yes I was what was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_19.wav it was very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_20.wav you know try to keep it as hidden

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_22.wav but it was no cure for it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_25.wav because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_26.wav because the way that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_28.wav  and now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_29.wav  free Lee away
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_30.wav yes I actually I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_31.wav Catterin Association conference
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_33.wav  well actually I didn't say

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_35.wav two years ago I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/90/WomenWhoStutter_90_38.wav direction that your life's going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_1.wav um yeah it hasn't come up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_2.wav what about do you have people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_3.wav and maybe something that helps me understand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_4.wav what approach would you suggest that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_5.wav  people that are going to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_6.wav souly based on what I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_8.wav so I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_10.wav  Who pays for it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_14.wav did you have to buy like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_15.wav  War

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_17.wav you know when
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_18.wav secular Muslim state

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_20.wav  food
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_22.wav what you do with yourself yeah for sure

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_23.wav  that I am working hard
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_24.wav well I guess I'm not really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_25.wav I really take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_26.wav  the bible as very much my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_28.wav  else in capable
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_30.wav  like see it as a punishment

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_32.wav  yeah I'm just very interested in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_33.wav punished by you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_34.wav  Stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_36.wav seemingly

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_37.wav  community I mean all of that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_38.wav  said a couple times you don't know you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/91/WomenWhoStutter_91_39.wav  learning about how they see the world
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_0.wav  it's not really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_1.wav yeah kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_2.wav and things and stuff and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_3.wav I could talk you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_4.wav  she think of mommy stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_5.wav where I don't care if
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_6.wav  how did you actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_7.wav  hide the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_8.wav  I just surfed on a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_9.wav  so now I just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_10.wav the closer I got the less I could speak

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_11.wav  all the relief
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_12.wav well you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_13.wav in England particularly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_15.wav  I did great guys

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_16.wav  that you're doing it doesn't it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_19.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_21.wav  more than my fear gets higher
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_22.wav  so I can't be doing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_23.wav can you tell them that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_24.wav  like they're kind of enabling you a little bit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_27.wav  last couple months
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_28.wav has a lot to do with my anxiety

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_29.wav  I don't really stutter that much and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_30.wav  therapy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_34.wav  and share
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_36.wav perfect to do that especially

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_37.wav  breathing techniques with McGuire
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_38.wav I don't I think if I was to do that that might speed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/92/WomenWhoStutter_92_39.wav have a lot of anxiety and stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_0.wav what day I hope I got
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_2.wav low yourself down a little

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_3.wav no I don't know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_5.wav  yes because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_6.wav okay I see so it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_8.wav to repeat herself

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_10.wav hello
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_11.wav have you met other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_13.wav person who doesn't stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_14.wav people that do stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_15.wav be patient
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_19.wav  yes I like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_20.wav okay so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_21.wav  there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_23.wav no they don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_24.wav  didn't help okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_27.wav with stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_34.wav stuttering doesn't bother him

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_35.wav people who stutter especially women
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_37.wav that is very exciting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/93/WomenWhoStutter_93_38.wav affect it your life
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_0.wav  today is always I'm really excited

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_1.wav  people it really it is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_2.wav  wow like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_3.wav good question
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_5.wav  I had to take this class to graduate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_8.wav okay thanks
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_9.wav  mimicked you was just a couple

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_10.wav did she say anything to you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_12.wav  like clear the air

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_13.wav  I don't know I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_14.wav educate her about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_17.wav  I would be having this conversation with you I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_19.wav  self you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_20.wav person that stutters
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_21.wav I meant one person that used

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_22.wav will come out of my mouth nothing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_23.wav  right now talking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_25.wav too stutter I would say
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_27.wav  you know people I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_28.wav  so it's just like kind of a guess
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_30.wav and a lot of people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_35.wav  about the group
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_36.wav why did you use that word

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_37.wav but you should feel so proud
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_38.wav  Grateful that you felt

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/94/WomenWhoStutter_94_39.wav no I don't really know her
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_0.wav people and their selfish

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_1.wav  stop
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_2.wav  I really believe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_3.wav take the exploration
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_6.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_7.wav for the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_8.wav so that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_10.wav on my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_11.wav  speech starts

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_12.wav then I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_13.wav no like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_15.wav  so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_16.wav me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_18.wav that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_19.wav I'm not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_20.wav pitt the things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_21.wav and so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_24.wav  instead of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_25.wav me that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_27.wav  problem
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_32.wav  of that group is that Eric

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_34.wav  lack
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_36.wav  I did one year in high school

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_37.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_38.wav I had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/95/WomenWhoStutter_95_39.wav Yano Lee
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_0.wav good have you on the show

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_1.wav  want when you want with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_2.wav without thinking about stuttering or the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_3.wav  without interfering with communication
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_4.wav  so that last part is very important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_5.wav  connecting in content
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_6.wav  and your stuttering is not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_7.wav that everybody deserves
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_8.wav  wow

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_10.wav permission to start or then they don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_11.wav I guess I didn't understand that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_12.wav you feel and how you think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_13.wav then you're in recovery

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_14.wav  wow
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_15.wav  to others you know the whole

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_16.wav damn it and when I finally figured
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_17.wav not only easier but it's more

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_18.wav freeing to just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_19.wav do that my life trend

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_20.wav hard note
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_23.wav  yeah I find that trying to get some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_24.wav  I'm sure that it was actually saying
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_25.wav I didn't avoid

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_26.wav the cause of treating in a group Miliu
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_27.wav watching people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_29.wav  person would be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_30.wav  would be successful in a group setting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_31.wav  yeah I always do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_32.wav something to say I want in they love it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_33.wav it and I think because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_35.wav what type of work you do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_37.wav the idea that flu and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_38.wav  to be rewarded

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_39.wav risktaking is to be rewarded
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_40.wav  they get thumbs up for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_41.wav or wow you ordered your own food
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_42.wav  they are but it's about taking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_43.wav taking the role of a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_45.wav  mine is just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_46.wav  any strategies per se
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_47.wav so if I give you an example of the way we were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_48.wav and certainly through desensitization
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_49.wav we use all of those tools

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_50.wav that are making people struggle so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_51.wav so you take a look at what typical

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_52.wav  in some way leading to struggle or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_53.wav  or interfering with communication

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_55.wav and that interjection that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_58.wav  My name is a Vivian

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_60.wav from the actual stuttering to begin with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_61.wav so we begin unraveling that pattern

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_64.wav you were stuttering you don't learn to do that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_65.wav I think that's the topic that's open to discussion

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_66.wav Josie and would have believed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_67.wav in response to the fear of stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_68.wav and so when you have somebody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_69.wav let's say there is a silent block

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_70.wav that face
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_71.wav what do you have when they're all gone

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_73.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_74.wav  pretty much comfortable forward moving

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_75.wav  rich or prolongation
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_76.wav we're not doing anything we're

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_77.wav  that lead to struggled speech we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_78.wav  we don't for fluency

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_79.wav that kept us struggling
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_81.wav but say today is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_83.wav  I don't even know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_85.wav  Tuesday okay what I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_86.wav success on a path to recovery
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_87.wav and so that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_88.wav again
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_89.wav  failure you'll feel bad about it.

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_90.wav  it so with before therapy somebody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_91.wav  stuttering it's okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_92.wav to get on the sound and start of the way I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_93.wav their ideas that have been

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_94.wav the ideas that have been so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_95.wav accepted all through their life

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_96.wav and all of a sudden they're being supposed when you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_99.wav it sounds like it could be a little

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_102.wav  you get down to some pretty
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_103.wav raw emotion I would think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_105.wav  eating you fear stuff
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_106.wav  or stuttering even if you don't stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_110.wav it's just as effective for people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_111.wav  how successful they are in doing that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_112.wav  I get
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_113.wav  while that I what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_114.wav  what I had come to understand
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_115.wav covert stuttering was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_116.wav not speech language pathology from stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_117.wav and been interested ever since

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_118.wav  be disappointed in myself for having
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_119.wav  having you know believe

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_120.wav  rather other people who
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_122.wav  it takes them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_123.wav month to even
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_124.wav is that they're generally

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_125.wav I wouldn't say all of them but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_126.wav the sound of the word that they fear

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_127.wav Does that make sense to you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_129.wav so I might say go pick up the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_132.wav go pick up
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_134.wav so when I actually get to key

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_135.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_136.wav and I think that's the most interesting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_137.wav I feel some sort of relief because I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_138.wav  behavior is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_140.wav and so there's this false sense that you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_141.wav and finally stutters on the cake

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_142.wav  go get that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_143.wav the time to celebrate for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_144.wav  yeah I can relate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_145.wav  that even in front of other

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_146.wav people that stutter so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_147.wav  be a very shameful process

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_148.wav  people and when you're in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_150.wav  that probably the crux of the matter that they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_151.wav feeling that we're afraid of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_153.wav actually welcoming it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_154.wav  struggle avoid the struggle
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_155.wav you go for the struggle

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_156.wav how can we invite that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_157.wav so whatever it is that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_158.wav and we're going to make friends with it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_160.wav they're generally an hour and a half to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_161.wav challenges and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_162.wav just have that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_163.wav  as much as I teach
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_164.wav  I'm graduate students and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_165.wav  so that's a big part of it as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_167.wav  find you an

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_169.wav  to you looking for something different
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_170.wav yeah that happens quite a bit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_171.wav  I just find that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_172.wav if you're looking to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_173.wav work in this way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_174.wav my description of it during the diagnosis

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_175.wav you go right into the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_176.wav  frame that we had agreed on what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_177.wav what led you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_178.wav  like a letter that cell

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_180.wav I used to struggle with communication
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_181.wav  a different person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_183.wav they have the ability to communicate
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_184.wav as a person who stutters and that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_185.wav  how do you feel about that as strongly as this one does
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_186.wav  wow radiant

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_189.wav Does your husband still stutter
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_190.wav he would say yes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_191.wav butters and as a communicator
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_193.wav recovery from stuttering

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_194.wav Recovery from Stunner I'll give you my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/96/WomenWhoStutter_96_195.wav I can relate

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_1.wav  touched a lot of lives and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_2.wav I'm glad that I met you along the way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_3.wav or young or not so young you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_6.wav would you want to share with others that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_7.wav  learned along the way
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_8.wav  I think it's very important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_10.wav  journey and be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_11.wav  attainable

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_13.wav does that have any personal meaning
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_15.wav that was unrealistic for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_16.wav  not hate it and function with it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_18.wav what made you make the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_19.wav  keep me in New Jersey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_20.wav  that's awesome so kind of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_21.wav  she's an extremely
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_22.wav  we spiritual so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_26.wav  um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_27.wav and I saw Grasshopper

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_29.wav  it's all great
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_30.wav  Wow that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_33.wav that is for damn sure and I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_35.wav  to the blog make room for the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_36.wav  stuttering and it's also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_39.wav  a Masters in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_40.wav  everything and then I hear
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_41.wav  that there's an or

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_42.wav  you basically going in front of a jury and then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_43.wav  and then they going to present

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_44.wav  that diagnosis etc
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_45.wav  at that point

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_47.wav  I'm a battering kick my butt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_50.wav  it and I just said you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_51.wav  you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_53.wav  lesson

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_54.wav  away from opportunity
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_56.wav  a download on itunes today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_57.wav  today I'm excited to have that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_61.wav  just fly by the seat of my pants and see what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_62.wav the deer kept me there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_63.wav  you know fear of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_65.wav  so I can relate you know because
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_66.wav  what kept me there was just fear you know I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_67.wav fear I was stuck and I was afraid to move
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_68.wav  but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_72.wav  whatever that self doubt
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_73.wav  but it's it to take a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_74.wav and you know if you hadn't you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_75.wav you might still be stuck where you were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_78.wav  my name is
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_81.wav  wanted because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_82.wav  stuck
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_83.wav but I joined a gym and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_84.wav  you know the physical aspect but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_85.wav  but go into the gym that's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_86.wav but going to the gym that's what I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_90.wav  to it's important to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_91.wav  Mindful of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_92.wav  of just being gentle with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_95.wav  got something there you know actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_96.wav basically creating a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_97.wav  wouldn't feel so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_98.wav  so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_100.wav I don't know I can't even find the word for it but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_101.wav  anywhere

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_102.wav  mhm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_104.wav  even if it's for 10 minutes

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_105.wav but that you didn't have for the rest of the day
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_107.wav  you sound to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_108.wav  so much more at peace with
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_113.wav  um

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_115.wav  what I'm feeling inside yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_117.wav  then something hit me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_119.wav  and loving every minute of it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_120.wav  of it and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_124.wav  putting myself out there I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_125.wav  not constantly talking about it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_127.wav  it just took some pressure off
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_128.wav  Don't you feel it that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_129.wav  selfish I mean you have so much that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_130.wav  taking care of yourself okay

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_131.wav okay so sometimes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_136.wav  break then I'm not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_138.wav to do anything for anyone
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_146.wav  in this world together and sometimes it's going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_147.wav  to apologize I actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_148.wav  you're right

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_149.wav you're right sometimes take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_150.wav  sometimes taking care of ourselves

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_153.wav I mean the word self is part of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_155.wav people so I actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_157.wav hey that sounds like a plan
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_165.wav  No, um what about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_166.wav  about people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_167.wav people that you're meeting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_168.wav  your new community I mean what's it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_169.wav  what's it like when you meet people for the first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_170.wav  do you find yourself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_176.wav  oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_177.wav oh it sounds like you're really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_178.wav  and being retired so can I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_179.wav  so can I ask like what exactly do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_180.wav and so happy to hear all of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_181.wav  all of that I can hear it in your voice
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_182.wav  oh gosh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_184.wav  being the present so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_186.wav  France

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_187.wav  yes it will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_191.wav  quarter of the people there so

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_195.wav  am I journey
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_196.wav  journey with stuttering it has been a little

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/97/WomenWhoStutter_97_200.wav gender
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_0.wav directly linked to the blog

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_2.wav it's not anything that I can control so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_4.wav duttering before you wouldn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_6.wav thatters has to deal with a lot
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_7.wav people who started

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_8.wav  a chapter that meets around your area
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_9.wav yeah definitely I think so too

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_11.wav people the same way that I have been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_12.wav  well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_14.wav  about so did you ever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_17.wav when I was in 4th grade I went through the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_19.wav it was much less
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_20.wav there was a lot less teasing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_21.wav  as an undergrad in one of my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_22.wav  almost kind of gives the person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_25.wav function in life when you're
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_26.wav oh it totally is because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_27.wav it just kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_28.wav  best

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_30.wav deal with it I guess I'll ask that first and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_32.wav therapy help you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_33.wav  friends with a girl from band
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_35.wav hey that's not right and I'm gonna

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_36.wav it's a topic
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_37.wav the research and when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/98/WomenWhoStutter_98_39.wav duttering affects the entire education
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_0.wav stuttering and it's all

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_2.wav pay attention but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_4.wav support like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_5.wav are you involved at all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_7.wav good and there are times

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_8.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_9.wav not person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_11.wav kid
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_12.wav  school and he did have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_14.wav  stuttering problem and he was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_15.wav heard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_16.wav shuttered so it was kind
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_20.wav  and it was great

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_21.wav  unless he cho
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_22.wav chocho's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_23.wav  yeah totally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_24.wav  me is this the first time you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_25.wav  chat it with another
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_26.wav also female

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_27.wav no actually I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_28.wav to someone who does have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_30.wav  Shutter because I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_32.wav get that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_34.wav I find it very
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_36.wav  sometimes it's just really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_41.wav  podcast I think it's important
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_42.wav  I just think it's really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_44.wav right the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_46.wav  show it was really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_47.wav good talking to you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_48.wav not really when I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_49.wav say I found it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_50.wav  run yourself into the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_51.wav ground this is the play
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_52.wav  like a world squad

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_53.wav  well there will
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_54.wav the country is too

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_55.wav together but then
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_58.wav  so were there people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_59.wav  was the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_60.wav work that you did

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_61.wav pands on the country in the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_63.wav  good I'm really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_65.wav  country Ecuador we did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_66.wav  we did ground

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_68.wav for a church
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_69.wav and so that was really hard

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_70.wav  wasn't a case like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_71.wav the second one

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_75.wav treat children and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_76.wav  have to go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_77.wav back on
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_79.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_80.wav ports cam
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_82.wav from and what you do to keep busy

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_83.wav well my name
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_85.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_86.wav  sounds like such an amazing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_88.wav I think recently returned

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_89.wav I totally am like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_90.wav American we are

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_92.wav where I have had to take
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_94.wav  lived out of a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_95.wav pack that I only
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_97.wav  in the other countries

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_98.wav we were actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_99.wav  since you bring it up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_100.wav what was the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_101.wav it calls up but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_102.wav it was crazy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_104.wav project and I'm

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_105.wav that even though I do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_108.wav God

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_109.wav guide me into make me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_112.wav and just

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_114.wav people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_115.wav to their blindness like they were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_116.wav  it seems like
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_117.wav  this opportunity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_118.wav how did you handle that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_119.wav um as first I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_120.wav big of a deal now
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_121.wav it was hard cuz

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_124.wav  family friend
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_125.wav wow 11 country

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_128.wav  English so they probably
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_130.wav Safety net that you used

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_131.wav you know like reacting
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_132.wav  negatively or you know

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_133.wav  that I know that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_135.wav  no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_136.wav what did your family think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_137.wav  think about you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_138.wav making this decision that this was something
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_139.wav my family was very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_140.wav portive me and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_143.wav he was like I almost

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_144.wav cry because she has always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_145.wav like so intense

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_146.wav it is it really is and it's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_150.wav uttering and much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_151.wav  also
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_152.wav told us what the link is because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_153.wav  I've made a lot of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_154.wav piece with it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_155.wav I kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_156.wav it's kind of hard to explain

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_157.wav  I kind of hated my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_159.wav  don't love it but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_160.wav I no longer hate it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_162.wav disabler

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_163.wav I think of it as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_166.wav  so it almost sounds like

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_167.wav well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_168.wav in 2010 I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_169.wav  that you had was over the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_170.wav telephone and I know that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_172.wav challenging
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_173.wav is the phone tough for you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_175.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_176.wav friend and I didn't

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_177.wav the other at all so it all
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_179.wav yes I have heard of it

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_181.wav  no
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_182.wav  no my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_183.wav  my uncle no longer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_184.wav sodiers and my mom

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_186.wav stutters but all that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_187.wav  I kind of was on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_189.wav yeah she's really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_191.wav and she's very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_193.wav  nursing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_199.wav  of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_200.wav all timers is a
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_202.wav please and some

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_203.wav talk to them
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_206.wav  you're definitely a service

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_208.wav that are blanched at
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_210.wav  by helping others

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_216.wav  a lot of people do the complete
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_217.wav opposite because they

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_218.wav  made me less than other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_219.wav  people so it took me a long

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_220.wav  an effective
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_222.wav you never let that get in the way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_223.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_226.wav so I kind of blew it off

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_229.wav  even though I therapy I was kind of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/99/WomenWhoStutter_99_230.wav  different times of the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_0.wav  10 minute conversation they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_1.wav well it sounds like you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_3.wav and they both knew
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_4.wav and to go through the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_5.wav  years of school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_6.wav  do you still going to be kind

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_7.wav handicap I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_9.wav she was an amazing person

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_10.wav and I remember when I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_11.wav and now understand what she expected

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_12.wav  Pleasure to talk with somebody
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_13.wav  a special kindergarten for kids

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_15.wav  about what you're doing presently
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_16.wav I said okay I know now what

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_18.wav then I contacted him and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_19.wav  research and studying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_20.wav  disfluent to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_21.wav normal speech

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_23.wav  person stops talking it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_26.wav  doesn't for me

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_27.wav me I doesn't work for anybody to tell you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_30.wav  all kinds of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_31.wav  and he's trying to write he's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_32.wav  he's going to do better

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_36.wav  well does your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/100/WomenWhoStutter_100_39.wav sheet so when I pass the first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_2.wav  keep my head down and be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_4.wav but what we have to be careful of as well

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_13.wav  well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_15.wav  raise awareness and you know let

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_17.wav  on board with you as well
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_18.wav well I think the big thing is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_20.wav  probably one of the most boring things
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_23.wav  sometimes you know it is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_26.wav what a perfect way to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_27.wav  conversation I must

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_28.wav  I must say this has been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_29.wav such a confident

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_31.wav  so many
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_32.wav people thank you so much

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_33.wav it has and this has been
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_40.wav  it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_41.wav one of the classes that I enjoyed
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_44.wav confidence

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_47.wav  so I left home as soon as I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_50.wav  ready to actually talk

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_51.wav  talk about my summer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_53.wav  download on itunes today

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_54.wav today as always I have the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_58.wav  I remember looking

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_63.wav stomer
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_64.wav and it came up with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_71.wav one other person that's downward
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_72.wav and that was a guy in school it was a complete

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_74.wav  so please join me in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_75.wav but not

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_79.wav  an absolute life-changing weekend
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_80.wav no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_82.wav and it was a lady called
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_84.wav the reason that I asked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_85.wav question is because you would
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_86.wav feel like to meet other women

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_87.wav other women that you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_89.wav every time you came out of that room there was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_90.wav  if you don't like yourself you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_95.wav man D

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_97.wav where's the people see you as
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_103.wav  you know feel like our

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_104.wav you know developed a good
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_106.wav  so we started talking when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_107.wav  side of London so we just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_109.wav person to stay with her that was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_110.wav that was the only way I could afford it so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_112.wav person ever that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_114.wav man D hey Mandy
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_115.wav  stuttered so to get off the airplane

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_120.wav  here in Northern Ireland
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_122.wav who is our meeting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_124.wav what's 7 of us not so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_126.wav it's cool it's fine now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_128.wav  reach to get these people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_129.wav  people to come to your group I mean you said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_131.wav find them well basically
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_138.wav  until you actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_139.wav  on a Movie Act very quickly
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_141.wav ind you how did hear about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_143.wav  program so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_148.wav which is an actual public

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_153.wav  skype allows us to talk to people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_154.wav  talk to people in other parts of the world

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_161.wav the only thing that we do have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_162.wav  hair and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_166.wav what is the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_168.wav helpful

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_170.wav  how long is the meat
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_172.wav  it's really exciting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_173.wav  so with that little
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_174.wav  High smooth

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_178.wav  people relax and actually
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_180.wav you're making a difference and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_181.wav and you know for people that are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_182.wav listening you know it's important

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_183.wav  talk to the right
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_185.wav people and advertised and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_186.wav  them on to you so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_187.wav so and that is the starting

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_188.wav is actually mental health
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_192.wav my name is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_193.wav  I'm
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_194.wav offer that support that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_196.wav  of people with a star
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_202.wav see yourself eventually going

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_203.wav  going in that direction and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_204.wav helping actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_208.wav disability
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_209.wav well this is a big debit that we

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_211.wav  you it really depends how affection
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/101/WomenWhoStutter_101_212.wav that it makes you feel that way

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_0.wav  I think it's actually taught me to be more
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_1.wav yes I think that's true especially

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_2.wav  happened
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_3.wav  either

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_4.wav  about your speech therapy that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_5.wav about 4 years old

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_6.wav I really don't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_7.wav  system a lot of people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_9.wav  I remember the other one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_10.wav it's for

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_12.wav  I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_13.wav  a lot of people like in class

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_14.wav  we'll just you know stay quiet
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_16.wav  Not many of them

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_17.wav have you ever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_19.wav special for your

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_20.wav birthday
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_21.wav  we can prepare

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_23.wav how do you think you'll handle that one
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_24.wav to be on the pocket

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_25.wav and we just relaxed together
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_27.wav or not because I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_28.wav you know develop
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_31.wav  about how some people can be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_32.wav it's amazing that there are
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_33.wav people that are still looking for that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_34.wav yeah well that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_35.wav  is absolutely

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_36.wav  interested in doing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/102/WomenWhoStutter_102_39.wav your speech wasn't part of that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_0.wav my name is Annie Bradbury
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_2.wav  I just wanted to say don't think that I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_3.wav but everything together you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_5.wav it's funny how many people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_7.wav and it definitely sounds like you have
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_9.wav  Association

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_10.wav that's a long story but basically
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_11.wav being one of the first

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_12.wav people outside of San Francisco
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_13.wav every year she becomes stronger and stronger

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_15.wav see that in today's
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_18.wav together because what was happening is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_21.wav oh make me feel guilty
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_22.wav  bringing their children and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_23.wav and there was nothing in place I remember in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_25.wav I grabbed Pat and I said help

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_26.wav  I think we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_27.wav we presented the Year of the Child

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_28.wav  because for me personally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_29.wav my speech pathologist from the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_30.wav  old and you can't follow the after
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_31.wav but she is now involved in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_33.wav  13
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_34.wav 13 that I would take her to her

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_35.wav kind of cool when I see a lot of the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_36.wav speech pathologist that now have their doctor

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_38.wav my heart to have been a part of
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_39.wav you hear that coming through

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_41.wav so what type of non-profit
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_42.wav profit work are you involved in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_43.wav  which in the mid 50s to 60 in an
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_44.wav and then there was three young women are for in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_45.wav and it's the conversation evolved and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_46.wav and the three young women

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_47.wav  have changed over the years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_49.wav you have any

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_50.wav  particular
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_51.wav  that I wish I wasn't dealing with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_53.wav you know there is I am you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_54.wav there's not much I won't do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_55.wav  about and I even expressed that you know perhaps
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_56.wav you know when I was working for the NS

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_57.wav  profile I'm just very fortunate to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_58.wav to know a lot of people we have

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_60.wav it's the situation that I allow myself
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_61.wav to do some diverse things

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_63.wav  interested in them but I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_64.wav  So

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_65.wav so I often
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_66.wav Cib and say that I am now

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_68.wav it and I will self talk and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_70.wav cockout the phone's ringing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_71.wav  part comes in because when I get done people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_72.wav people walk up to me and they go oh honey

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_73.wav  myself a little bit because I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_74.wav but I let the situation

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_75.wav the female part
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_76.wav  comes in what did you mean by

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_78.wav  kind of comes in and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_80.wav dictates how you felt about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_81.wav  10 years I did
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_82.wav I did for 10 years I've been a member

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_83.wav oh I don't think if there was a man in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_84.wav I think as a man I would have gotten that oh

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_85.wav that oh honey you know oh my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_86.wav  or something but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_88.wav  that's where like maybe the
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_89.wav expressions of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_92.wav it's also helped me
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_93.wav also helped me on the job you know it really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_95.wav so I then can walk up to him I remember
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_96.wav  this person have her in and of course what I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_98.wav I remember going on one interview
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_99.wav and I didn't realize I was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_100.wav  orange
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_101.wav  orange County California

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_102.wav  open up communication and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_104.wav  and I remember seeing all these young

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_105.wav Savvy looking good-looking guys
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_108.wav one-on-one with another

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_109.wav person that may not know that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_110.wav we have to be you know and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_112.wav  when we you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_113.wav part of our stuttering journey whatever it might

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_117.wav was a lot more severe
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_122.wav are you looking for something

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_124.wav  the fight lessons I think
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_126.wav  that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_127.wav you know just I think you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_128.wav  and love ourselves I think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_131.wav  laugh that they are too
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_133.wav  and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_134.wav when I stop getting angry
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_135.wav she was young and she was working for Target

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_136.wav and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_137.wav the kind of calls I get a lot of and and I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_138.wav and I said do you really think this grown
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_141.wav  flat sideways you know but

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_149.wav  being able to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_150.wav  get away with

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_151.wav  so now personally
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_152.wav what's it like for you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_153.wav  socially just as Annie
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_154.wav  you know when

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_155.wav you know when I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_157.wav it was a challenge you would laugh if you

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_158.wav  really there to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_161.wav it was Annie the director of the NSA

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_162.wav to stick my hand out
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_163.wav and shake and introduce

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_164.wav  trying to work on that but so I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_166.wav like sticking my hand out

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_167.wav  out and forcing myself to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_168.wav  be vulnerable and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_174.wav like you said that authentic self
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_175.wav  without the NSA there

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_176.wav and that's kind of what I heard you saying there that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_178.wav  think

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_179.wav  Thank you I appreciate that and thank
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_180.wav listen

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_184.wav  20 then and I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/103/WomenWhoStutter_103_185.wav I reached out to them I actually

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_0.wav that's good okay so
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_5.wav  yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_6.wav  big change that's true
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_8.wav I started writing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_9.wav when I was about 33 years old
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_11.wav cured you wrote you said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_15.wav where are you still stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_16.wav  talking about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_18.wav but for some reason
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_20.wav she thought she was right about everything

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_22.wav  Delightful sense of humor
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_25.wav  is and I haven't talked to him in years

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_26.wav oh you know
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_28.wav  to speak I mean I find

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_30.wav  or that was
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_32.wav  yeah I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_38.wav  have they told you that it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/104/WomenWhoStutter_104_39.wav  pleasure to listen to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_0.wav comfort and confidence
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_1.wav Barbara have you asked

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_2.wav  done presentations of your
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_3.wav  and if they have that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_4.wav and where you're from and what you do
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_5.wav  There were

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_6.wav  alliance who are just
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_7.wav  you taught me to do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_8.wav  and I help people
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_9.wav  it's been quite

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_10.wav and we work on that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_11.wav  with normal speech production

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_12.wav  I just want them to be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_13.wav  and of course

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_15.wav  that's an interesting way to put
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_17.wav  that people who stutter do

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_18.wav what they said sounded
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_19.wav  I think that it has its benefit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_21.wav  detected a bit of a new
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_22.wav  so I really

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_23.wav  trying to say words
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_24.wav well it was really certain

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_27.wav  rewire or
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_29.wav  you know they go

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_30.wav  a very interesting study
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_31.wav  fluency treatment

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_35.wav we have a speaking system
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_36.wav  if I feel that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_37.wav something has to change
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_38.wav but there was some people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/105/WomenWhoStutter_105_39.wav  as a by-product of what they
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_0.wav as a community of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_1.wav people who stutter which
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_2.wav  to talk to somebody

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_3.wav  it when you're communicating but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_4.wav stutter or have stuttered because

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_5.wav they have a conference every year we
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_6.wav of people who stutter and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_7.wav that those first
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_9.wav people at work with us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_10.wav  something wrong that
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_11.wav being open with my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_12.wav stuttering part of my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_13.wav and

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_14.wav not very well known to
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_15.wav when I was trying

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_16.wav  should share
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_17.wav my little corner of the world

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_18.wav now after having
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_19.wav and most of the people

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_20.wav  for the last five years
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_22.wav you I'm also fairly active

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_24.wav talking about stuttering
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_25.wav whose daughters opens their mouth to speak

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_27.wav nervous laugh
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_28.wav and again a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_29.wav the movies
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_30.wav the better movies that we've had

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_31.wav are still often discriminated
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_32.wav people who stutter still

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_35.wav people about what this
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_36.wav  rockstar.com

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_37.wav  by your men
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_38.wav impact that it has on

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/106/WomenWhoStutter_106_39.wav  I hope so and I hope you like it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_0.wav  at work it carries over into the

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_1.wav  public I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_2.wav  feel for you to be

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_4.wav  gives a different perspective
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_5.wav  calling someone a sputterer

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_6.wav and it was just something I wanted
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_7.wav  or doesn't come out of our mouth

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_8.wav what do you mean by objective
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_10.wav  and it's helped me a lot yeah

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_11.wav thank you
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_12.wav  or secondary behaviors

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_13.wav  today
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_17.wav  I started realizing

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_20.wav do something about it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_24.wav  yeah I found it very frustrating

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_25.wav blog stuff I've been writing
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_26.wav  the end of that I had just gotten

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_28.wav  because like you said it takes
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_31.wav that as being bad

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_33.wav  yeah
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_37.wav  that there's no need to pity us

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/107/WomenWhoStutter_107_38.wav  changing her exception
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_0.wav  privilege and opportunity

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_1.wav I was different and that I didn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_2.wav and I want to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_4.wav course will be
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_5.wav  doing this convert

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_7.wav  I am actually a poof by today
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_8.wav how do you feel about that I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_11.wav  for me I always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_12.wav where do you think that is

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_13.wav  so they always
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_15.wav  and I was very

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_16.wav  having to give a piece and
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_19.wav  been it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_20.wav um
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_23.wav better because you weren't worried about

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_25.wav  I do have to do public speaking
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_26.wav  yes it was

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_27.wav  conference and meeting so many other
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_28.wav  kind of like tease me and all that stuff

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_29.wav  I would like try to talk to my
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_31.wav and it sounds like such a perfect fit

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_33.wav  what wasn't ever
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_34.wav that it's okay to stutter

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_36.wav  in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_38.wav  as well yeah no

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/108/WomenWhoStutter_108_39.wav shaped your life at this point
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_0.wav well I would probably

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_3.wav oh wow that's really cool
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_6.wav to me it's kind of a waste of

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_7.wav  and I actually have a really
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_8.wav it'll be life right now I'm in

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_9.wav you said something very interesting there
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_11.wav why do I have to tell

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_12.wav someone most even personal
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_14.wav  I don't think of it as it's

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_15.wav  I mean for me then it
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_16.wav well I

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_17.wav  you know but I mean
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_18.wav  okay my parents a

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_19.wav hamphlet on our local youth
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_20.wav  people that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_21.wav what about your parents
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_22.wav  I was about to

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_23.wav  started stuttering in
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_24.wav  quit speech therapy my

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_25.wav Freshman year of high school
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_28.wav in middle school but my parents said

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_29.wav  just keep sticking with it'll be fine but
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_31.wav  them up

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_32.wav and I mean I
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_33.wav how have you been involved

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_34.wav  Well I wasn't
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_35.wav  you know how did you get involved in that

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_37.wav I watch a lot of like crime stuff
/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_38.wav  and I mean

/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/home/alien/Programming/env/lib/python3.12/site-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/WomenWhoStutter/109/WomenWhoStutter_109_39.wav even at my age

In [12]:
import csv
import string

# Define the file path
input_file_path = 'transcription_small_tt_nowordrep.csv'  # Replace with your file path
output_file_path = 'transcription_small_tt_nowordrep_formatted.csv'  # This will be the output file path

# Create a translation table to remove punctuation
remove_punctuation = str.maketrans('', '', string.punctuation)

# Read the input CSV file
with open(input_file_path, 'r', newline='', encoding='utf-8') as infile:
    csvreader = csv.DictReader(infile)
    fieldnames = csvreader.fieldnames

    # Open the output CSV file for writing
    with open(output_file_path, 'w', newline='', encoding='utf-8') as outfile:
        csvwriter = csv.DictWriter(outfile, fieldnames=fieldnames)
        csvwriter.writeheader()

        # Iterate over each row in the CSV
        for row in csvreader:
            # Remove punctuation only from the 'result' column (adjust the column name if necessary)
            if 'result' in row:
                row['result'] = row['result'].translate(remove_punctuation)
            
            # Write the modified row to the output file
            csvwriter.writerow(row)

print(f"Punctuation marks removed from the 'result' column. Modified content saved to {output_file_path}")

Punctuation marks removed from the 'result' column. Modified content saved to transcription_small_tt_nowordrep_formatted.csv