In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
root_fp = "../../DATA/ml-stuttering-events-dataset/"
CLIPS_DIR = "/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/"
df = pd.read_csv("/home/alien/Git/DATA/ml-stuttering-events-dataset/SEP-28k_labels.csv")
df.head()
df.shape

(28177, 17)

In [3]:
df

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,WordRep,DifficultToUnderstand,Interjection,NoStutteredWords,NaturalPause,Music,NoSpeech
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,0,0,0,3,1,0,0
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,0,0,0,3,1,0,0
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,0,0,0,3,0,0,0
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,0,0,0,2,0,0,0
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28172,WomenWhoStutter,109,35,25793600,25841600,0,0,0,0,0,0,0,3,3,0,0,0
28173,WomenWhoStutter,109,36,26168480,26216480,0,0,1,1,3,0,1,1,0,0,0,0
28174,WomenWhoStutter,109,37,3569440,3617440,0,0,0,0,0,0,0,3,3,1,0,0
28175,WomenWhoStutter,109,38,28479840,28527840,0,0,1,0,0,0,0,3,2,1,0,0
28176,WomenWhoStutter,109,39,29318080,29366080,0,0,0,0,0,0,0,0,3,0,0,0

In [4]:
df = df[df.PoorAudioQuality == 0]
df = df[df.DifficultToUnderstand == 0]
df = df[df.Music == 0]
df = df[df.NoSpeech == 0]
df = df[df.Unsure == 0]

In [5]:
df = df[(df.WordRep == 0)]

In [6]:
df

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,WordRep,DifficultToUnderstand,Interjection,NoStutteredWords,NaturalPause,Music,NoSpeech
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,0,0,0,3,1,0,0
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,0,0,0,3,1,0,0
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,0,0,0,3,0,0,0
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,0,0,0,2,0,0,0
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28171,WomenWhoStutter,109,34,24781440,24829440,0,0,0,0,0,0,0,2,3,0,0,0
28172,WomenWhoStutter,109,35,25793600,25841600,0,0,0,0,0,0,0,3,3,0,0,0
28174,WomenWhoStutter,109,37,3569440,3617440,0,0,0,0,0,0,0,3,3,1,0,0
28175,WomenWhoStutter,109,38,28479840,28527840,0,0,1,0,0,0,0,3,2,1,0,0
28176,WomenWhoStutter,109,39,29318080,29366080,0,0,0,0,0,0,0,0,3,0,0,0

In [7]:
df = df.reset_index(drop=True)

In [8]:
df

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,WordRep,DifficultToUnderstand,Interjection,NoStutteredWords,NaturalPause,Music,NoSpeech
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,0,0,0,3,1,0,0
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,0,0,0,3,1,0,0
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,0,0,0,3,0,0,0
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,0,0,0,2,0,0,0
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17221,WomenWhoStutter,109,34,24781440,24829440,0,0,0,0,0,0,0,2,3,0,0,0
17222,WomenWhoStutter,109,35,25793600,25841600,0,0,0,0,0,0,0,3,3,0,0,0
17223,WomenWhoStutter,109,37,3569440,3617440,0,0,0,0,0,0,0,3,3,1,0,0
17224,WomenWhoStutter,109,38,28479840,28527840,0,0,1,0,0,0,0,3,2,1,0,0
17225,WomenWhoStutter,109,39,29318080,29366080,0,0,0,0,0,0,0,0,3,0,0,0

In [9]:
df.to_csv('./no_wordrep.csv')

In [10]:
df['filepath'] = df.apply(lambda x: f"/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/{x[0]}/{x[1]}/{x[0]}_{x[1]}_{x[2]}.wav", axis=1)

# Step 3: Optionally, save the modified DataFrame back to a CSV file
df.to_csv('no_wordrep_fps.csv', index=False)

/tmp/ipykernel_10725/4166108988.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['filepath'] = df.apply(lambda x: f"/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/{x[0]}/{x[1]}/{x[0]}_{x[1]}_{x[2]}.wav", axis=1)

In [11]:
df = df['filepath']
df.to_csv('no_wordrep_fps.csv', index=False)